<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Foundry;
use App\Bootstrap\CanonicalJson;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class SubordinateConstructionAuthorizationAcceptanceService
{
    private string $inbox; private string $occupancy; private string $acceptances;
    public function __construct(#[Autowire("%kernel.project_dir%")] string $projectDir){$this->inbox=$projectDir."/var/imperium/offices/foundry/inbox/subordinate-construction-commissions";$this->occupancy=$projectDir."/var/imperium/offices/foundry/occupancy";$this->acceptances=$projectDir."/var/imperium/offices/foundry/subordinate-construction-acceptances";}
    public function accept(string $commissionId,string $bindingId):array
    {
        if(!preg_match('/^guildhall-subordinate-construction-commission-[a-f0-9]{20}$/',$commissionId))throw new \InvalidArgumentException("F90_GUILDHALL_COMMISSION_ID_INVALID");
        if(!preg_match('/^foundry-artificer-binding-[a-f0-9]{20}$/',$bindingId))throw new \InvalidArgumentException("F91_ARTIFICER_BINDING_ID_INVALID");
        $commission=$this->read($this->inbox."/".$commissionId.".json","F92_GUILDHALL_COMMISSION_ABSENT");$binding=$this->read($this->occupancy."/".$bindingId.".json","F94_ARTIFICER_BINDING_ABSENT");$refs=$commission["authorized_resolutions"]??null;
        if(!$this->ok($commission)||!$this->ok($binding)||$commissionId!==($commission["commission_id"]??null)||"imperium.guildhall-subordinate-construction-commission/v1"!==($commission["schema"]??null)||"guildhall"!==($commission["requester"]["office"]??null)||"foundry.artificer"!==($commission["recipient"]["seat"]??null)||"COMMISSIONED_PENDING_FOUNDRY_ACCEPTANCE"!==($commission["status"]??null)||null!==($commission["recipient_acceptance"]??null)||true!==($commission["construction_authority"]??null)||false!==($commission["construction_authority_exercisable"]??null)||true===($commission["persona_selection_authority"]??null)||true===($commission["admission_authority"]??null)||true===($commission["execution_authority"]??null)||!is_array($refs)||[]===$refs||!in_array($binding["schema"]??null,["imperium.foundry-artificer-occupancy/v1","imperium.operator-root-seat-occupancy/v1"],true)||"foundry"!==($binding["office"]??null)||"foundry.artificer"!==($binding["seat"]??null)||"ACTIVE"!==($binding["status"]??null)||true!==($binding["binding_atomic"]??null)||($commission["instance_id"]??null)!==($binding["instance_id"]??null)||true===($binding["execution_authority"]??null))throw new \RuntimeException("F93_GUILDHALL_COMMISSION_INVALID");
        $id="foundry-subordinate-acceptance-".substr(hash("sha256",CanonicalJson::encode([$commissionId,$commission["record_digest"],$bindingId,$binding["record_digest"],$refs])),0,20);
        return $this->save($id,["schema"=>"imperium.foundry-subordinate-construction-authorization-acceptance/v1","acceptance_id"=>$id,"instance_id"=>$commission["instance_id"],"guildhall_commission_id"=>$commissionId,"guildhall_commission_digest"=>$commission["record_digest"],"authorization_act_id"=>$commission["authorization_act_id"],"authorization_act_digest"=>$commission["authorization_act_digest"],"binding_id"=>$bindingId,"binding_digest"=>$binding["record_digest"],"actor"=>["seat"=>"foundry.artificer","manifestation_id"=>$binding["manifestation_id"],"occupancy_generation"=>$binding["occupancy_generation"]],"authorized_resolutions"=>$refs,"disposition"=>"ACCEPTED_FOR_EXACT_SUBORDINATE_CONSTRUCTION","recipient_acceptance"=>true,"construction_authority"=>true,"construction_authority_exercisable"=>true,"persona_selection_authority"=>false,"profile_approval_authority"=>false,"spawning_authority"=>false,"seat_binding_authority"=>false,"execution_authority"=>false]);
    }
    private function save(string$id,array$r):array{if(!is_dir($this->acceptances)&&!mkdir($this->acceptances,0770,true)&&!is_dir($this->acceptances))throw new \RuntimeException("F98_ACCEPTANCE_FAILED");$r["record_digest"]=hash("sha256",CanonicalJson::encode($r));$p=$this->acceptances."/".$id.".json";if(is_file($p)){$o=$this->read($p,"F99_ACCEPTANCE_CONFLICT");if(CanonicalJson::encode($o)!==CanonicalJson::encode($r))throw new \RuntimeException("F99_ACCEPTANCE_CONFLICT");return$o;}foreach(glob($this->acceptances."/foundry-subordinate-acceptance-*.json")?:[] as$existingPath){$existing=$this->read($existingPath,"F99_ACCEPTANCE_CONFLICT");if(($r["guildhall_commission_id"]??null)===($existing["guildhall_commission_id"]??null))throw new \RuntimeException("F99_GUILDHALL_COMMISSION_ALREADY_DISPOSED");}$t=$p.".tmp.".bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException("F98_ACCEPTANCE_FAILED");}return$r;}
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r["record_digest"]??null;unset($r["record_digest"]);return is_string($d)&&hash_equals($d,hash("sha256",CanonicalJson::encode($r)));}
}
