<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Conscription;
use App\Bootstrap\BootstrapState;use App\Bootstrap\CanonicalJson;use App\Bootstrap\StateStore;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class ExaminationManifestationAssemblyService
{
 private string $authorizations;private string $candidates;private string $custody;private string $deliveries;
 public function __construct(#[Autowire('%kernel.project_dir%')] string $root,private StateStore $bootstrap){$this->authorizations=$root.'/var/imperium/offices/conscription/examination-assembly-authorization-dispositions';$this->candidates=$root.'/var/imperium/offices/laboratorium/profile-candidates';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->deliveries=$root.'/var/imperium/offices/senate/examination-manifestation-intake';}
 public function assemble(string $id):array
 {
  if(!preg_match('/^examination-assembly-authorization-disposition-[a-f0-9]{20}$/',$id))throw new \InvalidArgumentException('R100_EXAMINATION_ASSEMBLY_AUTHORIZATION_ID_INVALID');
  $a=$this->read($this->authorizations.'/'.$id.'.json','R101_EXAMINATION_ASSEMBLY_AUTHORIZATION_ABSENT');$candidateId=$a['source_profile_candidate']['id']??null;$p=is_string($candidateId)?$this->read($this->candidates.'/'.$candidateId.'.json','R102_PROFILE_CANDIDATE_ABSENT'):[];$custodyId=$a['custody_lease']['custody_id']??null;$c=is_string($custodyId)?$this->read($this->custody.'/'.$custodyId.'.json','R103_PROFILE_CANDIDATE_CUSTODY_ABSENT'):[];[$instance,$r]=$this->recruiter();$this->validate($a,$p,$c,$instance,$r);
  foreach(glob($this->deliveries.'/examination-manifestation-delivery-*.json')?:[] as $path){$x=$this->read($path,'R106_EXAMINATION_MANIFESTATION_CONFLICT');if(!$this->ok($x))throw new \RuntimeException('R106_EXAMINATION_MANIFESTATION_CONFLICT');if(($x['source_authorization']['id']??null)===$id)return $x;}
  $actor=['seat'=>'conscription.recruiter','manifestation_id'=>$r['manifestation_id'],'occupancy_generation'=>$r['occupancy_generation']];
  $mid='examination-manifestation-'.substr(hash('sha256',CanonicalJson::encode([$a['record_digest'],$p['record_digest'],$a['assembly_contract']])),0,20);
  $m=['manifestation_id'=>$mid,'instance_id'=>$instance,'persona'=>$a['persona'],'profile'=>['profile_id'=>$p['profile_id'],'profile_version'=>$p['profile_version'],'candidate_id'=>$candidateId,'candidate_digest'=>$p['record_digest'],'installation_class'=>'EXAMINATION_ONLY'],'substrate'=>['kind'=>'generic-officer','version'=>0,'identity_contribution'=>false,'authority_contribution'=>false],'purpose'=>'SENATE_EXAMINATION_ONLY','target'=>'senate.stand','return_destination'=>'conscription.recruiter','operational_use_permitted'=>false,'credentials_granted'=>false,'tool_access_granted'=>false,'external_action_authority'=>false];
  $deliveryId='examination-manifestation-delivery-'.substr(hash('sha256',CanonicalJson::encode([$id,$a['record_digest'],$m])),0,20);
  return $this->save($deliveryId,['schema'=>'imperium.conscription-senate-examination-manifestation-delivery/v1','delivery_id'=>$deliveryId,'instance_id'=>$instance,'proceeding_id'=>$a['proceeding_id'],'assembler'=>$actor,'recipient'=>['office'=>'senate','seat'=>'senate.bailiff','surface'=>'senate.stand.intake'],'source_authorization'=>['id'=>$id,'digest'=>$a['record_digest']],'source_profile_candidate'=>$a['source_profile_candidate'],'source_profile_candidate_acceptance'=>$a['source_profile_candidate_acceptance'],'source_return'=>$a['source_return'],'source_authorization_act'=>$a['source_authorization_act'],'source_reservation_disposition'=>$a['source_reservation_disposition'],'source_plan'=>$a['source_plan'],'profile_scope'=>$a['profile_scope'],'custody_lease'=>$a['custody_lease'],'assembly_contract'=>$a['assembly_contract'],'manifestation'=>$m,'examination_profile_installed'=>true,'examination_manifestation_assembled'=>true,'examination_profile_installation_authority_consumed'=>true,'examination_assembly_authority_consumed'=>true,'status'=>'EXAMINATION_MANIFESTATION_ASSEMBLED_DELIVERED_PENDING_SENATE_STAND_INTAKE','recipient_acceptance'=>null,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'examination_assembly_authority'=>false,'senate_examination_authority'=>false,'custody_release_authority'=>false,'persona_substitution_authority'=>false,'spawning_authority'=>false,'seat_binding_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
 }
 private function validate(array $a,array $p,array $c,string $instance,array $r):void{$x=$a['assembly_contract']??null;if(!$this->ok($a)||!$this->ok($p)||!$this->ok($c)||'imperium.senate-conscription-examination-assembly-authorization-disposition/v1'!==($a['schema']??null)||$instance!==($a['instance_id']??null)||'ACCEPTED'!==($a['disposition']??null)||'EXAMINATION_ASSEMBLY_AUTHORIZED_PENDING_CONSCRIPTION_ASSEMBLY'!==($a['status']??null)||true!==($a['examination_profile_installation_authority']??null)||true!==($a['examination_assembly_authority']??null)||true!==($a['examination_assembly_authority_exercisable']??null)||true===($a['profile_installation_authority']??null)||true===($a['senate_examination_authority']??null)||!is_array($x)||'generic-officer'!==($x['substrate']['kind']??null)||0!==($x['substrate']['version']??null)||'SENATE_EXAMINATION_ONLY'!==($x['purpose']??null)||'senate.stand'!==($x['target']??null)||false!==($x['operational_use_permitted']??null)||($a['source_profile_candidate']['digest']??null)!==($p['record_digest']??null)||CanonicalJson::encode($a['persona']??null)!==CanonicalJson::encode($p['persona']??null)||'ADMITTED_HELD'!==($c['custody_state']??null)||true!==($c['available']??null)||($a['custody_lease']['custody_digest']??null)!==($c['record_digest']??null)||($a['recipient']['manifestation_id']??null)!==($r['manifestation_id']??null))throw new \RuntimeException('R104_EXAMINATION_ASSEMBLY_CHAIN_INVALID');}
 private function recruiter():array{$s=$this->bootstrap->read();if(!is_array($s)||BootstrapState::CuriaReady->value!==($s['state']??null))throw new \RuntimeException('R105_RECRUITER_UNAVAILABLE');for($i=count($s['events']??[])-1;$i>=0;--$i){$e=$s['events'][$i];$r='T04'===($e['transition']??null)&&'SUCCESS'===($e['result']??null)?($e['output']['successor']??null):null;if(is_array($r)&&'conscription.recruiter'===($r['seat']??null)&&'ordinary-recruiter'===($r['authority']??null))return[(string)($s['binding']['instance_id']??''),$r];}throw new \RuntimeException('R105_RECRUITER_UNAVAILABLE');}
 private function read(string $p,string $e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array $r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
 private function save(string $id,array $r):array{if(!is_dir($this->deliveries)&&!mkdir($this->deliveries,0770,true)&&!is_dir($this->deliveries))throw new \RuntimeException('R107_EXAMINATION_MANIFESTATION_ASSEMBLY_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->deliveries.'/'.$id.'.json';if(is_file($p)){if(CanonicalJson::encode($x=$this->read($p,'R106_EXAMINATION_MANIFESTATION_CONFLICT'))!==CanonicalJson::encode($r))throw new \RuntimeException('R106_EXAMINATION_MANIFESTATION_CONFLICT');return $x;}$t=$p.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException('R107_EXAMINATION_MANIFESTATION_ASSEMBLY_FAILED');}return $r;}
}
