<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Conscription;
use App\Bootstrap\{BootstrapState,CanonicalJson,StateStore};use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class ModelBoundOperationalProfileQualificationService
{
 private string $approvals;private string $dispositions;private string $bindings;private string $attestations;private string $authorizations;private string $qualifications;
 public function __construct(#[Autowire('%kernel.project_dir%')]string$root,private StateStore$bootstrap){$this->approvals=$root.'/var/imperium/imperator/model-bound-profile-approval-decisions';$this->dispositions=$root.'/var/imperium/offices/senate/model-bound-profile-dispositions';$this->bindings=$root.'/var/imperium/offices/conscription/profile-model-bindings';$this->attestations=$root.'/var/imperium/offices/clavium/profile-model-access-attestations';$this->authorizations=$root.'/var/imperium/authorizations/missions';$this->qualifications=$root.'/var/imperium/offices/conscription/model-bound-operational-profile-qualifications';}
 public function qualify(string$id,\DateTimeImmutable$qualifiedAt):array
 {
  if(!preg_match('/^model-bound-profile-approval-decision-[a-f0-9]{20}$/',$id))throw new \InvalidArgumentException('R200_MODEL_BOUND_PROFILE_APPROVAL_ID_INVALID');$a=$this->read($this->approvals.'/'.$id.'.json','R201_MODEL_BOUND_PROFILE_APPROVAL_ABSENT');foreach(glob($this->qualifications.'/*.json')?:[]as$p){$x=$this->read($p,'R208_MODEL_BOUND_QUALIFICATION_CONFLICT');if(($x['source_imperator_approval']['id']??null)===$id){if(($x['source_imperator_approval']['digest']??null)!==($a['record_digest']??null))throw new \RuntimeException('R208_MODEL_BOUND_QUALIFICATION_CONFLICT');return$x;}}
  $d=$this->read($this->dispositions.'/'.($a['source_senate_disposition']['id']??'').'.json','R202_MODEL_BOUND_SENATE_DISPOSITION_ABSENT');$b=$this->binding($a['subject_profile']??[]);$t=$this->attestation($b);$m=$this->read($this->authorizations.'/'.($b['mission_authorization']['id']??'').'.json','R203_MODEL_BOUND_MISSION_AUTHORIZATION_ABSENT');[$instance,$recruiter]=$this->recruiter();$this->validate($id,$a,$d,$b,$t,$m,$instance,$qualifiedAt);$profile=$b['sealed_profile'];$actor=['seat'=>'conscription.recruiter','manifestation_id'=>$recruiter['manifestation_id'],'occupancy_generation'=>$recruiter['occupancy_generation']];$authority=$a['operational_qualification_request'];$assemblyAuthority='model-bound-manifestation-assembly-authority-'.substr(hash('sha256',CanonicalJson::encode([$id,$a['record_digest'],$profile['content_digest']])),0,20);$qid='model-bound-operational-profile-qualification-'.substr(hash('sha256',CanonicalJson::encode([$id,$a['record_digest'],$b['record_digest'],$t['record_digest'],$actor,$qualifiedAt->format(DATE_ATOM)])),0,20);
  return$this->save($qid,['schema'=>'imperium.conscription-model-bound-operational-profile-qualification/v1','qualification_id'=>$qid,'instance_id'=>$instance,'case_id'=>$a['case_id'],'case_digest'=>$a['case_digest'],'qualifier'=>$actor,'qualified_at'=>$qualifiedAt->format(DATE_ATOM),'source_imperator_approval'=>['id'=>$id,'digest'=>$a['record_digest']],'source_senate_disposition'=>$a['source_senate_disposition'],'source_model_binding'=>['id'=>$b['binding_id'],'digest'=>$b['record_digest']],'source_access_attestation'=>['id'=>$t['attestation_id'],'digest'=>$t['record_digest']],'source_mission_authorization'=>['id'=>$m['authorization_id'],'digest'=>$m['record_digest']],'subject_profile'=>$a['subject_profile'],'operational_profile'=>$profile,'source_persona'=>$profile['source_persona'],'intended_seat'=>$profile['target'],'substrate_contract'=>['kind'=>'generic-officer','version'=>0,'identity_contribution'=>false,'authority_contribution'=>false],'qualification_request_authority'=>['id'=>$authority['authority_id'],'consumed'=>true,'continuing_authority'=>false],'qualification_checks'=>['imperator_approval_exact'=>true,'senate_disposition_approved'=>true,'model_binding_exact'=>true,'access_available'=>true,'mission_authorization_exact'=>true,'source_persona_admitted'=>true,'target_seat_immutable'=>true,'generic_officer_v0_compatible'=>true],'status'=>'PROFILE_OPERATIONALLY_QUALIFIED_PENDING_MANIFESTATION_ASSEMBLY','profile_installation_scope_consumed'=>true,'profile_installed'=>true,'profile_operationally_qualified'=>true,'manifestation_assembly_authority'=>['authority_id'=>$assemblyAuthority,'authority_single_use'=>true,'consumed'=>false],'manifestation_assembly_authority_exercisable'=>true,'seat_binding_authority'=>false,'deployment_authority'=>false,'custody_transfer_authority'=>false,'tool_use_authority'=>false,'credential_use_authority'=>false,'external_action_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
 }
 private function validate(string$id,array$a,array$d,array$b,array$t,array$m,string$instance,\DateTimeImmutable$qualifiedAt):void{$p=$b['sealed_profile']??[];$q=$a['operational_qualification_request']??[];if(!$this->ok($a)||!$this->ok($d)||!$this->ok($b)||!$this->ok($t)||!$this->ok($m)||'imperium.imperator-model-bound-profile-approval-decision/v1'!==($a['schema']??null)||$id!==($a['decision_id']??null)||$instance!==($a['instance_id']??null)||'APPROVED'!==($a['disposition']??null)||'IMPERATOR_PROFILE_APPROVED_PENDING_CONSCRIPTION_OPERATIONAL_QUALIFICATION'!==($a['status']??null)||true!==($a['profile_approved']??null)||true!==($a['operational_qualification_request_authority']??null)||true!==($q['authority_single_use']??null)||false!==($q['consumed']??null)||'conscription.recruiter'!==($q['destination']??null)||'REQUEST_ONE_EXACT_OPERATIONAL_PROFILE_QUALIFICATION'!==($q['purpose']??null)||true!==($a['sealed']??null)||($a['source_senate_disposition']['digest']??null)!==($d['record_digest']??null)||'APPROVED'!==($d['decision']['disposition']??null)||true===($d['mandatory_security_blocking_condition']??null)||($a['subject_profile']??null)!==($d['subject_profile']??null)||($a['subject_profile']['content_digest']??null)!==($p['content_digest']??null)||!$this->profileOk($p)||'officer'!==($p['artifact_class']??null)||'admitted'!==($p['source_persona']['admission_state']??null)||'seat'!==($p['target']['kind']??null)||($t['model_binding']['binding_digest']??null)!==$b['record_digest']||'imperium.senate-model-bound-profile-disposition/v1'!==($d['schema']??null)||'imperium.conscription-profile-model-binding/v1'!==($b['schema']??null)||'imperium.clavium-profile-model-access-attestation/v1'!==($t['schema']??null)||'imperium.mission-authorization/v1'!==($m['schema']??null)||'ACCESS_AVAILABLE'!==($t['status']??null)||!is_string($t['provider_access_evidence']['expires_at']??null)||new \DateTimeImmutable($t['provider_access_evidence']['expires_at'])<=$qualifiedAt||true!==($t['sealed']??null)||($b['mission_authorization']['digest']??null)!==$m['record_digest']||'MISSION_AUTHORIZATION_SEALED_PENDING_AUTHORIZED_PREPARATION'!==($m['status']??null))throw new \RuntimeException('R204_MODEL_BOUND_QUALIFICATION_CHAIN_INVALID');foreach(['operational_qualification_authority','profile_installation_authority','profile_activation_authority','manifestation_assembly_authority','seat_binding_authority','deployment_authority','custody_transfer_authority','tool_use_authority','credential_use_authority','external_action_authority','execution_authority']as$f)if(true===($a[$f]??null))throw new \RuntimeException('R204_MODEL_BOUND_QUALIFICATION_CHAIN_INVALID');}
 private function binding(array$s):array{foreach(glob($this->bindings.'/*.json')?:[]as$p){$b=$this->read($p,'R205_MODEL_BOUND_PROFILE_BINDING_CONFLICT');$x=$b['sealed_profile']??[];if(($s['profile_id']??null)===($x['profile_id']??null)&&($s['profile_version']??null)===($x['profile_version']??null)&&($s['content_digest']??null)===($x['content_digest']??null)&&($s['target']??null)===($x['target']??null))return$b;}throw new \RuntimeException('R205_MODEL_BOUND_PROFILE_BINDING_ABSENT');}
 private function attestation(array$b):array{foreach(glob($this->attestations.'/*.json')?:[]as$p){$t=$this->read($p,'R206_MODEL_BOUND_ACCESS_ATTESTATION_CONFLICT');if(($t['model_binding']['binding_id']??null)===($b['binding_id']??null)&&($t['model_binding']['binding_digest']??null)===($b['record_digest']??null))return$t;}throw new \RuntimeException('R206_MODEL_BOUND_ACCESS_ATTESTATION_ABSENT');}
 private function recruiter():array{$s=$this->bootstrap->read();if(!is_array($s)||BootstrapState::CuriaReady->value!==($s['state']??null))throw new \RuntimeException('R207_MODEL_BOUND_RECRUITER_UNAVAILABLE');for($i=count($s['events']??[])-1;$i>=0;--$i){$r='T04'===($s['events'][$i]['transition']??null)&&'SUCCESS'===($s['events'][$i]['result']??null)?($s['events'][$i]['output']['successor']??null):null;if(is_array($r)&&'conscription.recruiter'===($r['seat']??null)&&'ordinary-recruiter'===($r['authority']??null))return[(string)$s['binding']['instance_id'],$r];}throw new \RuntimeException('R207_MODEL_BOUND_RECRUITER_UNAVAILABLE');}
 private function profileOk(array$p):bool{$d=$p['content_digest']??null;unset($p['content_digest']);return is_string($d)&&hash_equals($d,'sha256:'.hash('sha256',CanonicalJson::encode($p)));}private function read($p,$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save($id,array$r):array{if(!is_dir($this->qualifications))mkdir($this->qualifications,0770,true);$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->qualifications.'/'.$id.'.json';if(is_file($p))return$this->read($p,'R208_MODEL_BOUND_QUALIFICATION_CONFLICT');file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
