<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Conscription;
use App\Bootstrap\BootstrapState;use App\Bootstrap\CanonicalJson;use App\Bootstrap\StateStore;use App\Imperium\Runtime\Identity\OfficerClass;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class OperationalManifestationAssemblyService
{
 private string$qualifications;private string$candidates;private string$custody;private string$assemblies;
 public function __construct(#[Autowire('%kernel.project_dir%')]string$root,private StateStore$bootstrap){$this->qualifications=$root.'/var/imperium/offices/conscription/operational-profile-qualifications';$this->candidates=$root.'/var/imperium/offices/laboratorium/profile-candidates';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->assemblies=$root.'/var/imperium/offices/conscription/operational-manifestation-assemblies';}
 public function assemble(string$qualificationId):array
 {
  if(!preg_match('/^operational-profile-qualification-[a-f0-9]{20}$/',$qualificationId))throw new \InvalidArgumentException('R116_OPERATIONAL_PROFILE_QUALIFICATION_ID_INVALID');
  $q=$this->read($this->qualifications.'/'.$qualificationId.'.json','R117_OPERATIONAL_PROFILE_QUALIFICATION_ABSENT');foreach(glob($this->assemblies.'/operational-manifestation-assembly-*.json')?:[]as$path){$prior=$this->read($path,'R122_OPERATIONAL_MANIFESTATION_ASSEMBLY_CONFLICT');if(!$this->ok($prior))throw new \RuntimeException('R122_OPERATIONAL_MANIFESTATION_ASSEMBLY_CONFLICT');if(($prior['source_qualification']['id']??null)===$qualificationId){if(($prior['source_qualification']['digest']??null)!==($q['record_digest']??null))throw new \RuntimeException('R122_OPERATIONAL_MANIFESTATION_ASSEMBLY_CONFLICT');return$prior;}}
  $candidateId=$q['profile_candidate']['id']??null;$p=is_string($candidateId)?$this->read($this->candidates.'/'.$candidateId.'.json','R118_PROFILE_CANDIDATE_ABSENT'):[];$custodyId=$q['custody_lease']['custody_id']??null;$c=is_string($custodyId)?$this->read($this->custody.'/'.$custodyId.'.json','R119_OPERATIONAL_MANIFESTATION_CUSTODY_ABSENT'):[];[$instance,$recruiter]=$this->recruiter();$this->validate($qualificationId,$q,$p,$c,$instance);
  $actor=['seat'=>'conscription.recruiter','manifestation_id'=>$recruiter['manifestation_id'],'occupancy_generation'=>$recruiter['occupancy_generation']];$profile=$q['operational_profile'];$mid='operational-manifestation-'.substr(hash('sha256',CanonicalJson::encode([$qualificationId,$q['record_digest'],$q['persona_identity'],$profile,$profile['substrate_contract']])),0,20);
  $m=['manifestation_id'=>$mid,'instance_id'=>$instance,'officer_class'=>OfficerClass::Delegate->value,'persona'=>$q['persona_identity'],'profile'=>$profile,'substrate'=>$profile['substrate_contract'],'intended_seat'=>$profile['intended_seat'],'custody_lease'=>$q['custody_lease'],'return_destination'=>$profile['return_destination'],'status'=>'ASSEMBLED_UNBOUND','seat_bound'=>false,'operational_use_permitted'=>false,'tool_access_granted'=>false,'credentials_granted'=>false,'external_action_authority'=>false,'deployment_authority'=>false,'custody_transfer_authority'=>false,'execution_authority'=>false];
  $id='operational-manifestation-assembly-'.substr(hash('sha256',CanonicalJson::encode([$qualificationId,$q['record_digest'],$p['record_digest'],$c['record_digest'],$actor,$m])),0,20);
  return$this->save($id,['schema'=>'imperium.conscription-operational-manifestation-assembly/v1','assembly_id'=>$id,'instance_id'=>$instance,'case_id'=>$q['case_id'],'case_digest'=>$q['case_digest'],'assembler'=>$actor,'source_qualification'=>['id'=>$qualificationId,'digest'=>$q['record_digest']],'source_imperator_approval'=>$q['source_imperator_approval'],'source_senate_disposition'=>$q['source_senate_disposition'],'admitted_findings'=>$q['admitted_findings'],'reconciliation'=>$q['reconciliation'],'profile_candidate'=>$q['profile_candidate'],'persona_identity'=>$q['persona_identity'],'custody_lease'=>$q['custody_lease'],'manifestation'=>$m,'status'=>'OPERATIONAL_MANIFESTATION_ASSEMBLED_PENDING_SEAT_BINDING','manifestation_assembly_authority_consumed'=>true,'operational_manifestation_assembled'=>true,'seat_binding_authority'=>true,'seat_binding_authority_exercisable'=>true,'seat_bound'=>false,'deployment_authority'=>false,'custody_transfer_authority'=>false,'tool_access_authority'=>false,'credentials_authority'=>false,'external_action_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
 }
 private function validate(string$id,array$q,array$p,array$c,string$instance):void
 {
  $o=$q['operational_profile']??null;if(!$this->ok($q)||!$this->ok($p)||!$this->ok($c)||'imperium.conscription-operational-profile-qualification/v1'!==($q['schema']??null)||$id!==($q['qualification_id']??null)||$instance!==($q['instance_id']??null)||'PROFILE_OPERATIONALLY_QUALIFIED_PENDING_MANIFESTATION_ASSEMBLY'!==($q['status']??null)||true!==($q['operational_qualification_request_authority_consumed']??null)||true!==($q['profile_installation_scope_consumed']??null)||true!==($q['profile_installed']??null)||true!==($q['profile_operationally_qualified']??null)||true!==($q['manifestation_assembly_authority']??null)||true!==($q['manifestation_assembly_authority_exercisable']??null)||true===($q['seat_binding_authority']??null)||true===($q['deployment_authority']??null)||true===($q['custody_transfer_authority']??null)||true===($q['execution_authority']??null)||true!==($q['sealed']??null)||!is_array($o)
  ||'imperium.laboratorium-profile-candidate/v1'!==($p['schema']??null)||($q['profile_candidate']['id']??null)!==($p['candidate_id']??null)||($q['profile_candidate']['digest']??null)!==($p['record_digest']??null)||CanonicalJson::encode($q['persona_identity']??null)!==CanonicalJson::encode($p['persona']??null)||($o['candidate_digest']??null)!==($p['record_digest']??null)||CanonicalJson::encode($o['mission']??null)!==CanonicalJson::encode($p['profile']['mission']??null)||CanonicalJson::encode($o['limitations']??null)!==CanonicalJson::encode($p['profile']['limitations']??null)||'generic-officer'!==($o['substrate_contract']['kind']??null)||0!==($o['substrate_contract']['version']??null)||false!==($o['substrate_contract']['identity_contribution']??null)||false!==($o['substrate_contract']['authority_contribution']??null)||!is_string($o['intended_seat']['seat']??null)||'mission.operative.'.($p['profile_scope']['capability_slot_id']??'')!==($o['intended_seat']['seat']??null)
  ||'imperium.garrison-persona-custody/v1'!==($c['schema']??null)||($q['custody_lease']['custody_digest']??null)!==($c['record_digest']??null)||($q['persona_identity']['persona_id']??null)!==($c['persona_id']??null)||$instance!==($c['instance_id']??null)||'ADMITTED_HELD'!==($c['custody_state']??null)||true!==($c['available']??null))throw new \RuntimeException('R120_OPERATIONAL_MANIFESTATION_ASSEMBLY_CHAIN_INVALID');
 }
 private function recruiter():array{$s=$this->bootstrap->read();if(!is_array($s)||BootstrapState::CuriaReady->value!==($s['state']??null))throw new \RuntimeException('R121_RECRUITER_UNAVAILABLE');for($i=count($s['events']??[])-1;$i>=0;--$i){$e=$s['events'][$i];$r='T04'===($e['transition']??null)&&'SUCCESS'===($e['result']??null)?($e['output']['successor']??null):null;if(is_array($r)&&'conscription.recruiter'===($r['seat']??null)&&'ordinary-recruiter'===($r['authority']??null)&&is_string($r['manifestation_id']??null))return[(string)($s['binding']['instance_id']??''),$r];}throw new \RuntimeException('R121_RECRUITER_UNAVAILABLE');}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
 private function save(string$id,array$r):array{if(!is_dir($this->assemblies)&&!mkdir($this->assemblies,0770,true)&&!is_dir($this->assemblies))throw new \RuntimeException('R123_OPERATIONAL_MANIFESTATION_ASSEMBLY_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->assemblies.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'R122_OPERATIONAL_MANIFESTATION_ASSEMBLY_CONFLICT');if(CanonicalJson::encode($x)!==CanonicalJson::encode($r))throw new \RuntimeException('R122_OPERATIONAL_MANIFESTATION_ASSEMBLY_CONFLICT');return$x;}$t=$p.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException('R123_OPERATIONAL_MANIFESTATION_ASSEMBLY_FAILED');}return$r;}
}
