<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Conscription;
use App\Bootstrap\BootstrapState;use App\Bootstrap\CanonicalJson;use App\Bootstrap\StateStore;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class OperationalProfileQualificationService
{
 private string$approvals;private string$candidates;private string$custody;private string$qualifications;
 public function __construct(#[Autowire('%kernel.project_dir%')]string$root,private StateStore$bootstrap){$this->approvals=$root.'/var/imperium/imperator/profile-approval-decisions';$this->candidates=$root.'/var/imperium/offices/laboratorium/profile-candidates';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->qualifications=$root.'/var/imperium/offices/conscription/operational-profile-qualifications';}
 public function qualify(string$approvalId):array
 {
  if(!preg_match('/^profile-approval-decision-[a-f0-9]{20}$/',$approvalId))throw new \InvalidArgumentException('R108_PROFILE_APPROVAL_ID_INVALID');
  $a=$this->read($this->approvals.'/'.$approvalId.'.json','R109_PROFILE_APPROVAL_ABSENT');$candidateId=$a['profile_candidate']['candidate_id']??null;$p=is_string($candidateId)?$this->read($this->candidates.'/'.$candidateId.'.json','R110_PROFILE_CANDIDATE_ABSENT'):[];$custodyId=$a['custody_lease']['custody_id']??null;$c=is_string($custodyId)?$this->read($this->custody.'/'.$custodyId.'.json','R111_OPERATIONAL_PROFILE_CUSTODY_ABSENT'):[];[$instance,$recruiter]=$this->recruiter();$this->validate($approvalId,$a,$p,$c,$instance);
  foreach(glob($this->qualifications.'/operational-profile-qualification-*.json')?:[]as$path){$prior=$this->read($path,'R114_OPERATIONAL_PROFILE_QUALIFICATION_CONFLICT');if(!$this->ok($prior))throw new \RuntimeException('R114_OPERATIONAL_PROFILE_QUALIFICATION_CONFLICT');if(($prior['source_imperator_approval']['id']??null)===$approvalId)return$prior;}
  $actor=['seat'=>'conscription.recruiter','manifestation_id'=>$recruiter['manifestation_id'],'occupancy_generation'=>$recruiter['occupancy_generation']];$slot=$p['profile_scope']['capability_slot_id'];$seat='mission.operative.'.$slot;
  $operational=['profile_id'=>$p['profile_id'],'profile_version'=>$p['profile_version'],'candidate_id'=>$candidateId,'candidate_digest'=>$p['record_digest'],'installation_class'=>'OPERATIONAL_QUALIFIED','intended_seat'=>['seat'=>$seat,'seat_class'=>'mission.operative','capability_slot_id'=>$slot],'mission'=>$p['profile']['mission'],'limitations'=>$p['profile']['limitations'],'tool_requirements'=>$p['profile_scope']['tool_requirements'],'data_requirements'=>$p['profile_scope']['data_requirements'],'stop_conditions'=>$p['profile_scope']['stop_conditions'],'return_destination'=>$p['return_destination'],'examination_return_destination'=>$a['return_destination'],'substrate_contract'=>['kind'=>'generic-officer','version'=>0,'identity_contribution'=>false,'authority_contribution'=>false]];
  $id='operational-profile-qualification-'.substr(hash('sha256',CanonicalJson::encode([$approvalId,$a['record_digest'],$p['record_digest'],$c['record_digest'],$actor,$operational])),0,20);
  return$this->save($id,['schema'=>'imperium.conscription-operational-profile-qualification/v1','qualification_id'=>$id,'instance_id'=>$instance,'case_id'=>$a['case_id'],'case_digest'=>$a['case_digest'],'qualifier'=>$actor,'source_imperator_approval'=>['id'=>$approvalId,'digest'=>$a['record_digest']],'source_senate_disposition'=>$a['source_senate_disposition'],'admitted_findings'=>$a['admitted_findings'],'reconciliation'=>$a['reconciliation'],'profile_candidate'=>['id'=>$candidateId,'digest'=>$p['record_digest']],'persona_identity'=>$a['persona_identity'],'custody_lease'=>$a['custody_lease'],'operational_profile'=>$operational,'qualification_checks'=>['imperator_approval_exact'=>true,'senate_disposition_approved'=>true,'persona_identity_exact'=>true,'custody_live_and_available'=>true,'mission_scope_immutable'=>true,'tools_and_data_bounded'=>true,'stop_conditions_present'=>true,'return_contract_preserved'=>true,'generic_officer_v0_compatible'=>true,'intended_seat_derived_from_capability_slot'=>true],'status'=>'PROFILE_OPERATIONALLY_QUALIFIED_PENDING_MANIFESTATION_ASSEMBLY','operational_qualification_request_authority_consumed'=>true,'profile_installation_scope_consumed'=>true,'profile_installed'=>true,'profile_operationally_qualified'=>true,'manifestation_assembly_authority'=>true,'manifestation_assembly_authority_exercisable'=>true,'seat_binding_authority'=>false,'deployment_authority'=>false,'custody_transfer_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
 }
 private function validate(string$id,array$a,array$p,array$c,string$instance):void
 {
  if(!$this->ok($a)||!$this->ok($p)||!$this->ok($c)||'imperium.imperator-profile-approval-decision/v1'!==($a['schema']??null)||$id!==($a['decision_id']??null)||$instance!==($a['instance_id']??null)||'APPROVED'!==($a['disposition']??null)||'IMPERATOR_PROFILE_APPROVED_PENDING_CONSCRIPTION_OPERATIONAL_QUALIFICATION'!==($a['status']??null)||true!==($a['imperator_profile_approval_consumed']??null)||true!==($a['profile_approved']??null)||true!==($a['operational_qualification_request_authority']??null)||true===($a['profile_installation_authority']??null)||true===($a['manifestation_assembly_authority']??null)||true===($a['seat_binding_authority']??null)||true===($a['deployment_authority']??null)||true===($a['execution_authority']??null)||true!==($a['sealed']??null)||'APPROVED'!==($a['source_senate_disposition']['decision']['disposition']??null)||!is_array($a['admitted_findings']??null)||3!==count($a['admitted_findings'])||!is_array($a['reconciliation']??null)
  ||'imperium.laboratorium-profile-candidate/v1'!==($p['schema']??null)||($a['profile_candidate']['candidate_id']??null)!==($p['candidate_id']??null)||($a['profile_candidate']['candidate_digest']??null)!==($p['record_digest']??null)||true!==($p['profile_elaboration_complete']??null)||true!==($p['sealed']??null)||'MISSION_OPERATIVE'!==($p['profile_scope']['target_kind']??null)||!is_string($p['profile_scope']['capability_slot_id']??null)||''===trim($p['profile_scope']['capability_slot_id'])||!is_array($p['profile_scope']['tool_requirements']??null)||[]===($p['profile_scope']['tool_requirements']??[])||!is_array($p['profile_scope']['data_requirements']??null)||[]===($p['profile_scope']['data_requirements']??[])||!is_array($p['profile_scope']['stop_conditions']??null)||[]===($p['profile_scope']['stop_conditions']??[])||CanonicalJson::encode($a['persona_identity']??null)!==CanonicalJson::encode($p['persona']??null)||CanonicalJson::encode($a['custody_lease']??null)!==CanonicalJson::encode($p['custody_lease']??null)||'conscription.recruiter'!==($a['return_destination']??null)||'conscription'!==($p['return_destination']['office']??null)||'conscription.recruiter'!==($p['return_destination']['seat']??null)
  ||'imperium.garrison-persona-custody/v1'!==($c['schema']??null)||($a['custody_lease']['custody_digest']??null)!==($c['record_digest']??null)||($a['persona_identity']['persona_id']??null)!==($c['persona_id']??null)||$instance!==($c['instance_id']??null)||'ADMITTED_HELD'!==($c['custody_state']??null)||true!==($c['available']??null)||'garrison'!==($a['custody_lease']['custodian']??null))throw new \RuntimeException('R112_OPERATIONAL_PROFILE_QUALIFICATION_CHAIN_INVALID');
 }
 private function recruiter():array{$s=$this->bootstrap->read();if(!is_array($s)||BootstrapState::CuriaReady->value!==($s['state']??null))throw new \RuntimeException('R113_RECRUITER_UNAVAILABLE');for($i=count($s['events']??[])-1;$i>=0;--$i){$e=$s['events'][$i];$r='T04'===($e['transition']??null)&&'SUCCESS'===($e['result']??null)?($e['output']['successor']??null):null;if(is_array($r)&&'conscription.recruiter'===($r['seat']??null)&&'ordinary-recruiter'===($r['authority']??null)&&is_string($r['manifestation_id']??null))return[(string)($s['binding']['instance_id']??''),$r];}throw new \RuntimeException('R113_RECRUITER_UNAVAILABLE');}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
 private function save(string$id,array$r):array{if(!is_dir($this->qualifications)&&!mkdir($this->qualifications,0770,true)&&!is_dir($this->qualifications))throw new \RuntimeException('R115_OPERATIONAL_PROFILE_QUALIFICATION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->qualifications.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'R114_OPERATIONAL_PROFILE_QUALIFICATION_CONFLICT');if(CanonicalJson::encode($x)!==CanonicalJson::encode($r))throw new \RuntimeException('R114_OPERATIONAL_PROFILE_QUALIFICATION_CONFLICT');return$x;}$t=$p.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException('R115_OPERATIONAL_PROFILE_QUALIFICATION_FAILED');}return$r;}
}
