<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Conscription;
use App\Bootstrap\BootstrapState;use App\Bootstrap\CanonicalJson;use App\Bootstrap\StateStore;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class OperationalManifestationSeatBindingService
{
 private string$assemblies;private string$qualifications;private string$custody;private string$occupancy;
 public function __construct(#[Autowire('%kernel.project_dir%')]string$root,private StateStore$bootstrap){$this->assemblies=$root.'/var/imperium/offices/conscription/operational-manifestation-assemblies';$this->qualifications=$root.'/var/imperium/offices/conscription/operational-profile-qualifications';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->occupancy=$root.'/var/imperium/mission/occupancy';}
 public function bind(string$assemblyId):array
 {
  if(!preg_match('/^operational-manifestation-assembly-[a-f0-9]{20}$/',$assemblyId))throw new \InvalidArgumentException('R124_OPERATIONAL_MANIFESTATION_ASSEMBLY_ID_INVALID');
  $a=$this->read($this->assemblies.'/'.$assemblyId.'.json','R125_OPERATIONAL_MANIFESTATION_ASSEMBLY_ABSENT');foreach(glob($this->occupancy.'/operational-seat-binding-*.json')?:[]as$path){$prior=$this->read($path,'R130_OPERATIONAL_SEAT_BINDING_CONFLICT');if(!$this->ok($prior))throw new \RuntimeException('R130_OPERATIONAL_SEAT_BINDING_CONFLICT');if(($prior['source_assembly']['id']??null)===$assemblyId){if(($prior['source_assembly']['digest']??null)!==($a['record_digest']??null))throw new \RuntimeException('R130_OPERATIONAL_SEAT_BINDING_CONFLICT');return$prior;}if(($prior['seat']??null)===($a['manifestation']['intended_seat']['seat']??null)&&in_array($prior['status']??null,['OPERATIONAL_MANIFESTATION_BOUND_PENDING_DEPLOYMENT_AUTHORIZATION','ACTIVE'],true))throw new \RuntimeException('R131_OPERATIONAL_SEAT_ALREADY_OCCUPIED');}
  $qualificationId=$a['source_qualification']['id']??null;$q=is_string($qualificationId)?$this->read($this->qualifications.'/'.$qualificationId.'.json','R126_OPERATIONAL_PROFILE_QUALIFICATION_ABSENT'):[];$custodyId=$a['custody_lease']['custody_id']??null;$c=is_string($custodyId)?$this->read($this->custody.'/'.$custodyId.'.json','R127_OPERATIONAL_SEAT_BINDING_CUSTODY_ABSENT'):[];[$instance,$recruiter]=$this->recruiter();$this->validate($assemblyId,$a,$q,$c,$instance);
  $actor=['seat'=>'conscription.recruiter','manifestation_id'=>$recruiter['manifestation_id'],'occupancy_generation'=>$recruiter['occupancy_generation']];$seat=$a['manifestation']['intended_seat']['seat'];$id='operational-seat-binding-'.substr(hash('sha256',CanonicalJson::encode([$assemblyId,$a['record_digest'],$q['record_digest'],$c['record_digest'],$actor,$seat,0,1,null])),0,20);
  return$this->save($id,['schema'=>'imperium.operational-manifestation-seat-binding/v1','binding_id'=>$id,'instance_id'=>$instance,'case_id'=>$a['case_id'],'case_digest'=>$a['case_digest'],'binder'=>$actor,'office'=>'mission','seat'=>$seat,'manifestation_id'=>$a['manifestation']['manifestation_id'],'manifestation'=>$a['manifestation'],'source_assembly'=>['id'=>$assemblyId,'digest'=>$a['record_digest']],'source_qualification'=>$a['source_qualification'],'source_imperator_approval'=>$a['source_imperator_approval'],'source_senate_disposition'=>$a['source_senate_disposition'],'admitted_findings'=>$a['admitted_findings'],'reconciliation'=>$a['reconciliation'],'profile_candidate'=>$a['profile_candidate'],'persona_identity'=>$a['persona_identity'],'custody_lease'=>$a['custody_lease'],'prior_occupancy_generation'=>0,'occupancy_generation'=>1,'supersedes'=>null,'status'=>'OPERATIONAL_MANIFESTATION_BOUND_PENDING_DEPLOYMENT_AUTHORIZATION','binding_atomic'=>true,'seat_binding_authority_consumed'=>true,'seat_bound'=>true,'supersession_authority'=>false,'operational_use_permitted'=>false,'tool_access_authority'=>false,'credentials_authority'=>false,'external_action_authority'=>false,'deployment_authorization_pending'=>true,'deployment_authority'=>false,'custody_transfer_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
 }
 private function validate(string$id,array$a,array$q,array$c,string$instance):void
 {
  $m=$a['manifestation']??null;if(!$this->ok($a)||!$this->ok($q)||!$this->ok($c)||'imperium.conscription-operational-manifestation-assembly/v1'!==($a['schema']??null)||$id!==($a['assembly_id']??null)||$instance!==($a['instance_id']??null)||'OPERATIONAL_MANIFESTATION_ASSEMBLED_PENDING_SEAT_BINDING'!==($a['status']??null)||true!==($a['manifestation_assembly_authority_consumed']??null)||true!==($a['operational_manifestation_assembled']??null)||true!==($a['seat_binding_authority']??null)||true!==($a['seat_binding_authority_exercisable']??null)||false!==($a['seat_bound']??null)||true===($a['deployment_authority']??null)||true===($a['custody_transfer_authority']??null)||true===($a['tool_access_authority']??null)||true===($a['credentials_authority']??null)||true===($a['external_action_authority']??null)||true===($a['execution_authority']??null)||true!==($a['sealed']??null)||!is_array($m)||'ASSEMBLED_UNBOUND'!==($m['status']??null)||false!==($m['seat_bound']??null)||false!==($m['operational_use_permitted']??null)||false!==($m['tool_access_granted']??null)||false!==($m['credentials_granted']??null)||false!==($m['external_action_authority']??null)||false!==($m['deployment_authority']??null)||false!==($m['custody_transfer_authority']??null)||false!==($m['execution_authority']??null)
  ||'imperium.conscription-operational-profile-qualification/v1'!==($q['schema']??null)||($a['source_qualification']['id']??null)!==($q['qualification_id']??null)||($a['source_qualification']['digest']??null)!==($q['record_digest']??null)||CanonicalJson::encode($m['persona']??null)!==CanonicalJson::encode($q['persona_identity']??null)||CanonicalJson::encode($m['profile']??null)!==CanonicalJson::encode($q['operational_profile']??null)||CanonicalJson::encode($m['intended_seat']??null)!==CanonicalJson::encode($q['operational_profile']['intended_seat']??null)||'mission.operative.'.($q['operational_profile']['intended_seat']['capability_slot_id']??'')!==($m['intended_seat']['seat']??null)
  ||'imperium.garrison-persona-custody/v1'!==($c['schema']??null)||($a['custody_lease']['custody_digest']??null)!==($c['record_digest']??null)||($a['persona_identity']['persona_id']??null)!==($c['persona_id']??null)||$instance!==($c['instance_id']??null)||'ADMITTED_HELD'!==($c['custody_state']??null)||true!==($c['available']??null))throw new \RuntimeException('R128_OPERATIONAL_SEAT_BINDING_CHAIN_INVALID');
 }
 private function recruiter():array{$s=$this->bootstrap->read();if(!is_array($s)||BootstrapState::CuriaReady->value!==($s['state']??null))throw new \RuntimeException('R129_RECRUITER_UNAVAILABLE');for($i=count($s['events']??[])-1;$i>=0;--$i){$e=$s['events'][$i];$r='T04'===($e['transition']??null)&&'SUCCESS'===($e['result']??null)?($e['output']['successor']??null):null;if(is_array($r)&&'conscription.recruiter'===($r['seat']??null)&&'ordinary-recruiter'===($r['authority']??null)&&is_string($r['manifestation_id']??null))return[(string)($s['binding']['instance_id']??''),$r];}throw new \RuntimeException('R129_RECRUITER_UNAVAILABLE');}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
 private function save(string$id,array$r):array{if(!is_dir($this->occupancy)&&!mkdir($this->occupancy,0770,true)&&!is_dir($this->occupancy))throw new \RuntimeException('R132_OPERATIONAL_SEAT_BINDING_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->occupancy.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'R130_OPERATIONAL_SEAT_BINDING_CONFLICT');if(CanonicalJson::encode($x)!==CanonicalJson::encode($r))throw new \RuntimeException('R130_OPERATIONAL_SEAT_BINDING_CONFLICT');return$x;}$t=$p.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException('R132_OPERATIONAL_SEAT_BINDING_FAILED');}return$r;}
}
