<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Mission;
use App\Bootstrap\CanonicalJson;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class BoundedOperationalExecutionService
{
 private string$authorizations;private string$transitions;private string$bindings;private string$custody;private string$executions;
 public function __construct(#[Autowire('%kernel.project_dir%')]string$root,private OperationalExecutionCognitionGateway$cognition){$this->authorizations=$root.'/var/imperium/offices/curia/bounded-execution-authorizations';$this->transitions=$root.'/var/imperium/offices/garrison/operational-custody-transitions';$this->bindings=$root.'/var/imperium/mission/occupancy';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->executions=$root.'/var/imperium/mission/bounded-executions';}
 public function execute(string$authorizationId):array
 {
  if(!preg_match('/^bounded-execution-authorization-[a-f0-9]{20}$/',$authorizationId))throw new \InvalidArgumentException('M201_BOUNDED_EXECUTION_AUTHORIZATION_ID_INVALID');$a=$this->read($this->authorizations.'/'.$authorizationId.'.json','M202_BOUNDED_EXECUTION_AUTHORIZATION_ABSENT');foreach(glob($this->executions.'/bounded-operational-execution-*.json')?:[]as$p){$x=$this->read($p,'M207_BOUNDED_EXECUTION_CONFLICT');if(!$this->ok($x))throw new \RuntimeException('M207_BOUNDED_EXECUTION_CONFLICT');if(($x['source_execution_authorization']['id']??null)===$authorizationId){if(($x['source_execution_authorization']['digest']??null)!==($a['record_digest']??null))throw new \RuntimeException('M207_BOUNDED_EXECUTION_CONFLICT');return$x;}}
  $tid=$a['source_custody_transition']['id']??null;$t=is_string($tid)?$this->read($this->transitions.'/'.$tid.'.json','M203_OPERATIONAL_CUSTODY_TRANSITION_ABSENT'):[];$bid=$a['source_binding']['id']??null;$b=is_string($bid)?$this->read($this->bindings.'/'.$bid.'.json','M204_OPERATIONAL_BINDING_ABSENT'):[];$cid=$a['operational_custody']['id']??null;$c=is_string($cid)?$this->read($this->custody.'/'.$cid.'.json','M205_OPERATIONAL_CUSTODY_ABSENT'):[];$this->validate($authorizationId,$a,$t,$b,$c);
  $out=$this->cognition->execute($a,$a['manifestation']);$id='bounded-operational-execution-'.substr(hash('sha256',CanonicalJson::encode([$authorizationId,$a['record_digest'],$out])),0,20);
  return$this->save($id,['schema'=>'imperium.mission-bounded-operational-execution/v1','execution_id'=>$id,'instance_id'=>$a['instance_id'],'case_id'=>$a['case_id'],'case_digest'=>$a['case_digest'],'source_execution_authorization'=>['id'=>$authorizationId,'digest'=>$a['record_digest']],'source_custody_transition'=>$a['source_custody_transition'],'source_deployment_authorization'=>$a['source_deployment_authorization'],'source_binding'=>$a['source_binding'],'seat'=>$a['seat'],'manifestation_id'=>$a['manifestation_id'],'manifestation'=>$a['manifestation'],'persona_identity'=>$a['persona_identity'],'profile_candidate'=>$a['profile_candidate'],'operational_custody'=>$a['operational_custody'],'mission_use'=>$a['mission_use'],'input'=>$a['input'],'input_digest'=>$a['input_digest'],'output'=>$out,'status'=>'OPERATIONAL_MANIFESTATION_BOUNDED_EXECUTION_COMPLETED_PENDING_RETURN','bounded_execution_authority_consumed'=>true,'iterations_consumed'=>1,'execution_complete'=>true,'output_attributable'=>true,'operational_use_permitted'=>false,'tool_access_used'=>false,'credentials_used'=>false,'external_action_performed'=>false,'network_access_performed'=>false,'continuing_execution_authority'=>false,'return_authority'=>false,'retirement_authority'=>false,'unbinding_authority'=>false,'supersession_authority'=>false,'sealed'=>true]);
 }
 private function validate(string$id,array$a,array$t,array$b,array$c):void{if(!$this->ok($a)||!$this->ok($t)||!$this->ok($b)||!$this->ok($c)||'imperium.curia-bounded-execution-authorization/v1'!==($a['schema']??null)||$id!==($a['authorization_id']??null)||'BOUNDED_EXECUTION_AUTHORIZED_PENDING_ONE_ITERATION'!==($a['status']??null)||true!==($a['bounded_execution_authority']??null)||true!==($a['bounded_execution_authority_exercisable']??null)||1!==($a['maximum_iterations']??null)||true===($a['tool_access_authority']??null)||true===($a['credentials_authority']??null)||true===($a['external_action_authority']??null)||true===($a['network_access_authority']??null)||'imperium.garrison-operational-custody-transition/v1'!==($t['schema']??null)||($a['source_custody_transition']['digest']??null)!==($t['record_digest']??null)||'imperium.operational-manifestation-seat-binding/v1'!==($b['schema']??null)||($a['source_binding']['digest']??null)!==($b['record_digest']??null)||($a['manifestation_id']??null)!==($b['manifestation_id']??null)||'imperium.garrison-persona-custody/v1'!==($c['schema']??null)||($a['operational_custody']['digest']??null)!==($c['record_digest']??null)||'DEPLOYED_BOUND'!==($c['custody_state']??null)||false!==($c['available']??null)||($a['input_digest']??null)!==hash('sha256',CanonicalJson::encode($a['input']??null)))throw new \RuntimeException('M206_BOUNDED_EXECUTION_CHAIN_INVALID');}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$id,array$r):array{if(!is_dir($this->executions)&&!mkdir($this->executions,0770,true)&&!is_dir($this->executions))throw new \RuntimeException('M208_BOUNDED_EXECUTION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->executions.'/'.$id.'.json';if(is_file($p)){if(CanonicalJson::encode($x=$this->read($p,'M207_BOUNDED_EXECUTION_CONFLICT'))!==CanonicalJson::encode($r))throw new \RuntimeException('M207_BOUNDED_EXECUTION_CONFLICT');return$x;}if(false===file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX))throw new \RuntimeException('M208_BOUNDED_EXECUTION_FAILED');return$r;}
}
