<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Mission;
use App\Imperium\Runtime\Cognition\BoundedTransientCognitionCaller;use Symfony\AI\Agent\AgentInterface;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class SymfonyAiOperationalExecutionCognitionGateway implements OperationalExecutionCognitionGateway
{
 public function __construct(#[Autowire(service:'ai.agent.operational_manifestation_execution')]private AgentInterface$agent,private ?BoundedTransientCognitionCaller$transientCaller=null){}
 public function execute(array$a,array$m):array
 {
  $prompt=implode("\n",['Exact one-use execution authorization: '.json_encode($a,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),'Exact bound Manifestation: '.json_encode($m,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),'Perform exactly one internal cognition iteration against the supplied input and installed Profile. Do not access the URL, use tools, credentials, network, external data, memory, or any undeclared input. Produce an attributable bounded output and stop.','Return one JSON object with exactly disposition, output, evidence_claims, uncertainties, stop_condition_triggered, and stop_rationale. disposition must be COMPLETED or STOPPED. output and stop_rationale must be non-empty strings; evidence_claims and uncertainties must be arrays of non-empty strings; stop_condition_triggered must be boolean. No markdown or extra fields.']);
  $c=($this->transientCaller??new BoundedTransientCognitionCaller())->call($this->agent,$prompt,'M209_OPERATIONAL_EXECUTION_COGNITION_INVALID');if(!is_string($c))throw new \RuntimeException('M209_OPERATIONAL_EXECUTION_COGNITION_INVALID: NON_TEXT_RESPONSE');$c=trim($c);if(str_starts_with($c,'```'))$c=preg_replace('/^```(?:json)?\s*|\s*```$/i','',$c)??$c;try{$r=json_decode(trim($c),true,16,JSON_THROW_ON_ERROR);}catch(\JsonException$e){throw new \RuntimeException('M209_OPERATIONAL_EXECUTION_COGNITION_INVALID: JSON_INVALID',0,$e);}$keys=is_array($r)?array_keys($r):[];sort($keys,SORT_STRING);if(['disposition','evidence_claims','output','stop_condition_triggered','stop_rationale','uncertainties']!==$keys||!in_array($r['disposition']??null,['COMPLETED','STOPPED'],true)||!is_string($r['output']??null)||''===trim($r['output'])||!is_bool($r['stop_condition_triggered']??null)||('STOPPED'===$r['disposition'])!==$r['stop_condition_triggered']||!is_string($r['stop_rationale']??null)||''===trim($r['stop_rationale']))throw new \RuntimeException('M209_OPERATIONAL_EXECUTION_COGNITION_INVALID: CONTRACT_INVALID');foreach(['evidence_claims','uncertainties']as$f){if(!is_array($r[$f])||!array_is_list($r[$f]))throw new \RuntimeException('M209_OPERATIONAL_EXECUTION_COGNITION_INVALID: CONTRACT_INVALID');foreach($r[$f]as$v)if(!is_string($v)||''===trim($v))throw new \RuntimeException('M209_OPERATIONAL_EXECUTION_COGNITION_INVALID: CONTRACT_INVALID');}return$r;
 }
}
