<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Senate;
use App\Bootstrap\CanonicalJson;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class DelegateMissionFindingReconciliationService
{
    private string $openings;private string $findings;private string $occupancy;private string $custody;private string $reconciliations;
    public function __construct(#[Autowire('%kernel.project_dir%')]string $root,private ProfileExaminationReconciliationCognitionGateway $cognition){$s=$root.'/var/imperium/offices/senate';$this->openings=$s.'/delegate-mission-profile-examination-deliberation-openings';$this->findings=$s.'/delegate-mission-profile-examination-senator-findings';$this->occupancy=$s.'/occupancy';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->reconciliations=$s.'/delegate-mission-profile-examination-reconciliations';}
    public function reconcile(string $deliberationId,string $lordSpeakerBindingId,\DateTimeImmutable $reconciledAt):array
    {
        if(!preg_match('/^delegate-mission-profile-examination-deliberation-opening-[a-f0-9]{20}$/',$deliberationId))throw new \InvalidArgumentException('S750_DELEGATE_MISSION_DELIBERATION_ID_INVALID');foreach(glob($this->reconciliations.'/*.json')?:[]as$p){$x=$this->read($p,'S759_DELEGATE_MISSION_RECONCILIATION_CONFLICT');if(($x['source_deliberation_opening']['id']??null)===$deliberationId){if(!$this->valid($x)||($x['lord_speaker']['binding_id']??null)!==$lordSpeakerBindingId)throw new \RuntimeException('S759_DELEGATE_MISSION_RECONCILIATION_CONFLICT');return$x;}}
        $o=$this->read($this->openings.'/'.$deliberationId.'.json','S751_DELEGATE_MISSION_DELIBERATION_ABSENT');$l=$this->read($this->occupancy.'/'.$lordSpeakerBindingId.'.json','S752_DELEGATE_MISSION_LORD_SPEAKER_UNAVAILABLE');$custodyId=$o['custody_lease']['custody_id']??'';$c=$this->read($this->custody.'/'.$custodyId.'.json','S753_DELEGATE_MISSION_CUSTODY_ABSENT');$authority=$o['reconciliation_authority']??null;
        if(!$this->valid($o)||!$this->valid($l)||!$this->valid($c)||'imperium.senate-delegate-mission-profile-examination-deliberation-opening/v1'!==($o['schema']??null)||'DELEGATE_MISSION_DELIBERATION_OPENED_PENDING_FINDING_RECONCILIATION'!==($o['status']??null)||true!==($o['deliberation_open']??null)||!is_array($authority)||true!==($authority['authority_single_use']??null)||true!==($authority['authority_exercisable']??null)||false!==($authority['consumed']??null)||'RECONCILE_THREE_UNCHANGED_SENATOR_FINDINGS'!==($authority['purpose']??null)||false!==($authority['voting_included']??null)||false!==($authority['aggregation_included']??null)||($authority['holder']??null)!==($o['lord_speaker']??null)||false!==($o['vote_authority']??null)||false!==($o['aggregation_authority']??null)||false!==($o['senate_disposition_authority']??null)||($o['custody_lease']['custody_digest']??null)!==$c['record_digest']||'ADMITTED_HELD'!==($c['custody_state']??null)||true!==($c['available']??null)||$lordSpeakerBindingId!==($l['binding_id']??null)||$o['lord_speaker']['binding_digest']!==$l['record_digest']||($o['instance_id']??null)!==($l['instance_id']??null)||'ACTIVE'!==($l['status']??null)||true!==($l['binding_atomic']??null)||true===($l['execution_authority']??null))throw new \RuntimeException('S754_DELEGATE_MISSION_RECONCILIATION_CHAIN_INVALID');
        $found=[];$refs=[];foreach($o['admitted_findings']??[]as$snapshot){$id=$snapshot['finding_id']??'';$f=$this->read($this->findings.'/'.$id.'.json','S755_DELEGATE_MISSION_FINDING_ABSENT');$j=$f['jurisdiction']??null;if(!$this->valid($f)||$snapshot!==$f||!in_array($j,['trust','security','usability'],true)||isset($found[$j]))throw new \RuntimeException('S754_DELEGATE_MISSION_RECONCILIATION_CHAIN_INVALID');$found[$j]=$f;$refs[$j]='delegate-finding:'.$j.':'.$f['record_digest'];}foreach(['trust','security','usability']as$j)if(!isset($found[$j]))throw new \RuntimeException('S754_DELEGATE_MISSION_RECONCILIATION_CHAIN_INVALID');$ordered=array_map(static fn(string$j):array=>$found[$j],['trust','security','usability']);$references=array_map(static fn(string$j):string=>$refs[$j],['trust','security','usability']);
        $surface=['deliberation_id'=>$deliberationId,'deliberation_digest'=>$o['record_digest'],'lord_speaker'=>$o['lord_speaker'],'available_finding_references'=>$references,'mandatory_security_blocking_condition'=>$o['mandatory_security_blocking_condition'],'reconciliation_authority_exercisable'=>true,'vote_authority'=>false,'aggregation_authority'=>false,'senate_disposition_authority'=>false];$decision=$this->cognition->reconcile($surface,$ordered);$this->validateDecision($decision,$references,$ordered,$o['mandatory_security_blocking_condition']);$id='delegate-mission-profile-examination-reconciliation-'.substr(hash('sha256',CanonicalJson::encode([$deliberationId,$o['record_digest'],$lordSpeakerBindingId,$decision])),0,20);$next=['authority_id'=>'delegate-mission-disposition-phase-opening-authority-'.substr(hash('sha256',CanonicalJson::encode([$id,$decision,$o['mandatory_security_blocking_condition']])),0,20),'authority_single_use'=>true,'authority_exercisable'=>true,'holder'=>'senate.lord-speaker','purpose'=>'OPEN_ONE_SENATE_DISPOSITION_AUTHORITY','consumed'=>false,'continuing_authority'=>false];
        return$this->save($id,['schema'=>'imperium.senate-delegate-mission-profile-examination-reconciliation/v1','reconciliation_id'=>$id,'instance_id'=>$o['instance_id'],'officer_class'=>$o['officer_class'],'source_deliberation_opening'=>['id'=>$deliberationId,'digest'=>$o['record_digest']],'lord_speaker'=>$o['lord_speaker'],'source_profile_candidate'=>$o['source_profile_candidate'],'custody_lease'=>$o['custody_lease'],'manifestation'=>$o['manifestation'],'hearing_contract'=>$o['hearing_contract'],'defect_attribution_rubric'=>$o['defect_attribution_rubric'],'admitted_findings'=>$ordered,'mandatory_security_blocking_condition'=>$o['mandatory_security_blocking_condition'],'reconciliation'=>$decision,'reconciliation_authority'=>['id'=>$authority['authority_id'],'consumed'=>true,'continuing_authority'=>false],'disposition_phase_opening_authority'=>$next,'reconciled_at'=>$reconciledAt->format(DATE_ATOM),'status'=>'DELEGATE_MISSION_FINDINGS_RECONCILED_PENDING_DISPOSITION_AUTHORITY_OPENING','deliberation_open'=>true,'vote_authority'=>false,'aggregation_authority'=>false,'senate_disposition_authority'=>false,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'mission_seat_binding_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
    }
    private function validateDecision(array$d,array$refs,array$findings,bool$block):void{$keys=array_keys($d);sort($keys,SORT_STRING);if(['agreements','attribution_treatment','disagreements','finding_references','limitations','mandatory_security_blocking_condition_preserved','rationale','severity_treatment','uncertainties']!==$keys||$refs!==($d['finding_references']??null)||$block!==($d['mandatory_security_blocking_condition_preserved']??null)||!is_string($d['rationale']??null)||''===trim($d['rationale']))throw new \RuntimeException('S756_DELEGATE_MISSION_RECONCILIATION_COGNITION_INVALID');foreach(['agreements','disagreements','attribution_treatment','severity_treatment','limitations','uncertainties']as$f)if(!is_array($d[$f]??null)||!array_is_list($d[$f])||array_filter($d[$f],static fn($v):bool=>!is_string($v)||''===trim($v)))throw new \RuntimeException('S756_DELEGATE_MISSION_RECONCILIATION_COGNITION_INVALID');if([]===$d['attribution_treatment']||[]===$d['severity_treatment'])throw new \RuntimeException('S756_DELEGATE_MISSION_RECONCILIATION_COGNITION_INVALID');$signatures=array_unique(array_map(static fn(array$f):string=>CanonicalJson::encode([$f['decision']['disposition'],$f['decision']['attributed_defect'],$f['decision']['severity']]),$findings));if(1<count($signatures)&&[]===$d['disagreements'])throw new \RuntimeException('S756_DELEGATE_MISSION_RECONCILIATION_COGNITION_INVALID');}
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function valid(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$id,array$r):array{if(!is_dir($this->reconciliations)&&!mkdir($this->reconciliations,0770,true)&&!is_dir($this->reconciliations))throw new \RuntimeException('S758_DELEGATE_MISSION_RECONCILIATION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->reconciliations.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'S759_DELEGATE_MISSION_RECONCILIATION_CONFLICT');if($x!==$r)throw new \RuntimeException('S759_DELEGATE_MISSION_RECONCILIATION_CONFLICT');return$x;}if(false===file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX))throw new \RuntimeException('S758_DELEGATE_MISSION_RECONCILIATION_FAILED');return$r;}
}
