<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Senate;

use App\Bootstrap\CanonicalJson;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

final readonly class DelegateMissionSenateDispositionService
{
    private string $openings; private string $reconciliations; private string $findings; private string $occupancy; private string $custody; private string $dispositions;
    public function __construct(#[Autowire('%kernel.project_dir%')] string $root,private ProfileExaminationDispositionCognitionGateway $cognition)
    {
        $s=$root.'/var/imperium/offices/senate';$this->openings=$s.'/delegate-mission-profile-examination-disposition-authority-openings';$this->reconciliations=$s.'/delegate-mission-profile-examination-reconciliations';$this->findings=$s.'/delegate-mission-profile-examination-senator-findings';$this->occupancy=$s.'/occupancy';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->dispositions=$s.'/delegate-mission-profile-examination-dispositions';
    }
    public function decide(string $openingId,string $lordSpeakerBindingId,\DateTimeImmutable $decidedAt):array
    {
        if(!preg_match('/^delegate-mission-profile-examination-disposition-authority-opening-[a-f0-9]{20}$/',$openingId))throw new \InvalidArgumentException('S770_DELEGATE_MISSION_DISPOSITION_OPENING_ID_INVALID');foreach(glob($this->dispositions.'/*.json')?:[]as$p){$x=$this->read($p,'S779_DELEGATE_MISSION_DISPOSITION_CONFLICT');if(($x['source_disposition_authority_opening']['id']??null)===$openingId){if(!$this->valid($x)||($x['lord_speaker']['binding_id']??null)!==$lordSpeakerBindingId)throw new \RuntimeException('S779_DELEGATE_MISSION_DISPOSITION_CONFLICT');return$x;}}
        $o=$this->read($this->openings.'/'.$openingId.'.json','S771_DELEGATE_MISSION_DISPOSITION_OPENING_ABSENT');$reconciliationId=$o['source_reconciliation']['id']??'';$r=$this->read($this->reconciliations.'/'.$reconciliationId.'.json','S772_DELEGATE_MISSION_RECONCILIATION_ABSENT');$l=$this->read($this->occupancy.'/'.$lordSpeakerBindingId.'.json','S773_DELEGATE_MISSION_LORD_SPEAKER_UNAVAILABLE');$custodyId=$o['custody_lease']['custody_id']??'';$c=$this->read($this->custody.'/'.$custodyId.'.json','S774_DELEGATE_MISSION_CUSTODY_ABSENT');$a=$o['disposition_authority']??null;
        if(!$this->valid($o)||!$this->valid($r)||!$this->valid($l)||!$this->valid($c)||'imperium.senate-delegate-mission-profile-examination-disposition-authority-opening/v1'!==($o['schema']??null)||'DELEGATE_MISSION_DISPOSITION_AUTHORITY_OPENED_PENDING_LORD_SPEAKER_DISPOSITION'!==($o['status']??null)||($o['source_reconciliation']['digest']??null)!==($r['record_digest']??null)||!is_array($a)||true!==($a['authority_single_use']??null)||true!==($a['authority_exercisable']??null)||false!==($a['consumed']??null)||($a['holder']??null)!==($o['lord_speaker']??null)||['APPROVED','RETURN_FOR_REVISION','REFUSED','UNRESOLVED']!==($a['permitted_dispositions']??null)||true!==($a['security_block_must_be_preserved']??null)||true!==($o['senate_disposition_authority']??null)||null!==($o['senate_disposition']??null)||false!==($o['vote_authority']??null)||false!==($o['aggregation_authority']??null)||($o['source_profile_candidate']??null)!==($r['source_profile_candidate']??null)||($o['custody_lease']??null)!==($r['custody_lease']??null)||($o['manifestation']??null)!==($r['manifestation']??null)||($o['hearing_contract']??null)!==($r['hearing_contract']??null)||($o['defect_attribution_rubric']??null)!==($r['defect_attribution_rubric']??null)||($o['admitted_findings']??null)!==($r['admitted_findings']??null)||($o['reconciliation']??null)!==($r['reconciliation']??null)||($o['custody_lease']['custody_digest']??null)!==($c['record_digest']??null)||'ADMITTED_HELD'!==($c['custody_state']??null)||true!==($c['available']??null)||$lordSpeakerBindingId!==($l['binding_id']??null)||($o['lord_speaker']['binding_digest']??null)!==($l['record_digest']??null)||($o['instance_id']??null)!==($l['instance_id']??null)||'senate.lord-speaker'!==($l['seat']??null)||'ACTIVE'!==($l['status']??null)||true!==($l['binding_atomic']??null)||true===($l['execution_authority']??null)||($o['mandatory_security_blocking_condition']??null)!==($r['mandatory_security_blocking_condition']??null))throw new \RuntimeException('S775_DELEGATE_MISSION_DISPOSITION_CHAIN_INVALID');
        $found=[];$refs=[];foreach($o['admitted_findings']??[]as$snapshot){$id=$snapshot['finding_id']??'';$f=$this->read($this->findings.'/'.$id.'.json','S776_DELEGATE_MISSION_FINDING_ABSENT');$j=$f['jurisdiction']??null;if(!$this->valid($f)||$snapshot!==$f||!in_array($j,['trust','security','usability'],true)||isset($found[$j]))throw new \RuntimeException('S775_DELEGATE_MISSION_DISPOSITION_CHAIN_INVALID');$found[$j]=$f;$refs[$j]='delegate-finding:'.$j.':'.$f['record_digest'];}foreach(['trust','security','usability']as$j)if(!isset($found[$j]))throw new \RuntimeException('S775_DELEGATE_MISSION_DISPOSITION_CHAIN_INVALID');$ordered=array_map(static fn(string$j):array=>$found[$j],['trust','security','usability']);$references=array_map(static fn(string$j):string=>$refs[$j],['trust','security','usability']);
        $surface=['disposition_authority_id'=>$a['authority_id'],'available_finding_references'=>$references,'permitted_dispositions'=>$a['permitted_dispositions'],'mandatory_security_blocking_condition'=>$o['mandatory_security_blocking_condition'],'profile_approval_authority'=>false];$d=$this->cognition->decide($surface,$ordered,$o['reconciliation']);$this->validateDecision($d,$references);if(true===$o['mandatory_security_blocking_condition']&&'APPROVED'===$d['disposition'])throw new \RuntimeException('S778_DELEGATE_MISSION_PROFILE_SECURITY_VETO');
        $id='delegate-mission-profile-examination-disposition-'.substr(hash('sha256',CanonicalJson::encode([$openingId,$o['record_digest'],$a['authority_id'],$d])),0,20);return$this->save($id,['schema'=>'imperium.senate-delegate-mission-profile-examination-disposition/v1','disposition_id'=>$id,'instance_id'=>$o['instance_id'],'officer_class'=>$o['officer_class'],'source_disposition_authority_opening'=>['id'=>$openingId,'digest'=>$o['record_digest']],'source_reconciliation'=>$o['source_reconciliation'],'lord_speaker'=>$o['lord_speaker'],'source_profile_candidate'=>$o['source_profile_candidate'],'custody_lease'=>$o['custody_lease'],'manifestation'=>$o['manifestation'],'hearing_contract'=>$o['hearing_contract'],'defect_attribution_rubric'=>$o['defect_attribution_rubric'],'admitted_findings'=>$ordered,'reconciliation'=>$o['reconciliation'],'mandatory_security_blocking_condition'=>$o['mandatory_security_blocking_condition'],'disposition_authority'=>['id'=>$a['authority_id'],'consumed'=>true,'continuing_authority'=>false],'decision'=>$d,'decided_at'=>$decidedAt->format(DATE_ATOM),'status'=>'DELEGATE_MISSION_SENATE_DISPOSITION_SEALED_PENDING_IMPERATOR_PROFILE_APPROVAL','senate_disposition_authority_consumed'=>true,'imperator_profile_approval_pending'=>true,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'mission_seat_binding_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
    }
    private function validateDecision(array$d,array$refs):void{$k=array_keys($d);sort($k,SORT_STRING);if(['disposition','finding_references','limitations','rationale','reconciliation_treatment','uncertainties']!==$k||!in_array($d['disposition']??null,['APPROVED','RETURN_FOR_REVISION','REFUSED','UNRESOLVED'],true)||$refs!==($d['finding_references']??null)||!is_string($d['rationale']??null)||''===trim($d['rationale'])||!is_string($d['reconciliation_treatment']??null)||''===trim($d['reconciliation_treatment']))throw new \RuntimeException('S777_DELEGATE_MISSION_DISPOSITION_COGNITION_INVALID');foreach(['limitations','uncertainties']as$f)if(!is_array($d[$f]??null)||!array_is_list($d[$f])||array_filter($d[$f],static fn($v):bool=>!is_string($v)||''===trim($v)))throw new \RuntimeException('S777_DELEGATE_MISSION_DISPOSITION_COGNITION_INVALID');}
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function valid(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$id,array$r):array{if(!is_dir($this->dispositions)&&!mkdir($this->dispositions,0770,true)&&!is_dir($this->dispositions))throw new \RuntimeException('S779_DELEGATE_MISSION_DISPOSITION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->dispositions.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'S779_DELEGATE_MISSION_DISPOSITION_CONFLICT');if($x!==$r)throw new \RuntimeException('S779_DELEGATE_MISSION_DISPOSITION_CONFLICT');return$x;}if(false===file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX))throw new \RuntimeException('S779_DELEGATE_MISSION_DISPOSITION_FAILED');return$r;}
}
