<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Senate;

use App\Bootstrap\CanonicalJson;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

final readonly class DelegateMissionDispositionAuthorityOpeningService
{
    private string $reconciliations; private string $findings; private string $occupancy; private string $custody; private string $openings;
    public function __construct(#[Autowire('%kernel.project_dir%')] string $root)
    {
        $s=$root.'/var/imperium/offices/senate';$this->reconciliations=$s.'/delegate-mission-profile-examination-reconciliations';$this->findings=$s.'/delegate-mission-profile-examination-senator-findings';$this->occupancy=$s.'/occupancy';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->openings=$s.'/delegate-mission-profile-examination-disposition-authority-openings';
    }
    public function open(string $reconciliationId,string $lordSpeakerBindingId,\DateTimeImmutable $openedAt):array
    {
        if(!preg_match('/^delegate-mission-profile-examination-reconciliation-[a-f0-9]{20}$/',$reconciliationId))throw new \InvalidArgumentException('S760_DELEGATE_MISSION_RECONCILIATION_ID_INVALID');
        $r=$this->read($this->reconciliations.'/'.$reconciliationId.'.json','S761_DELEGATE_MISSION_RECONCILIATION_ABSENT');$l=$this->read($this->occupancy.'/'.$lordSpeakerBindingId.'.json','S762_DELEGATE_MISSION_LORD_SPEAKER_UNAVAILABLE');$custodyId=$r['custody_lease']['custody_id']??'';$c=$this->read($this->custody.'/'.$custodyId.'.json','S763_DELEGATE_MISSION_CUSTODY_ABSENT');$a=$r['disposition_phase_opening_authority']??null;
        if(!$this->valid($r)||!$this->valid($l)||!$this->valid($c)||'imperium.senate-delegate-mission-profile-examination-reconciliation/v1'!==($r['schema']??null)||'DELEGATE_MISSION_FINDINGS_RECONCILED_PENDING_DISPOSITION_AUTHORITY_OPENING'!==($r['status']??null)||!is_array($a)||true!==($a['authority_single_use']??null)||true!==($a['authority_exercisable']??null)||'senate.lord-speaker'!==($a['holder']??null)||'OPEN_ONE_SENATE_DISPOSITION_AUTHORITY'!==($a['purpose']??null)||false!==($a['consumed']??null)||false!==($r['vote_authority']??null)||false!==($r['aggregation_authority']??null)||false!==($r['senate_disposition_authority']??null)||($r['custody_lease']['custody_digest']??null)!==($c['record_digest']??null)||'ADMITTED_HELD'!==($c['custody_state']??null)||true!==($c['available']??null)||$lordSpeakerBindingId!==($l['binding_id']??null)||($r['lord_speaker']['binding_id']??null)!==$lordSpeakerBindingId||($r['lord_speaker']['binding_digest']??null)!==($l['record_digest']??null)||($r['instance_id']??null)!==($l['instance_id']??null)||'senate.lord-speaker'!==($l['seat']??null)||'ACTIVE'!==($l['status']??null)||true!==($l['binding_atomic']??null)||true!==($l['delegate_disposition_phase_opening_authority']??null)||true===($l['execution_authority']??null))throw new \RuntimeException('S764_DELEGATE_MISSION_DISPOSITION_OPENING_CHAIN_INVALID');
        $found=[];foreach($r['admitted_findings']??[]as$snapshot){$id=$snapshot['finding_id']??'';$f=$this->read($this->findings.'/'.$id.'.json','S765_DELEGATE_MISSION_FINDING_ABSENT');$j=$f['jurisdiction']??null;if(!$this->valid($f)||$snapshot!==$f||!in_array($j,['trust','security','usability'],true)||isset($found[$j]))throw new \RuntimeException('S764_DELEGATE_MISSION_DISPOSITION_OPENING_CHAIN_INVALID');$found[$j]=$f;}foreach(['trust','security','usability']as$j)if(!isset($found[$j]))throw new \RuntimeException('S764_DELEGATE_MISSION_DISPOSITION_OPENING_CHAIN_INVALID');$ordered=array_map(static fn(string$j):array=>$found[$j],['trust','security','usability']);
        $actor=['seat'=>'senate.lord-speaker','binding_id'=>$lordSpeakerBindingId,'binding_digest'=>$l['record_digest'],'manifestation_id'=>$l['manifestation_id'],'occupancy_generation'=>$l['occupancy_generation']];$authorityId='delegate-mission-senate-disposition-authority-'.substr(hash('sha256',CanonicalJson::encode([$reconciliationId,$r['record_digest'],$actor,array_column($ordered,'record_digest')])),0,20);$id='delegate-mission-profile-examination-disposition-authority-opening-'.substr(hash('sha256',CanonicalJson::encode([$authorityId,$a['authority_id']])),0,20);
        return$this->save($id,['schema'=>'imperium.senate-delegate-mission-profile-examination-disposition-authority-opening/v1','opening_id'=>$id,'instance_id'=>$r['instance_id'],'officer_class'=>$r['officer_class'],'source_reconciliation'=>['id'=>$reconciliationId,'digest'=>$r['record_digest']],'lord_speaker'=>$actor,'source_profile_candidate'=>$r['source_profile_candidate'],'custody_lease'=>$r['custody_lease'],'manifestation'=>$r['manifestation'],'hearing_contract'=>$r['hearing_contract'],'defect_attribution_rubric'=>$r['defect_attribution_rubric'],'admitted_findings'=>$ordered,'reconciliation'=>$r['reconciliation'],'mandatory_security_blocking_condition'=>$r['mandatory_security_blocking_condition'],'disposition_phase_opening_authority'=>['id'=>$a['authority_id'],'consumed'=>true,'continuing_authority'=>false],'disposition_authority'=>['authority_id'=>$authorityId,'authority_single_use'=>true,'authority_exercisable'=>true,'holder'=>$actor,'permitted_dispositions'=>['APPROVED','RETURN_FOR_REVISION','REFUSED','UNRESOLVED'],'security_block_must_be_preserved'=>true,'consumed'=>false,'continuing_authority'=>false],'opened_at'=>$openedAt->format(DATE_ATOM),'status'=>'DELEGATE_MISSION_DISPOSITION_AUTHORITY_OPENED_PENDING_LORD_SPEAKER_DISPOSITION','senate_disposition_authority'=>true,'senate_disposition'=>null,'vote_authority'=>false,'aggregation_authority'=>false,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'mission_seat_binding_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
    }
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function valid(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$id,array$r):array{if(!is_dir($this->openings)&&!mkdir($this->openings,0770,true)&&!is_dir($this->openings))throw new \RuntimeException('S768_DELEGATE_MISSION_DISPOSITION_OPENING_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->openings.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'S769_DELEGATE_MISSION_DISPOSITION_OPENING_CONFLICT');if($x!==$r)throw new \RuntimeException('S769_DELEGATE_MISSION_DISPOSITION_OPENING_CONFLICT');return$x;}if(false===file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX))throw new \RuntimeException('S768_DELEGATE_MISSION_DISPOSITION_OPENING_FAILED');return$r;}
}
