<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Senate;

use App\Bootstrap\CanonicalJson;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

final readonly class DelegateMissionDeliberationOpeningService
{
    private string $readiness; private string $findings; private string $findingOpenings; private string $occupancy; private string $custody; private string $deliberations;
    public function __construct(#[Autowire('%kernel.project_dir%')] string $root)
    {
        $s=$root.'/var/imperium/offices/senate';$this->readiness=$s.'/delegate-mission-profile-examination-finding-readiness';$this->findings=$s.'/delegate-mission-profile-examination-senator-findings';$this->findingOpenings=$s.'/delegate-mission-profile-examination-finding-authority-openings';$this->occupancy=$s.'/occupancy';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->deliberations=$s.'/delegate-mission-profile-examination-deliberation-openings';
    }
    public function open(string $readinessId,string $lordSpeakerBindingId,\DateTimeImmutable $openedAt):array
    {
        if(!preg_match('/^delegate-mission-profile-examination-finding-readiness-[a-f0-9]{20}$/',$readinessId))throw new \InvalidArgumentException('S740_DELEGATE_MISSION_FINDING_READINESS_ID_INVALID');
        $r=$this->read($this->readiness.'/'.$readinessId.'.json','S741_DELEGATE_MISSION_FINDING_READINESS_ABSENT');$openingId=$r['source_finding_authority_opening']['id']??'';$o=$this->read($this->findingOpenings.'/'.$openingId.'.json','S742_DELEGATE_MISSION_FINDING_OPENING_ABSENT');$l=$this->read($this->occupancy.'/'.$lordSpeakerBindingId.'.json','S743_DELEGATE_MISSION_LORD_SPEAKER_UNAVAILABLE');$custodyId=$r['custody_lease']['custody_id']??'';$c=$this->read($this->custody.'/'.$custodyId.'.json','S744_DELEGATE_MISSION_CUSTODY_ABSENT');$authority=$r['deliberation_opening_authority']??null;
        if(!$this->valid($r)||!$this->valid($o)||!$this->valid($l)||!$this->valid($c)||'imperium.senate-delegate-mission-profile-examination-finding-readiness/v1'!==($r['schema']??null)||'DELEGATE_MISSION_SENATOR_FINDINGS_SEALED_PENDING_DELIBERATION_OPENING'!==($r['status']??null)||true!==($r['all_finding_authorities_consumed']??null)||false!==($r['deliberation_authority']??null)||false!==($r['senate_disposition_authority']??null)||!is_array($authority)||true!==($authority['authority_single_use']??null)||true!==($authority['authority_exercisable']??null)||'senate.lord-speaker'!==($authority['holder']??null)||'OPEN_FINDING_RECONCILIATION'!==($authority['purpose']??null)||false!==($authority['consumed']??null)||($r['source_finding_authority_opening']['digest']??null)!==($o['record_digest']??null)||($r['custody_lease']['custody_digest']??null)!==($c['record_digest']??null)||'ADMITTED_HELD'!==($c['custody_state']??null)||true!==($c['available']??null)||$lordSpeakerBindingId!==($l['binding_id']??null)||'senate.lord-speaker'!==($l['seat']??null)||'ACTIVE'!==($l['status']??null)||true!==($l['binding_atomic']??null)||true!==($l['delegate_deliberation_opening_authority']??null)||true===($l['execution_authority']??null)||($r['instance_id']??null)!==($l['instance_id']??null))throw new \RuntimeException('S745_DELEGATE_MISSION_DELIBERATION_OPENING_CHAIN_INVALID');
        $found=[];foreach($r['senator_findings']??[]as$ref){$id=$ref['id']??'';$f=$this->read($this->findings.'/'.$id.'.json','S746_DELEGATE_MISSION_FINDING_ABSENT');$j=$f['jurisdiction']??null;if(!$this->valid($f)||!in_array($j,['trust','security','usability'],true)||isset($found[$j])||($ref['jurisdiction']??null)!==$j||($ref['digest']??null)!==($f['record_digest']??null)||'DELEGATE_MISSION_SENATOR_FINDING_AUTHORED_SEALED_PENDING_PANEL_COMPLETION'!==($f['status']??null)||false!==($f['deliberation_authority']??null)||($f['source_finding_authority_opening']['id']??null)!==$openingId||($f['source_finding_authority_opening']['digest']??null)!==$o['record_digest']||$f['manifestation']!==$o['manifestation']||$f['custody_lease']!==$o['custody_lease']||$f['hearing_contract']!==$o['hearing_contract']||$f['defect_attribution_rubric']!==$o['defect_attribution_rubric'])throw new \RuntimeException('S745_DELEGATE_MISSION_DELIBERATION_OPENING_CHAIN_INVALID');$found[$j]=$f;}foreach(['trust','security','usability']as$j)if(!isset($found[$j]))throw new \RuntimeException('S745_DELEGATE_MISSION_DELIBERATION_OPENING_CHAIN_INVALID');$ordered=array_map(static fn(string$j):array=>$found[$j],['trust','security','usability']);
        $actor=['seat'=>'senate.lord-speaker','binding_id'=>$lordSpeakerBindingId,'binding_digest'=>$l['record_digest'],'manifestation_id'=>$l['manifestation_id'],'occupancy_generation'=>$l['occupancy_generation']];$id='delegate-mission-profile-examination-deliberation-opening-'.substr(hash('sha256',CanonicalJson::encode([$readinessId,$r['record_digest'],$actor,array_column($ordered,'record_digest')])),0,20);$reconciliation=['authority_id'=>'delegate-mission-reconciliation-authority-'.substr(hash('sha256',CanonicalJson::encode([$id,array_column($ordered,'record_digest')])),0,20),'authority_single_use'=>true,'authority_exercisable'=>true,'holder'=>$actor,'purpose'=>'RECONCILE_THREE_UNCHANGED_SENATOR_FINDINGS','consumed'=>false,'voting_included'=>false,'aggregation_included'=>false,'continuing_authority'=>false];
        return$this->save($id,['schema'=>'imperium.senate-delegate-mission-profile-examination-deliberation-opening/v1','deliberation_id'=>$id,'instance_id'=>$r['instance_id'],'officer_class'=>$r['officer_class'],'source_finding_readiness'=>['id'=>$readinessId,'digest'=>$r['record_digest']],'source_finding_authority_opening'=>$r['source_finding_authority_opening'],'lord_speaker'=>$actor,'source_profile_candidate'=>$r['source_profile_candidate'],'custody_lease'=>$r['custody_lease'],'manifestation'=>$r['manifestation'],'hearing_contract'=>$r['hearing_contract'],'defect_attribution_rubric'=>$r['defect_attribution_rubric'],'admitted_findings'=>$ordered,'mandatory_security_blocking_condition'=>$r['mandatory_security_blocking_condition'],'deliberation_opening_authority'=>['id'=>$authority['authority_id'],'consumed'=>true,'continuing_authority'=>false],'reconciliation_authority'=>$reconciliation,'opened_at'=>$openedAt->format(DATE_ATOM),'status'=>'DELEGATE_MISSION_DELIBERATION_OPENED_PENDING_FINDING_RECONCILIATION','deliberation_open'=>true,'vote_authority'=>false,'aggregation_authority'=>false,'senate_disposition_authority'=>false,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'mission_seat_binding_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
    }
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function valid(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$id,array$r):array{if(!is_dir($this->deliberations)&&!mkdir($this->deliberations,0770,true)&&!is_dir($this->deliberations))throw new \RuntimeException('S748_DELEGATE_MISSION_DELIBERATION_OPENING_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->deliberations.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'S749_DELEGATE_MISSION_DELIBERATION_OPENING_CONFLICT');if($x!==$r)throw new \RuntimeException('S749_DELEGATE_MISSION_DELIBERATION_OPENING_CONFLICT');return$x;}if(false===file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX))throw new \RuntimeException('S748_DELEGATE_MISSION_DELIBERATION_OPENING_FAILED');return$r;}
}
