<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Senate;
use App\Bootstrap\CanonicalJson;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class ExaminationManifestationStandAdmissionService
{
 private string $deliveries;private string $custody;private string $occupancy;private string $admissions;
 public function __construct(#[Autowire('%kernel.project_dir%')] string $root){$s=$root.'/var/imperium/offices/senate';$this->deliveries=$s.'/examination-manifestation-intake';$this->occupancy=$s.'/occupancy';$this->admissions=$s.'/examination-stand-admissions';$this->custody=$root.'/var/imperium/offices/garrison/custody';}
 public function admit(string $deliveryId,string $bindingId):array
 {
  if(!preg_match('/^examination-manifestation-delivery-[a-f0-9]{20}$/',$deliveryId))throw new \InvalidArgumentException('S186_EXAMINATION_MANIFESTATION_DELIVERY_ID_INVALID');
  if(!preg_match('/^senate-bailiff-binding-[a-f0-9]{20}$/',$bindingId))throw new \InvalidArgumentException('S187_BAILIFF_BINDING_ID_INVALID');
  $d=$this->read($this->deliveries.'/'.$deliveryId.'.json','S188_EXAMINATION_MANIFESTATION_DELIVERY_ABSENT');$custodyId=$d['custody_lease']['custody_id']??null;$c=is_string($custodyId)?$this->read($this->custody.'/'.$custodyId.'.json','S189_EXAMINATION_CUSTODY_ABSENT'):[];$b=$this->read($this->occupancy.'/'.$bindingId.'.json','S190_BAILIFF_UNAVAILABLE');$this->validate($deliveryId,$d,$c,$bindingId,$b);
  foreach(glob($this->admissions.'/examination-stand-admission-*.json')?:[] as $path){$x=$this->read($path,'S192_EXAMINATION_STAND_ADMISSION_CONFLICT');if(!$this->ok($x))throw new \RuntimeException('S192_EXAMINATION_STAND_ADMISSION_CONFLICT');if(($x['source_delivery']['id']??null)===$deliveryId)return $x;}
  $actor=['seat'=>'senate.bailiff','binding_id'=>$bindingId,'binding_digest'=>$b['record_digest'],'manifestation_id'=>$b['manifestation_id'],'occupancy_generation'=>$b['occupancy_generation']];$id='examination-stand-admission-'.substr(hash('sha256',CanonicalJson::encode([$deliveryId,$d['record_digest'],$actor])),0,20);
  return $this->save($id,['schema'=>'imperium.senate-examination-manifestation-stand-admission/v1','admission_id'=>$id,'instance_id'=>$d['instance_id'],'proceeding_id'=>$d['proceeding_id'],'bailiff'=>$actor,'source_delivery'=>['id'=>$deliveryId,'digest'=>$d['record_digest']],'source_authorization'=>$d['source_authorization'],'source_profile_candidate'=>$d['source_profile_candidate'],'custody_lease'=>$d['custody_lease'],'manifestation'=>$d['manifestation'],'stand'=>'senate.stand','stand_admission'=>true,'proceeding_security_active'=>true,'status'=>'EXAMINATION_MANIFESTATION_ADMITTED_SECURED_PENDING_SENATE_EXAMINATION_OPENING','recipient_acceptance'=>true,'senate_examination_authority'=>false,'profile_approval_authority'=>false,'custody_release_authority'=>false,'seat_binding_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
 }
 private function validate(string $id,array $d,array $c,string $bindingId,array $b):void{$m=$d['manifestation']??null;if(!$this->ok($d)||!$this->ok($c)||!$this->ok($b)||'imperium.conscription-senate-examination-manifestation-delivery/v1'!==($d['schema']??null)||$id!==($d['delivery_id']??null)||'senate.bailiff'!==($d['recipient']['seat']??null)||'senate.stand.intake'!==($d['recipient']['surface']??null)||'EXAMINATION_MANIFESTATION_ASSEMBLED_DELIVERED_PENDING_SENATE_STAND_INTAKE'!==($d['status']??null)||null!==($d['recipient_acceptance']??null)||true!==($d['examination_profile_installation_authority_consumed']??null)||true!==($d['examination_assembly_authority_consumed']??null)||true===($d['senate_examination_authority']??null)||!is_array($m)||'SENATE_EXAMINATION_ONLY'!==($m['purpose']??null)||'senate.stand'!==($m['target']??null)||false!==($m['operational_use_permitted']??null)||false!==($m['credentials_granted']??null)||false!==($m['tool_access_granted']??null)||false!==($m['external_action_authority']??null)||($d['custody_lease']['custody_digest']??null)!==($c['record_digest']??null)||'ADMITTED_HELD'!==($c['custody_state']??null)||true!==($c['available']??null)||!in_array($b['schema']??null,['imperium.senate-bailiff-occupancy/v1','imperium.operator-root-seat-occupancy/v1'],true)||$bindingId!==($b['binding_id']??null)||'senate.bailiff'!==($b['seat']??null)||'ACTIVE'!==($b['status']??null)||true!==($b['binding_atomic']??null)||true!==($b['proceeding_security_authority']??null)||true===($b['execution_authority']??null)||($d['instance_id']??null)!==($b['instance_id']??null))throw new \RuntimeException('S191_EXAMINATION_STAND_INTAKE_CHAIN_INVALID');}
 private function read(string $p,string $e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array $r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
 private function save(string $id,array $r):array{if(!is_dir($this->admissions)&&!mkdir($this->admissions,0770,true)&&!is_dir($this->admissions))throw new \RuntimeException('S193_EXAMINATION_STAND_ADMISSION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->admissions.'/'.$id.'.json';if(is_file($p)){if(CanonicalJson::encode($x=$this->read($p,'S192_EXAMINATION_STAND_ADMISSION_CONFLICT'))!==CanonicalJson::encode($r))throw new \RuntimeException('S192_EXAMINATION_STAND_ADMISSION_CONFLICT');return $x;}$t=$p.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException('S193_EXAMINATION_STAND_ADMISSION_FAILED');}return $r;}
}
