<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Senate;
use App\Bootstrap\CanonicalJson;

final readonly class ModelBoundProfileExaminationOpeningService
{
 private string $attestations;private string $bindings;private string $authorizations;private string $occupancy;private string $cases;private string $commissions;
 public function __construct(string$root){$this->attestations=$root.'/var/imperium/offices/clavium/profile-model-access-attestations';$this->bindings=$root.'/var/imperium/offices/conscription/profile-model-bindings';$this->authorizations=$root.'/var/imperium/authorizations/missions';$this->occupancy=$root.'/var/imperium/offices/senate/occupancy';$this->cases=$root.'/var/imperium/offices/senate/profile-examination-cases';$this->commissions=$root.'/var/imperium/offices/senate/profile-examination-commission-inbox';}
 public function open(string$attestationId,string$lordSpeakerBindingId,\DateTimeImmutable$openedAt):array
 {
  $existing=$this->existing($attestationId);if(null!==$existing)return$existing;
  $a=$this->read($this->attestations.'/'.$attestationId.'.json','S240_PROFILE_MODEL_ACCESS_ATTESTATION_ABSENT');$bindingId=$a['model_binding']['binding_id']??'';$authorizationId=$a['mission_authorization']['id']??'';
  $b=$this->read($this->bindings.'/'.$bindingId.'.json','S241_PROFILE_MODEL_BINDING_ABSENT');$m=$this->read($this->authorizations.'/'.$authorizationId.'.json','S242_MISSION_AUTHORIZATION_ABSENT');$l=$this->read($this->occupancy.'/'.$lordSpeakerBindingId.'.json','S243_LORD_SPEAKER_UNAVAILABLE');$p=$b['sealed_profile']??[];
  if(!$this->ok($a)||'imperium.clavium-profile-model-access-attestation/v1'!==($a['schema']??null)||'PROFILE_MODEL_ACCESS_ATTESTED_PENDING_APPROVAL_AND_ACTIVATION'!==($a['checkpoint']??null)||'ACCESS_AVAILABLE'!==($a['status']??null)||true!==($a['sealed']??null)
   ||true===($a['credential_released']??null)||true===($a['provider_invocation_authority']??null)||true===($a['profile_approval_authority']??null)||true===($a['execution_authority']??null)
   ||!$this->ok($b)||'imperium.conscription-profile-model-binding/v1'!==($b['schema']??null)||true!==($b['sealed']??null)||($a['model_binding']['binding_digest']??null)!==($b['record_digest']??null)
   ||($a['sealed_profile']['profile_id']??null)!==($p['profile_id']??null)||($a['sealed_profile']['profile_version']??null)!==($p['profile_version']??null)||($a['sealed_profile']['content_digest']??null)!==($p['content_digest']??null)||!$this->profileOk($p)
   ||!$this->ok($m)||'imperium.mission-authorization/v1'!==($m['schema']??null)||($a['mission_authorization']['digest']??null)!==($m['record_digest']??null)
   ||!$this->ok($l)||'senate.lord-speaker'!==($l['seat']??null)||'ACTIVE'!==($l['status']??null)||true!==($l['binding_atomic']??null)||true!==($l['senate_disposition_authority']??null)||true===($l['execution_authority']??null)
   ||($a['instance_id']??null)!==($m['instance_id']??null)||($a['instance_id']??null)!==($l['instance_id']??null))throw new \RuntimeException('S244_MODEL_BOUND_PROFILE_EXAMINATION_CHAIN_INVALID');
  $actor=['seat'=>'senate.lord-speaker','binding_id'=>$lordSpeakerBindingId,'binding_digest'=>$l['record_digest'],'manifestation_id'=>$l['manifestation_id'],'occupancy_generation'=>$l['occupancy_generation']];$panel=['senate.committee.trust','senate.committee.security','senate.committee.usability'];$rubric=['model_selection_provenance','model_profile_compatibility','configuration_and_limits','fallback_governance','access_restrictions','trust','security','usability','insufficient_evidence'];
  $evidence=['mission_authorization'=>['id'=>$authorizationId,'digest'=>$m['record_digest']],'profile_model_binding'=>['id'=>$bindingId,'digest'=>$b['record_digest']],'profile_model_access_attestation'=>['id'=>$attestationId,'digest'=>$a['record_digest']],'approved_dossier'=>$m['authority_source']['dossier']??null,'imperator_review'=>$m['authority_source']['imperator_review']??null,'authorized_dossier_lines'=>$m['authorized_dossier_lines']??[],'provider_access_assertion'=>$a['provider_access_evidence']??null];
  $caseId='profile-examination-case-'.substr(hash('sha256',CanonicalJson::encode([$attestationId,$a['record_digest'],$actor,$p['content_digest'],$panel,$rubric])),0,20);$case=$this->save($this->cases,$caseId,['schema'=>'imperium.senate-model-bound-profile-examination-case/v1','case_id'=>$caseId,'instance_id'=>$a['instance_id'],'lord_speaker'=>$actor,'subject_profile'=>['profile_id'=>$p['profile_id'],'profile_version'=>$p['profile_version'],'content_digest'=>$p['content_digest'],'target'=>$p['target']],'model_binding'=>['provider_model_version'=>$p['model_binding']['provider_model_version'],'configuration'=>$p['model_binding']['configuration'],'constraints'=>$p['model_binding']['constraints'],'fallbacks'=>$p['model_binding']['fallbacks']],'access_status'=>$a['status'],'access_restrictions'=>$a['restrictions']??[],'evidence_chain'=>$evidence,'panel'=>$panel,'examination_rubric'=>$rubric,'opened_at'=>$openedAt->format(DATE_ATOM),'status'=>'PROFILE_EXAMINATION_OPENED_PENDING_SENATOR_ACCEPTANCE','testimony_open'=>false,'deliberation_open'=>false,'senator_question_authority_exercisable'=>false,'senator_finding_authority_exercisable'=>false,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'profile_activation_authority'=>false,'credential_use_authority'=>false,'provider_invocation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
  $commissions=[];foreach($panel as$seat){$id='profile-examination-commission-'.substr(hash('sha256',CanonicalJson::encode([$caseId,$case['record_digest'],$seat])),0,20);$commissions[]=$this->save($this->commissions,$id,['schema'=>'imperium.senate-model-bound-profile-examination-commission/v1','commission_id'=>$id,'instance_id'=>$a['instance_id'],'case_id'=>$caseId,'case_digest'=>$case['record_digest'],'recipient'=>['office'=>'senate','seat'=>$seat],'subject_profile'=>$case['subject_profile'],'evidence_chain'=>$evidence,'examination_rubric'=>$rubric,'status'=>'ISSUED_PENDING_SENATOR_ACCEPTANCE','recipient_acceptance'=>null,'senator_question_authority'=>true,'senator_question_authority_exercisable'=>false,'senator_finding_authority'=>false,'senator_finding_authority_exercisable'=>false,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'profile_activation_authority'=>false,'credential_use_authority'=>false,'provider_invocation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);}return['case'=>$case,'commissions'=>$commissions];
 }
 private function existing(string$id):?array{if(!is_dir($this->cases))return null;foreach(glob($this->cases.'/profile-examination-case-*.json')?:[]as$p){$case=$this->read($p,'S246_MODEL_BOUND_PROFILE_EXAMINATION_CONFLICT');if(($case['evidence_chain']['profile_model_access_attestation']['id']??null)===$id){if(!$this->ok($case))throw new \RuntimeException('S246_MODEL_BOUND_PROFILE_EXAMINATION_CONFLICT');$c=[];foreach(glob($this->commissions.'/profile-examination-commission-*.json')?:[]as$q){$x=$this->read($q,'S246_MODEL_BOUND_PROFILE_EXAMINATION_CONFLICT');if(($x['case_id']??null)===$case['case_id'])$c[]=$x;}$order=array_flip($case['panel']);usort($c,static fn(array$a,array$b):int=>($order[$a['recipient']['seat']]??PHP_INT_MAX)<=>($order[$b['recipient']['seat']]??PHP_INT_MAX));return['case'=>$case,'commissions'=>$c];}}return null;}
 private function profileOk(array$p):bool{$d=$p['content_digest']??null;unset($p['content_digest']);return is_string($d)&&hash_equals($d,'sha256:'.hash('sha256',CanonicalJson::encode($p)));}
 private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}
 private function save(string$d,string$id,array$r):array{if(!is_dir($d)&&!mkdir($d,0770,true)&&!is_dir($d))throw new \RuntimeException('S245_MODEL_BOUND_PROFILE_EXAMINATION_OPENING_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$d.'/'.$id.'.json';if(is_file($p))return$this->read($p,'S246_MODEL_BOUND_PROFILE_EXAMINATION_CONFLICT');if(false===file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX))throw new \RuntimeException('S245_MODEL_BOUND_PROFILE_EXAMINATION_OPENING_FAILED');return$r;}
}
