<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Senate;use App\Bootstrap\CanonicalJson;
final readonly class ModelBoundProfileReconciliationService
{
 private string $openings;private string $findings;private string $reconciliations;
 public function __construct(string$root,private ProfileExaminationReconciliationCognitionGateway$cognition){$s=$root.'/var/imperium/offices/senate';$this->openings=$s.'/model-bound-profile-deliberation-openings';$this->findings=$s.'/model-bound-profile-senator-findings';$this->reconciliations=$s.'/model-bound-profile-reconciliations';}
 public function reconcile(string$id,string$authorityId):array
 {
  foreach(glob($this->reconciliations.'/*.json')?:[]as$p){$x=$this->read($p,'S293_MODEL_BOUND_RECONCILIATION_CONFLICT');if(($x['source_deliberation_opening']['id']??null)===$id)return$x;}$o=$this->read($this->openings.'/'.$id.'.json','S290_MODEL_BOUND_DELIBERATION_ABSENT');$a=$o['reconciliation_authority']??[];
  if(!$this->ok($o)||'PROFILE_EXAMINATION_DELIBERATION_OPENED_PENDING_RECONCILIATION'!==($o['status']??null)||true!==($o['deliberation_open']??null)||true!==($o['reconciliation_authority_exercisable']??null)||$authorityId!==($a['authority_id']??null)||true!==($a['authority_single_use']??null)||false!==($o['vote_authority']??null)||false!==($o['aggregation_authority']??null)||false!==($o['senate_disposition_authority']??null))throw new \RuntimeException('S291_MODEL_BOUND_RECONCILIATION_CHAIN_INVALID');
  $found=[];$refs=[];foreach($o['admitted_findings']??[]as$x){$f=$this->read($this->findings.'/'.$x['finding_id'].'.json','S292_MODEL_BOUND_FINDING_ABSENT');if(!$this->ok($f)||($x['finding_digest']??null)!==$f['record_digest']||($x['decision']??null)!==$f['decision']||($x['mandatory_security_blocking_condition']??null)!==$f['mandatory_security_blocking_condition'])throw new \RuntimeException('S291_MODEL_BOUND_RECONCILIATION_CHAIN_INVALID');$found[]=$f;$refs[]='finding:'.$f['jurisdiction'].':'.$f['record_digest'];}if(array_column($found,'jurisdiction')!==['trust','security','usability'])throw new \RuntimeException('S291_MODEL_BOUND_RECONCILIATION_CHAIN_INVALID');
  $authority=['reconciliation_authority_id'=>$authorityId,'available_finding_references'=>$refs,'mandatory_security_blocking_condition'=>$o['mandatory_security_blocking_condition'],'vote_authority'=>false,'aggregation_authority'=>false,'senate_disposition_authority'=>false];$d=$this->cognition->reconcile($authority,$found);$this->validate($d,$refs,$found);$phaseId='model-bound-profile-disposition-phase-opening-authority-'.substr(hash('sha256',CanonicalJson::encode([$id,$o['record_digest'],$d])),0,20);$rid='model-bound-profile-reconciliation-'.substr(hash('sha256',CanonicalJson::encode([$id,$o['record_digest'],$d])),0,20);
  return$this->save($rid,['schema'=>'imperium.senate-model-bound-profile-reconciliation/v1','reconciliation_id'=>$rid,'instance_id'=>$o['instance_id'],'case_id'=>$o['case_id'],'case_digest'=>$o['case_digest'],'source_deliberation_opening'=>['id'=>$id,'digest'=>$o['record_digest']],'subject_profile'=>$o['subject_profile'],'admitted_findings'=>$o['admitted_findings'],'mandatory_security_blocking_condition'=>$o['mandatory_security_blocking_condition'],'reconciliation'=>$d,'reconciliation_authority'=>['id'=>$authorityId,'consumed'=>true,'continuing_authority'=>false],'disposition_phase_opening_authority'=>['authority_id'=>$phaseId,'authority_single_use'=>true,'status'=>'OPEN_PENDING_DISPOSITION_AUTHORITY_OPENING'],'status'=>'PROFILE_EXAMINATION_FINDINGS_RECONCILED_PENDING_DISPOSITION_AUTHORITY_OPENING','deliberation_open'=>true,'vote_authority'=>false,'aggregation_authority'=>false,'senate_disposition_authority'=>false,'profile_approval_authority'=>false,'profile_activation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
 }
 private function validate(array$d,array$r,array$f):void{$k=array_keys($d);sort($k);if(['agreements','attribution_treatment','disagreements','finding_references','limitations','rationale','severity_treatment','uncertainties']!==$k||$r!==($d['finding_references']??null)||!is_string($d['rationale']??null)||''===trim($d['rationale']))throw new \RuntimeException('S294_MODEL_BOUND_RECONCILIATION_INVALID');foreach(['agreements','disagreements','attribution_treatment','severity_treatment','limitations','uncertainties']as$x)if(!is_array($d[$x]??null)||!array_is_list($d[$x]))throw new \RuntimeException('S294_MODEL_BOUND_RECONCILIATION_INVALID');if([]===$d['attribution_treatment']||[]===$d['severity_treatment'])throw new \RuntimeException('S294_MODEL_BOUND_RECONCILIATION_INVALID');$s=array_unique(array_map(static fn($x)=>CanonicalJson::encode([$x['decision']['disposition'],$x['decision']['severity'],$x['decision']['attributed_defect']]),$f));if(1<count($s)&&[]===$d['disagreements'])throw new \RuntimeException('S294_MODEL_BOUND_RECONCILIATION_INVALID');}
 private function read($p,$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save($id,array$r):array{if(!is_dir($this->reconciliations))mkdir($this->reconciliations,0770,true);$r['record_digest']=hash('sha256',CanonicalJson::encode($r));file_put_contents($this->reconciliations.'/'.$id.'.json',json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
