<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Senate;use App\Bootstrap\CanonicalJson;
final readonly class ModelBoundProfileDispositionService
{
 private string $openings;private string $reconciliations;private string $findings;private string $occupancy;private string $dispositions;
 public function __construct(string$root,private ProfileExaminationDispositionCognitionGateway$cognition){$s=$root.'/var/imperium/offices/senate';$this->openings=$s.'/model-bound-profile-disposition-authority-openings';$this->reconciliations=$s.'/model-bound-profile-reconciliations';$this->findings=$s.'/model-bound-profile-senator-findings';$this->occupancy=$s.'/occupancy';$this->dispositions=$s.'/model-bound-profile-dispositions';}
 public function decide(string$openingId,string$authorityId,string$bindingId):array
 {
  foreach(glob($this->dispositions.'/*.json')?:[]as$p){$x=$this->read($p,'S304_MODEL_BOUND_DISPOSITION_CONFLICT');if(($x['source_disposition_authority_opening']['id']??null)===$openingId)return$x;}
  $o=$this->read($this->openings.'/'.$openingId.'.json','S299_MODEL_BOUND_DISPOSITION_OPENING_ABSENT');$r=$this->read($this->reconciliations.'/'.($o['source_reconciliation']['id']??'').'.json','S300_MODEL_BOUND_RECONCILIATION_ABSENT');$l=$this->read($this->occupancy.'/'.$bindingId.'.json','S301_LORD_SPEAKER_UNAVAILABLE');$a=$o['disposition_authority']??[];
  if(!$this->ok($o)||!$this->ok($r)||!$this->ok($l)||($o['source_reconciliation']['digest']??null)!==$r['record_digest']||'PROFILE_EXAMINATION_DISPOSITION_AUTHORITY_OPENED_PENDING_LORD_SPEAKER_DISPOSITION'!==($o['status']??null)||true!==($o['senate_disposition_authority']??null)||null!==($o['disposition']??null)||$authorityId!==($a['authority_id']??null)||true!==($a['authority_single_use']??null)||true!==($a['security_block_must_be_preserved']??null)||['APPROVED','RETURN_FOR_REVISION','REFUSED','UNRESOLVED']!==($a['permitted_dispositions']??null)||($o['lord_speaker']['binding_id']??null)!==$bindingId||($o['lord_speaker']['binding_digest']??null)!==$l['record_digest']||'senate.lord-speaker'!==($l['seat']??null)||'ACTIVE'!==($l['status']??null)||true!==($l['binding_atomic']??null)||true===($l['execution_authority']??null)||($o['mandatory_security_blocking_condition']??null)!==($r['mandatory_security_blocking_condition']??null)||($o['subject_profile']??null)!==($r['subject_profile']??null))throw new \RuntimeException('S302_MODEL_BOUND_DISPOSITION_CHAIN_INVALID');
  $found=[];$refs=[];foreach($r['admitted_findings']??[]as$x){$f=$this->read($this->findings.'/'.$x['finding_id'].'.json','S303_MODEL_BOUND_FINDING_ABSENT');if(!$this->ok($f)||($x['finding_digest']??null)!==$f['record_digest']||($x['decision']??null)!==$f['decision']||($x['mandatory_security_blocking_condition']??null)!==$f['mandatory_security_blocking_condition'])throw new \RuntimeException('S302_MODEL_BOUND_DISPOSITION_CHAIN_INVALID');$found[]=$f;$refs[]='finding:'.$f['jurisdiction'].':'.$f['record_digest'];}if(array_column($found,'jurisdiction')!==['trust','security','usability'])throw new \RuntimeException('S302_MODEL_BOUND_DISPOSITION_CHAIN_INVALID');
  $authority=['disposition_authority_id'=>$authorityId,'available_finding_references'=>$refs,'permitted_dispositions'=>$a['permitted_dispositions'],'mandatory_security_blocking_condition'=>$o['mandatory_security_blocking_condition'],'profile_approval_authority'=>false];$d=$this->cognition->decide($authority,$found,$r['reconciliation']);$this->validate($d,$refs);if(true===$o['mandatory_security_blocking_condition']&&'APPROVED'===$d['disposition'])throw new \RuntimeException('S306_MODEL_BOUND_PROFILE_SECURITY_VETO');
  $id='model-bound-profile-disposition-'.substr(hash('sha256',CanonicalJson::encode([$openingId,$o['record_digest'],$authorityId,$d])),0,20);return$this->save($id,['schema'=>'imperium.senate-model-bound-profile-disposition/v1','disposition_id'=>$id,'instance_id'=>$o['instance_id'],'case_id'=>$o['case_id'],'case_digest'=>$o['case_digest'],'source_disposition_authority_opening'=>['id'=>$openingId,'digest'=>$o['record_digest']],'source_reconciliation'=>$o['source_reconciliation'],'subject_profile'=>$o['subject_profile'],'admitted_findings'=>$r['admitted_findings'],'reconciliation'=>$r['reconciliation'],'mandatory_security_blocking_condition'=>$o['mandatory_security_blocking_condition'],'lord_speaker'=>$o['lord_speaker'],'disposition_authority'=>['id'=>$authorityId,'consumed'=>true,'continuing_authority'=>false],'decision'=>$d,'status'=>'PROFILE_EXAMINATION_DISPOSITION_SEALED_PENDING_IMPERATOR_PROFILE_APPROVAL','senate_disposition_authority_consumed'=>true,'imperator_profile_approval_pending'=>true,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'profile_activation_authority'=>false,'seat_binding_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
 }
 private function validate(array$d,array$refs):void{$k=array_keys($d);sort($k);if(['disposition','finding_references','limitations','rationale','reconciliation_treatment','uncertainties']!==$k||!in_array($d['disposition']??null,['APPROVED','RETURN_FOR_REVISION','REFUSED','UNRESOLVED'],true)||$refs!==($d['finding_references']??null)||!is_string($d['rationale']??null)||''===trim($d['rationale'])||!is_string($d['reconciliation_treatment']??null)||''===trim($d['reconciliation_treatment']))throw new \RuntimeException('S305_MODEL_BOUND_DISPOSITION_INVALID');foreach(['limitations','uncertainties']as$x)if(!is_array($d[$x]??null)||!array_is_list($d[$x]))throw new \RuntimeException('S305_MODEL_BOUND_DISPOSITION_INVALID');}
 private function read($p,$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save($id,array$r):array{if(!is_dir($this->dispositions))mkdir($this->dispositions,0770,true);$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->dispositions.'/'.$id.'.json';if(is_file($p)){if($this->read($p,'S304_MODEL_BOUND_DISPOSITION_CONFLICT')!==$r)throw new \RuntimeException('S304_MODEL_BOUND_DISPOSITION_CONFLICT');return$r;}file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
