<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Senate;
use App\Bootstrap\CanonicalJson;

final readonly class ModelBoundProfileEvidenceQuestioningService
{
 private string $openings;private string $cases;private string $acceptances;private string $occupancy;private string $turns;private string $readiness;
 public function __construct(string$root){$s=$root.'/var/imperium/offices/senate';$this->openings=$s.'/model-bound-profile-examination-testimony-openings';$this->cases=$s.'/profile-examination-cases';$this->acceptances=$s.'/model-bound-profile-examination-commission-acceptances';$this->occupancy=$s.'/occupancy';$this->turns=$s.'/model-bound-profile-evidence-testimony-turns';$this->readiness=$s.'/model-bound-profile-evidence-testimony-readiness';}
 public function examine(string$openingId,string$acceptanceId,string$senatorBindingId,\DateTimeImmutable$examinedAt):array
 {
  foreach(glob($this->turns.'/model-bound-profile-evidence-turn-*.json')?:[]as$p){$x=$this->read($p,'S267_MODEL_BOUND_EVIDENCE_TURN_CONFLICT');if(($x['source_acceptance']['id']??null)===$acceptanceId)return['turn'=>$x,'readiness'=>$this->ready($x['case_id'])];}
  $o=$this->read($this->openings.'/'.$openingId.'.json','S260_MODEL_BOUND_TESTIMONY_OPENING_ABSENT');$caseId=$o['case_id']??'';$case=$this->read($this->cases.'/'.$caseId.'.json','S261_MODEL_BOUND_EXAMINATION_CASE_ABSENT');$a=$this->read($this->acceptances.'/'.$acceptanceId.'.json','S262_MODEL_BOUND_ACCEPTANCE_ABSENT');$b=$this->read($this->occupancy.'/'.$senatorBindingId.'.json','S263_MODEL_BOUND_SENATOR_UNAVAILABLE');$seat=$b['seat']??'';$jurisdiction=str_starts_with($seat,'senate.committee.')?substr($seat,17):'';$authority=null;foreach($o['question_authorities']??[]as$x)if(($x['seat']??null)===$seat)$authority=$x;
  if(!$this->ok($o)||!$this->ok($case)||!$this->ok($a)||!$this->ok($b)||'imperium.senate-model-bound-profile-examination-testimony-opening/v1'!==($o['schema']??null)||'PROFILE_EXAMINATION_TESTIMONY_OPENED_PENDING_SENATOR_QUESTIONING'!==($o['status']??null)||true!==($o['testimony_open']??null)||true!==($o['senator_question_authority_exercisable']??null)||false!==($o['senator_finding_authority']??null)
   ||($o['case_digest']??null)!==($case['record_digest']??null)||($o['subject_profile']??null)!==($case['subject_profile']??null)||($o['evidence_chain']??null)!==($case['evidence_chain']??null)||($a['case_id']??null)!==$caseId||($a['case_digest']??null)!==$case['record_digest']||($a['senator']['binding_id']??null)!==$senatorBindingId||($a['senator']['binding_digest']??null)!==$b['record_digest']
   ||!in_array($jurisdiction,['trust','security','usability'],true)||!is_array($authority)||($authority['acceptance_id']??null)!==$acceptanceId||($authority['acceptance_digest']??null)!==$a['record_digest']||true!==($authority['senator_question_authority_exercisable']??null)||false!==($authority['senator_finding_authority']??null)||'ACTIVE'!==($b['status']??null)||true!==($b['binding_atomic']??null)||true!==($b['senator_question_authority']??null)||true===($b['execution_authority']??null))throw new \RuntimeException('S264_MODEL_BOUND_EVIDENCE_QUESTION_CHAIN_INVALID');
  $questions=['trust'=>'Does the sealed evidence establish trustworthy provenance, bounded behavior, and governed fallback handling?','security'=>'Does the sealed evidence preserve credential isolation, access restrictions, data boundaries, and safe configuration?','usability'=>'Does the sealed evidence establish task fitness, usable limits, and disclosed cost, latency, and fallback constraints?'];$citations=[];foreach(array_keys($case['evidence_chain'])as$key)$citations[]=['evidence_key'=>$key,'evidence_digest'=>'sha256:'.hash('sha256',CanonicalJson::encode($case['evidence_chain'][$key]))];$answer=['determination'=>'EVIDENCE_PRESENT_FOR_SENATOR_ASSESSMENT','citations'=>$citations,'access_status'=>$case['access_status'],'access_restrictions'=>$case['access_restrictions'],'model_configuration_digest'=>'sha256:'.hash('sha256',CanonicalJson::encode($case['model_binding'])),'limitations'=>['No live Manifestation was questioned.','No provider or assigned model was invoked.','Insufficient evidence must be attributed explicitly in the Senator finding.']];
  $id='model-bound-profile-evidence-turn-'.substr(hash('sha256',CanonicalJson::encode([$openingId,$o['record_digest'],$acceptanceId,$a['record_digest'],$seat,$questions[$jurisdiction],$answer])),0,20);$turn=$this->save($this->turns,$id,['schema'=>'imperium.senate-model-bound-profile-evidence-testimony-turn/v1','turn_id'=>$id,'instance_id'=>$o['instance_id'],'case_id'=>$caseId,'case_digest'=>$case['record_digest'],'source_testimony_opening'=>['id'=>$openingId,'digest'=>$o['record_digest']],'source_acceptance'=>['id'=>$acceptanceId,'digest'=>$a['record_digest']],'senator'=>$a['senator'],'jurisdiction'=>$jurisdiction,'subject_profile'=>$case['subject_profile'],'evidence_chain'=>$case['evidence_chain'],'examination_rubric'=>$case['examination_rubric'],'question'=>['purpose'=>'EXAMINE_SEALED_MODEL_BOUND_PROFILE_EVIDENCE','text'=>$questions[$jurisdiction]],'evidentiary_response'=>$answer,'examined_at'=>$examinedAt->format(DATE_ATOM),'question_authority_consumed'=>true,'question_dispatched_unchanged'=>true,'evidentiary_response_sealed'=>true,'live_witness_questioned'=>false,'provider_invoked'=>false,'assigned_model_invoked'=>false,'status'=>'PROFILE_EXAMINATION_TESTIMONY_ANSWER_SEALED_PENDING_PANEL_COMPLETION','senator_finding'=>null,'senator_finding_authority_exercisable'=>false,'deliberation_open'=>false,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'profile_activation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);return['turn'=>$turn,'readiness'=>$this->ready($caseId)];
 }
 private function ready(string$caseId):?array{$turns=[];foreach(glob($this->turns.'/model-bound-profile-evidence-turn-*.json')?:[]as$p){$t=$this->read($p,'S267_MODEL_BOUND_EVIDENCE_TURN_CONFLICT');if(!$this->ok($t))throw new \RuntimeException('S267_MODEL_BOUND_EVIDENCE_TURN_CONFLICT');if(($t['case_id']??null)===$caseId)$turns[$t['jurisdiction']]=$t;}foreach(['trust','security','usability']as$j)if(!isset($turns[$j]))return null;$ordered=[];foreach(['trust','security','usability']as$j)$ordered[]=$turns[$j];$authorityId='model-bound-profile-finding-opening-authority-'.substr(hash('sha256',CanonicalJson::encode([$caseId,array_column($ordered,'record_digest')])),0,20);$id='model-bound-profile-evidence-readiness-'.substr(hash('sha256',CanonicalJson::encode([$caseId,$authorityId])),0,20);return$this->save($this->readiness,$id,['schema'=>'imperium.senate-model-bound-profile-evidence-testimony-readiness/v1','readiness_id'=>$id,'instance_id'=>$ordered[0]['instance_id'],'case_id'=>$caseId,'case_digest'=>$ordered[0]['case_digest'],'subject_profile'=>$ordered[0]['subject_profile'],'evidence_chain'=>$ordered[0]['evidence_chain'],'testimony_turns'=>array_map(static fn(array$t):array=>['jurisdiction'=>$t['jurisdiction'],'turn_id'=>$t['turn_id'],'turn_digest'=>$t['record_digest']],$ordered),'finding_authority_opening_authority'=>['authority_id'=>$authorityId,'authority_single_use'=>true,'lord_speaker_consumption_required'=>true,'status'=>'OPEN_PENDING_FINDING_AUTHORITY_OPENING'],'status'=>'PROFILE_EXAMINATION_TESTIMONY_ANSWERS_SEALED_PENDING_FINDING_AUTHORITY_OPENING','all_questions_dispatched_unchanged'=>true,'all_evidentiary_responses_sealed'=>true,'live_witness_questioned'=>false,'provider_invoked'=>false,'senator_finding_authority_exercisable'=>false,'deliberation_open'=>false,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'profile_activation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$d,string$id,array$r):array{if(!is_dir($d)&&!mkdir($d,0770,true)&&!is_dir($d))throw new \RuntimeException('S266_MODEL_BOUND_EVIDENCE_TURN_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$d.'/'.$id.'.json';if(is_file($p)){if($this->read($p,'S267_MODEL_BOUND_EVIDENCE_TURN_CONFLICT')!==$r)throw new \RuntimeException('S267_MODEL_BOUND_EVIDENCE_TURN_CONFLICT');return$r;}file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
