<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Senate;
use App\Bootstrap\CanonicalJson;

final readonly class ModelBoundProfileDeliberationOpeningService
{
 private string $readiness;private string $findings;private string $occupancy;private string $openings;
 public function __construct(string$root){$s=$root.'/var/imperium/offices/senate';$this->readiness=$s.'/model-bound-profile-finding-readiness';$this->findings=$s.'/model-bound-profile-senator-findings';$this->occupancy=$s.'/occupancy';$this->openings=$s.'/model-bound-profile-deliberation-openings';}
 public function open(string$readinessId,string$authorityId,string$lordSpeakerBindingId,\DateTimeImmutable$openedAt):array
 {
  $r=$this->read($this->readiness.'/'.$readinessId.'.json','S284_MODEL_BOUND_FINDING_READINESS_ABSENT');$l=$this->read($this->occupancy.'/'.$lordSpeakerBindingId.'.json','S285_MODEL_BOUND_DELIBERATION_LORD_SPEAKER_UNAVAILABLE');$authority=$r['deliberation_opening_authority']??[];
  if(!$this->ok($r)||!$this->ok($l)||'imperium.senate-model-bound-profile-finding-readiness/v1'!==($r['schema']??null)||'PROFILE_EXAMINATION_SENATOR_FINDINGS_SEALED_PENDING_DELIBERATION_OPENING'!==($r['status']??null)||true!==($r['all_finding_authorities_consumed']??null)||false!==($r['deliberation_open']??null)||$authorityId!==($authority['authority_id']??null)||true!==($authority['authority_single_use']??null)||'senate.lord-speaker'!==($l['seat']??null)||'ACTIVE'!==($l['status']??null)||true!==($l['binding_atomic']??null)||true!==($l['profile_examination_deliberation_opening_authority']??null)||true===($l['execution_authority']??null)||($r['instance_id']??null)!==$l['instance_id'])throw new \RuntimeException('S286_MODEL_BOUND_DELIBERATION_OPENING_CHAIN_INVALID');
  $admitted=[];foreach($r['senator_findings']??[]as$x){$f=$this->read($this->findings.'/'.$x['finding_id'].'.json','S287_MODEL_BOUND_SENATOR_FINDING_ABSENT');if(!$this->ok($f)||($x['finding_digest']??null)!==$f['record_digest']||($x['jurisdiction']??null)!==$f['jurisdiction']||($x['disposition']??null)!==$f['decision']['disposition']||($x['severity']??null)!==$f['decision']['severity']||($x['mandatory_security_blocking_condition']??null)!==$f['mandatory_security_blocking_condition']||($r['case_id']??null)!==$f['case_id']||($r['case_digest']??null)!==$f['case_digest']||true!==($f['senator_finding_authority_consumed']??null)||false!==($f['deliberation_open']??null))throw new \RuntimeException('S286_MODEL_BOUND_DELIBERATION_OPENING_CHAIN_INVALID');$admitted[]=['jurisdiction'=>$f['jurisdiction'],'finding_id'=>$f['finding_id'],'finding_digest'=>$f['record_digest'],'decision'=>$f['decision'],'mandatory_security_blocking_condition'=>$f['mandatory_security_blocking_condition']];}
  if(array_column($admitted,'jurisdiction')!==['trust','security','usability'])throw new \RuntimeException('S286_MODEL_BOUND_DELIBERATION_OPENING_CHAIN_INVALID');$security=array_values(array_filter($admitted,static fn(array$f):bool=>'security'===$f['jurisdiction']))[0];if(($r['mandatory_security_blocking_condition']??null)!==$security['mandatory_security_blocking_condition'])throw new \RuntimeException('S286_MODEL_BOUND_DELIBERATION_OPENING_CHAIN_INVALID');$actor=['seat'=>'senate.lord-speaker','binding_id'=>$lordSpeakerBindingId,'binding_digest'=>$l['record_digest'],'manifestation_id'=>$l['manifestation_id'],'occupancy_generation'=>$l['occupancy_generation']];$reconciliationId='model-bound-profile-reconciliation-authority-'.substr(hash('sha256',CanonicalJson::encode([$readinessId,$r['record_digest'],$admitted])),0,20);$id='model-bound-profile-deliberation-opening-'.substr(hash('sha256',CanonicalJson::encode([$readinessId,$r['record_digest'],$authorityId,$actor])),0,20);
  return$this->save($id,['schema'=>'imperium.senate-model-bound-profile-deliberation-opening/v1','opening_id'=>$id,'instance_id'=>$r['instance_id'],'case_id'=>$r['case_id'],'case_digest'=>$r['case_digest'],'source_finding_readiness'=>['id'=>$readinessId,'digest'=>$r['record_digest']],'deliberation_opening_authority'=>['id'=>$authorityId,'consumed'=>true,'continuing_authority'=>false],'lord_speaker'=>$actor,'subject_profile'=>$r['subject_profile'],'admitted_findings'=>$admitted,'mandatory_security_blocking_condition'=>$r['mandatory_security_blocking_condition'],'reconciliation_authority'=>['authority_id'=>$reconciliationId,'authority_single_use'=>true,'security_block_must_be_preserved'=>true,'status'=>'OPEN_PENDING_RECONCILIATION'],'opened_at'=>$openedAt->format(DATE_ATOM),'status'=>'PROFILE_EXAMINATION_DELIBERATION_OPENED_PENDING_RECONCILIATION','deliberation_open'=>true,'reconciliation_authority_exercisable'=>true,'vote_authority'=>false,'aggregation_authority'=>false,'senate_disposition_authority'=>false,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'profile_activation_authority'=>false,'operational_qualification_authority'=>false,'manifestation_assembly_authority'=>false,'seat_binding_authority'=>false,'credential_use_authority'=>false,'provider_invocation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
 }
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$id,array$r):array{if(!is_dir($this->openings)&&!mkdir($this->openings,0770,true)&&!is_dir($this->openings))throw new \RuntimeException('S288_MODEL_BOUND_DELIBERATION_OPENING_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->openings.'/'.$id.'.json';if(is_file($p)){if($this->read($p,'S289_MODEL_BOUND_DELIBERATION_OPENING_CONFLICT')!==$r)throw new \RuntimeException('S289_MODEL_BOUND_DELIBERATION_OPENING_CONFLICT');return$r;}file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
