<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Senate;use App\Bootstrap\CanonicalJson;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class ProfileExaminationCommissionAcceptanceService
{
 private string $commissions;private string $cases;private string $occupancy;private string $acceptances;private string $readiness;
 public function __construct(#[Autowire('%kernel.project_dir%')]string $root){$s=$root.'/var/imperium/offices/senate';$this->commissions=$s.'/profile-examination-commission-inbox';$this->cases=$s.'/profile-examination-cases';$this->occupancy=$s.'/occupancy';$this->acceptances=$s.'/profile-examination-commission-acceptances';$this->readiness=$s.'/profile-examination-panel-readiness';}
 public function accept(string $commissionId,string $bindingId):array
 {
  if(!preg_match('/^profile-examination-commission-[a-f0-9]{20}$/',$commissionId))throw new \InvalidArgumentException('S200_PROFILE_EXAMINATION_COMMISSION_ID_INVALID');$c=$this->read($this->commissions.'/'.$commissionId.'.json','S201_PROFILE_EXAMINATION_COMMISSION_ABSENT');$caseId=$c['case_id']??null;$case=is_string($caseId)?$this->read($this->cases.'/'.$caseId.'.json','S202_PROFILE_EXAMINATION_CASE_ABSENT'):[];$b=$this->read($this->occupancy.'/'.$bindingId.'.json','S203_EXAMINATION_SENATOR_UNAVAILABLE');
  if(!$this->ok($c)||!$this->ok($case)||!$this->ok($b)||'imperium.senate-profile-examination-commission/v1'!==($c['schema']??null)||'ISSUED_PENDING_SENATOR_ACCEPTANCE'!==($c['status']??null)||null!==($c['recipient_acceptance']??null)||true!==($c['senator_question_authority']??null)||false!==($c['senator_question_authority_exercisable']??null)||true!==($c['senator_finding_authority']??null)||false!==($c['senator_finding_authority_exercisable']??null)||'PROFILE_EXAMINATION_OPENED_PENDING_SENATOR_ACCEPTANCE'!==($case['status']??null)||false!==($case['testimony_open']??null)||false!==($case['deliberation_open']??null)||($c['case_digest']??null)!==($case['record_digest']??null)||($c['recipient']['seat']??null)!==($b['seat']??null)||!in_array($b['seat']??null,$case['panel']??[],true)||'ACTIVE'!==($b['status']??null)||true!==($b['binding_atomic']??null)||true!==($b['senator_question_authority']??null)||true!==($b['senator_finding_authority']??null)||true===($b['execution_authority']??null)||($c['instance_id']??null)!==($b['instance_id']??null))throw new \RuntimeException('S204_PROFILE_EXAMINATION_COMMISSION_CHAIN_INVALID');
  foreach(glob($this->acceptances.'/profile-examination-commission-acceptance-*.json')?:[]as$p){$x=$this->read($p,'S206_PROFILE_EXAMINATION_ACCEPTANCE_CONFLICT');if(($x['source_commission']['id']??null)===$commissionId)return['acceptance'=>$x,'panel_readiness'=>$this->ready($case)];}
  $actor=['seat'=>$b['seat'],'binding_id'=>$bindingId,'binding_digest'=>$b['record_digest'],'manifestation_id'=>$b['manifestation_id'],'occupancy_generation'=>$b['occupancy_generation']];$id='profile-examination-commission-acceptance-'.substr(hash('sha256',CanonicalJson::encode([$commissionId,$c['record_digest'],$actor])),0,20);$a=$this->save($this->acceptances,$id,['schema'=>'imperium.senate-profile-examination-commission-acceptance/v1','acceptance_id'=>$id,'instance_id'=>$c['instance_id'],'case_id'=>$caseId,'case_digest'=>$case['record_digest'],'source_commission'=>['id'=>$commissionId,'digest'=>$c['record_digest']],'senator'=>$actor,'defect_attribution_rubric'=>$c['defect_attribution_rubric'],'disposition'=>'ACCEPTED_EXACT_PROFILE_EXAMINATION_COMMISSION','status'=>'PROFILE_EXAMINATION_COMMISSION_ACCEPTED_PENDING_PANEL_READINESS','recipient_acceptance'=>true,'senator_question_authority'=>true,'senator_question_authority_exercisable'=>false,'senator_finding_authority'=>true,'senator_finding_authority_exercisable'=>false,'testimony_open'=>false,'deliberation_open'=>false,'profile_approval_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);return['acceptance'=>$a,'panel_readiness'=>$this->ready($case)];
 }
 private function ready(array$case):?array{$found=[];foreach(glob($this->acceptances.'/profile-examination-commission-acceptance-*.json')?:[]as$p){$a=$this->read($p,'S206_PROFILE_EXAMINATION_ACCEPTANCE_CONFLICT');if(!$this->ok($a))throw new \RuntimeException('S206_PROFILE_EXAMINATION_ACCEPTANCE_CONFLICT');if(($a['case_id']??null)===($case['case_id']??null))$found[$a['senator']['seat']]=$a;}foreach($case['panel']as$s)if(!isset($found[$s]))return null;ksort($found);$id='profile-examination-panel-readiness-'.substr(hash('sha256',CanonicalJson::encode([$case['case_id'],$case['record_digest'],array_column($found,'record_digest')])),0,20);return$this->save($this->readiness,$id,['schema'=>'imperium.senate-profile-examination-panel-readiness/v1','readiness_id'=>$id,'instance_id'=>$case['instance_id'],'case_id'=>$case['case_id'],'case_digest'=>$case['record_digest'],'accepted_panel'=>array_map(fn($a)=>['seat'=>$a['senator']['seat'],'acceptance_id'=>$a['acceptance_id'],'acceptance_digest'=>$a['record_digest']],array_values($found)),'status'=>'PROFILE_EXAMINATION_PANEL_ACCEPTED_PENDING_TESTIMONY_OPENING','panel_ready'=>true,'testimony_open'=>false,'deliberation_open'=>false,'senator_question_authority_exercisable'=>false,'senator_finding_authority_exercisable'=>false,'profile_approval_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$d,string$id,array$r):array{if(!is_dir($d)&&!mkdir($d,0770,true)&&!is_dir($d))throw new \RuntimeException('S205_PROFILE_EXAMINATION_ACCEPTANCE_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$d.'/'.$id.'.json';if(is_file($p))return$this->read($p,'S206_PROFILE_EXAMINATION_ACCEPTANCE_CONFLICT');file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
