<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Senate;

use App\Bootstrap\CanonicalJson;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

final readonly class ProfileExaminationReconciliationService
{
    private string $openings;private string $findings;private string $occupancy;private string $custody;private string $reconciliations;
    public function __construct(#[Autowire('%kernel.project_dir%')]string $root,private ProfileExaminationReconciliationCognitionGateway $cognition){$senate=$root.'/var/imperium/offices/senate';$this->openings=$senate.'/profile-examination-deliberation-openings';$this->findings=$senate.'/profile-examination-senator-findings';$this->occupancy=$senate.'/occupancy';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->reconciliations=$senate.'/profile-examination-reconciliations';}

    public function reconcile(string $deliberationId,string $lordSpeakerBindingId):array
    {
        if(!preg_match('/^profile-examination-deliberation-opening-[a-f0-9]{20}$/',$deliberationId))throw new \InvalidArgumentException('S263_PROFILE_EXAMINATION_DELIBERATION_ID_INVALID');
        foreach(glob($this->reconciliations.'/*.json')?:[] as $path){$existing=$this->read($path,'S269_PROFILE_EXAMINATION_RECONCILIATION_CONFLICT');if(($existing['source_deliberation_opening']['id']??null)===$deliberationId){if(!$this->valid($existing)||($existing['lord_speaker']['binding_id']??null)!==$lordSpeakerBindingId)throw new \RuntimeException('S269_PROFILE_EXAMINATION_RECONCILIATION_CONFLICT');return $existing;}}
        $opening=$this->read($this->openings.'/'.$deliberationId.'.json','S264_PROFILE_EXAMINATION_DELIBERATION_ABSENT');
        $lordSpeaker=$this->read($this->occupancy.'/'.$lordSpeakerBindingId.'.json','S265_LORD_SPEAKER_UNAVAILABLE');
        $custodyId=$opening['custody_lease']['custody_id']??null;$custody=is_string($custodyId)?$this->read($this->custody.'/'.$custodyId.'.json','S266_PROFILE_EXAMINATION_CUSTODY_ABSENT'):[];
        if(!$this->valid($opening)||!$this->valid($lordSpeaker)||!$this->valid($custody)
            ||'imperium.senate-profile-examination-deliberation-opening/v1'!==($opening['schema']??null)||'PROFILE_EXAMINATION_DELIBERATION_OPENED_PENDING_RECONCILIATION'!==($opening['status']??null)
            ||true!==($opening['deliberation_open']??null)||true!==($opening['reconciliation_authority_exercisable']??null)||null!==($opening['reconciliation']??null)
            ||false!==($opening['vote_authority']??null)||false!==($opening['aggregation_authority']??null)||false!==($opening['senate_disposition_authority']??null)
            ||($opening['custody_lease']['custody_digest']??null)!==($custody['record_digest']??null)||'ADMITTED_HELD'!==($custody['custody_state']??null)||true!==($custody['available']??null)
            ||'senate.lord-speaker'!==($lordSpeaker['seat']??null)||'ACTIVE'!==($lordSpeaker['status']??null)||true!==($lordSpeaker['binding_atomic']??null)||true===($lordSpeaker['execution_authority']??null)
            ||($opening['lord_speaker']['binding_id']??null)!==$lordSpeakerBindingId||($opening['lord_speaker']['binding_digest']??null)!==($lordSpeaker['record_digest']??null)||($opening['instance_id']??null)!==($lordSpeaker['instance_id']??null)
        )throw new \RuntimeException('S267_PROFILE_EXAMINATION_RECONCILIATION_CHAIN_INVALID');
        $admitted=$opening['admitted_findings']??null;if(!is_array($admitted)||3!==count($admitted))throw new \RuntimeException('S267_PROFILE_EXAMINATION_RECONCILIATION_CHAIN_INVALID');
        $findings=[];$references=[];
        foreach($admitted as $snapshot){$id=$snapshot['finding_id']??null;$finding=is_string($id)?$this->read($this->findings.'/'.$id.'.json','S268_PROFILE_EXAMINATION_FINDING_ABSENT'):[];$jurisdiction=$finding['jurisdiction']??null;if(!$this->valid($finding)||$snapshot!==$finding||!in_array($jurisdiction,['trust','security','usability'],true)||isset($findings[$jurisdiction])||'PROFILE_EXAMINATION_SENATOR_FINDING_AUTHORED_SEALED_PENDING_PANEL_COMPLETION'!==($finding['status']??null)||true!==($finding['senator_finding_authority_consumed']??null)||false!==($finding['deliberation_open']??null)||false!==($finding['senate_disposition_authority']??null))throw new \RuntimeException('S267_PROFILE_EXAMINATION_RECONCILIATION_CHAIN_INVALID');$findings[$jurisdiction]=$finding;$references[$jurisdiction]='finding:'.$jurisdiction.':'.$finding['record_digest'];}
        foreach(['trust','security','usability']as$jurisdiction)if(!isset($findings[$jurisdiction]))throw new \RuntimeException('S267_PROFILE_EXAMINATION_RECONCILIATION_CHAIN_INVALID');ksort($findings);ksort($references);
        $authority=['deliberation_id'=>$deliberationId,'deliberation_digest'=>$opening['record_digest'],'lord_speaker'=>$opening['lord_speaker'],'available_finding_references'=>array_values($references),'reconciliation_authority_exercisable'=>true,'vote_authority'=>false,'aggregation_authority'=>false,'senate_disposition_authority'=>false];
        $decision=$this->cognition->reconcile($authority,array_values($findings));$this->validateDecision($decision,array_values($references),array_values($findings));
        $id='profile-examination-reconciliation-'.substr(hash('sha256',CanonicalJson::encode([$deliberationId,$opening['record_digest'],$lordSpeakerBindingId,$decision])),0,20);
        return $this->save($id,['schema'=>'imperium.senate-profile-examination-reconciliation/v1','reconciliation_id'=>$id,'instance_id'=>$opening['instance_id'],'case_id'=>$opening['case_id'],'case_digest'=>$opening['case_digest'],'source_deliberation_opening'=>['id'=>$deliberationId,'digest'=>$opening['record_digest']],'lord_speaker'=>$opening['lord_speaker'],'manifestation'=>$opening['manifestation'],'profile_candidate'=>$opening['profile_candidate'],'persona_identity'=>$opening['persona_identity'],'custody_lease'=>$opening['custody_lease'],'return_destination'=>$opening['return_destination'],'defect_attribution_rubric'=>$opening['defect_attribution_rubric'],'admitted_findings'=>array_values($findings),'reconciliation'=>$decision,'status'=>'PROFILE_EXAMINATION_FINDINGS_RECONCILED_PENDING_DISPOSITION_AUTHORITY_OPENING','reconciliation_authority_consumed'=>true,'deliberation_open'=>true,'vote_authority'=>false,'aggregation_authority'=>false,'senate_disposition_authority'=>false,'profile_approval_authority'=>false,'profile_installation_authority'=>false,'seat_binding_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
    }

    private function validateDecision(array $decision,array $references,array $findings):void{$keys=array_keys($decision);sort($keys,SORT_STRING);if(['agreements','attribution_treatment','disagreements','finding_references','limitations','rationale','severity_treatment','uncertainties']!==$keys)throw $this->invalidDecision('FIELDS_INVALID');if($references!==($decision['finding_references']??null))throw $this->invalidDecision('FINDING_REFERENCES_INVALID');if(!is_string($decision['rationale']??null)||''===trim($decision['rationale']))throw $this->invalidDecision('RATIONALE_INVALID');foreach(['agreements','disagreements','attribution_treatment','severity_treatment','limitations','uncertainties']as$field){if(!is_array($decision[$field]??null)||!array_is_list($decision[$field]))throw $this->invalidDecision(strtoupper($field).'_TYPE_INVALID');foreach($decision[$field]as$value)if(!is_string($value)||''===trim($value))throw $this->invalidDecision(strtoupper($field).'_ITEM_INVALID');}if([]===($decision['attribution_treatment']??[]))throw $this->invalidDecision('ATTRIBUTION_TREATMENT_REQUIRED');if([]===($decision['severity_treatment']??[]))throw $this->invalidDecision('SEVERITY_TREATMENT_REQUIRED');$signatures=array_unique(array_map(static fn(array $finding):string=>CanonicalJson::encode([$finding['decision']['disposition']??null,$finding['decision']['attributed_defect']??null,$finding['decision']['severity']??null]),$findings));if(1<count($signatures)&&[]===($decision['disagreements']??[]))throw $this->invalidDecision('DISAGREEMENT_OMITTED');if(1===count($signatures)&&[]===($decision['agreements']??[]))throw $this->invalidDecision('AGREEMENT_OMITTED');}
    private function invalidDecision(string $reason):\RuntimeException{return new \RuntimeException('S270_PROFILE_EXAMINATION_RECONCILIATION_INVALID: '.$reason);}
    private function read(string $path,string $error):array{if(!is_file($path))throw new \RuntimeException($error);return json_decode((string)file_get_contents($path),true,512,JSON_THROW_ON_ERROR);}
    private function valid(array $record):bool{$digest=$record['record_digest']??null;unset($record['record_digest']);return is_string($digest)&&hash_equals($digest,hash('sha256',CanonicalJson::encode($record)));}
    private function save(string $id,array $record):array{if(!is_dir($this->reconciliations)&&!mkdir($this->reconciliations,0770,true)&&!is_dir($this->reconciliations))throw new \RuntimeException('S271_PROFILE_EXAMINATION_RECONCILIATION_FAILED');$record['record_digest']=hash('sha256',CanonicalJson::encode($record));$path=$this->reconciliations.'/'.$id.'.json';if(is_file($path)){$existing=$this->read($path,'S269_PROFILE_EXAMINATION_RECONCILIATION_CONFLICT');if($existing!==$record)throw new \RuntimeException('S269_PROFILE_EXAMINATION_RECONCILIATION_CONFLICT');return $existing;}$temporary=$path.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($temporary,json_encode($record,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($temporary,$path)){@unlink($temporary);throw new \RuntimeException('S271_PROFILE_EXAMINATION_RECONCILIATION_FAILED');}return $record;}
}
