<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Senate;use App\Bootstrap\CanonicalJson;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class ProfileExaminationOpeningService
{
 private string $admissions;private string $occupancy;private string $cases;private string $commissions;
 public function __construct(#[Autowire('%kernel.project_dir%')]string $root){$s=$root.'/var/imperium/offices/senate';$this->admissions=$s.'/examination-stand-admissions';$this->occupancy=$s.'/occupancy';$this->cases=$s.'/profile-examination-cases';$this->commissions=$s.'/profile-examination-commission-inbox';}
 public function open(string $admissionId,string $bindingId):array
 {
  if(!preg_match('/^examination-stand-admission-[a-f0-9]{20}$/',$admissionId))throw new \InvalidArgumentException('S194_STAND_ADMISSION_ID_INVALID');$a=$this->read($this->admissions.'/'.$admissionId.'.json','S195_STAND_ADMISSION_ABSENT');$l=$this->read($this->occupancy.'/'.$bindingId.'.json','S196_LORD_SPEAKER_UNAVAILABLE');
  if(!$this->ok($a)||!$this->ok($l)||'EXAMINATION_MANIFESTATION_ADMITTED_SECURED_PENDING_SENATE_EXAMINATION_OPENING'!==($a['status']??null)||true!==($a['stand_admission']??null)||true!==($a['proceeding_security_active']??null)||true===($a['senate_examination_authority']??null)||'senate.lord-speaker'!==($l['seat']??null)||'ACTIVE'!==($l['status']??null)||true!==($l['binding_atomic']??null)||true!==($l['senate_disposition_authority']??null)||true===($l['execution_authority']??null)||($a['instance_id']??null)!==($l['instance_id']??null))throw new \RuntimeException('S197_PROFILE_EXAMINATION_OPENING_CHAIN_INVALID');
  foreach(glob($this->cases.'/profile-examination-case-*.json')?:[]as$p){$x=$this->read($p,'S199_PROFILE_EXAMINATION_CASE_CONFLICT');if(!$this->ok($x))throw new \RuntimeException('S199_PROFILE_EXAMINATION_CASE_CONFLICT');if(($x['source_stand_admission']['id']??null)===$admissionId)return['case'=>$x,'commissions'=>$this->existing($x['case_id'])];}
  $actor=['seat'=>'senate.lord-speaker','binding_id'=>$bindingId,'binding_digest'=>$l['record_digest'],'manifestation_id'=>$l['manifestation_id'],'occupancy_generation'=>$l['occupancy_generation']];$rubric=['persona','profile_elaboration','profile_derivation_and_sealing','conscription_assembly','generic_officer_substrate','persona_profile_compatibility','insufficient_evidence'];$caseId='profile-examination-case-'.substr(hash('sha256',CanonicalJson::encode([$admissionId,$a['record_digest'],$actor,$rubric])),0,20);$case=$this->save($this->cases,$caseId,['schema'=>'imperium.senate-profile-examination-case/v1','case_id'=>$caseId,'instance_id'=>$a['instance_id'],'proceeding_id'=>$a['proceeding_id'],'lord_speaker'=>$actor,'bailiff'=>$a['bailiff'],'source_stand_admission'=>['id'=>$admissionId,'digest'=>$a['record_digest']],'manifestation'=>$a['manifestation'],'custody_lease'=>$a['custody_lease'],'panel'=>['senate.committee.trust','senate.committee.security','senate.committee.usability'],'defect_attribution_rubric'=>$rubric,'status'=>'PROFILE_EXAMINATION_OPENED_PENDING_SENATOR_ACCEPTANCE','testimony_open'=>false,'deliberation_open'=>false,'senate_disposition'=>null,'profile_approval_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);$cs=[];foreach($case['panel']as$seat){$id='profile-examination-commission-'.substr(hash('sha256',CanonicalJson::encode([$caseId,$case['record_digest'],$seat])),0,20);$cs[]=$this->save($this->commissions,$id,['schema'=>'imperium.senate-profile-examination-commission/v1','commission_id'=>$id,'instance_id'=>$a['instance_id'],'case_id'=>$caseId,'case_digest'=>$case['record_digest'],'recipient'=>['office'=>'senate','seat'=>$seat],'manifestation_id'=>$a['manifestation']['manifestation_id'],'defect_attribution_rubric'=>$rubric,'status'=>'ISSUED_PENDING_SENATOR_ACCEPTANCE','recipient_acceptance'=>null,'senator_question_authority'=>true,'senator_question_authority_exercisable'=>false,'senator_finding_authority'=>true,'senator_finding_authority_exercisable'=>false,'profile_approval_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);}return['case'=>$case,'commissions'=>$cs];
 }
 private function existing(string$id):array{$r=[];foreach(glob($this->commissions.'/profile-examination-commission-*.json')?:[]as$p){$x=$this->read($p,'S199_PROFILE_EXAMINATION_CASE_CONFLICT');if(($x['case_id']??null)===$id)$r[]=$x;}return$r;}private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$dir,string$id,array$r):array{if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))throw new \RuntimeException('S198_PROFILE_EXAMINATION_OPENING_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$dir.'/'.$id.'.json';if(is_file($p))return$this->read($p,'S199_PROFILE_EXAMINATION_CASE_CONFLICT');file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
