<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Senate;

use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Cognition\GovernanceCognitionAuthorityResolver;
use App\Imperium\Runtime\Persistence\RecordReferenceValidator;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

final readonly class SenatePersonaFreshConsistencyQuestionGovernanceCognitionAuthorityResolver implements GovernanceCognitionAuthorityResolver
{
    private string $senate;private RecordReferenceValidator $validator;
    public function __construct(#[Autowire('%kernel.project_dir%')]string $root,?RecordReferenceValidator $validator=null){$this->senate=$root.'/var/imperium/offices/senate';$this->validator=$validator??new RecordReferenceValidator($root);}
    public function supports(string $cluster,string $authorityType):bool{return'senate-persona-confirmation'===$cluster&&'question-fresh-consistency'===$authorityType;}
    public function resolve(string $cluster,string $authorityType,string $authorityId):array
    {
        if(!$this->supports($cluster,$authorityType))throw new \RuntimeException('GCA590_FRESH_CONSISTENCY_AUTHORITY_UNSUPPORTED');
        $baseline=$this->read('jurisdiction-baselines',$authorityId);$source=$this->read('persona-witnesses',(string)($baseline['manifestation_id']??''));$target=$this->turn($baseline);
        $bailiff=$this->occupant('senate.bailiff','proceeding_security_authority',(string)$baseline['instance_id'],$source['bailiff']??null);$senator=$this->occupant('senate.committee.consistency','senator_question_authority',(string)$baseline['instance_id']);
        $freshId='senate-persona-witness-'.substr(hash('sha256',CanonicalJson::encode([$authorityId,$baseline['record_digest'],$source['manifestation_id'],$source['record_digest'],'FRESH_INSTANCE_CONSISTENCY_TRIAL'])),0,20);$fresh=$this->read('persona-witnesses',$freshId);
        $expected=$this->witness($freshId,$source,$bailiff);$actual=$fresh;unset($actual['record_digest']);
        $valid='imperium.senate-persona-jurisdiction-baseline/v1'===($baseline['schema']??null)&&'REQUIRED_JURISDICTION_BASELINE_COMPLETE_PENDING_ADDITIONAL_TRIALS'===($baseline['status']??null)&&true===($baseline['additional_trials_required']??null)
            &&($baseline['manifestation_digest']??null)===($source['record_digest']??null)&&CanonicalJson::encode($expected)===CanonicalJson::encode($actual)&&false===($baseline['execution_authority']??null);
        if(!$valid)throw new \RuntimeException('GCA592_FRESH_CONSISTENCY_AUTHORITY_INVALID');
        $assignment=['jurisdiction'=>'consistency','authority_id'=>$authorityId,'cognition_authority_type'=>'question-fresh-consistency','senator'=>$this->actor($senator),'scope'=>'fresh-instance contradiction, drift, priority, and materially different conduct',
            'baseline_id'=>$authorityId,'baseline_digest'=>$baseline['record_digest'],'equivalence_target_turn_digest'=>$target['turn_digest'],'equivalent_question_required'=>true,'fresh_manifestation_required'=>true,'question_authority'=>true,'finding_authority_exercisable'=>false];
        $context=['baseline'=>$baseline,'comparison_target'=>$target,'fresh_manifestation_id'=>$freshId];
        return['cluster'=>$cluster,'authority_type'=>$authorityType,'authority_id'=>$authorityId,'instance_id'=>$baseline['instance_id'],'case_id'=>$authorityId,'case_digest'=>$baseline['record_digest'],'seat'=>'senate.committee.consistency','purpose'=>'author-persona-question',
            'input_digest'=>hash('sha256',CanonicalJson::encode([$assignment,$context,$fresh])),'source'=>['id'=>$authorityId,'digest'=>$baseline['record_digest']],'single_use'=>true,'exercisable'=>true,'consumed'=>$this->consumed($authorityId),'expires_at'=>'9999-12-31T23:59:59+00:00'];
    }
    private function consumed(string $baselineId):bool{foreach(glob($this->senate.'/fresh-consistency-questions/*.json')?:[]as$path){$record=$this->validator->read($path,'GCA592_FRESH_CONSISTENCY_AUTHORITY_INVALID');if($this->validator->isIntact($record)&&$baselineId===($record['baseline_id']??null))return true;}return false;}
    private function turn(array $baseline):array{$matches=array_values(array_filter($baseline['turns']??[],static fn(mixed $turn):bool=>is_array($turn)&&'consistency'===($turn['jurisdiction']??null)));if(1!==count($matches)||!is_string($matches[0]['turn_digest']??null))throw new \RuntimeException('GCA592_FRESH_CONSISTENCY_AUTHORITY_INVALID');return$matches[0];}
    private function occupant(string $seat,string $authority,string $instanceId,mixed $reference=null):array{$matches=[];foreach(glob($this->senate.'/occupancy/*.json')?:[]as$path){$record=$this->validator->read($path,'GCA592_FRESH_CONSISTENCY_AUTHORITY_INVALID');if($this->validator->isIntact($record)&&$seat===($record['seat']??null))$matches[]=$record;}if(1!==count($matches)||$instanceId!==($matches[0]['instance_id']??null)||'ACTIVE'!==($matches[0]['status']??null)||true!==($matches[0][$authority]??null)||true===($matches[0]['execution_authority']??null)||(is_array($reference)&&(($reference['binding_id']??null)!==($matches[0]['binding_id']??null)||($reference['binding_digest']??null)!==($matches[0]['record_digest']??null))))throw new \RuntimeException('GCA592_FRESH_CONSISTENCY_AUTHORITY_INVALID');return$matches[0];}
    private function witness(string $id,array $source,array $bailiff):array{return['schema'=>'imperium.senate-persona-witness-manifestation/v1','manifestation_id'=>$id,'instance_id'=>$source['instance_id'],'confirmation_acceptance_id'=>$source['confirmation_acceptance_id'],'confirmation_acceptance_digest'=>$source['confirmation_acceptance_digest'],'confirmation_case_id'=>$source['confirmation_case_id'],'confirmation_case_digest'=>$source['confirmation_case_digest'],'candidate_id'=>$source['candidate_id'],'candidate_digest'=>$source['candidate_digest'],'originating_guildhall_commission_id'=>$source['originating_guildhall_commission_id'],'originating_guildhall_commission_digest'=>$source['originating_guildhall_commission_digest'],'persona_name'=>$source['persona_name'],'persona_specification_version'=>$source['persona_specification_version'],'persona'=>$source['persona'],'review_target_lineage'=>$source['review_target_lineage'],'lord_speaker'=>$source['lord_speaker'],'bailiff'=>$this->actor($bailiff),'source_manifestation_id'=>$source['manifestation_id'],'source_manifestation_digest'=>$source['record_digest'],'trial_class'=>'FRESH_INSTANCE_CONSISTENCY_TRIAL','manifestation_class'=>'STERILE_PERSONA_ONLY_STAND_INSTANCE','location'=>'senate.stand','profile'=>null,'officer_substrate'=>null,'seat'=>null,'operational_authority'=>false,'ordinary_use_prohibited'=>true,'retirement_required_after_disposition'=>true,'status'=>'INSTANTIATED_ON_STAND_PENDING_CONSISTENCY_TRIAL','senate_finding_authority'=>false,'admission_authority'=>false,'spawning_authority'=>false,'seat_binding_authority'=>false,'execution_authority'=>false,'sealed'=>true];}
    private function actor(array $binding):array{return['seat'=>$binding['seat'],'binding_id'=>$binding['binding_id'],'binding_digest'=>$binding['record_digest'],'manifestation_id'=>$binding['manifestation_id'],'occupancy_generation'=>$binding['occupancy_generation'],'founding_class'=>$binding['founding_class']??'ARTIFACT_BACKED','placeholder_version'=>$binding['placeholder_version']??null];}
    private function read(string $directory,string $id):array{$record=$this->validator->read($this->senate.'/'.$directory.'/'.$id.'.json','GCA591_FRESH_CONSISTENCY_AUTHORITY_ABSENT');return$this->validator->requireIntact($record,'GCA592_FRESH_CONSISTENCY_AUTHORITY_INVALID');}
}
