<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Senate;

use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Persistence\AtomicTransition;
use App\Imperium\Runtime\Persistence\ImmutableRecordStore;
use App\Imperium\Runtime\Persistence\RecordReferenceValidator;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

final readonly class SubordinatePersonaFreshConsistencyQuestionService
{
    private string $senate;private RecordReferenceValidator $validator;private ImmutableRecordStore $records;
    public function __construct(#[Autowire('%kernel.project_dir%')]string $root,private PersonaWitnessTestimonyCognitionGateway $cognition,?RecordReferenceValidator $validator=null,?ImmutableRecordStore $records=null){$this->senate=$root.'/var/imperium/offices/senate';$this->validator=$validator??new RecordReferenceValidator($root);$this->records=$records??new ImmutableRecordStore($root,new AtomicTransition($root));}
    public function author(string $baselineId):array
    {
        if(!preg_match('/^senate-persona-jurisdiction-baseline-[a-f0-9]{20}$/',$baselineId))throw new \InvalidArgumentException('S863_BASELINE_ID_INVALID');
        $baseline=$this->read('jurisdiction-baselines',$baselineId,'S864_BASELINE_ABSENT');$source=$this->read('persona-witnesses',(string)($baseline['manifestation_id']??''),'S865_FRESH_QUESTION_CHAIN_INVALID');
        $target=$this->turn($baseline,'consistency');$bailiff=$this->occupant('senate.bailiff','proceeding_security_authority',(string)$baseline['instance_id'],$source['bailiff']??null);$senator=$this->occupant('senate.committee.consistency','senator_question_authority',(string)$baseline['instance_id']);
        if('imperium.senate-persona-jurisdiction-baseline/v1'!==($baseline['schema']??null)||'REQUIRED_JURISDICTION_BASELINE_COMPLETE_PENDING_ADDITIONAL_TRIALS'!==($baseline['status']??null)||true!==($baseline['additional_trials_required']??null)
            ||($baseline['manifestation_digest']??null)!==($source['record_digest']??null)||'STERILE_PERSONA_ONLY_STAND_INSTANCE'!==($source['manifestation_class']??null)||true===($baseline['admission_authority']??null)||true===($baseline['execution_authority']??null))throw new \RuntimeException('S865_FRESH_QUESTION_CHAIN_INVALID');
        $freshId='senate-persona-witness-'.substr(hash('sha256',CanonicalJson::encode([$baselineId,$baseline['record_digest'],$source['manifestation_id'],$source['record_digest'],'FRESH_INSTANCE_CONSISTENCY_TRIAL'])),0,20);
        if($freshId===$source['manifestation_id'])throw new \RuntimeException('S866_FRESH_WITNESS_COLLISION');
        $fresh=$this->records->put('var/imperium/offices/senate/persona-witnesses',$freshId,$this->witness($freshId,$source,$bailiff));
        $assignment=['jurisdiction'=>'consistency','authority_id'=>$baselineId,'cognition_authority_type'=>'question-fresh-consistency','senator'=>$this->actor($senator),'scope'=>'fresh-instance contradiction, drift, priority, and materially different conduct',
            'baseline_id'=>$baselineId,'baseline_digest'=>$baseline['record_digest'],'equivalence_target_turn_digest'=>$target['turn_digest'],'equivalent_question_required'=>true,'fresh_manifestation_required'=>true,'question_authority'=>true,'finding_authority_exercisable'=>false];
        $context=['baseline'=>$baseline,'comparison_target'=>$target,'fresh_manifestation_id'=>$freshId];
        $question=$this->cognition->authorQuestion($assignment,$context,$fresh);$this->validateQuestion($question);
        if(($target['question']['trial_id']??null)===($question['trial_id']??null))throw new \RuntimeException('S867_FRESH_QUESTION_INVALID');
        $id='senate-persona-fresh-consistency-question-'.substr(hash('sha256',CanonicalJson::encode([$baselineId,$baseline['record_digest'],$freshId,$fresh['record_digest'],$question])),0,20);
        return$this->records->put('var/imperium/offices/senate/fresh-consistency-questions',$id,[
            'schema'=>'imperium.senate-persona-fresh-consistency-question/v1','question_record_id'=>$id,'instance_id'=>$baseline['instance_id'],'baseline_id'=>$baselineId,'baseline_digest'=>$baseline['record_digest'],
            'candidate_id'=>$baseline['candidate_id'],'candidate_digest'=>$baseline['candidate_digest'],'originating_guildhall_commission_id'=>$baseline['originating_guildhall_commission_id'],'originating_guildhall_commission_digest'=>$baseline['originating_guildhall_commission_digest'],'review_target_lineage'=>$baseline['review_target_lineage'],
            'source_manifestation'=>['id'=>$source['manifestation_id'],'digest'=>$source['record_digest']],'fresh_witness'=>['manifestation_id'=>$freshId,'manifestation_digest'=>$fresh['record_digest'],'source_manifestation_id'=>$source['manifestation_id'],'bailiff'=>$this->actor($bailiff)],
            'comparison_target'=>$target,'assignment'=>$assignment,'question'=>$question,'question_authority_consumed'=>true,
            'testimony_authority'=>['authority_id'=>'persona-fresh-consistency-testimony-authority-'.substr(hash('sha256',CanonicalJson::encode([$id,$question,$fresh['record_digest']])),0,20),'authority_single_use'=>true,'authority_exercisable'=>true,'witness_manifestation_id'=>$freshId,'witness_manifestation_digest'=>$fresh['record_digest'],'consumed'=>false,'continuing_authority'=>false],
            'testimony'=>null,'testimony_sealed'=>false,'status'=>'FRESH_INSTANCE_CONSISTENCY_QUESTION_SEALED_PENDING_TESTIMONY_COGNITION_AUTHORIZATION','pressure_trials_required'=>true,'senator_finding'=>null,'senate_disposition'=>null,'admission_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
    }
    private function witness(string $id,array $source,array $bailiff):array{return['schema'=>'imperium.senate-persona-witness-manifestation/v1','manifestation_id'=>$id,'instance_id'=>$source['instance_id'],'confirmation_acceptance_id'=>$source['confirmation_acceptance_id'],'confirmation_acceptance_digest'=>$source['confirmation_acceptance_digest'],'confirmation_case_id'=>$source['confirmation_case_id'],'confirmation_case_digest'=>$source['confirmation_case_digest'],'candidate_id'=>$source['candidate_id'],'candidate_digest'=>$source['candidate_digest'],'originating_guildhall_commission_id'=>$source['originating_guildhall_commission_id'],'originating_guildhall_commission_digest'=>$source['originating_guildhall_commission_digest'],'persona_name'=>$source['persona_name'],'persona_specification_version'=>$source['persona_specification_version'],'persona'=>$source['persona'],'review_target_lineage'=>$source['review_target_lineage'],'lord_speaker'=>$source['lord_speaker'],'bailiff'=>$this->actor($bailiff),'source_manifestation_id'=>$source['manifestation_id'],'source_manifestation_digest'=>$source['record_digest'],'trial_class'=>'FRESH_INSTANCE_CONSISTENCY_TRIAL','manifestation_class'=>'STERILE_PERSONA_ONLY_STAND_INSTANCE','location'=>'senate.stand','profile'=>null,'officer_substrate'=>null,'seat'=>null,'operational_authority'=>false,'ordinary_use_prohibited'=>true,'retirement_required_after_disposition'=>true,'status'=>'INSTANTIATED_ON_STAND_PENDING_CONSISTENCY_TRIAL','senate_finding_authority'=>false,'admission_authority'=>false,'spawning_authority'=>false,'seat_binding_authority'=>false,'execution_authority'=>false,'sealed'=>true];}
    private function turn(array $baseline,string $jurisdiction):array{$matches=array_values(array_filter($baseline['turns']??[],static fn(mixed $turn):bool=>is_array($turn)&&$jurisdiction===($turn['jurisdiction']??null)));if(1!==count($matches)||!is_string($matches[0]['turn_digest']??null))throw new \RuntimeException('S865_FRESH_QUESTION_CHAIN_INVALID');return$matches[0];}
    private function occupant(string $seat,string $authority,string $instanceId,mixed $reference=null):array{$matches=[];foreach(glob($this->senate.'/occupancy/*.json')?:[]as$path){$record=$this->validator->read($path,'S865_FRESH_QUESTION_CHAIN_INVALID');if($this->validator->isIntact($record)&&$seat===($record['seat']??null))$matches[]=$record;}if(1!==count($matches)||$instanceId!==($matches[0]['instance_id']??null)||'ACTIVE'!==($matches[0]['status']??null)||true!==($matches[0][$authority]??null)||true===($matches[0]['execution_authority']??null)||(is_array($reference)&&(($reference['binding_id']??null)!==($matches[0]['binding_id']??null)||($reference['binding_digest']??null)!==($matches[0]['record_digest']??null))))throw new \RuntimeException('S865_FRESH_QUESTION_CHAIN_INVALID');return$matches[0];}
    private function actor(array $binding):array{return['seat'=>$binding['seat'],'binding_id'=>$binding['binding_id'],'binding_digest'=>$binding['record_digest'],'manifestation_id'=>$binding['manifestation_id'],'occupancy_generation'=>$binding['occupancy_generation'],'founding_class'=>$binding['founding_class']??'ARTIFACT_BACKED','placeholder_version'=>$binding['placeholder_version']??null];}
    private function validateQuestion(array $question):void{$keys=array_keys($question);sort($keys,SORT_STRING);if(['purpose','question','question_set_id','trial_id']!==$keys)throw new \RuntimeException('S867_FRESH_QUESTION_INVALID');foreach($question as$value)if(!is_string($value)||''===trim($value))throw new \RuntimeException('S867_FRESH_QUESTION_INVALID');}
    private function read(string $directory,string $id,string $error):array{$record=$this->validator->read($this->senate.'/'.$directory.'/'.$id.'.json',$error);return$this->validator->requireIntact($record,$error);}
}
