<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Citadel;

use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Persistence\RecordReferenceValidator;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

final readonly class LegateBoundedCognitionTurnService
{
    private string $providerActivations;private string $decisions;private string $occupancy;private string $claims;private string $turns;private RecordReferenceValidator $validator;
    public function __construct(#[Autowire('%kernel.project_dir%')]string $root,private LegateCognitionGateway $cognition,?RecordReferenceValidator $validator=null){$this->providerActivations=$root.'/var/imperium/offices/clavium/citadel-legate-provider-invocation-activations';$this->decisions=$root.'/var/imperium/operational/citadel-legate-cognition-turn-authorization-decisions';$this->occupancy=$root.'/var/imperium/operational/occupancy';$this->claims=$root.'/var/imperium/operational/citadel-legate-provider-invocation-claims';$this->turns=$root.'/var/imperium/operational/citadel-legate-bounded-cognition-turns';$this->validator=$validator??new RecordReferenceValidator($root);}
    public function perform(string $activationId,\DateTimeImmutable $performedAt):array
    {
        if(!preg_match('/^citadel-legate-provider-invocation-activation-[a-f0-9]{20}$/',$activationId))throw new \InvalidArgumentException('CIT410_PROVIDER_ACTIVATION_ID_INVALID');
        $activation=$this->read($this->providerActivations.'/'.$activationId.'.json','CIT411_PROVIDER_ACTIVATION_ABSENT');
        foreach(glob($this->turns.'/*.json')?:[]as$path){$prior=$this->read($path,'CIT416_COGNITION_TURN_CONFLICT');if(($prior['source_provider_activation']['id']??null)===$activationId){if(($prior['source_provider_activation']['digest']??null)!==($activation['record_digest']??null))throw new \RuntimeException('CIT416_COGNITION_TURN_CONFLICT');return$prior;}}
        $decision=$this->source($this->decisions,$activation['source_cognition_turn_authorization']??[]);
        $target=$this->read($this->occupancy.'/'.($activation['target']['binding_id']??'').'.json','CIT412_TARGET_OCCUPANCY_ABSENT');
        $this->validate($activationId,$activation,$decision,$target,$performedAt);$this->assertSole($target);
        $claim=$this->claim($activationId,$activation,$performedAt);
        $output=$this->validateOutput($this->cognition->cognize($activation),$activation['contract']);
        $id='citadel-legate-bounded-cognition-turn-'.substr(hash('sha256',CanonicalJson::encode([$activationId,$activation['record_digest'],$output])),0,20);
        return$this->save($id,[
            'schema'=>'imperium.citadel-legate-bounded-cognition-turn/v1','turn_id'=>$id,'instance_id'=>$activation['instance_id'],'case_id'=>$activation['case_id'],'case_digest'=>$activation['case_digest'],
            'source_provider_activation'=>['id'=>$activationId,'digest'=>$activation['record_digest']],'source_provider_invocation_claim'=>['id'=>$claim['claim_id'],'digest'=>$claim['record_digest']],'source_cognition_turn_authorization'=>$activation['source_cognition_turn_authorization'],'source_commission'=>$decision['source_commission'],'source_commission_disposition'=>$decision['source_commission_disposition'],'source_runtime_activation'=>$decision['source_runtime_activation'],'source_model_binding'=>$activation['source_model_binding'],'source_access_attestation'=>$activation['source_access_attestation'],
            'target'=>$activation['target'],'contract'=>$activation['contract'],'model'=>$activation['model'],'output'=>$output,'performed_at'=>$performedAt->format(DATE_ATOM),
            'bounded_cognition_turn_authority'=>['id'=>$activation['bounded_cognition_turn_authority']['authority_id'],'consumed'=>true,'turns_consumed'=>1,'continuing_authority'=>false],
            'credential_lease'=>['id'=>$activation['credential_lease']['lease_id'],'consumed'=>true,'credential_reference_disclosed'=>false,'credential_possession_transferred'=>false,'continuing_authority'=>false],
            'status'=>'CITADEL_LEGATE_GOVERNED_COGNITION_TURN_'.($output['disposition']==='COMPLETED'?'COMPLETED':'STOPPED').'_SEALED_NO_CONTINUING_AUTHORITY',
            'commission_exercisable'=>false,'governed_cognition_authority'=>false,'provider_invocation_authority'=>false,'credential_use_authority'=>false,'provider_invoked'=>true,'cognition_performed'=>true,'turns_consumed'=>1,
            'operational_use_permitted'=>false,'autonomous_cognition_authority'=>false,'tool_use_authority'=>false,'tools_used'=>false,'external_action_authority'=>false,'external_action_performed'=>false,'execution_authority'=>false,'continuing_turn_authority'=>false,'sealed'=>true,
        ]);
    }
    private function validate(string$id,array$a,array$d,array$t,\DateTimeImmutable$at):void{$turn=$a['bounded_cognition_turn_authority']??[];$lease=$a['credential_lease']??[];if(!$this->ok($a)||'imperium.clavium-citadel-legate-provider-invocation-activation/v1'!==($a['schema']??null)||$id!==($a['activation_id']??null)||'CITADEL_LEGATE_PROVIDER_INVOCATION_ACTIVATED_PENDING_ONE_BOUNDED_COGNITION_TURN'!==($a['status']??null)||true!==($a['commission_exercisable']??null)||true!==($a['governed_cognition_authority']??null)||true!==($a['provider_invocation_authority']??null)||true!==($a['credential_use_authority']??null)||true===($a['provider_invoked']??null)||true===($a['cognition_performed']??null)||true!==($turn['authority_single_use']??null)||1!==($turn['maximum_turns']??null)||false!==($turn['consumed']??null)||true!==($lease['authority_single_use']??null)||false!==($lease['consumed']??null)||true===($lease['credential_reference_disclosed']??null)||true===($lease['credential_possession_transferred']??null)||new \DateTimeImmutable($a['expires_at'])<=$at||!$this->ok($d)||'AUTHORIZED'!==($d['decision']??null)||($a['source_cognition_turn_authorization']['digest']??null)!==$d['record_digest']||!$this->ok($t)||'imperium.model-bound-operational-manifestation-seat-binding/v1'!==($t['schema']??null)||true!==($t['binding_atomic']??null)||true!==($t['sealed']??null)||($a['target']['binding_id']??null)!==($t['binding_id']??null)||($a['target']['binding_digest']??null)!==($t['record_digest']??null)||($a['target']['manifestation_id']??null)!==($t['manifestation_id']??null)||($a['target']['occupancy_generation']??null)!==($t['occupancy_generation']??null)||!in_array($t['status']??null,['OPERATIONAL_MANIFESTATION_BOUND_PENDING_DEPLOYMENT_AUTHORIZATION','ACTIVE'],true)||true===($a['tool_use_authority']??null)||true===($a['external_action_authority']??null)||true===($a['execution_authority']??null)||true===($a['continuing_turn_authority']??null))throw new \RuntimeException('CIT413_COGNITION_TURN_CHAIN_INVALID');}
    private function validateOutput(array$o,array$c):array{$keys=array_keys($o);sort($keys);$expected=['disposition','evidence_references','output','stop_condition_triggered','stop_rationale','uncertainties'];sort($expected);if($keys!==$expected||!in_array($o['disposition']??null,['COMPLETED','STOPPED','REFUSED'],true)||!is_string($o['output']??null)||''===trim($o['output'])||!is_bool($o['stop_condition_triggered']??null)||(('COMPLETED'!==$o['disposition'])!==$o['stop_condition_triggered'])||!is_string($o['stop_rationale']??null)||''===trim($o['stop_rationale']))throw new \RuntimeException('CIT414_COGNITION_OUTPUT_CONTRACT_INVALID');foreach(['evidence_references','uncertainties']as$f){if(!is_array($o[$f])||!array_is_list($o[$f]))throw new \RuntimeException('CIT414_COGNITION_OUTPUT_CONTRACT_INVALID');foreach($o[$f]as$v)if(!is_string($v)||''===trim($v))throw new \RuntimeException('CIT414_COGNITION_OUTPUT_CONTRACT_INVALID');}if([]!==array_diff($o['evidence_references'],$c['inputs']??[]))throw new \RuntimeException('CIT414_COGNITION_OUTPUT_CONTRACT_INVALID');return$o;}
    private function assertSole(array$t):void{foreach(glob($this->occupancy.'/*.json')?:[]as$p){$o=$this->read($p,'CIT417_TARGET_OCCUPANCY_CONFLICT');if(($o['seat']??null)===($t['seat']??null)&&($o['binding_id']??null)!==($t['binding_id']??null)&&in_array($o['status']??null,['OPERATIONAL_MANIFESTATION_BOUND_PENDING_DEPLOYMENT_AUTHORIZATION','ACTIVE'],true))throw new \RuntimeException('CIT417_TARGET_OCCUPANCY_CONFLICT');}}
    private function claim(string$activationId,array$a,\DateTimeImmutable$at):array{$id='citadel-legate-provider-invocation-claim-'.substr(hash('sha256',CanonicalJson::encode([$activationId,$a['record_digest']])),0,20);$path=$this->claims.'/'.$id.'.json';if(!is_dir($this->claims)&&!mkdir($this->claims,0770,true)&&!is_dir($this->claims))throw new \RuntimeException('CIT415_COGNITION_TURN_PERSISTENCE_FAILED');$r=['schema'=>'imperium.citadel-legate-provider-invocation-claim/v1','claim_id'=>$id,'source_provider_activation'=>['id'=>$activationId,'digest'=>$a['record_digest']],'claimed_at'=>$at->format(DATE_ATOM),'status'=>'PROVIDER_INVOCATION_CLAIMED_AT_MOST_ONCE','replay_permitted'=>false,'sealed'=>true];$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$handle=@fopen($path,'x');if(false===$handle)throw new \RuntimeException('CIT418_PROVIDER_INVOCATION_ALREADY_CLAIMED');try{$json=json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n";if(false===fwrite($handle,$json)||!fflush($handle))throw new \RuntimeException('CIT415_COGNITION_TURN_PERSISTENCE_FAILED');}finally{fclose($handle);}return$r;}
    private function source(string$dir,array$ref):array{return$this->validator->resolve($dir,$ref,'CIT412_COGNITION_SOURCE_ABSENT','CIT413_COGNITION_TURN_CHAIN_INVALID');}private function read(string$p,string$e):array{return$this->validator->read($p,$e);}private function ok(array$r):bool{return$this->validator->isIntact($r);}
    private function save(string$id,array$r):array{if(!is_dir($this->turns)&&!mkdir($this->turns,0770,true)&&!is_dir($this->turns))throw new \RuntimeException('CIT415_COGNITION_TURN_PERSISTENCE_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->turns.'/'.$id.'.json';if(is_file($p)){if(CanonicalJson::encode($x=$this->read($p,'CIT416_COGNITION_TURN_CONFLICT'))!==CanonicalJson::encode($r))throw new \RuntimeException('CIT416_COGNITION_TURN_CONFLICT');return$x;}if(false===file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX))throw new \RuntimeException('CIT415_COGNITION_TURN_PERSISTENCE_FAILED');return$r;}
}
