<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Authorship;
use App\Bootstrap\CanonicalJson;
final readonly class AuthorshipSubordinateResolutionService
{
    private string $officeRoot;
    public function __construct(string $projectDir,private AuthorshipSubordinateCognitionGateway $cognition){$this->officeRoot=$projectDir.'/var/imperium/offices';}
    public function resolve(string $office,string $acceptanceId):array
    {
        [$role,$seat,$subordinate]=match($office){'hagiography'=>['sanctographer','hagiography.sanctographer','Chronicler'],'studium'=>['chancellor','studium.chancellor','Notary'],default=>throw new \InvalidArgumentException('A79_AUTHORSHIP_OFFICE_INVALID')};if(!preg_match('/^'.$office.'-acceptance-[a-f0-9]{20}$/',$acceptanceId))throw new \InvalidArgumentException('A83_ACCEPTANCE_INVALID');$acceptance=$this->read($this->officeRoot.'/'.$office.'/acceptances/'.$acceptanceId.'.json','A84_ACCEPTANCE_ABSENT');
        if(!$this->digestMatches($acceptance)||'imperium.authorship-commission-acceptance/v1'!==($acceptance['schema']??null)||'ACCEPTED_FOR_RESIDENT_AUTHORSHIP'!==($acceptance['disposition']??null)||true!==($acceptance['recipient_acceptance']??null)||true!==($acceptance['authorship_authority_exercisable']??null)||true!==($acceptance['subordinate_staff_resolution_authority']??null)||true!==($acceptance['subordinate_staff_resolution_pending']??null)||$subordinate!==($acceptance['subordinate_staff_class']??null)||true===($acceptance['execution_authority']??null))throw new \RuntimeException('A85_ACCEPTANCE_INVALID');
        $commissionId=$acceptance['commission_id']??null;$commission=is_string($commissionId)?$this->read($this->officeRoot.'/'.$office.'/inbox/'.$commissionId.'.json','A86_COMMISSION_ABSENT'):[];$bindingId=$acceptance['binding_id']??null;$binding=is_string($bindingId)?$this->read($this->officeRoot.'/'.$office.'/occupancy/'.$bindingId.'.json','A87_OCCUPANCY_ABSENT'):[];
        if(!$this->digestMatches($commission)||($acceptance['commission_digest']??null)!==($commission['record_digest']??null)||$seat!==($commission['target_seat']??null)||true!==($commission['authorship_authority']??null)||true===($commission['execution_authority']??null))throw new \RuntimeException('A88_COMMISSION_CHANGED');if(!$this->digestMatches($binding)||($acceptance['binding_digest']??null)!==($binding['record_digest']??null)||'ACTIVE'!==($binding['status']??null)||$seat!==($binding['seat']??null)||true!==($binding['subordinate_staff_resolution_authority']??null))throw new \RuntimeException('A89_OCCUPANCY_CHANGED');
        foreach(glob($this->officeRoot.'/'.$office.'/subordinate-resolutions/'.$office.'-subordinate-resolution-*.json')?:[]as$path){$old=$this->read($path,'A92_RESOLUTION_REPLAY_CONFLICT');if($acceptanceId===($old['acceptance_id']??null)&&$this->digestMatches($old))return $old;}
        $decision=$this->cognition->resolve($office,$acceptance,$commission,$binding);$complete='SUBORDINATE_REQUIREMENTS_DETERMINED'===($decision['disposition']??null);$id=$office.'-subordinate-resolution-'.substr(hash('sha256',CanonicalJson::encode([$acceptanceId,$acceptance['record_digest'],$decision])),0,20);
        return $this->persist($office,$id,['schema'=>'imperium.authorship-subordinate-resolution/v1','resolution_id'=>$id,'instance_id'=>$acceptance['instance_id'],'office'=>$office,'resident'=>['role'=>$role,'seat'=>$seat,'manifestation_id'=>$binding['manifestation_id'],'occupancy_generation'=>$binding['occupancy_generation']],'acceptance_id'=>$acceptanceId,'acceptance_digest'=>$acceptance['record_digest'],'commission_id'=>$commissionId,'commission_digest'=>$commission['record_digest'],'binding_id'=>$bindingId,'binding_digest'=>$binding['record_digest'],'subordinate_staff_class'=>$subordinate,'decision'=>$decision,'status'=>$complete?'PENDING_CURIA_SUBORDINATE_CONSTRUCTION_AUTHORIZATION':'CLARIFICATION_REQUIRED','subordinate_staff_resolution_complete'=>$complete,'construction_request_authority'=>$complete,'construction_authority'=>false,'persona_selection_authority'=>false,'profile_approval_authority'=>false,'spawning_authority'=>false,'seat_binding_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
    }
    private function read(string $path,string $error):array{if(!is_file($path))throw new \RuntimeException($error);return json_decode((string)file_get_contents($path),true,512,JSON_THROW_ON_ERROR);}private function digestMatches(array $r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function persist(string $office,string $id,array $r):array{$dir=$this->officeRoot.'/'.$office.'/subordinate-resolutions';if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))throw new \RuntimeException('Subordinate resolution directory cannot be created.');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$path=$dir.'/'.$id.'.json';if(is_file($path)){$old=$this->read($path,'A92_RESOLUTION_REPLAY_CONFLICT');if(CanonicalJson::encode($old)!==CanonicalJson::encode($r))throw new \RuntimeException('A92_RESOLUTION_REPLAY_CONFLICT');return $old;}$tmp=$path.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($tmp,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($tmp,$path)){@unlink($tmp);throw new \RuntimeException('Subordinate resolution cannot be committed atomically.');}return $r;}
}
