<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Authorship;

use App\Bootstrap\BootstrapState;
use App\Bootstrap\CanonicalJson;
use App\Bootstrap\StateStore;
use App\Imperium\Runtime\Conscription\GenericOfficerSubstrateRegistry;

final readonly class AuthorshipResidentSeatBindingService
{
    private string $deliveryDirectory; private string $caseDirectory; private string $officeRoot;
    public function __construct(string $projectDir, private StateStore $bootstrap, private CanonicalAuthorshipStaffRegistry $staff, private GenericOfficerSubstrateRegistry $substrate) { $this->deliveryDirectory = $projectDir.'/var/imperium/mastermason/qualified-manifestations'; $this->caseDirectory = $projectDir.'/var/imperium/mastermason/activation-cases'; $this->officeRoot = $projectDir.'/var/imperium/offices'; }
    public function bind(string $office, string $deliveryId): array
    {
        [$role, $seat, $subordinate] = match ($office) { 'hagiography' => ['sanctographer', 'hagiography.sanctographer', 'Chronicler'], 'studium' => ['chancellor', 'studium.chancellor', 'Notary'], default => throw new \InvalidArgumentException('A59_AUTHORSHIP_OFFICE_INVALID') };
        if (!preg_match('/^qualified-delivery-[a-f0-9]{20}$/', $deliveryId)) throw new \InvalidArgumentException('A60_DELIVERY_INVALID');
        $state = $this->bootstrap->read(); if (!is_array($state) || BootstrapState::CuriaReady->value !== ($state['state'] ?? null)) throw new \RuntimeException('A61_IMPERIUM_NOT_READY'); $instanceId = $state['binding']['instance_id'] ?? null; if (!is_string($instanceId) || '' === $instanceId) throw new \RuntimeException('A61_IMPERIUM_NOT_READY');
        $packet = $this->read($this->deliveryDirectory.'/'.$deliveryId.'.json', 'A62_DELIVERY_ABSENT'); $member = $this->staff->member($office); $qualification = $packet['qualification'] ?? null;
        if (!$this->digestMatches($packet) || $deliveryId !== ($packet['delivery_id'] ?? null) || 'imperium.qualified-manifestation-packet/v1' !== ($packet['schema'] ?? null) || true !== ($packet['commission']['consumed'] ?? null)
            || $instanceId !== ($packet['candidate']['instance_id'] ?? null) || $seat !== ($packet['candidate']['target_seat'] ?? null) || 'QUALIFIED_UNBOUND' !== ($packet['candidate']['status'] ?? null) || 1 !== ($packet['candidate']['target_occupancy_generation'] ?? null)
            || 'PROFILE_INSTALLED' !== ($packet['candidate']['substrate_instance']['status'] ?? null) || CanonicalJson::encode($this->substrate->current()) !== CanonicalJson::encode($packet['candidate']['substrate_instance']['substrate'] ?? null)
            || CanonicalJson::encode($member['persona']) !== CanonicalJson::encode($packet['candidate']['persona'] ?? null) || CanonicalJson::encode($member['profile']) !== CanonicalJson::encode($packet['candidate']['profile'] ?? null)
            || !is_array($qualification) || 'QUALIFIED' !== ($qualification['disposition'] ?? null) || ($packet['candidate']['manifestation_id'] ?? null) !== ($qualification['candidate_id'] ?? null)
            || CanonicalJson::encode($member['qualification_contract']) !== CanonicalJson::encode($qualification['qualification_contract'] ?? null) || !hash_equals((string) ($packet['qualification_digest'] ?? ''), hash('sha256', CanonicalJson::encode($qualification)))
            || true !== ($packet['sealed'] ?? null) || true === ($packet['authorship_authority'] ?? null) || true === ($packet['subordinate_staff_resolution_authority'] ?? null) || true === ($packet['seat_binding_authority'] ?? null) || true === ($packet['recipient_acceptance'] ?? null) || true === ($packet['execution_authority'] ?? null)) throw new \RuntimeException('A63_QUALIFIED_PACKET_INVALID');
        $caseId = $packet['source_provisioning_case_id'] ?? null; if (!is_string($caseId)) throw new \RuntimeException('A64_PROVISIONING_CHAIN_INVALID'); $case = $this->read($this->caseDirectory.'/'.$caseId.'.json', 'A64_PROVISIONING_CHAIN_INVALID');
        if (!$this->digestMatches($case) || $caseId !== ($case['case_id'] ?? null) || $office !== ($case['office'] ?? null) || $seat !== ($case['seat'] ?? null) || 'CANONICAL_STAFF_READY' !== ($case['status'] ?? null) || true !== ($case['authorship_authority'] ?? null) || true === ($case['authorship_authority_exercisable'] ?? null) || CanonicalJson::encode($this->staff->current($office)) !== CanonicalJson::encode($case['canonical_staff_package'] ?? null)) throw new \RuntimeException('A64_PROVISIONING_CHAIN_INVALID');
        return $this->persist($office, $role, ['schema' => 'imperium.authorship-resident-occupancy/v1', 'binding_id' => $office.'-'.$role.'-binding-'.substr(hash('sha256', CanonicalJson::encode([$instanceId, $deliveryId, $packet['record_digest'], $case['record_digest'], $member])), 0, 20), 'instance_id' => $instanceId, 'office' => $office, 'seat' => $seat, 'manifestation_id' => $packet['candidate']['manifestation_id'], 'prior_occupancy_generation' => 0, 'occupancy_generation' => 1, 'source_delivery_id' => $deliveryId, 'source_packet_digest' => $packet['record_digest'], 'source_provisioning_case_id' => $caseId, 'source_provisioning_case_digest' => $case['record_digest'], 'canonical_staff_package' => $this->staff->current($office), 'status' => 'ACTIVE', 'binding_atomic' => true, 'seat_binding_authority' => true, 'seat_binding_disposition' => 'CONSUMED_BY_ATOMIC_BINDING', 'authorship_authority' => true, 'authorship_authority_scope' => 'exact commissions accepted by this occupied resident Seat only', 'subordinate_staff_resolution_authority' => true, 'subordinate_staff_resolution_scope' => 'exact '.$subordinate.' requirements derived after acceptance of an exact commission only', 'recipient_acceptance' => false, 'execution_authority' => false]);
    }
    private function read(string $path, string $error): array { if (!is_file($path)) throw new \RuntimeException($error); return json_decode((string) file_get_contents($path), true, 512, JSON_THROW_ON_ERROR); }
    private function digestMatches(array $record): bool { $digest = $record['record_digest'] ?? null; unset($record['record_digest']); return is_string($digest) && hash_equals($digest, hash('sha256', CanonicalJson::encode($record))); }
    private function persist(string $office, string $role, array $record): array { $directory = $this->officeRoot.'/'.$office.'/occupancy'; if (!is_dir($directory) && !mkdir($directory, 0770, true) && !is_dir($directory)) throw new \RuntimeException('Authorship occupancy directory cannot be created.'); $record['record_digest'] = hash('sha256', CanonicalJson::encode($record)); $path=$directory.'/'.$record['binding_id'].'.json'; if (is_file($path)) { $old=$this->read($path,'A65_BINDING_ABSENT'); if (CanonicalJson::encode($old)!==CanonicalJson::encode($record)) throw new \RuntimeException('A66_BINDING_REPLAY_CONFLICT'); return $old; } if ([] !== (glob($directory.'/'.$office.'-'.$role.'-binding-*.json') ?: [])) throw new \RuntimeException('A67_RESIDENT_ALREADY_BOUND'); $tmp=$path.'.tmp.'.bin2hex(random_bytes(6)); if (false===file_put_contents($tmp,json_encode($record,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($tmp,$path)){@unlink($tmp);throw new \RuntimeException('Authorship occupancy cannot be committed atomically.');} return $record; }
}
