<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Authorship;
use App\Imperium\Runtime\Clavium\GovernanceCognitionInvoker;
final readonly class SymfonyAiAuthorshipSubordinateCognitionGateway implements AuthorshipSubordinateCognitionGateway
{
    public function __construct(private GovernanceCognitionInvoker $invoker){}
    public function resolve(string $office,array $acceptance,array $commission,array $occupancy):array
    {
        [$type,$seat,$subordinate]=match($office){'hagiography'=>['hagiography-subordinate-requirements','hagiography.sanctographer','Chronicler'],'studium'=>['studium-subordinate-requirements','studium.chancellor','Notary'],default=>throw new \InvalidArgumentException('A79_AUTHORSHIP_OFFICE_INVALID')};
        $prompt=implode("\n",['Accepted commission: '.json_encode($acceptance,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),'Original commission: '.json_encode($commission,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),'Resident occupancy: '.json_encode($occupancy,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR),'Determine only the exact '.$subordinate.' staff requirements for this commission. Do not select people, invent existing Personas or Profiles, authorize construction, spawn, bind, or execute.','Return only one JSON object with exactly these keys: disposition, rationale, required_specializations, seat_requirements, profile_requirements, assignment_boundaries, source_requirements, return_contracts, stop_conditions.','disposition must be SUBORDINATE_REQUIREMENTS_DETERMINED or CLARIFICATION_REQUIRED. rationale must be a non-empty string. Every other field must be an array of explicit non-empty strings. A complete determination requires at least one required_specialization.']);
        $content=$this->invoker->invoke('resident-requirements',$type,(string)($acceptance['acceptance_id']??''),$seat,'resolve-subordinate-requirements',[$acceptance,$commission,$occupancy],$prompt);if(''===trim($content))throw new \RuntimeException('A80_SUBORDINATE_COGNITION_EMPTY');$content=trim($content);if(str_starts_with($content,'```'))$content=preg_replace('/^```(?:json)?\s*|\s*```$/i','',$content)??$content;
        try{$result=json_decode(trim($content),true,32,JSON_THROW_ON_ERROR);}catch(\JsonException$e){throw new \RuntimeException('A81_SUBORDINATE_COGNITION_INVALID',0,$e);}if(!is_array($result))throw new \RuntimeException('A81_SUBORDINATE_COGNITION_INVALID');$keys=array_keys($result);sort($keys,SORT_STRING);$expected=['assignment_boundaries','disposition','profile_requirements','rationale','required_specializations','return_contracts','seat_requirements','source_requirements','stop_conditions'];
        if($expected!==$keys||!in_array($result['disposition']??null,['SUBORDINATE_REQUIREMENTS_DETERMINED','CLARIFICATION_REQUIRED'],true)||!is_string($result['rationale']??null)||''===trim($result['rationale']))throw new \RuntimeException('A82_SUBORDINATE_COGNITION_CONTRACT_INVALID');foreach(array_diff($expected,['disposition','rationale'])as$field){if(!is_array($result[$field]))throw new \RuntimeException('A82_SUBORDINATE_COGNITION_CONTRACT_INVALID');foreach($result[$field]as$item)if(!is_string($item)||''===trim($item))throw new \RuntimeException('A82_SUBORDINATE_COGNITION_CONTRACT_INVALID');}if('SUBORDINATE_REQUIREMENTS_DETERMINED'===$result['disposition']&&[]===$result['required_specializations'])throw new \RuntimeException('A82_SUBORDINATE_COGNITION_CONTRACT_INVALID');return $result;
    }
}
