<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Imperator;

use App\Bootstrap\CanonicalJson;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

final readonly class DelegateMissionProfileApprovalDecisionService
{
    private const string IMPERATOR_ID='imperator-development-root';
    private const array DISPOSITIONS=['APPROVED','REFUSED','RETURNED_FOR_REVISION','ALTERNATIVE_PROPOSED','CLARIFICATION_REQUIRED','DEFERRED'];
    private string $dispositions;private string $reconciliations;private string $findings;private string $decisions;
    public function __construct(#[Autowire('%kernel.project_dir%')]string $root){$s=$root.'/var/imperium/offices/senate';$this->dispositions=$s.'/delegate-mission-profile-examination-dispositions';$this->reconciliations=$s.'/delegate-mission-profile-examination-reconciliations';$this->findings=$s.'/delegate-mission-profile-examination-senator-findings';$this->decisions=$root.'/var/imperium/imperator/delegate-mission-profile-approval-decisions';}
    public function decide(string$sourceId,string$disposition,string$response,string$limitations,\DateTimeImmutable$decidedAt):array
    {
        if(!preg_match('/^delegate-mission-profile-examination-disposition-[a-f0-9]{20}$/',$sourceId))throw new \InvalidArgumentException('I240_DELEGATE_MISSION_PROFILE_DISPOSITION_ID_INVALID');$disposition=strtoupper(trim($disposition));$response=trim($response);$limitations=trim($limitations);if(!in_array($disposition,self::DISPOSITIONS,true)||''===$response||''===$limitations)throw new \InvalidArgumentException('I241_DELEGATE_MISSION_PROFILE_APPROVAL_DISPOSITION_INVALID');
        $s=$this->read($this->dispositions.'/'.$sourceId.'.json','I242_DELEGATE_MISSION_PROFILE_DISPOSITION_ABSENT');$this->validateSenate($s,$sourceId);[$r,$findings]=$this->validateCompleteRecord($s);if('APPROVED'===$disposition&&('APPROVED'!==($s['decision']['disposition']??null)||true===($s['mandatory_security_blocking_condition']??null)))throw new \RuntimeException('I244_DELEGATE_MISSION_SENATE_DISPOSITION_NOT_APPROVED');
        foreach(glob($this->decisions.'/*.json')?:[]as$p){$x=$this->read($p,'I248_DELEGATE_MISSION_PROFILE_APPROVAL_CONFLICT');if(($x['source_senate_disposition']['id']??null)===$sourceId){if(($x['disposition']??null)===$disposition&&($x['response']??null)===$response&&($x['limitations']??null)===$limitations)return$x;throw new \RuntimeException('I248_DELEGATE_MISSION_PROFILE_APPROVAL_CONFLICT');}}
        $approved='APPROVED'===$disposition;$id='delegate-mission-profile-approval-decision-'.substr(hash('sha256',CanonicalJson::encode([$sourceId,$s['record_digest'],self::IMPERATOR_ID,$disposition,$response,$limitations])),0,20);$authorityId=$approved?'delegate-mission-operational-qualification-request-authority-'.substr(hash('sha256',CanonicalJson::encode([$id,$sourceId,$s['record_digest']])),0,20):null;
        return$this->save($id,['schema'=>'imperium.imperator-delegate-mission-profile-approval-decision/v1','decision_id'=>$id,'instance_id'=>$s['instance_id'],'officer_class'=>$s['officer_class'],'actor'=>['kind'=>'imperator','id'=>self::IMPERATOR_ID],'authority_basis'=>'development-local-cli','source_senate_disposition'=>['id'=>$sourceId,'digest'=>$s['record_digest'],'decision'=>$s['decision']],'source_reconciliation'=>['id'=>$s['source_reconciliation']['id'],'digest'=>$r['record_digest']],'source_profile_candidate'=>$s['source_profile_candidate'],'custody_lease'=>$s['custody_lease'],'manifestation'=>$s['manifestation'],'hearing_contract'=>$s['hearing_contract'],'defect_attribution_rubric'=>$s['defect_attribution_rubric'],'admitted_findings'=>$s['admitted_findings'],'reconciliation'=>$s['reconciliation'],'mandatory_security_blocking_condition'=>$s['mandatory_security_blocking_condition'],'lord_speaker'=>$s['lord_speaker'],'senate_disposition_authority_consumed'=>true,'verified_finding_digests'=>array_column($findings,'record_digest'),'disposition'=>$disposition,'response'=>$response,'limitations'=>$limitations,'decided_at'=>$decidedAt->format(DATE_ATOM),'status'=>$approved?'DELEGATE_MISSION_PROFILE_APPROVED_PENDING_CONSCRIPTION_OPERATIONAL_QUALIFICATION':'DELEGATE_MISSION_NON_APPROVING_PROFILE_DISPOSITION_RECORDED','imperator_profile_approval_consumed'=>true,'profile_approved'=>$approved,'operational_qualification_request_authority'=>$approved,'operational_qualification_request'=>$approved?['authority_id'=>$authorityId,'authority_single_use'=>true,'authority_exercisable'=>true,'destination'=>'conscription.recruiter','purpose'=>'REQUEST_ONE_EXACT_DELEGATE_OPERATIONAL_PROFILE_QUALIFICATION','consumed'=>false,'continuing_authority'=>false]:null,'operational_qualification_authority'=>false,'profile_installation_authority'=>false,'manifestation_assembly_authority'=>false,'mission_seat_binding_authority'=>false,'custody_transfer_authority'=>false,'tool_use_authority'=>false,'credential_use_authority'=>false,'provider_invocation_authority'=>false,'external_action_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
    }
    private function validateSenate(array$s,string$id):void{if(!$this->valid($s)||'imperium.senate-delegate-mission-profile-examination-disposition/v1'!==($s['schema']??null)||$id!==($s['disposition_id']??null)||'DELEGATE_MISSION_SENATE_DISPOSITION_SEALED_PENDING_IMPERATOR_PROFILE_APPROVAL'!==($s['status']??null)||true!==($s['senate_disposition_authority_consumed']??null)||true!==($s['imperator_profile_approval_pending']??null)||true===($s['profile_approval_authority']??null)||true===($s['profile_installation_authority']??null)||true===($s['mission_seat_binding_authority']??null)||true===($s['deployment_authority']??null)||true===($s['execution_authority']??null)||true!==($s['disposition_authority']['consumed']??null)||false!==($s['disposition_authority']['continuing_authority']??null)||true!==($s['sealed']??null)||!is_array($s['source_profile_candidate']??null)||!is_array($s['custody_lease']??null)||!is_array($s['manifestation']??null)||!is_array($s['admitted_findings']??null)||3!==count($s['admitted_findings'])||!is_array($s['reconciliation']??null)||!is_bool($s['mandatory_security_blocking_condition']??null)||!in_array($s['decision']['disposition']??null,['APPROVED','RETURN_FOR_REVISION','REFUSED','UNRESOLVED'],true))throw new \RuntimeException('I243_DELEGATE_MISSION_PROFILE_APPROVAL_CHAIN_INVALID');}
    private function validateCompleteRecord(array$s):array
    {
        $source=$s['source_reconciliation']??[];$r=$this->read($this->reconciliations.'/'.($source['id']??'').'.json','I245_DELEGATE_MISSION_RECONCILIATION_ABSENT');if(!$this->valid($r)||'imperium.senate-delegate-mission-profile-examination-reconciliation/v1'!==($r['schema']??null)||($source['id']??null)!==($r['reconciliation_id']??null)||($source['digest']??null)!==$r['record_digest']||'DELEGATE_MISSION_FINDINGS_RECONCILED_PENDING_DISPOSITION_AUTHORITY_OPENING'!==($r['status']??null)||true!==($r['reconciliation_authority']['consumed']??null)||false!==($r['reconciliation_authority']['continuing_authority']??null)||true!==($r['sealed']??null)||($s['source_profile_candidate']??null)!==($r['source_profile_candidate']??null)||($s['custody_lease']??null)!==($r['custody_lease']??null)||($s['manifestation']??null)!==($r['manifestation']??null)||($s['admitted_findings']??null)!==($r['admitted_findings']??null)||($s['reconciliation']??null)!==($r['reconciliation']??null)||($s['mandatory_security_blocking_condition']??null)!==($r['mandatory_security_blocking_condition']??null))throw new \RuntimeException('I243_DELEGATE_MISSION_PROFILE_APPROVAL_CHAIN_INVALID');
        $found=[];$refs=[];foreach($s['admitted_findings']as$snapshot){$f=$this->read($this->findings.'/'.($snapshot['finding_id']??'').'.json','I246_DELEGATE_MISSION_FINDING_ABSENT');$j=$f['jurisdiction']??null;if(!$this->valid($f)||$snapshot!==$f||!in_array($j,['trust','security','usability'],true)||isset($found[$j]))throw new \RuntimeException('I243_DELEGATE_MISSION_PROFILE_APPROVAL_CHAIN_INVALID');$found[$j]=$f;$refs[$j]='delegate-finding:'.$j.':'.$f['record_digest'];}foreach(['trust','security','usability']as$j)if(!isset($found[$j]))throw new \RuntimeException('I243_DELEGATE_MISSION_PROFILE_APPROVAL_CHAIN_INVALID');$ordered=array_map(static fn(string$j):array=>$found[$j],['trust','security','usability']);$references=array_map(static fn(string$j):string=>$refs[$j],['trust','security','usability']);if($references!==($s['decision']['finding_references']??null)||$references!==($s['reconciliation']['finding_references']??null))throw new \RuntimeException('I243_DELEGATE_MISSION_PROFILE_APPROVAL_CHAIN_INVALID');return[$r,$ordered];
    }
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function valid(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$id,array$r):array{if(!is_dir($this->decisions)&&!mkdir($this->decisions,0770,true)&&!is_dir($this->decisions))throw new \RuntimeException('I249_DELEGATE_MISSION_PROFILE_APPROVAL_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->decisions.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'I248_DELEGATE_MISSION_PROFILE_APPROVAL_CONFLICT');if($x!==$r)throw new \RuntimeException('I248_DELEGATE_MISSION_PROFILE_APPROVAL_CONFLICT');return$x;}if(false===file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX))throw new \RuntimeException('I249_DELEGATE_MISSION_PROFILE_APPROVAL_FAILED');return$r;}
}
