<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Imperator;
use App\Bootstrap\CanonicalJson;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class ProfileApprovalDecisionService
{
    private const string IMPERATOR_ID='imperator-development-root';
    private const array DISPOSITIONS=['APPROVED','REFUSED','RETURNED_FOR_REVISION','ALTERNATIVE_PROPOSED','CLARIFICATION_REQUIRED','DEFERRED'];
    private string $sources; private string $decisions;
    public function __construct(#[Autowire('%kernel.project_dir%')]string $root){$this->sources=$root.'/var/imperium/offices/senate/profile-examination-dispositions';$this->decisions=$root.'/var/imperium/imperator/profile-approval-decisions';}
    public function decide(string $sourceId,string $disposition,string $response,string $limitations):array
    {
        if(!preg_match('/^profile-examination-disposition-[a-f0-9]{20}$/',$sourceId))throw new \InvalidArgumentException('I201_PROFILE_EXAMINATION_DISPOSITION_ID_INVALID');
        $disposition=strtoupper(trim($disposition));$response=trim($response);$limitations=trim($limitations);
        if(!in_array($disposition,self::DISPOSITIONS,true)||''===$response||''===$limitations)throw new \InvalidArgumentException('I202_PROFILE_APPROVAL_DISPOSITION_INVALID');
        $s=$this->read($this->sources.'/'.$sourceId.'.json','I203_PROFILE_EXAMINATION_DISPOSITION_ABSENT');
        if(!$this->valid($s)||'imperium.senate-profile-examination-disposition/v1'!==($s['schema']??null)||$sourceId!==($s['disposition_id']??null)||'PROFILE_EXAMINATION_DISPOSITION_SEALED_PENDING_IMPERATOR_PROFILE_APPROVAL'!==($s['status']??null)||true!==($s['senate_disposition_authority_consumed']??null)||true!==($s['imperator_profile_approval_pending']??null)||true===($s['profile_approval_authority']??null)||true===($s['profile_installation_authority']??null)||true===($s['seat_binding_authority']??null)||true===($s['deployment_authority']??null)||true===($s['execution_authority']??null)||true!==($s['sealed']??null)||!is_array($s['profile_candidate']??null)||!is_array($s['persona_identity']??null)||!is_array($s['custody_lease']??null)||!is_array($s['manifestation']??null)||!is_array($s['admitted_findings']??null)||3!==count($s['admitted_findings'])||!is_array($s['reconciliation']??null))throw new \RuntimeException('I204_PROFILE_APPROVAL_CHAIN_INVALID');
        if('APPROVED'===$disposition&&'APPROVED'!==($s['decision']['disposition']??null))throw new \RuntimeException('I205_SENATE_DISPOSITION_NOT_APPROVED');
        foreach(glob($this->decisions.'/profile-approval-decision-*.json')?:[]as$path){$prior=$this->read($path,'I208_PROFILE_APPROVAL_DECISION_CONFLICT');if(($prior['source_senate_disposition']['id']??null)===$sourceId){if(($prior['disposition']??null)===$disposition&&($prior['response']??null)===$response&&($prior['limitations']??null)===$limitations)return$prior;throw new \RuntimeException('I208_PROFILE_APPROVAL_DECISION_CONFLICT');}}
        $approved='APPROVED'===$disposition;$id='profile-approval-decision-'.substr(hash('sha256',CanonicalJson::encode([$sourceId,$s['record_digest'],self::IMPERATOR_ID,$disposition,$response,$limitations])),0,20);
        return$this->save($id,['schema'=>'imperium.imperator-profile-approval-decision/v1','decision_id'=>$id,'instance_id'=>$s['instance_id'],'case_id'=>$s['case_id'],'case_digest'=>$s['case_digest'],'actor'=>['kind'=>'imperator','id'=>self::IMPERATOR_ID],'authority_basis'=>'development-local-cli','source_senate_disposition'=>['id'=>$sourceId,'digest'=>$s['record_digest'],'decision'=>$s['decision']],'manifestation'=>$s['manifestation'],'profile_candidate'=>$s['profile_candidate'],'persona_identity'=>$s['persona_identity'],'custody_lease'=>$s['custody_lease'],'return_destination'=>$s['return_destination'],'admitted_findings'=>$s['admitted_findings'],'reconciliation'=>$s['reconciliation'],'disposition'=>$disposition,'response'=>$response,'limitations'=>$limitations,'status'=>$approved?'IMPERATOR_PROFILE_APPROVED_PENDING_CONSCRIPTION_OPERATIONAL_QUALIFICATION':'NON_APPROVING_IMPERATOR_PROFILE_DISPOSITION_RECORDED','imperator_profile_approval_consumed'=>true,'profile_approved'=>$approved,'operational_qualification_request_authority'=>$approved,'profile_installation_authority'=>false,'manifestation_assembly_authority'=>false,'seat_binding_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true]);
    }
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}
    private function valid(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
    private function save(string$id,array$r):array{if(!is_dir($this->decisions)&&!mkdir($this->decisions,0770,true)&&!is_dir($this->decisions))throw new \RuntimeException('I206_PROFILE_APPROVAL_DECISION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->decisions.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'I208_PROFILE_APPROVAL_DECISION_CONFLICT');if(CanonicalJson::encode($x)!==CanonicalJson::encode($r))throw new \RuntimeException('I208_PROFILE_APPROVAL_DECISION_CONFLICT');return$x;}$t=$p.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException('I206_PROFILE_APPROVAL_DECISION_FAILED');}return$r;}
}
