<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Garrison;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Persistence\RecordReferenceValidator;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class DelegateMissionOperationalCustodyTransitionService
{
 private string$a;private string$o;private string$c;private RecordReferenceValidator$v;private DelegateMissionDeploymentCustodyTransitionCoordinator$coordinator;
 public function __construct(#[Autowire('%kernel.project_dir%')]string$root,?RecordReferenceValidator$v=null,?DelegateMissionDeploymentCustodyTransitionCoordinator$coordinator=null){$this->a=$root.'/var/imperium/offices/curia/delegate-mission-deployment-authorizations';$this->o=$root.'/var/imperium/offices/garrison/occupancy';$this->c=$root.'/var/imperium/offices/garrison/custody';$this->v=$v??new RecordReferenceValidator($root);$this->coordinator=$coordinator??new DelegateMissionDeploymentCustodyTransitionCoordinator($root);}
 public function transition(string$id,string$bindingId,\DateTimeImmutable$at):array
 {
  if(!preg_match('/^delegate-mission-deployment-authorization-[a-f0-9]{20}$/',$id))throw new\InvalidArgumentException('GA240_DELEGATE_MISSION_DEPLOYMENT_ID_INVALID');
  $a=$this->read($this->a.'/'.$id.'.json','GA241_DELEGATE_MISSION_DEPLOYMENT_ABSENT');$k=$this->read($this->o.'/'.$bindingId.'.json','GA242_DELEGATE_MISSION_CONSTABLE_ABSENT');
  if(null!==($recovered=$this->coordinator->resumeForAuthorization($id))){if(!$this->ok($a)||!$this->ok($recovered)||($recovered['source_deployment_authorization']['digest']??null)!==($a['record_digest']??null)||($recovered['constable']['binding_id']??null)!==$bindingId)throw new\RuntimeException('GA249_DELEGATE_MISSION_CUSTODY_CONFLICT');return$recovered;}
  $c=$this->read($this->c.'/'.($a['custody_lease']['custody_id']??'').'.json','GA243_DELEGATE_MISSION_CUSTODY_ABSENT');$auth=$a['garrison_custody_transition_authority']??[];
  if(!$this->ok($a)||!$this->ok($k)||!$this->ok($c)||'imperium.curia-delegate-mission-deployment-authorization/v1'!==($a['schema']??null)||'AUTHORIZED'!==($a['disposition']??null)||'DELEGATE_MISSION_DEPLOYMENT_AUTHORIZED_PENDING_GARRISON_CUSTODY_TRANSITION'!==($a['status']??null)||true!==($a['deployment_authority']??null)||true!==($auth['authority_single_use']??null)||true!==($auth['authority_exercisable']??null)||false!==($auth['consumed']??null)||'garrison.constable'!==($auth['holder']??null)||'imperium.garrison-constable-occupancy/v1'!==($k['schema']??null)||$bindingId!==($k['binding_id']??null)||($a['instance_id']??null)!==($k['instance_id']??null)||'ACTIVE'!==($k['status']??null)||true!==($k['delegate_mission_operational_custody_transition_authority']??null)||true===($k['selection_authority']??null)||true===($k['execution_authority']??null)||($a['custody_lease']['custody_digest']??null)!==$c['record_digest']||'ADMITTED_HELD'!==($c['custody_state']??null)||true!==($c['available']??null))throw new\RuntimeException('GA244_DELEGATE_MISSION_CUSTODY_CHAIN_INVALID');
  $actor=['seat'=>'garrison.constable','binding_id'=>$bindingId,'binding_digest'=>$k['record_digest'],'manifestation_id'=>$k['manifestation_id'],'occupancy_generation'=>$k['occupancy_generation']];$next=$c;unset($next['record_digest']);$next['custody_state']='DELEGATE_MISSION_DEPLOYED_BOUND';$next['available']=false;$next['operational_custodian']=['office'=>'mission','seat'=>$a['seat'],'manifestation_id'=>$a['manifestation_id']];$next['source_deployment_authorization']=['id'=>$id,'digest'=>$a['record_digest']];$next['execution_authority']=false;$next['record_digest']=hash('sha256',CanonicalJson::encode($next));$tid='delegate-mission-operational-custody-transition-'.substr(hash('sha256',CanonicalJson::encode([$id,$a['record_digest'],$c['record_digest'],$next['record_digest'],$actor])),0,20);
  $r=['schema'=>'imperium.garrison-delegate-mission-operational-custody-transition/v1','transition_id'=>$tid,'instance_id'=>$a['instance_id'],'officer_class'=>$a['officer_class'],'constable'=>$actor,'source_deployment_authorization'=>['id'=>$id,'digest'=>$a['record_digest']],'source_binding'=>$a['source_binding'],'seat'=>$a['seat'],'manifestation_id'=>$a['manifestation_id'],'manifestation'=>$a['manifestation'],'persona'=>$a['persona'],'mission_use'=>$a['mission_use'],'prior_custody'=>['id'=>$c['custody_id'],'digest'=>$c['record_digest'],'state'=>$c['custody_state'],'available'=>$c['available']],'operational_custody'=>['id'=>$next['custody_id'],'digest'=>$next['record_digest'],'state'=>$next['custody_state'],'available'=>$next['available'],'custodian'=>$next['operational_custodian']],'custody_transition_authority'=>['id'=>$auth['authority_id'],'consumed'=>true,'continuing_authority'=>false],'transitioned_at'=>$at->format(DATE_ATOM),'status'=>'DELEGATE_MISSION_DEPLOYED_CUSTODY_TRANSITIONED_PENDING_MISSION_ACTIVATION','deployment_authority_consumed'=>true,'deployed'=>true,'operational_use_permitted'=>false,'mission_activation_authority'=>false,'cognition_authority'=>false,'provider_invocation_authority'=>false,'data_access_authority'=>false,'tool_use_authority'=>false,'credential_use_authority'=>false,'perimeter_crossing_authority'=>false,'external_action_authority'=>false,'execution_authority'=>false,'return_authority'=>false,'unbinding_authority'=>false,'sealed'=>true];
  return$this->coordinator->run($id,$tid,$r,$c,$next);
 }
 private function read(string$p,string$e):array{return$this->v->read($p,$e);}private function ok(array$r):bool{return$this->v->isIntact($r);}
}
