<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Garrison;
use App\Imperium\Runtime\Persistence\AtomicTransition;
use App\Imperium\Runtime\Persistence\ImmutableRecordStore;
use App\Imperium\Runtime\Persistence\MutableStateStore;
use App\Imperium\Runtime\Persistence\ReplayFingerprint;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class DelegateMissionTerminalTransitionCoordinator
{
 private AtomicTransition $atomic;private ImmutableRecordStore $records;private MutableStateStore $state;
 public function __construct(#[Autowire('%kernel.project_dir%')]private string$root,?AtomicTransition$atomic=null,?ImmutableRecordStore$records=null,?MutableStateStore$state=null,private ?TerminalTransitionFaultInjector$faults=null){$this->atomic=$atomic??new AtomicTransition($root);$this->records=$records??new ImmutableRecordStore($root,$this->atomic);$this->state=$state??new MutableStateStore($root,$this->atomic);}
 public function resumeForAuthorization(string$authorizationId):?array{foreach(glob($this->root.'/var/imperium/runtime/delegate-mission-terminal-transitions/*.json')?:[]as$file){$tx=$this->state->read('var/imperium/runtime/delegate-mission-terminal-transitions/'.basename($file));if(($tx['authorization_id']??null)===$authorizationId)return$this->resume($tx);}return null;}
 public function run(string$authorizationId,string$terminalId,array$terminal,array$priorCustody,array$restoredCustody,array$priorBinding,array$retiredBinding):array{return$this->atomic->run('delegate-terminal:'.hash('sha256',$authorizationId),function()use($authorizationId,$terminalId,$terminal,$priorCustody,$restoredCustody,$priorBinding,$retiredBinding):array{$path='var/imperium/runtime/delegate-mission-terminal-transitions/'.$terminalId.'.json';$inputs=['authorization_id'=>$authorizationId,'terminal_id'=>$terminalId,'terminal'=>$terminal,'prior_custody'=>$priorCustody,'restored_custody'=>$restoredCustody,'prior_binding'=>$priorBinding,'retired_binding'=>$retiredBinding];try{$tx=$this->state->read($path);ReplayFingerprint::requireMatch($tx['replay_fingerprint']??null,$inputs,'GA309_DELEGATE_TERMINAL_RETURN_CONFLICT');}catch(\RuntimeException$e){if('PST122_MUTABLE_STATE_ABSENT'!==$e->getMessage())throw$e;$tx=$this->state->compareAndSwap($path,null,['schema'=>'imperium.garrison-delegate-mission-terminal-transition/v1','transition_id'=>$terminalId,'authorization_id'=>$authorizationId,'replay_fingerprint'=>ReplayFingerprint::of($inputs),'prior_custody'=>$priorCustody,'restored_custody'=>$restoredCustody,'prior_binding'=>$priorBinding,'retired_binding'=>$retiredBinding,'terminal'=>$terminal,'checkpoint'=>'PREPARED','automatic_rollback_permitted'=>false]);$this->faults?->after('PREPARED');}if('PREPARED'===$tx['checkpoint']){$this->advance('var/imperium/offices/garrison/custody/'.$restoredCustody['custody_id'].'.json',$priorCustody,$restoredCustody);$tx=$this->checkpoint($path,$tx,'CUSTODY_RESTORED');$this->faults?->after('CUSTODY_RESTORED');}if('CUSTODY_RESTORED'===$tx['checkpoint']){$this->advance('var/imperium/mission/occupancy/'.$retiredBinding['binding_id'].'.json',$priorBinding,$retiredBinding);$tx=$this->checkpoint($path,$tx,'BINDING_RETIRED');$this->faults?->after('BINDING_RETIRED');}if('BINDING_RETIRED'===$tx['checkpoint']){$record=$this->records->put('var/imperium/offices/garrison/delegate-mission-terminal-returns',$terminalId,$terminal);$tx=$this->checkpoint($path,$tx,'TERMINAL_RECORDED');$this->faults?->after('TERMINAL_RECORDED');}else{$record=$this->records->read('var/imperium/offices/garrison/delegate-mission-terminal-returns',$terminalId);}if('TERMINAL_RECORDED'===$tx['checkpoint']){$this->checkpoint($path,$tx,'COMPLETE');$this->faults?->after('COMPLETE');}return$record;});}
 private function advance(string$path,array$prior,array$next):void{$current=$this->state->read($path);if($current===$next)return;if($current!==$prior)throw new\RuntimeException('GA309_DELEGATE_TERMINAL_RETURN_CONFLICT');$digest=$prior['record_digest'];unset($next['record_digest']);$this->state->compareAndSwap($path,$digest,$next);}
 private function checkpoint(string$path,array$tx,string$status):array{$digest=$tx['record_digest'];unset($tx['record_digest']);$tx['checkpoint']=$status;return$this->state->compareAndSwap($path,$digest,$tx);}
 private function resume(array$tx):array{return$this->run($tx['authorization_id'],$tx['transition_id'],$tx['terminal'],$tx['prior_custody'],$tx['restored_custody'],$tx['prior_binding'],$tx['retired_binding']);}
}
