<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Garrison;
use App\Bootstrap\CanonicalJson;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class OperationalReturnRetirementService
{
 private string$authorizations;private string$executions;private string$bindings;private string$occupancy;private string$custody;private string$terminals;
 public function __construct(#[Autowire('%kernel.project_dir%')]string$root){$this->authorizations=$root.'/var/imperium/offices/curia/operational-return-authorizations';$this->executions=$root.'/var/imperium/mission/bounded-executions';$this->bindings=$root.'/var/imperium/mission/occupancy';$this->occupancy=$root.'/var/imperium/offices/garrison/occupancy';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->terminals=$root.'/var/imperium/offices/garrison/operational-return-retirements';}
 public function complete(string$authorizationId,string$constableBindingId):array
 {
  if(!preg_match('/^operational-return-authorization-[a-f0-9]{20}$/',$authorizationId))throw new \InvalidArgumentException('GA208_OPERATIONAL_RETURN_AUTHORIZATION_ID_INVALID');$a=$this->read($this->authorizations.'/'.$authorizationId.'.json','GA209_OPERATIONAL_RETURN_AUTHORIZATION_ABSENT');foreach(glob($this->terminals.'/operational-return-retirement-*.json')?:[]as$p){$x=$this->read($p,'GA215_OPERATIONAL_RETURN_RETIREMENT_CONFLICT');if(!$this->ok($x))throw new \RuntimeException('GA215_OPERATIONAL_RETURN_RETIREMENT_CONFLICT');if(($x['source_return_authorization']['id']??null)===$authorizationId)return$x;}
  $eid=$a['source_bounded_execution']['id']??null;$e=is_string($eid)?$this->read($this->executions.'/'.$eid.'.json','GA210_BOUNDED_EXECUTION_ABSENT'):[];$bid=$a['source_binding']['id']??null;$b=is_string($bid)?$this->read($this->bindings.'/'.$bid.'.json','GA211_OPERATIONAL_BINDING_ABSENT'):[];$k=$this->read($this->occupancy.'/'.$constableBindingId.'.json','GA212_CONSTABLE_OCCUPANCY_ABSENT');$cid=$a['operational_custody']['id']??null;$c=is_string($cid)?$this->read($this->custody.'/'.$cid.'.json','GA213_OPERATIONAL_CUSTODY_ABSENT'):[];$this->validate($authorizationId,$a,$e,$b,$constableBindingId,$k,$c);
  $actor=['seat'=>'garrison.constable','binding_id'=>$constableBindingId,'manifestation_id'=>$k['manifestation_id'],'occupancy_generation'=>$k['occupancy_generation']];$restored=$c;unset($restored['record_digest'],$restored['operational_custodian']);$restored['custody_state']='ADMITTED_HELD';$restored['available']=true;$restored['execution_authority']=false;$restored['last_retired_manifestation_id']=$a['manifestation_id'];$restored['return_destination']=$a['return_destination'];$restored['record_digest']=hash('sha256',CanonicalJson::encode($restored));$id='operational-return-retirement-'.substr(hash('sha256',CanonicalJson::encode([$authorizationId,$a['record_digest'],$e['record_digest'],$b['record_digest'],$c['record_digest'],$restored['record_digest'],$actor])),0,20);
  $record=['schema'=>'imperium.garrison-operational-return-retirement/v1','terminal_id'=>$id,'instance_id'=>$a['instance_id'],'case_id'=>$a['case_id'],'case_digest'=>$a['case_digest'],'constable'=>$actor,'source_return_authorization'=>['id'=>$authorizationId,'digest'=>$a['record_digest']],'source_bounded_execution'=>$a['source_bounded_execution'],'source_execution_authorization'=>$a['source_execution_authorization'],'source_custody_transition'=>$a['source_custody_transition'],'source_deployment_authorization'=>$a['source_deployment_authorization'],'source_binding'=>$a['source_binding'],'seat'=>$a['seat'],'manifestation_id'=>$a['manifestation_id'],'persona_identity'=>$a['persona_identity'],'profile_candidate'=>$a['profile_candidate'],'return_destination'=>$a['return_destination'],'operational_transcript'=>['mission_use'=>$a['mission_use'],'input'=>$a['input'],'input_digest'=>$a['input_digest'],'output'=>$a['output']],'prior_operational_custody'=>['id'=>$c['custody_id'],'digest'=>$c['record_digest'],'state'=>$c['custody_state'],'available'=>$c['available']],'restored_custody'=>['id'=>$restored['custody_id'],'digest'=>$restored['record_digest'],'state'=>$restored['custody_state'],'available'=>$restored['available']],'status'=>'OPERATIONAL_MANIFESTATION_RETURNED_RETIRED_CUSTODY_RESTORED','return_authority_consumed'=>true,'retirement_authority_consumed'=>true,'unbinding_authority_consumed'=>true,'custody_restoration_authority_consumed'=>true,'returned'=>true,'manifestation_retired'=>true,'seat_bound'=>false,'custody_restored'=>true,'operational_use_permitted'=>false,'tool_access_authority'=>false,'credentials_authority'=>false,'external_action_authority'=>false,'network_access_authority'=>false,'execution_authority'=>false,'continuing_authority'=>false,'redeployment_authority'=>false,'reuse_authority'=>false,'supersession_authority'=>false,'sealed'=>true];$record=$this->save($id,$record);$this->replaceCustody($c,$restored);return$record;
 }
 private function validate(string$id,array$a,array$e,array$b,string$kid,array$k,array$c):void{if(!$this->ok($a)||!$this->ok($e)||!$this->ok($b)||!$this->ok($k)||!$this->ok($c)||'imperium.curia-operational-return-authorization/v1'!==($a['schema']??null)||$id!==($a['authorization_id']??null)||'OPERATIONAL_RETURN_AUTHORIZED_PENDING_GARRISON_RETIREMENT'!==($a['status']??null)||true!==($a['return_authority_exercisable']??null)||true!==($a['retirement_authority_exercisable']??null)||true!==($a['unbinding_authority_exercisable']??null)||true!==($a['custody_restoration_authority_exercisable']??null)||true===($a['execution_authority']??null)||'imperium.mission-bounded-operational-execution/v1'!==($e['schema']??null)||($a['source_bounded_execution']['digest']??null)!==($e['record_digest']??null)||true!==($e['execution_complete']??null)||true===($e['continuing_execution_authority']??null)||'imperium.operational-manifestation-seat-binding/v1'!==($b['schema']??null)||($a['source_binding']['digest']??null)!==($b['record_digest']??null)||true!==($b['seat_bound']??null)||($a['manifestation_id']??null)!==($b['manifestation_id']??null)||'imperium.garrison-constable-occupancy/v1'!==($k['schema']??null)||$kid!==($k['binding_id']??null)||($a['instance_id']??null)!==($k['instance_id']??null)||'ACTIVE'!==($k['status']??null)||true!==($k['operational_return_retirement_authority']??null)||true===($k['execution_authority']??null)||'imperium.garrison-persona-custody/v1'!==($c['schema']??null)||($a['operational_custody']['digest']??null)!==($c['record_digest']??null)||'DEPLOYED_BOUND'!==($c['custody_state']??null)||false!==($c['available']??null)||($a['manifestation_id']??null)!==($c['operational_custodian']['manifestation_id']??null))throw new \RuntimeException('GA214_OPERATIONAL_RETURN_RETIREMENT_CHAIN_INVALID');}
 private function replaceCustody(array$prior,array$next):void{$p=$this->custody.'/'.$prior['custody_id'].'.json';if(CanonicalJson::encode($this->read($p,'GA213_OPERATIONAL_CUSTODY_ABSENT'))!==CanonicalJson::encode($prior))throw new \RuntimeException('GA215_OPERATIONAL_RETURN_RETIREMENT_CONFLICT');$t=$p.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($next,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException('GA216_OPERATIONAL_RETURN_RETIREMENT_FAILED');}}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$id,array$r):array{if(!is_dir($this->terminals)&&!mkdir($this->terminals,0770,true)&&!is_dir($this->terminals))throw new \RuntimeException('GA216_OPERATIONAL_RETURN_RETIREMENT_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->terminals.'/'.$id.'.json';if(is_file($p)){if(CanonicalJson::encode($x=$this->read($p,'GA215_OPERATIONAL_RETURN_RETIREMENT_CONFLICT'))!==CanonicalJson::encode($r))throw new \RuntimeException('GA215_OPERATIONAL_RETURN_RETIREMENT_CONFLICT');return$x;}if(false===file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX))throw new \RuntimeException('GA216_OPERATIONAL_RETURN_RETIREMENT_FAILED');return$r;}
}
