<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Garrison;
use App\Bootstrap\CanonicalJson;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class OperationalCustodyTransitionService
{
 private string$authorizations;private string$occupancy;private string$custody;private string$transitions;
 public function __construct(#[Autowire('%kernel.project_dir%')]string$root){$this->authorizations=$root.'/var/imperium/offices/curia/operational-deployment-authorizations';$this->occupancy=$root.'/var/imperium/offices/garrison/occupancy';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->transitions=$root.'/var/imperium/offices/garrison/operational-custody-transitions';}
 public function transition(string$authorizationId,string$constableBindingId):array
 {
  if(!preg_match('/^operational-deployment-authorization-[a-f0-9]{20}$/',$authorizationId))throw new \InvalidArgumentException('GA201_DEPLOYMENT_AUTHORIZATION_ID_INVALID');$a=$this->read($this->authorizations.'/'.$authorizationId.'.json','GA202_DEPLOYMENT_AUTHORIZATION_ABSENT');$k=$this->read($this->occupancy.'/'.$constableBindingId.'.json','GA203_CONSTABLE_OCCUPANCY_ABSENT');
  foreach(glob($this->transitions.'/operational-custody-transition-*.json')?:[]as$p){$x=$this->read($p,'GA206_OPERATIONAL_CUSTODY_TRANSITION_CONFLICT');if(!$this->ok($x))throw new \RuntimeException('GA206_OPERATIONAL_CUSTODY_TRANSITION_CONFLICT');if(($x['source_deployment_authorization']['id']??null)===$authorizationId){if(($x['source_deployment_authorization']['digest']??null)!==($a['record_digest']??null)||($x['constable']['binding_id']??null)!==$constableBindingId||($x['constable']['binding_id']??null)!==($k['binding_id']??null))throw new \RuntimeException('GA206_OPERATIONAL_CUSTODY_TRANSITION_CONFLICT');return$x;}}
  $custodyId=$a['custody_lease']['custody_id']??null;$c=is_string($custodyId)?$this->read($this->custody.'/'.$custodyId.'.json','GA204_CUSTODY_RECORD_ABSENT'):[];$this->validate($authorizationId,$a,$constableBindingId,$k,$c);
  $actor=['seat'=>'garrison.constable','binding_id'=>$constableBindingId,'manifestation_id'=>$k['manifestation_id'],'occupancy_generation'=>$k['occupancy_generation']];$next=$c;unset($next['record_digest']);$next['custody_state']='DEPLOYED_BOUND';$next['available']=false;$next['operational_custodian']=['office'=>'mission','seat'=>$a['seat'],'manifestation_id'=>$a['manifestation_id']];$next['source_deployment_authorization']=['id'=>$authorizationId,'digest'=>$a['record_digest']];$next['execution_authority']=false;$next['record_digest']=hash('sha256',CanonicalJson::encode($next));$id='operational-custody-transition-'.substr(hash('sha256',CanonicalJson::encode([$authorizationId,$a['record_digest'],$c['record_digest'],$next['record_digest'],$actor])),0,20);
  $record=['schema'=>'imperium.garrison-operational-custody-transition/v1','transition_id'=>$id,'instance_id'=>$a['instance_id'],'case_id'=>$a['case_id'],'case_digest'=>$a['case_digest'],'constable'=>$actor,'source_deployment_authorization'=>['id'=>$authorizationId,'digest'=>$a['record_digest']],'source_binding'=>$a['source_binding'],'seat'=>$a['seat'],'manifestation_id'=>$a['manifestation_id'],'manifestation'=>$a['manifestation'],'persona_identity'=>$a['persona_identity'],'profile_candidate'=>$a['profile_candidate'],'mission_use'=>$a['mission_use'],'prior_custody'=>['id'=>$c['custody_id'],'digest'=>$c['record_digest'],'state'=>$c['custody_state'],'available'=>$c['available']],'operational_custody'=>['id'=>$next['custody_id'],'digest'=>$next['record_digest'],'state'=>$next['custody_state'],'available'=>$next['available'],'custodian'=>$next['operational_custodian']],'status'=>'OPERATIONAL_MANIFESTATION_DEPLOYED_CUSTODY_TRANSITIONED_PENDING_BOUNDED_EXECUTION','deployment_authority_consumed'=>true,'garrison_custody_transition_authority_consumed'=>true,'deployed'=>true,'operational_use_permitted'=>false,'tool_access_authority'=>false,'credentials_authority'=>false,'external_action_authority'=>false,'execution_authority'=>false,'bounded_execution_authorization_pending'=>true,'return_authority'=>false,'retirement_authority'=>false,'unbinding_authority'=>false,'supersession_authority'=>false,'sealed'=>true];$record=$this->save($id,$record);$this->replaceCustody($c,$next);return$record;
 }
 private function validate(string$id,array$a,string$kid,array$k,array$c):void{if(!$this->ok($a)||!$this->ok($k)||!$this->ok($c)||'imperium.curia-operational-deployment-authorization/v1'!==($a['schema']??null)||$id!==($a['authorization_id']??null)||'DEPLOYMENT_AUTHORIZED_PENDING_GARRISON_CUSTODY_TRANSITION'!==($a['status']??null)||true!==($a['deployment_authority']??null)||true!==($a['deployment_authority_exercisable']??null)||true!==($a['garrison_custody_transition_authority']??null)||true!==($a['garrison_custody_transition_authority_exercisable']??null)||true===($a['execution_authority']??null)||'imperium.garrison-constable-occupancy/v1'!==($k['schema']??null)||$kid!==($k['binding_id']??null)||($a['instance_id']??null)!==($k['instance_id']??null)||'garrison.constable'!==($k['seat']??null)||'ACTIVE'!==($k['status']??null)||true!==($k['operational_custody_transition_authority']??null)||true===($k['selection_authority']??null)||true===($k['execution_authority']??null)||'imperium.garrison-persona-custody/v1'!==($c['schema']??null)||($a['custody_lease']['custody_id']??null)!==($c['custody_id']??null)||($a['custody_lease']['custody_digest']??null)!==($c['record_digest']??null)||($a['persona_identity']['persona_id']??null)!==($c['persona_id']??null)||'ADMITTED_HELD'!==($c['custody_state']??null)||true!==($c['available']??null))throw new \RuntimeException('GA205_OPERATIONAL_CUSTODY_TRANSITION_CHAIN_INVALID');}
 private function replaceCustody(array$prior,array$next):void{$p=$this->custody.'/'.$prior['custody_id'].'.json';$current=$this->read($p,'GA204_CUSTODY_RECORD_ABSENT');if(CanonicalJson::encode($current)!==CanonicalJson::encode($prior))throw new \RuntimeException('GA206_OPERATIONAL_CUSTODY_TRANSITION_CONFLICT');$t=$p.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($next,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException('GA207_OPERATIONAL_CUSTODY_TRANSITION_FAILED');}}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
 private function save(string$id,array$r):array{if(!is_dir($this->transitions)&&!mkdir($this->transitions,0770,true)&&!is_dir($this->transitions))throw new \RuntimeException('GA207_OPERATIONAL_CUSTODY_TRANSITION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->transitions.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'GA206_OPERATIONAL_CUSTODY_TRANSITION_CONFLICT');if(CanonicalJson::encode($x)!==CanonicalJson::encode($r))throw new \RuntimeException('GA206_OPERATIONAL_CUSTODY_TRANSITION_CONFLICT');return$x;}$t=$p.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException('GA207_OPERATIONAL_CUSTODY_TRANSITION_FAILED');}return$r;}
}
