<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Garrison;
use App\Bootstrap\CanonicalJson;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class SubordinatePersonaCanonicalAdmissionService
{
    private string$inbox;private string$occupancy;private string$dispositions;private string$custody;
    public function __construct(#[Autowire("%kernel.project_dir%")]string$p){$this->inbox=$p."/var/imperium/offices/garrison/inbox/canonical-subordinate-persona-admissions";$this->occupancy=$p."/var/imperium/offices/garrison/occupancy";$this->dispositions=$p."/var/imperium/offices/garrison/subordinate-persona-admission-dispositions";$this->custody=$p."/var/imperium/offices/garrison/custody";}
    public function admit(string$deliveryId,string$bindingId):array
    {
        if(!preg_match('/^guildhall-garrison-persona-admission-delivery-[a-f0-9]{20}$/',$deliveryId))throw new \InvalidArgumentException("GA86_CANONICAL_ADMISSION_DELIVERY_ID_INVALID");$d=$this->read($this->inbox."/".$deliveryId.".json","GA87_CANONICAL_ADMISSION_CHAIN_INVALID");$c=$this->read($this->occupancy."/".$bindingId.".json","GA87_CANONICAL_ADMISSION_CHAIN_INVALID");
        if(!$this->ok($d)||!$this->ok($c)||"CANONICAL_GUILDHALL_TO_GARRISON"!==($d["route_class"]??null)||"DELIVERED_PENDING_CONSTABLE_ADMISSION_DISPOSITION"!==($d["status"]??null)||"garrison.constable"!==($d["recipient"]["seat"]??null)||"garrison.constable"!==($c["seat"]??null)||($d["instance_id"]??null)!==($c["instance_id"]??null)||"ACTIVE"!==($c["status"]??null)||true!==($c["persona_admission_disposition_authority"]??null)||true!==($c["custody_registration_authority"]??null)||true===($c["selection_authority"]??null)||true===($c["execution_authority"]??null)||true===($d["admission_authority"]??null)||!is_string($d["senate_confirmation_record_id"]??null)||!is_string($d["originating_guildhall_commission_id"]??null))throw new \RuntimeException("GA87_CANONICAL_ADMISSION_CHAIN_INVALID");
        $id="garrison-subordinate-persona-admission-disposition-".substr(hash("sha256",CanonicalJson::encode([$deliveryId,$d["record_digest"],$bindingId,$c["record_digest"],"ADMIT"])),0,20);$custodyId="garrison-persona-custody-".substr(hash("sha256",CanonicalJson::encode([$d["candidate_id"],$d["candidate_digest"],$id])),0,20);
        $custody=$this->saveTo($this->custody,$custodyId,["schema"=>"imperium.garrison-persona-custody/v1","custody_id"=>$custodyId,"instance_id"=>$d["instance_id"],"persona_id"=>$d["candidate_id"],"persona_version"=>(string)$d["persona_specification_version"],"persona_name"=>$d["persona_name"],"persona_digest"=>$d["candidate_digest"],"persona"=>$d["persona"],"originating_guildhall_commission_id"=>$d["originating_guildhall_commission_id"],"originating_guildhall_commission_digest"=>$d["originating_guildhall_commission_digest"],"senate_confirmation_record_id"=>$d["senate_confirmation_record_id"],"senate_confirmation_record_digest"=>$d["senate_confirmation_record_digest"],"admission_disposition_id"=>$id,"custody_state"=>"ADMITTED_HELD","available"=>true,"execution_authority"=>false,"sealed"=>true],"GA88_CUSTODY_REGISTRATION_FAILED","GA89_CUSTODY_CONFLICT");
        return $this->saveTo($this->dispositions,$id,["schema"=>"imperium.garrison-subordinate-persona-admission-disposition/v1","disposition_id"=>$id,"instance_id"=>$d["instance_id"],"source_delivery_id"=>$deliveryId,"source_delivery_digest"=>$d["record_digest"],"candidate_id"=>$d["candidate_id"],"candidate_digest"=>$d["candidate_digest"],"originating_guildhall_commission_id"=>$d["originating_guildhall_commission_id"],"originating_guildhall_commission_digest"=>$d["originating_guildhall_commission_digest"],"senate_confirmation_record_id"=>$d["senate_confirmation_record_id"],"senate_confirmation_record_digest"=>$d["senate_confirmation_record_digest"],"constable"=>["seat"=>$c["seat"],"binding_id"=>$c["binding_id"],"binding_digest"=>$c["record_digest"],"manifestation_id"=>$c["manifestation_id"],"occupancy_generation"=>$c["occupancy_generation"]],"disposition"=>"ADMITTED","custody_created"=>true,"custody_id"=>$custodyId,"custody_digest"=>$custody["record_digest"],"status"=>"ADMITTED_HELD","admission_authority"=>false,"execution_authority"=>false,"sealed"=>true],"GA90_ADMISSION_DISPOSITION_FAILED","GA91_ADMISSION_DISPOSITION_CONFLICT");
    }
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$x=$r["record_digest"]??null;unset($r["record_digest"]);return is_string($x)&&hash_equals($x,hash("sha256",CanonicalJson::encode($r)));}
    private function saveTo(string$dir,string$id,array$r,string$fail,string$conflict):array{if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))throw new \RuntimeException($fail);$r["record_digest"]=hash("sha256",CanonicalJson::encode($r));$p=$dir."/".$id.".json";if(is_file($p)){ $o=$this->read($p,$conflict);if(CanonicalJson::encode($o)!==CanonicalJson::encode($r))throw new \RuntimeException($conflict);return$o;}$t=$p.".tmp.".bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException($fail);}return$r;}
}
