<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Governance;
use App\Bootstrap\CanonicalJson;use App\Imperium\Runtime\Persistence\AtomicTransition;use App\Imperium\Runtime\Persistence\ImmutableRecordStore;use App\Imperium\Runtime\Persistence\RecordReferenceValidator;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class InternalGovernanceInterruptionEnforcementService
{
 private const AUTHORITIES='var/imperium/runtime/continuous-governance-enforcement-authorities',RESULTS='var/imperium/runtime/continuous-governance-enforcement-results',DISPOSITIONS='var/imperium/runtime/continuous-governance-revocation-dispositions',CLAIMS='var/imperium/runtime/governance-cognition-invocation-claims',JOURNAL='var/imperium/runtime/provider-invocation-journal',OCCUPANCY='var/imperium/offices/clavium/occupancy';
 private RecordReferenceValidator $validator;private ImmutableRecordStore $records;private AtomicTransition $atomic;
 public function __construct(#[Autowire('%kernel.project_dir%')]private string$root,?RecordReferenceValidator$v=null,?ImmutableRecordStore$r=null,?AtomicTransition$a=null){$this->validator=$v??new RecordReferenceValidator($root);$this->atomic=$a??new AtomicTransition($root);$this->records=$r??new ImmutableRecordStore($root,$this->atomic);}
 public function enforce(string$authorityId,string$locksmithBindingId,\DateTimeImmutable$consumedAt):array
 {
  if(!preg_match('/^revocation-enforcement-authority-[a-f0-9]{20}$/',$authorityId)||!preg_match('/^clavium-locksmith-binding-[a-f0-9]{20}$/',$locksmithBindingId))throw new \InvalidArgumentException('CAG900_ENFORCEMENT_INPUT_INVALID');
  $a=$this->validator->read($this->root.'/'.self::AUTHORITIES.'/'.$authorityId.'.json','CAG901_ENFORCEMENT_AUTHORITY_ABSENT');$claimId=$a['affected_scope']['claim']['id']??null;if(!is_string($claimId)||!preg_match('/^governance-cognition-invocation-claim-[a-f0-9]{20}$/',$claimId))throw new \RuntimeException('CAG902_ENFORCEMENT_AUTHORITY_INVALID');$journalPath=self::JOURNAL.'/'.$claimId.'.json';
  return $this->atomic->run('mutable:'.hash('sha256',$journalPath),function()use($authorityId,$locksmithBindingId,$consumedAt,$a,$claimId):array{
   $this->assertAuthority($authorityId,$a,$locksmithBindingId,$consumedAt);$d=$this->resolve(self::DISPOSITIONS,$a['source_disposition']??[],'disposition_id','CAG903_SOURCE_DISPOSITION_INVALID');$claim=$this->resolve(self::CLAIMS,$a['affected_scope']['claim']??[],'claim_id','CAG904_SOURCE_CLAIM_INVALID');
   if('imperium.continuous-governance-revocation-disposition/v1'!==($d['schema']??null)||'INTERRUPT'!==($d['disposition']??null)||($d['affected_scope']??null)!==($a['affected_scope']??null)||($d['instance_id']??null)!==($a['instance_id']??null)||'imperium.clavium-governance-cognition-invocation-claim/v1'!==($claim['schema']??null)||($claim['instance_id']??null)!==($a['instance_id']??null)||'GOVERNANCE_INVOCATION_CLAIMED_DURABLE_PRE_IO'!==($claim['status']??null)||false!==($claim['provider_request']['external_io_started']??null)||is_file($this->root.'/'.self::JOURNAL.'/'.$claimId.'.json'))throw new \RuntimeException('CAG905_PROVIDER_ADMISSION_ALREADY_OPENED');
   $enforcer=$this->currentLocksmith($locksmithBindingId,(string)$a['instance_id']);if($enforcer!==($a['enforcer']??null))throw new \RuntimeException('CAG906_LOCKSMITH_ENFORCER_INVALID');$id='revocation-enforcement-result-'.substr(hash('sha256',CanonicalJson::encode([$authorityId,$a['record_digest'],$enforcer])),0,20);
   foreach(glob($this->root.'/'.self::RESULTS.'/*.json')?:[]as$p){$prior=$this->validator->read($p,'CAG907_ENFORCEMENT_RESULT_CONFLICT');if(($prior['source_authority']['id']??null)!==$authorityId)continue;if(!$this->validator->isIntact($prior)||($prior['source_authority']['digest']??null)!==$a['record_digest']||($prior['enforcer']??null)!==$enforcer)throw new \RuntimeException('CAG907_ENFORCEMENT_RESULT_CONFLICT');return$prior;}
   return $this->records->put(self::RESULTS,$id,['schema'=>'imperium.continuous-governance-enforcement-result/v1','result_id'=>$id,'instance_id'=>$a['instance_id'],'source_authority'=>['id'=>$authorityId,'digest'=>$a['record_digest']],'source_disposition'=>$a['source_disposition'],'enforcer'=>$enforcer,'affected_scope'=>$a['affected_scope'],'performed_transition'=>'DENY_PROVIDER_INVOCATION_JOURNAL_START_FOR_EXACT_CLAIM','consumed_at'=>$consumedAt->format(DATE_ATOM),'authority_consumed'=>true,'journal_created'=>false,'external_io_started'=>false,'claim_mutated'=>false,'lease_mutated'=>false,'credential_mutated'=>false,'propagation_performed'=>false,'continuation_authority'=>false,'sealed'=>true]);
  });
 }
 private function assertAuthority(string$id,array$a,string$binding,\DateTimeImmutable$at):void{if(!$this->validator->isIntact($a)||'imperium.continuous-governance-enforcement-authority/v1'!==($a['schema']??null)||$id!==($a['authority_id']??null)||$binding!==($a['enforcer']['binding_id']??null)||'clavium.locksmith'!==($a['enforcer']['seat']??null)||'INTERNAL_GOVERNANCE_COGNITION_INVOCATION'!==($a['affected_scope']['kind']??null)||'DENY_PROVIDER_INVOCATION_JOURNAL_START_FOR_EXACT_CLAIM'!==($a['permitted_transition']??null)||true!==($a['single_use']??null)||true!==($a['exercisable']??null)||false!==($a['consumed']??null)||false!==($a['continuing_authority']??null)||false!==($a['external_action_authority']??null)||false!==($a['perimeter_authority']??null)||true!==($a['sealed']??null)||new \DateTimeImmutable((string)($a['issued_at']??'2999-01-01'))>$at||new \DateTimeImmutable((string)($a['expires_at']??'1970-01-01'))<=$at)throw new \RuntimeException('CAG902_ENFORCEMENT_AUTHORITY_INVALID');}
 private function resolve(string$dir,array$ref,string$key,string$error):array{$id=$ref['id']??null;if(!is_string($id))throw new \RuntimeException($error);$r=$this->validator->read($this->root.'/'.$dir.'/'.$id.'.json',$error);if(!$this->validator->isIntact($r)||$id!==($r[$key]??null)||($ref['digest']??null)!==($r['record_digest']??null))throw new \RuntimeException($error);return$r;}
 private function currentLocksmith(string$id,string$instance):array{$o=$this->validator->read($this->root.'/'.self::OCCUPANCY.'/'.$id.'.json','CAG906_LOCKSMITH_ENFORCER_INVALID');if(!$this->validator->isIntact($o)||'imperium.clavium-locksmith-occupancy/v1'!==($o['schema']??null)||$id!==($o['binding_id']??null)||$instance!==($o['instance_id']??null)||'clavium.locksmith'!==($o['seat']??null)||'ACTIVE'!==($o['status']??null))throw new \RuntimeException('CAG906_LOCKSMITH_ENFORCER_INVALID');foreach(glob($this->root.'/'.self::OCCUPANCY.'/*.json')?:[]as$p){$x=$this->validator->read($p,'CAG906_LOCKSMITH_ENFORCER_INVALID');if('clavium.locksmith'===($x['seat']??null)&&'ACTIVE'===($x['status']??null)&&$instance===($x['instance_id']??null)&&$id!==($x['binding_id']??null))throw new \RuntimeException('CAG906_LOCKSMITH_ENFORCER_INVALID');}return['seat'=>'clavium.locksmith','binding_id'=>$id,'binding_digest'=>$o['record_digest'],'manifestation_id'=>$o['manifestation_id'],'occupancy_generation'=>$o['occupancy_generation']];}
}
