<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Governance;
use App\Bootstrap\CanonicalJson;use App\Imperium\Runtime\Persistence\AtomicTransition;use App\Imperium\Runtime\Persistence\ImmutableRecordStore;use App\Imperium\Runtime\Persistence\RecordReferenceValidator;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class InternalGovernanceLeaseInterruptionDispositionService
{
 private const LEASES='var/imperium/offices/clavium/governance-cognition-leases',CLAIMS='var/imperium/runtime/governance-cognition-invocation-claims',OCCUPANCY='var/imperium/operational/occupancy',DISPOSITIONS='var/imperium/runtime/continuous-governance-revocation-dispositions';private RecordReferenceValidator $validator;private ImmutableRecordStore $records;private AtomicTransition $atomic;
 public function __construct(#[Autowire('%kernel.project_dir%')]private string$root,?RecordReferenceValidator$v=null,?ImmutableRecordStore$r=null,?AtomicTransition$a=null){$this->validator=$v??new RecordReferenceValidator($root);$this->atomic=$a??new AtomicTransition($root);$this->records=$r??new ImmutableRecordStore($root,$this->atomic);}
 public function interrupt(string$leaseId,string$seneschalBindingId,string$reason,\DateTimeImmutable$effectiveAt):array
 {
  $reason=trim($reason);if(!preg_match('/^governance-cognition-lease-[a-f0-9]{20}$/',$leaseId)||!preg_match('/^operational-seat-binding-[a-f0-9]{20}$/',$seneschalBindingId)||''===$reason)throw new \InvalidArgumentException('CAG1200_LEASE_INTERRUPTION_INPUT_INVALID');
  return $this->atomic->run('gca-lease:'.hash('sha256',$leaseId),function()use($leaseId,$seneschalBindingId,$reason,$effectiveAt):array{
   $lease=$this->validator->read($this->root.'/'.self::LEASES.'/'.$leaseId.'.json','CAG1201_GOVERNANCE_LEASE_ABSENT');$this->assertUnclaimedLease($leaseId,$lease,$effectiveAt);$seneschal=$this->validator->read($this->root.'/'.self::OCCUPANCY.'/'.$seneschalBindingId.'.json','CAG1202_SENESCHAL_OCCUPANCY_ABSENT');$actor=$this->currentSeneschal($seneschalBindingId,$seneschal,(string)($lease['instance_id']??''));$id='revocation-disposition-'.substr(hash('sha256',CanonicalJson::encode([$leaseId,$lease['record_digest'],$actor,$reason])),0,20);
   foreach(glob($this->root.'/'.self::DISPOSITIONS.'/*.json')?:[]as$p){$prior=$this->validator->read($p,'CAG1206_LEASE_INTERRUPTION_DISPOSITION_CONFLICT');if(($prior['affected_scope']['lease']['id']??null)!==$leaseId)continue;if(!$this->validator->isIntact($prior)||($prior['affected_scope']['lease']['digest']??null)!==$lease['record_digest']||($prior['competent_actor']??null)!==$actor||($prior['reason']??null)!==$reason)throw new \RuntimeException('CAG1206_LEASE_INTERRUPTION_DISPOSITION_CONFLICT');return$prior;}
   return $this->records->put(self::DISPOSITIONS,$id,['schema'=>'imperium.continuous-governance-revocation-disposition/v1','disposition_id'=>$id,'instance_id'=>$lease['instance_id'],'disposition'=>'INTERRUPT','competent_actor'=>$actor,'authority_basis'=>['contract'=>'imperium.continuous-governance-revocation-authority-design/v1','jurisdiction'=>'SENESCHAL_ACTIVE_INTERNAL_MISSION_ITERATION','source_occupancy'=>['id'=>$seneschalBindingId,'digest'=>$seneschal['record_digest']]],'affected_scope'=>['kind'=>'UNCLAIMED_INTERNAL_GOVERNANCE_COGNITION_LEASE','lease'=>['id'=>$leaseId,'digest'=>$lease['record_digest']],'case_id'=>$lease['case_id'],'cluster'=>$lease['cluster'],'target'=>$lease['target'],'lease_consumed'=>false],'reason'=>$reason,'effective_at'=>$effectiveAt->format(DATE_ATOM),'prior_references'=>[['id'=>$leaseId,'digest'=>$lease['record_digest']]],'enforcement_required'=>true,'enforcement_authority_opened'=>false,'state_mutated'=>false,'authority_granted'=>false,'continuation_authority'=>false,'sealed'=>true]);
  });
 }
 private function assertUnclaimedLease(string$id,array$l,\DateTimeImmutable$at):void
 {if(!$this->validator->isIntact($l)||'imperium.clavium-governance-cognition-lease/v1'!==($l['schema']??null)||$id!==($l['lease_id']??null)||'GOVERNANCE_COGNITION_LEASE_ISSUED_PENDING_DURABLE_INVOCATION_CLAIM'!==($l['status']??null)||true!==($l['opaque']??null)||true!==($l['lease_single_use']??null)||false!==($l['lease_consumed']??null)||new \DateTimeImmutable((string)($l['issued_at']??'2999-01-01'))>$at||new \DateTimeImmutable((string)($l['expires_at']??'1970-01-01'))<=$at||true!==($l['sealed']??null))throw new \RuntimeException('CAG1203_GOVERNANCE_LEASE_NOT_INTERRUPTIBLE_UNCLAIMED');foreach(glob($this->root.'/'.self::CLAIMS.'/*.json')?:[]as$p){$c=$this->validator->read($p,'CAG1204_GOVERNANCE_CLAIM_UNREADABLE');if(($c['lease_consumption']['lease_id']??null)===$id)throw new \RuntimeException('CAG1203_GOVERNANCE_LEASE_NOT_INTERRUPTIBLE_UNCLAIMED');}}
 private function currentSeneschal(string$id,array$o,string$instance):array
 {if(!$this->validator->isIntact($o)||$id!==($o['binding_id']??null)||$instance!==($o['instance_id']??null)||'curia.seneschal'!==($o['seat']??null)||'ACTIVE'!==($o['status']??null)||true!==($o['sealed']??null)||!is_string($o['manifestation_id']??null)||!is_int($o['occupancy_generation']??null))throw new \RuntimeException('CAG1205_SENESCHAL_NOT_COMPETENT_CURRENT_OCCUPANT');foreach(glob($this->root.'/'.self::OCCUPANCY.'/*.json')?:[]as$p){$x=$this->validator->read($p,'CAG1205_SENESCHAL_NOT_COMPETENT_CURRENT_OCCUPANT');if('curia.seneschal'===($x['seat']??null)&&'ACTIVE'===($x['status']??null)&&$instance===($x['instance_id']??null)&&$id!==($x['binding_id']??null))throw new \RuntimeException('CAG1205_SENESCHAL_NOT_COMPETENT_CURRENT_OCCUPANT');}return['seat'=>'curia.seneschal','binding_id'=>$id,'binding_digest'=>$o['record_digest'],'manifestation_id'=>$o['manifestation_id'],'occupancy_generation'=>$o['occupancy_generation']];}
}
