<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Governance;
use App\Bootstrap\CanonicalJson;use App\Imperium\Runtime\Persistence\AtomicTransition;use App\Imperium\Runtime\Persistence\ImmutableRecordStore;use App\Imperium\Runtime\Persistence\RecordReferenceValidator;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class InternalGovernanceLeaseInterruptionEnforcementAuthorityService
{
 private const DISPOSITIONS='var/imperium/runtime/continuous-governance-revocation-dispositions',AUTHORITIES='var/imperium/runtime/continuous-governance-enforcement-authorities',LEASES='var/imperium/offices/clavium/governance-cognition-leases',CLAIMS='var/imperium/runtime/governance-cognition-invocation-claims',CURIA='var/imperium/operational/occupancy',CLAVIUM='var/imperium/offices/clavium/occupancy';private RecordReferenceValidator $validator;private ImmutableRecordStore $records;private AtomicTransition $atomic;
 public function __construct(#[Autowire('%kernel.project_dir%')]private string$root,?RecordReferenceValidator$v=null,?ImmutableRecordStore$r=null,?AtomicTransition$a=null){$this->validator=$v??new RecordReferenceValidator($root);$this->atomic=$a??new AtomicTransition($root);$this->records=$r??new ImmutableRecordStore($root,$this->atomic);}
 public function issue(string$dispositionId,string$locksmithBindingId,\DateTimeImmutable$issuedAt,\DateTimeImmutable$expiresAt):array
 {
  if(!preg_match('/^revocation-disposition-[a-f0-9]{20}$/',$dispositionId)||!preg_match('/^clavium-locksmith-binding-[a-f0-9]{20}$/',$locksmithBindingId)||$expiresAt<=$issuedAt||$expiresAt>$issuedAt->modify('+5 minutes'))throw new \InvalidArgumentException('CAG1300_LEASE_ENFORCEMENT_AUTHORITY_INPUT_INVALID');$d=$this->validator->read($this->root.'/'.self::DISPOSITIONS.'/'.$dispositionId.'.json','CAG1301_LEASE_INTERRUPTION_DISPOSITION_ABSENT');$leaseId=$d['affected_scope']['lease']['id']??null;if(!is_string($leaseId)||!preg_match('/^governance-cognition-lease-[a-f0-9]{20}$/',$leaseId))throw new \RuntimeException('CAG1302_LEASE_INTERRUPTION_DISPOSITION_INVALID');
  return $this->atomic->run('gca-lease:'.hash('sha256',$leaseId),function()use($dispositionId,$d,$leaseId,$locksmithBindingId,$issuedAt,$expiresAt):array{
   $this->assertDisposition($dispositionId,$d,$leaseId,$issuedAt);$lease=$this->validator->read($this->root.'/'.self::LEASES.'/'.$leaseId.'.json','CAG1303_GOVERNANCE_LEASE_ABSENT');$this->assertUnclaimedLease($d,$leaseId,$lease,$issuedAt,$expiresAt);$issuer=$this->currentActor(self::CURIA,'curia.seneschal',(string)($d['competent_actor']['binding_id']??''),(string)$d['instance_id'],'CAG1305_SENESCHAL_ISSUER_NOT_CURRENT');if($issuer!==($d['competent_actor']??null))throw new \RuntimeException('CAG1305_SENESCHAL_ISSUER_NOT_CURRENT');$enforcer=$this->currentActor(self::CLAVIUM,'clavium.locksmith',$locksmithBindingId,(string)$d['instance_id'],'CAG1306_LOCKSMITH_ENFORCER_NOT_CURRENT','imperium.clavium-locksmith-occupancy/v1');
   foreach(glob($this->root.'/'.self::AUTHORITIES.'/*.json')?:[]as$p){$prior=$this->validator->read($p,'CAG1307_LEASE_ENFORCEMENT_AUTHORITY_CONFLICT');if(($prior['source_disposition']['id']??null)!==$dispositionId)continue;if(!$this->validator->isIntact($prior)||($prior['source_disposition']['digest']??null)!==$d['record_digest']||($prior['issuer']??null)!==$issuer||($prior['enforcer']??null)!==$enforcer||'DENY_DURABLE_GOVERNANCE_INVOCATION_CLAIM_FOR_EXACT_LEASE'!==($prior['permitted_transition']??null))throw new \RuntimeException('CAG1307_LEASE_ENFORCEMENT_AUTHORITY_CONFLICT');return$prior;}
   $id='revocation-enforcement-authority-'.substr(hash('sha256',CanonicalJson::encode([$dispositionId,$d['record_digest'],$issuer,$enforcer])),0,20);return$this->records->put(self::AUTHORITIES,$id,['schema'=>'imperium.continuous-governance-enforcement-authority/v1','authority_id'=>$id,'instance_id'=>$d['instance_id'],'source_disposition'=>['id'=>$dispositionId,'digest'=>$d['record_digest']],'issuer'=>$issuer,'enforcer'=>$enforcer,'affected_scope'=>$d['affected_scope'],'permitted_transition'=>'DENY_DURABLE_GOVERNANCE_INVOCATION_CLAIM_FOR_EXACT_LEASE','issued_at'=>$issuedAt->format(DATE_ATOM),'expires_at'=>$expiresAt->format(DATE_ATOM),'single_use'=>true,'exercisable'=>true,'consumed'=>false,'continuing_authority'=>false,'external_action_authority'=>false,'perimeter_authority'=>false,'sealed'=>true]);
  });
 }
 private function assertDisposition(string$id,array$d,string$leaseId,\DateTimeImmutable$at):void{if(!$this->validator->isIntact($d)||'imperium.continuous-governance-revocation-disposition/v1'!==($d['schema']??null)||$id!==($d['disposition_id']??null)||'INTERRUPT'!==($d['disposition']??null)||'UNCLAIMED_INTERNAL_GOVERNANCE_COGNITION_LEASE'!==($d['affected_scope']['kind']??null)||false!==($d['affected_scope']['lease_consumed']??null)||$leaseId!==($d['prior_references'][0]['id']??null)||($d['affected_scope']['lease']['digest']??null)!==($d['prior_references'][0]['digest']??null)||true!==($d['enforcement_required']??null)||false!==($d['enforcement_authority_opened']??null)||false!==($d['state_mutated']??null)||false!==($d['authority_granted']??null)||false!==($d['continuation_authority']??null)||true!==($d['sealed']??null)||new \DateTimeImmutable((string)($d['effective_at']??'2999-01-01'))>$at)throw new \RuntimeException('CAG1302_LEASE_INTERRUPTION_DISPOSITION_INVALID');}
 private function assertUnclaimedLease(array$d,string$id,array$l,\DateTimeImmutable$issued,\DateTimeImmutable$expires):void{if(!$this->validator->isIntact($l)||'imperium.clavium-governance-cognition-lease/v1'!==($l['schema']??null)||$id!==($l['lease_id']??null)||($d['affected_scope']['lease']['digest']??null)!==($l['record_digest']??null)||($d['instance_id']??null)!==($l['instance_id']??null)||'GOVERNANCE_COGNITION_LEASE_ISSUED_PENDING_DURABLE_INVOCATION_CLAIM'!==($l['status']??null)||true!==($l['lease_single_use']??null)||false!==($l['lease_consumed']??null)||new \DateTimeImmutable((string)($l['expires_at']??'1970-01-01'))<=$issued||$expires>new \DateTimeImmutable((string)$l['expires_at'])||true!==($l['sealed']??null))throw new \RuntimeException('CAG1304_GOVERNANCE_LEASE_NO_LONGER_ENFORCEABLE_UNCLAIMED');foreach(glob($this->root.'/'.self::CLAIMS.'/*.json')?:[]as$p){$c=$this->validator->read($p,'CAG1304_GOVERNANCE_LEASE_NO_LONGER_ENFORCEABLE_UNCLAIMED');if(($c['lease_consumption']['lease_id']??null)===$id)throw new \RuntimeException('CAG1304_GOVERNANCE_LEASE_NO_LONGER_ENFORCEABLE_UNCLAIMED');}}
 private function currentActor(string$dir,string$seat,string$id,string$instance,string$error,?string$schema=null):array{$o=$this->validator->read($this->root.'/'.$dir.'/'.$id.'.json',$error);if(!$this->validator->isIntact($o)||(null!==$schema&&$schema!==($o['schema']??null))||$id!==($o['binding_id']??null)||$instance!==($o['instance_id']??null)||$seat!==($o['seat']??null)||'ACTIVE'!==($o['status']??null)||!is_string($o['manifestation_id']??null)||!is_int($o['occupancy_generation']??null))throw new \RuntimeException($error);foreach(glob($this->root.'/'.$dir.'/*.json')?:[]as$p){$x=$this->validator->read($p,$error);if($seat===($x['seat']??null)&&'ACTIVE'===($x['status']??null)&&$instance===($x['instance_id']??null)&&$id!==($x['binding_id']??null))throw new \RuntimeException($error);}return['seat'=>$seat,'binding_id'=>$id,'binding_digest'=>$o['record_digest'],'manifestation_id'=>$o['manifestation_id'],'occupancy_generation'=>$o['occupancy_generation']];}
}
