<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Governance;
use App\Imperium\Runtime\Persistence\RecordReferenceValidator;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class InternalGovernanceInterruptionReconstructionService
{
 private const CLAIMS='var/imperium/runtime/governance-cognition-invocation-claims',DISPOSITIONS='var/imperium/runtime/continuous-governance-revocation-dispositions',AUTHORITIES='var/imperium/runtime/continuous-governance-enforcement-authorities',RESULTS='var/imperium/runtime/continuous-governance-enforcement-results',JOURNAL='var/imperium/runtime/provider-invocation-journal';private RecordReferenceValidator $validator;
 public function __construct(#[Autowire('%kernel.project_dir%')]private string$root,?RecordReferenceValidator$v=null){$this->validator=$v??new RecordReferenceValidator($root);}
 public function reconstruct(string$claimId):array
 {
  if(!preg_match('/^governance-cognition-invocation-claim-[a-f0-9]{20}$/',$claimId))throw new \InvalidArgumentException('CAG1000_INTERRUPTION_RECONSTRUCTION_CLAIM_INVALID');$claim=$this->record(self::CLAIMS,$claimId,'claim_id');$matches=[];
  foreach(glob($this->root.'/'.self::RESULTS.'/*.json')?:[]as$p){$r=$this->validator->requireIntact($this->validator->read($p,'CAG1001_INTERRUPTION_RECONSTRUCTION_INVALID'),'CAG1001_INTERRUPTION_RECONSTRUCTION_INVALID');if(($r['affected_scope']['claim']['id']??null)===$claimId)$matches[]=$r;}
  if(1!==count($matches))throw new \RuntimeException('CAG1001_INTERRUPTION_RECONSTRUCTION_INVALID');$result=$matches[0];$authority=$this->source(self::AUTHORITIES,$result['source_authority']??[],'authority_id');$disposition=$this->source(self::DISPOSITIONS,$authority['source_disposition']??[],'disposition_id');$scope=$disposition['affected_scope']??null;
  if('imperium.clavium-governance-cognition-invocation-claim/v1'!==($claim['schema']??null)||'GOVERNANCE_INVOCATION_CLAIMED_DURABLE_PRE_IO'!==($claim['status']??null)||false!==($claim['provider_request']['external_io_started']??null)||true!==($claim['sealed']??null)||'imperium.continuous-governance-revocation-disposition/v1'!==($disposition['schema']??null)||'INTERRUPT'!==($disposition['disposition']??null)||true!==($disposition['enforcement_required']??null)||false!==($disposition['enforcement_authority_opened']??null)||false!==($disposition['state_mutated']??null)||false!==($disposition['authority_granted']??null)||false!==($disposition['continuation_authority']??null)||true!==($disposition['sealed']??null)||'imperium.continuous-governance-enforcement-authority/v1'!==($authority['schema']??null)||($authority['source_disposition']??null)!==['id'=>$disposition['disposition_id'],'digest'=>$disposition['record_digest']]||($authority['issuer']??null)!==($disposition['competent_actor']??null)||true!==($authority['single_use']??null)||true!==($authority['exercisable']??null)||false!==($authority['consumed']??null)||false!==($authority['continuing_authority']??null)||false!==($authority['external_action_authority']??null)||false!==($authority['perimeter_authority']??null)||true!==($authority['sealed']??null)||'imperium.continuous-governance-enforcement-result/v1'!==($result['schema']??null)||($result['source_disposition']??null)!==($authority['source_disposition']??null)||($result['enforcer']??null)!==($authority['enforcer']??null)||true!==($result['authority_consumed']??null)||false!==($result['journal_created']??null)||false!==($result['external_io_started']??null)||false!==($result['claim_mutated']??null)||false!==($result['lease_mutated']??null)||false!==($result['credential_mutated']??null)||false!==($result['propagation_performed']??null)||false!==($result['continuation_authority']??null)||true!==($result['sealed']??null)||'DENY_PROVIDER_INVOCATION_JOURNAL_START_FOR_EXACT_CLAIM'!==($authority['permitted_transition']??null)||($authority['permitted_transition']??null)!==($result['performed_transition']??null)||$scope!==($authority['affected_scope']??null)||$scope!==($result['affected_scope']??null)||($scope['claim']??null)!==['id'=>$claimId,'digest'=>$claim['record_digest']]||($claim['instance_id']??null)!==($disposition['instance_id']??null)||($claim['instance_id']??null)!==($authority['instance_id']??null)||($claim['instance_id']??null)!==($result['instance_id']??null)||is_file($this->root.'/'.self::JOURNAL.'/'.$claimId.'.json'))throw new \RuntimeException('CAG1001_INTERRUPTION_RECONSTRUCTION_INVALID');
  return['schema'=>'imperium.continuous-governance-interruption-reconstruction/v1','status'=>'INTERNAL_GOVERNANCE_PRE_IO_INTERRUPTION_RECONSTRUCTED','completeness_claim'=>'FOUR_ARTIFACT_PRE_IO_INTERRUPTION_SUBCHAIN_ONLY','root_claim'=>['id'=>$claimId,'digest'=>$claim['record_digest']],'instance_id'=>$claim['instance_id'],'included_evidence'=>['invocation_claim'=>$claim,'revocation_disposition'=>$disposition,'enforcement_authority'=>$authority,'enforcement_result'=>$result],'verified_artifact_count'=>4,'provider_journal_absent'=>true,'provider_response_absent_by_design'=>true,'read_only'=>true,'provider_reinvoked'=>false,'state_mutated'=>false,'propagation_performed'=>false,'authority_granted'=>false,'continuation_authority'=>false];
 }
 private function source(string$dir,array$ref,string$key):array{return$this->validator->resolve($this->root.'/'.$dir,$ref,'CAG1001_INTERRUPTION_RECONSTRUCTION_INVALID','CAG1001_INTERRUPTION_RECONSTRUCTION_INVALID',$key);}private function record(string$dir,string$id,string$key):array{$r=$this->validator->requireIntact($this->validator->read($this->root.'/'.$dir.'/'.$id.'.json','CAG1001_INTERRUPTION_RECONSTRUCTION_INVALID'),'CAG1001_INTERRUPTION_RECONSTRUCTION_INVALID');if($id!==($r[$key]??null))throw new \RuntimeException('CAG1001_INTERRUPTION_RECONSTRUCTION_INVALID');return$r;}
}
