<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Governance;
use App\Bootstrap\CanonicalJson;use App\Imperium\Runtime\Persistence\AtomicTransition;use App\Imperium\Runtime\Persistence\ImmutableRecordStore;use App\Imperium\Runtime\Persistence\RecordReferenceValidator;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class InternalGovernanceInterruptionEnforcementAuthorityService
{
 private const DISPOSITIONS='var/imperium/runtime/continuous-governance-revocation-dispositions',AUTHORITIES='var/imperium/runtime/continuous-governance-enforcement-authorities',CLAIMS='var/imperium/runtime/governance-cognition-invocation-claims',JOURNAL='var/imperium/runtime/provider-invocation-journal',CURIA='var/imperium/operational/occupancy',CLAVIUM='var/imperium/offices/clavium/occupancy';
 private RecordReferenceValidator $validator;private ImmutableRecordStore $records;private AtomicTransition $atomic;
 public function __construct(#[Autowire('%kernel.project_dir%')]private string$root,?RecordReferenceValidator$v=null,?ImmutableRecordStore$r=null,?AtomicTransition$a=null){$this->validator=$v??new RecordReferenceValidator($root);$this->atomic=$a??new AtomicTransition($root);$this->records=$r??new ImmutableRecordStore($root,$this->atomic);}
 public function issue(string$dispositionId,string$locksmithBindingId,\DateTimeImmutable$issuedAt,\DateTimeImmutable$expiresAt):array
 {
  if(!preg_match('/^revocation-disposition-[a-f0-9]{20}$/',$dispositionId)||!preg_match('/^clavium-locksmith-binding-[a-f0-9]{20}$/',$locksmithBindingId)||$expiresAt<=$issuedAt||$expiresAt>$issuedAt->modify('+5 minutes'))throw new \InvalidArgumentException('CAG800_ENFORCEMENT_AUTHORITY_INPUT_INVALID');
  $d=$this->validator->read($this->root.'/'.self::DISPOSITIONS.'/'.$dispositionId.'.json','CAG801_INTERRUPTION_DISPOSITION_ABSENT');$claimId=$d['affected_scope']['claim']['id']??null;if(!is_string($claimId)||!preg_match('/^governance-cognition-invocation-claim-[a-f0-9]{20}$/',$claimId))throw new \RuntimeException('CAG802_INTERRUPTION_DISPOSITION_INVALID');
  $journalPath=self::JOURNAL.'/'.$claimId.'.json';return $this->atomic->run('mutable:'.hash('sha256',$journalPath),function()use($dispositionId,$d,$claimId,$locksmithBindingId,$issuedAt,$expiresAt):array{
   $this->assertDisposition($dispositionId,$d,$claimId,$issuedAt);$claim=$this->validator->read($this->root.'/'.self::CLAIMS.'/'.$claimId.'.json','CAG803_GOVERNANCE_CLAIM_ABSENT');$this->assertUnstartedClaim($d,$claimId,$claim);$issuer=$this->currentIssuer($d);$enforcer=$this->currentLocksmith($locksmithBindingId,(string)$d['instance_id']);
   foreach(glob($this->root.'/'.self::AUTHORITIES.'/*.json')?:[]as$p){$prior=$this->validator->read($p,'CAG807_ENFORCEMENT_AUTHORITY_CONFLICT');if(($prior['source_disposition']['id']??null)!==$dispositionId)continue;if(!$this->validator->isIntact($prior)||($prior['source_disposition']['digest']??null)!==$d['record_digest']||($prior['issuer']??null)!==$issuer||($prior['enforcer']??null)!==$enforcer||'DENY_PROVIDER_INVOCATION_JOURNAL_START_FOR_EXACT_CLAIM'!==($prior['permitted_transition']??null))throw new \RuntimeException('CAG807_ENFORCEMENT_AUTHORITY_CONFLICT');return$prior;}
   $id='revocation-enforcement-authority-'.substr(hash('sha256',CanonicalJson::encode([$dispositionId,$d['record_digest'],$issuer,$enforcer])),0,20);
   return $this->records->put(self::AUTHORITIES,$id,['schema'=>'imperium.continuous-governance-enforcement-authority/v1','authority_id'=>$id,'instance_id'=>$d['instance_id'],'source_disposition'=>['id'=>$dispositionId,'digest'=>$d['record_digest']],'issuer'=>$issuer,'enforcer'=>$enforcer,'affected_scope'=>$d['affected_scope'],'permitted_transition'=>'DENY_PROVIDER_INVOCATION_JOURNAL_START_FOR_EXACT_CLAIM','issued_at'=>$issuedAt->format(DATE_ATOM),'expires_at'=>$expiresAt->format(DATE_ATOM),'single_use'=>true,'exercisable'=>true,'consumed'=>false,'continuing_authority'=>false,'external_action_authority'=>false,'perimeter_authority'=>false,'sealed'=>true]);
  });
 }
 private function assertDisposition(string$id,array$d,string$claimId,\DateTimeImmutable$at):void
 {if(!$this->validator->isIntact($d)||'imperium.continuous-governance-revocation-disposition/v1'!==($d['schema']??null)||$id!==($d['disposition_id']??null)||'INTERRUPT'!==($d['disposition']??null)||true!==($d['enforcement_required']??null)||false!==($d['enforcement_authority_opened']??null)||false!==($d['state_mutated']??null)||false!==($d['authority_granted']??null)||false!==($d['continuation_authority']??null)||true!==($d['sealed']??null)||'INTERNAL_GOVERNANCE_COGNITION_INVOCATION'!==($d['affected_scope']['kind']??null)||true===($d['affected_scope']['external_io_started']??null)||new \DateTimeImmutable((string)($d['effective_at']??'1970-01-01'))>$at||$claimId!==($d['prior_references'][0]['id']??null)||($d['affected_scope']['claim']['digest']??null)!==($d['prior_references'][0]['digest']??null))throw new \RuntimeException('CAG802_INTERRUPTION_DISPOSITION_INVALID');}
 private function assertUnstartedClaim(array$d,string$id,array$c):void
 {if(!$this->validator->isIntact($c)||'imperium.clavium-governance-cognition-invocation-claim/v1'!==($c['schema']??null)||($d['affected_scope']['claim']['digest']??null)!==($c['record_digest']??null)||$id!==($c['claim_id']??null)||($d['instance_id']??null)!==($c['instance_id']??null)||'GOVERNANCE_INVOCATION_CLAIMED_DURABLE_PRE_IO'!==($c['status']??null)||false!==($c['provider_request']['external_io_started']??null)||is_file($this->root.'/'.self::JOURNAL.'/'.$id.'.json'))throw new \RuntimeException('CAG804_GOVERNANCE_CLAIM_NO_LONGER_ENFORCEABLE_PRE_IO');}
 private function currentIssuer(array$d):array
 {$actor=$d['competent_actor']??[];$id=$actor['binding_id']??null;if(!is_string($id))throw new \RuntimeException('CAG805_SENESCHAL_ISSUER_NOT_CURRENT');$o=$this->validator->read($this->root.'/'.self::CURIA.'/'.$id.'.json','CAG805_SENESCHAL_ISSUER_NOT_CURRENT');$expected=['seat'=>'curia.seneschal','binding_id'=>$id,'binding_digest'=>$o['record_digest']??null,'manifestation_id'=>$o['manifestation_id']??null,'occupancy_generation'=>$o['occupancy_generation']??null];if(!$this->validator->isIntact($o)||$actor!==$expected||($d['instance_id']??null)!==($o['instance_id']??null)||'ACTIVE'!==($o['status']??null))throw new \RuntimeException('CAG805_SENESCHAL_ISSUER_NOT_CURRENT');$this->sole(self::CURIA,'curia.seneschal',$id,(string)$d['instance_id'],'CAG805_SENESCHAL_ISSUER_NOT_CURRENT');return$expected;}
 private function currentLocksmith(string$id,string$instance):array
 {$o=$this->validator->read($this->root.'/'.self::CLAVIUM.'/'.$id.'.json','CAG806_LOCKSMITH_ENFORCER_NOT_CURRENT');if(!$this->validator->isIntact($o)||'imperium.clavium-locksmith-occupancy/v1'!==($o['schema']??null)||$id!==($o['binding_id']??null)||$instance!==($o['instance_id']??null)||'clavium.locksmith'!==($o['seat']??null)||'ACTIVE'!==($o['status']??null))throw new \RuntimeException('CAG806_LOCKSMITH_ENFORCER_NOT_CURRENT');$this->sole(self::CLAVIUM,'clavium.locksmith',$id,$instance,'CAG806_LOCKSMITH_ENFORCER_NOT_CURRENT');return['seat'=>'clavium.locksmith','binding_id'=>$id,'binding_digest'=>$o['record_digest'],'manifestation_id'=>$o['manifestation_id'],'occupancy_generation'=>$o['occupancy_generation']];}
 private function sole(string$dir,string$seat,string$id,string$instance,string$error):void{foreach(glob($this->root.'/'.$dir.'/*.json')?:[]as$p){$o=$this->validator->read($p,$error);if($seat===($o['seat']??null)&&'ACTIVE'===($o['status']??null)&&$instance===($o['instance_id']??null)&&$id!==($o['binding_id']??null))throw new \RuntimeException($error);}}
}
