<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Curia;
use App\Bootstrap\CanonicalJson;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class BoundedExecutionAuthorizationService
{
 private string$transitions;private string$occupancy;private string$custody;private string$authorizations;
 public function __construct(#[Autowire('%kernel.project_dir%')]string$root){$this->transitions=$root.'/var/imperium/offices/garrison/operational-custody-transitions';$this->occupancy=$root.'/var/imperium/offices/curia/occupancy';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->authorizations=$root.'/var/imperium/offices/curia/bounded-execution-authorizations';}
 public function authorize(string$transitionId,string$seneschalBindingId,array$input):array
 {
  if(!preg_match('/^operational-custody-transition-[a-f0-9]{20}$/',$transitionId))throw new \InvalidArgumentException('C209_OPERATIONAL_CUSTODY_TRANSITION_ID_INVALID');if(array_keys($input)!==['target_url']||!is_string($input['target_url'])||1!==preg_match('#^https://[^\s]+$#',$input['target_url']))throw new \InvalidArgumentException('C210_BOUNDED_EXECUTION_INPUT_INVALID');$t=$this->read($this->transitions.'/'.$transitionId.'.json','C211_OPERATIONAL_CUSTODY_TRANSITION_ABSENT');$s=$this->read($this->occupancy.'/'.$seneschalBindingId.'.json','C212_SENESCHAL_OCCUPANCY_ABSENT');$custodyId=$t['operational_custody']['id']??null;$c=is_string($custodyId)?$this->read($this->custody.'/'.$custodyId.'.json','C213_OPERATIONAL_CUSTODY_ABSENT'):[];$this->validate($transitionId,$t,$seneschalBindingId,$s,$c);
  foreach(glob($this->authorizations.'/bounded-execution-authorization-*.json')?:[]as$p){$x=$this->read($p,'C215_BOUNDED_EXECUTION_AUTHORIZATION_CONFLICT');if(!$this->ok($x))throw new \RuntimeException('C215_BOUNDED_EXECUTION_AUTHORIZATION_CONFLICT');if(($x['source_custody_transition']['id']??null)===$transitionId){if(CanonicalJson::encode($x['input']??null)!==CanonicalJson::encode($input))throw new \RuntimeException('C215_BOUNDED_EXECUTION_AUTHORIZATION_CONFLICT');return$x;}}
  $actor=['seat'=>'curia.seneschal','binding_id'=>$seneschalBindingId,'manifestation_id'=>$s['manifestation_id'],'occupancy_generation'=>$s['occupancy_generation']];$id='bounded-execution-authorization-'.substr(hash('sha256',CanonicalJson::encode([$transitionId,$t['record_digest'],$actor,$input])),0,20);
  return$this->save($id,['schema'=>'imperium.curia-bounded-execution-authorization/v1','authorization_id'=>$id,'instance_id'=>$t['instance_id'],'case_id'=>$t['case_id'],'case_digest'=>$t['case_digest'],'authorizer'=>$actor,'source_custody_transition'=>['id'=>$transitionId,'digest'=>$t['record_digest']],'source_deployment_authorization'=>$t['source_deployment_authorization'],'source_binding'=>$t['source_binding'],'seat'=>$t['seat'],'manifestation_id'=>$t['manifestation_id'],'manifestation'=>$t['manifestation'],'persona_identity'=>$t['persona_identity'],'profile_candidate'=>$t['profile_candidate'],'operational_custody'=>$t['operational_custody'],'mission_use'=>$t['mission_use'],'input'=>$input,'input_digest'=>hash('sha256',CanonicalJson::encode($input)),'status'=>'BOUNDED_EXECUTION_AUTHORIZED_PENDING_ONE_ITERATION','bounded_execution_authority'=>true,'bounded_execution_authority_exercisable'=>true,'maximum_iterations'=>1,'tool_access_authority'=>false,'credentials_authority'=>false,'external_action_authority'=>false,'network_access_authority'=>false,'continuing_execution_authority'=>false,'return_authority'=>false,'unbinding_authority'=>false,'sealed'=>true]);
 }
 private function validate(string$id,array$t,string$sid,array$s,array$c):void{if(!$this->ok($t)||!$this->ok($s)||!$this->ok($c)||'imperium.garrison-operational-custody-transition/v1'!==($t['schema']??null)||$id!==($t['transition_id']??null)||'OPERATIONAL_MANIFESTATION_DEPLOYED_CUSTODY_TRANSITIONED_PENDING_BOUNDED_EXECUTION'!==($t['status']??null)||true!==($t['bounded_execution_authorization_pending']??null)||true===($t['execution_authority']??null)||'imperium.curia-seneschal-occupancy/v1'!==($s['schema']??null)||$sid!==($s['binding_id']??null)||($t['instance_id']??null)!==($s['instance_id']??null)||'ACTIVE'!==($s['status']??null)||true!==($s['bounded_execution_authorization_authority']??null)||true===($s['execution_authority']??null)||'imperium.garrison-persona-custody/v1'!==($c['schema']??null)||($t['operational_custody']['digest']??null)!==($c['record_digest']??null)||'DEPLOYED_BOUND'!==($c['custody_state']??null)||false!==($c['available']??null)||($t['manifestation_id']??null)!==($c['operational_custodian']['manifestation_id']??null))throw new \RuntimeException('C214_BOUNDED_EXECUTION_AUTHORIZATION_CHAIN_INVALID');}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$id,array$r):array{if(!is_dir($this->authorizations)&&!mkdir($this->authorizations,0770,true)&&!is_dir($this->authorizations))throw new \RuntimeException('C216_BOUNDED_EXECUTION_AUTHORIZATION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->authorizations.'/'.$id.'.json';if(is_file($p)){if(CanonicalJson::encode($x=$this->read($p,'C215_BOUNDED_EXECUTION_AUTHORIZATION_CONFLICT'))!==CanonicalJson::encode($r))throw new \RuntimeException('C215_BOUNDED_EXECUTION_AUTHORIZATION_CONFLICT');return$x;}if(false===file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX))throw new \RuntimeException('C216_BOUNDED_EXECUTION_AUTHORIZATION_FAILED');return$r;}
}
