<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Curia;

use App\Bootstrap\CanonicalJson;

final readonly class MissionAuthorizationDerivationService
{
    private string $reviews;private string $dossiers;private string $authorizations;
    public function __construct(string$root){$this->reviews=$root.'/var/imperium/offices/curia/planning-dossier-reviews';$this->dossiers=$root.'/var/imperium/offices/curia/planning-dossiers';$this->authorizations=$root.'/var/imperium/authorizations/missions';}

    public function derive(string$reviewId,string$authorityId,\DateTimeImmutable$derivedAt):array
    {
        $existing=$this->existing($authorityId);if(null!==$existing)return$existing;$r=$this->read($this->reviews.'/'.$reviewId.'.json','C254_DOSSIER_APPROVAL_ABSENT');$dossierId=$r['dossier']['id']??'';$d=$this->read($this->dossiers.'/'.$dossierId.'.json','C255_PLANNING_DOSSIER_ABSENT');$a=$r['mission_authorization_derivation_authority']??[];
        if(!$this->ok($r)||'imperium.imperator-planning-dossier-review/v1'!==($r['schema']??null)||'APPROVE_DOSSIER'!==($r['disposition']??null)||true!==($r['dossier_approval']??null)||true!==($r['all_lines_acknowledged']??null)||'IMPERATOR_PLANNING_DOSSIER_APPROVED_PENDING_MISSION_AUTHORIZATION'!==($r['status']??null)||$authorityId!==($a['authority_id']??null)||true!==($a['derivation_authority']??null)||true!==($a['authority_single_use']??null)
            ||!$this->ok($d)||($r['dossier']['digest']??null)!==($d['record_digest']??null)||($a['dossier']['digest']??null)!==($d['record_digest']??null)||($r['dossier']['version']??null)!==($d['dossier_version']??null)||($r['dossier']['line_count']??null)!==($d['line_count']??null)
        )throw new \RuntimeException('C256_MISSION_AUTHORIZATION_DERIVATION_INVALID');
        $source=['dossier'=>['id'=>$dossierId,'version'=>$d['dossier_version'],'digest'=>$d['record_digest']],'imperator_review'=>['id'=>$reviewId,'digest'=>$r['record_digest']],'derivation_authority_id'=>$authorityId];$id='mission-authorization-'.substr(hash('sha256',CanonicalJson::encode([$source,$d['lines'],$d['resource_demands']??[],$d['proposed_model_bindings']??[],$d['disclosures']??[]])),0,20);$preparation=$this->preparation($id,$d);
        return$this->save($id,['schema'=>'imperium.mission-authorization/v1','authorization_id'=>$id,'instance_id'=>$d['instance_id'],'authority_source'=>$source,'holder'=>['kind'=>'imperium-runtime','instance_id'=>$d['instance_id']],'authorized_dossier_lines'=>$d['lines'],'mission_plan'=>$d['mission_plan']??[],'authorized_resource_demands'=>$d['resource_demands']??[],'authorized_disclosures'=>$d['disclosures']??[],'authorized_proposed_model_bindings'=>$d['proposed_model_bindings']??[],'derived_at'=>$derivedAt->format(DATE_ATOM),'derivation_authority'=>['id'=>$authorityId,'consumed'=>true,'continuing_authority'=>false],'preparation_authorities'=>$preparation,'direct_execution_prohibited'=>true,'silent_scope_expansion_prohibited'=>true,'silent_model_substitution_prohibited'=>true,'profile_mutation_performed'=>false,'credential_release_performed'=>false,'provider_invocation_performed'=>false,'deployment_performed'=>false,'external_effect_performed'=>false,'execution_performed'=>false,'execution_authority'=>false,'status'=>'MISSION_AUTHORIZATION_SEALED_PENDING_AUTHORIZED_PREPARATION','sealed'=>true]);
    }

    private function preparation(string$id,array$d):array{$out=['model_binding_sealing'=>[],'personnel_preparation'=>null,'tool_credential_data_preparation'=>null,'execution_commission_derivation'=>null];foreach($d['proposed_model_bindings']??[]as$key=>$binding){$line=$this->line($d['lines']??[],'proposed_model_binding',$key);$aid='model-binding-sealing-authority-'.substr(hash('sha256',CanonicalJson::encode([$id,$key,$binding,$line])),0,20);$out['model_binding_sealing'][$key]=['authority_id'=>$aid,'authority_single_use'=>true,'target'=>$binding['target'],'provider_model_version'=>$binding['provider_model_version'],'configuration'=>$binding['configuration'],'source_line'=>$line,'conscription_profile_sealing_authority'=>true,'provider_invocation_authority'=>false,'execution_authority'=>false,'status'=>'OPEN_PENDING_CONSCRIPTION_MODEL_BINDING_SEALING'];}if([]!==($d['disclosures']['personnel']??[]))$out['personnel_preparation']=$this->bounded($id,'personnel-preparation',$d['disclosures']['personnel']);if([]!==($d['disclosures']['tools_credentials_data']??[]))$out['tool_credential_data_preparation']=$this->bounded($id,'tool-credential-data-preparation',$d['disclosures']['tools_credentials_data']);$out['execution_commission_derivation']=$this->bounded($id,'execution-commission-derivation',['Blocked until every required preparation authority is terminal.']);return$out;}
    private function bounded(string$id,string$kind,array$scope):array{return['authority_id'=>$kind.'-authority-'.substr(hash('sha256',CanonicalJson::encode([$id,$kind,$scope])),0,20),'authority_single_use'=>true,'scope'=>$scope,'preparation_authority'=>true,'execution_authority'=>false,'status'=>'OPEN_PENDING_AUTHORIZED_PREPARATION'];}
    private function line(array$lines,string$section,string$source):array{foreach($lines as$l)if($section===($l['section']??null)&&$source===($l['source']??null))return['line_number'=>$l['line_number'],'line_digest'=>$l['line_digest']];throw new \RuntimeException('C256_MISSION_AUTHORIZATION_DERIVATION_INVALID');}
    private function existing(string$a):?array{if(!is_dir($this->authorizations))return null;foreach(glob($this->authorizations.'/mission-authorization-*.json')?:[]as$p){$r=$this->read($p,'C257_MISSION_AUTHORIZATION_FAILED');if($a===($r['derivation_authority']['id']??null)){if(!$this->ok($r))throw new \RuntimeException('C257_MISSION_AUTHORIZATION_FAILED');return$r;}}return null;}
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$x=$r['record_digest']??null;unset($r['record_digest']);return is_string($x)&&hash_equals($x,hash('sha256',CanonicalJson::encode($r)));}
    private function save(string$id,array$r):array{if(!is_dir($this->authorizations)&&!mkdir($this->authorizations,0770,true)&&!is_dir($this->authorizations))throw new \RuntimeException('C257_MISSION_AUTHORIZATION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->authorizations.'/'.$id.'.json';if(is_file($p))return$this->read($p,'C257_MISSION_AUTHORIZATION_FAILED');file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
