<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Curia;

use App\Bootstrap\CanonicalJson;

final readonly class ModelRequirementCommissionService
{
    private string$occupancy;private string$snapshots;private string$commissions;private string$oracleInbox;
    public function __construct(string$root){$this->occupancy=$root.'/var/imperium/offices/curia/occupancy';$this->snapshots=$root.'/var/imperium/offices/oracle/model-intelligence-snapshots';$this->commissions=$root.'/var/imperium/offices/curia/model-requirement-commissions';$this->oracleInbox=$root.'/var/imperium/offices/oracle/model-requirement-inbox';}

    public function issue(string$snapshotId,string$seneschalBindingId,array$target,array$criteria,\DateTimeImmutable$issuedAt,\DateTimeImmutable$expiresAt):array
    {
        $s=$this->read($this->snapshots.'/'.$snapshotId.'.json','C230_ORACLE_SNAPSHOT_ABSENT');$c=$this->read($this->occupancy.'/'.$seneschalBindingId.'.json','C231_SENESCHAL_OCCUPANCY_ABSENT');
        if(!$this->ok($s)||'imperium.oracle-model-intelligence-snapshot/v1'!==($s['schema']??null)||$snapshotId!==($s['snapshot_id']??null)||'ORACLE_CANONICAL_CATALOGUE_SNAPSHOT_SEALED_NO_SELECTION_AUTHORITY'!==($s['status']??null)||true===($s['selection_authority']??null)
            ||!$this->ok($c)||'imperium.curia-seneschal-occupancy/v1'!==($c['schema']??null)||$seneschalBindingId!==($c['binding_id']??null)||($s['instance_id']??null)!==($c['instance_id']??null)||'curia.seneschal'!==($c['seat']??null)||'ACTIVE'!==($c['status']??null)||true!==($c['model_requirement_commission_authority']??null)||true===($c['execution_authority']??null)
        )throw new \RuntimeException('C232_MODEL_REQUIREMENT_COMMISSION_CHAIN_INVALID');
        $target=$this->target($target);$criteria=$this->criteria($criteria);if($expiresAt<=$issuedAt)throw new \InvalidArgumentException('C233_MODEL_REQUIREMENT_VALIDITY_INVALID');
        $issuer=['office'=>'curia','seat'=>'curia.seneschal','binding_id'=>$seneschalBindingId,'manifestation_id'=>$c['manifestation_id'],'occupancy_generation'=>$c['occupancy_generation']];
        $id='model-requirement-commission-'.substr(hash('sha256',CanonicalJson::encode([$s['instance_id'],$snapshotId,$s['record_digest'],$issuer,$target,$criteria,$issuedAt->format(DATE_ATOM),$expiresAt->format(DATE_ATOM)])),0,20);
        $record=['schema'=>'imperium.curia-model-requirement-commission/v1','commission_id'=>$id,'instance_id'=>$s['instance_id'],'issuer'=>$issuer,'recipient'=>['office'=>'oracle','seat'=>'oracle.augur'],'catalogue_snapshot'=>['id'=>$snapshotId,'digest'=>$s['record_digest'],'generation'=>$s['snapshot_generation']],'target'=>$target,'criteria'=>$criteria,'issued_at'=>$issuedAt->format(DATE_ATOM),'expires_at'=>$expiresAt->format(DATE_ATOM),'status'=>'ISSUED_PENDING_ORACLE_ACCEPTANCE','oracle_acceptance'=>null,'evaluation_authority'=>false,'research_authority'=>false,'recommendation_authority'=>false,'selection_authority'=>false,'model_assignment_authority'=>false,'profile_mutation_authority'=>false,'provider_invocation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'sealed'=>true];
        $record=$this->save($this->commissions,$id,$record);return$this->save($this->oracleInbox,$id,$record);
    }
    private function target(array$t):array{if(array_keys($t)!==['type','id','mission_id']||!in_array($t['type']??null,['OFFICE_SEAT','MISSION_FUNCTION'],true)||!$this->text($t['id']??null)||!(null===$t['mission_id']||$this->text($t['mission_id'])))throw new \InvalidArgumentException('C234_MODEL_REQUIREMENT_TARGET_INVALID');if('MISSION_FUNCTION'===$t['type']&&null===$t['mission_id'])throw new \InvalidArgumentException('C234_MODEL_REQUIREMENT_TARGET_INVALID');return$t;}
    private function criteria(array$c):array{$keys=['cognitive_task','required_capabilities','prohibited_capabilities','required_tools','minimum_context_tokens','data_classification','data_residency','permitted_providers','max_cost_per_million_tokens','max_latency_ms','minimum_reliability','fallback_policy','substitution_policy','evaluation_rubric','minimum_evidence_sources'];if(array_keys($c)!==$keys||!$this->text($c['cognitive_task']??null)||!$this->strings($c['required_capabilities']??null)||!$this->strings($c['prohibited_capabilities']??null,true)||!$this->strings($c['required_tools']??null,true)||!is_int($c['minimum_context_tokens']??null)||$c['minimum_context_tokens']<1||!$this->text($c['data_classification']??null)||!$this->text($c['data_residency']??null)||!$this->strings($c['permitted_providers']??null)||!is_int($c['max_cost_per_million_tokens']??null)||$c['max_cost_per_million_tokens']<0||!is_int($c['max_latency_ms']??null)||$c['max_latency_ms']<1||!is_float($c['minimum_reliability']??null)||$c['minimum_reliability']<0||$c['minimum_reliability']>1||!$this->text($c['fallback_policy']??null)||'SILENT_SUBSTITUTION_PROHIBITED'!==($c['substitution_policy']??null)||!$this->strings($c['evaluation_rubric']??null)||!is_int($c['minimum_evidence_sources']??null)||$c['minimum_evidence_sources']<1)throw new \InvalidArgumentException('C235_MODEL_REQUIREMENT_CRITERIA_INVALID');return$c;}
    private function text(mixed$v):bool{return is_string($v)&&''!==trim($v);}private function strings(mixed$v,bool$empty=false):bool{return is_array($v)&&($empty||[]!==$v)&&[]===array_filter($v,static fn($x)=>!is_string($x)||''===trim($x));}
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
    private function save(string$d,string$id,array$r):array{if(!is_dir($d)&&!mkdir($d,0770,true)&&!is_dir($d))throw new \RuntimeException('C236_MODEL_REQUIREMENT_COMMISSION_FAILED');unset($r['record_digest']);$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$d.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'C237_MODEL_REQUIREMENT_COMMISSION_CONFLICT');if(CanonicalJson::encode($x)!==CanonicalJson::encode($r))throw new \RuntimeException('C237_MODEL_REQUIREMENT_COMMISSION_CONFLICT');return$x;}file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
