<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Curia;

use App\Bootstrap\CanonicalJson;

final readonly class ModelSelectionPlanningDecisionService
{
    private string $recommendations;private string $cases;private string $occupancy;private string $decisions;
    public function __construct(string$root){$this->recommendations=$root.'/var/imperium/offices/oracle/model-recommendations';$this->cases=$root.'/var/imperium/offices/oracle/model-evaluation-cases';$this->occupancy=$root.'/var/imperium/offices/curia/occupancy';$this->decisions=$root.'/var/imperium/offices/curia/model-selection-planning-decisions';}

    public function decide(string$recommendationId,string$authorityId,string$seneschalBindingId,string$disposition,?string$selectedModel,array$configuration,string$rationale,string$deliberationRef,array$objections,\DateTimeImmutable$decidedAt):array
    {
        $existing=$this->existing($authorityId);if(null!==$existing)return$existing;$r=$this->read($this->recommendations.'/'.$recommendationId.'.json','C241_MODEL_RECOMMENDATION_ABSENT');$caseId=$r['case']['id']??'';$case=$this->read($this->cases.'/'.$caseId.'.json','C242_MODEL_EVALUATION_CASE_ABSENT');$o=$this->read($this->occupancy.'/'.$seneschalBindingId.'.json','C243_SENESCHAL_OCCUPANCY_ABSENT');$authority=$r['curia_selection_decision_authority']??[];$eligible=$r['eligible_models']??[];
        if(!$this->ok($r)||'imperium.oracle-model-recommendation/v1'!==($r['schema']??null)||'ORACLE_MODEL_RECOMMENDATION_SEALED_PENDING_CURIA_SELECTION_DECISION'!==($r['status']??null)||$authorityId!==($authority['authority_id']??null)||true!==($authority['selection_decision_authority']??null)||true!==($authority['authority_single_use']??null)||$eligible!==($authority['eligible_models']??null)
            ||!$this->ok($case)||($r['case']['digest']??null)!==($case['record_digest']??null)||!$this->ok($o)||$seneschalBindingId!==($o['binding_id']??null)||($case['instance_id']??null)!==($o['instance_id']??null)||'curia.seneschal'!==($o['seat']??null)||'ACTIVE'!==($o['status']??null)||($r['actor']['binding_id']??null)===$seneschalBindingId||!$this->text($rationale)||!$this->text($deliberationRef)||!$this->strings($objections,true)||!$this->configurationValid($disposition,$configuration)||!$this->decisionValid($disposition,$selectedModel,$r,$authority)
        )throw new \RuntimeException('C244_MODEL_SELECTION_PLANNING_DECISION_INVALID');
        $actor=['office'=>'curia','seat'=>'curia.seneschal','binding_id'=>$seneschalBindingId,'manifestation_id'=>$o['manifestation_id'],'occupancy_generation'=>$o['occupancy_generation']];$id='curia-model-selection-planning-decision-'.substr(hash('sha256',CanonicalJson::encode([$recommendationId,$r['record_digest'],$authorityId,$disposition,$selectedModel,$configuration,$rationale,$deliberationRef,$objections,$actor])),0,20);$selected=in_array($disposition,['SELECT_RECOMMENDED_MODEL','SELECT_OTHER_ELIGIBLE_MODEL'],true);$binding=$selected?['schema'=>'imperium.proposed-model-binding/v1','target'=>$case['target'],'provider_model_version'=>$selectedModel,'configuration'=>$configuration,'source_recommendation'=>['id'=>$recommendationId,'digest'=>$r['record_digest']],'selection_disposition'=>$disposition,'planning_only'=>true,'plan_dossier_inclusion_required'=>true,'imperator_plan_review_required'=>true,'status'=>'PROPOSED_MODEL_BINDING_PENDING_PLAN_AUTHORIZATION']:null;$status=$selected?'CURIA_PROPOSED_MODEL_BINDING_PENDING_PLANNING_DOSSIER_ASSEMBLY':('REJECT_ALL_MODELS'===$disposition?'CURIA_MODEL_CANDIDATES_REJECTED_PENDING_PLAN_REVISION':'CURIA_MODEL_SELECTION_RETURNED_FOR_NEW_COMMISSION');
        return$this->save($id,['schema'=>'imperium.curia-model-selection-planning-decision/v1','decision_id'=>$id,'recommendation'=>['id'=>$recommendationId,'digest'=>$r['record_digest']],'commission'=>$r['commission'],'catalogue_snapshot'=>$r['catalogue_snapshot'],'eligible_models'=>$eligible,'oracle_disposition'=>$r['disposition'],'oracle_recommended_model'=>$r['recommended_model'],'actor'=>$actor,'disposition'=>$disposition,'selected_model'=>$selectedModel,'rationale'=>$rationale,'deliberation_ref'=>$deliberationRef,'objections'=>$objections,'decided_at'=>$decidedAt->format(DATE_ATOM),'selection_decision_authority'=>['id'=>$authorityId,'consumed'=>true,'continuing_authority'=>false],'proposed_model_binding'=>$binding,'isolated_binding_approval_request'=>false,'planning_dossier_inclusion_required'=>$selected,'imperator_plan_review_required'=>$selected,'model_assignment_authority'=>false,'profile_mutation_authority'=>false,'credential_release_authority'=>false,'provider_invocation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'status'=>$status,'sealed'=>true]);
    }

    private function decisionValid(string$d,?string$m,array$r,array$a):bool{$map=['SELECT_RECOMMENDED_MODEL'=>'SELECT_ELIGIBLE_MODEL','SELECT_OTHER_ELIGIBLE_MODEL'=>'SELECT_ELIGIBLE_MODEL','REJECT_ALL_MODELS'=>'REJECT_ALL_MODELS','RETURN_NEW_COMMISSION'=>'RETURN_NEW_COMMISSION'];if(!isset($map[$d])||!in_array($map[$d],$a['permitted_decisions']??[],true))return false;if(str_starts_with($d,'SELECT_')&&(!is_string($m)||!in_array($m,$r['eligible_models']??[],true)))return false;if(!str_starts_with($d,'SELECT_')&&null!==$m)return false;if('SELECT_RECOMMENDED_MODEL'===$d&&$m!==($r['recommended_model']??null))return false;if('SELECT_OTHER_ELIGIBLE_MODEL'===$d&&$m===($r['recommended_model']??null))return false;return true;}
    private function configurationValid(string$d,array$c):bool{if(!str_starts_with($d,'SELECT_'))return[]===$c;if([]===$c||array_is_list($c))return false;foreach($c as$k=>$v){if(!is_string($k)||''===trim($k)||in_array(strtolower($k),['secret','token','api_key','apikey','password','credential'],true))return false;if(is_array($v)&&!$this->configurationTree($v))return false;}return true;}private function configurationTree(array$c):bool{foreach($c as$k=>$v){if(is_string($k)&&in_array(strtolower($k),['secret','token','api_key','apikey','password','credential'],true))return false;if(is_array($v)&&!$this->configurationTree($v))return false;}return true;}
    private function strings(mixed$v,bool$empty=false):bool{if(!is_array($v)||(!$empty&&[]===$v))return false;foreach($v as$x)if(!$this->text($x))return false;return array_values(array_unique($v))===$v;}private function text(mixed$v):bool{return is_string($v)&&''!==trim($v);}
    private function existing(string$a):?array{if(!is_dir($this->decisions))return null;foreach(glob($this->decisions.'/curia-model-selection-planning-decision-*.json')?:[]as$p){$r=$this->read($p,'C245_MODEL_SELECTION_PLANNING_DECISION_FAILED');if($a===($r['selection_decision_authority']['id']??null)){if(!$this->ok($r))throw new \RuntimeException('C245_MODEL_SELECTION_PLANNING_DECISION_FAILED');return$r;}}return null;}
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
    private function save(string$id,array$r):array{if(!is_dir($this->decisions)&&!mkdir($this->decisions,0770,true)&&!is_dir($this->decisions))throw new \RuntimeException('C245_MODEL_SELECTION_PLANNING_DECISION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->decisions.'/'.$id.'.json';if(is_file($p))return$this->read($p,'C245_MODEL_SELECTION_PLANNING_DECISION_FAILED');file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
