<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Curia;
use App\Bootstrap\CanonicalJson;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class OperationalReturnAuthorizationService
{
 private string$executions;private string$occupancy;private string$custody;private string$authorizations;
 public function __construct(#[Autowire('%kernel.project_dir%')]string$root){$this->executions=$root.'/var/imperium/mission/bounded-executions';$this->occupancy=$root.'/var/imperium/offices/curia/occupancy';$this->custody=$root.'/var/imperium/offices/garrison/custody';$this->authorizations=$root.'/var/imperium/offices/curia/operational-return-authorizations';}
 public function authorize(string$executionId,string$seneschalBindingId):array
 {
  if(!preg_match('/^bounded-operational-execution-[a-f0-9]{20}$/',$executionId))throw new \InvalidArgumentException('C217_BOUNDED_EXECUTION_ID_INVALID');$e=$this->read($this->executions.'/'.$executionId.'.json','C218_BOUNDED_EXECUTION_ABSENT');$s=$this->read($this->occupancy.'/'.$seneschalBindingId.'.json','C219_SENESCHAL_OCCUPANCY_ABSENT');
  foreach(glob($this->authorizations.'/operational-return-authorization-*.json')?:[]as$p){$x=$this->read($p,'C222_OPERATIONAL_RETURN_AUTHORIZATION_CONFLICT');if(!$this->ok($x))throw new \RuntimeException('C222_OPERATIONAL_RETURN_AUTHORIZATION_CONFLICT');if(($x['source_bounded_execution']['id']??null)===$executionId){if(($x['source_bounded_execution']['digest']??null)!==($e['record_digest']??null)||($x['authorizer']['binding_id']??null)!==$seneschalBindingId)throw new \RuntimeException('C222_OPERATIONAL_RETURN_AUTHORIZATION_CONFLICT');return$x;}}
  $cid=$e['operational_custody']['id']??null;$c=is_string($cid)?$this->read($this->custody.'/'.$cid.'.json','C220_OPERATIONAL_CUSTODY_ABSENT'):[];$this->validate($executionId,$e,$seneschalBindingId,$s,$c);
  $actor=['seat'=>'curia.seneschal','binding_id'=>$seneschalBindingId,'manifestation_id'=>$s['manifestation_id'],'occupancy_generation'=>$s['occupancy_generation']];$id='operational-return-authorization-'.substr(hash('sha256',CanonicalJson::encode([$executionId,$e['record_digest'],$actor])),0,20);
  return$this->save($id,['schema'=>'imperium.curia-operational-return-authorization/v1','authorization_id'=>$id,'instance_id'=>$e['instance_id'],'case_id'=>$e['case_id'],'case_digest'=>$e['case_digest'],'authorizer'=>$actor,'source_bounded_execution'=>['id'=>$executionId,'digest'=>$e['record_digest']],'source_execution_authorization'=>$e['source_execution_authorization'],'source_custody_transition'=>$e['source_custody_transition'],'source_deployment_authorization'=>$e['source_deployment_authorization'],'source_binding'=>$e['source_binding'],'seat'=>$e['seat'],'manifestation_id'=>$e['manifestation_id'],'manifestation'=>$e['manifestation'],'persona_identity'=>$e['persona_identity'],'profile_candidate'=>$e['profile_candidate'],'operational_custody'=>$e['operational_custody'],'mission_use'=>$e['mission_use'],'input'=>$e['input'],'input_digest'=>$e['input_digest'],'output'=>$e['output'],'return_destination'=>$e['manifestation']['return_destination'],'status'=>'OPERATIONAL_RETURN_AUTHORIZED_PENDING_GARRISON_RETIREMENT','return_authority'=>true,'return_authority_exercisable'=>true,'retirement_authority'=>true,'retirement_authority_exercisable'=>true,'unbinding_authority'=>true,'unbinding_authority_exercisable'=>true,'custody_restoration_authority'=>true,'custody_restoration_authority_exercisable'=>true,'execution_authority'=>false,'redeployment_authority'=>false,'supersession_authority'=>false,'sealed'=>true]);
 }
 private function validate(string$id,array$e,string$sid,array$s,array$c):void{if(!$this->ok($e)||!$this->ok($s)||!$this->ok($c)||'imperium.mission-bounded-operational-execution/v1'!==($e['schema']??null)||$id!==($e['execution_id']??null)||'OPERATIONAL_MANIFESTATION_BOUNDED_EXECUTION_COMPLETED_PENDING_RETURN'!==($e['status']??null)||true!==($e['bounded_execution_authority_consumed']??null)||1!==($e['iterations_consumed']??null)||true!==($e['execution_complete']??null)||true===($e['continuing_execution_authority']??null)||true===($e['tool_access_used']??null)||true===($e['credentials_used']??null)||true===($e['external_action_performed']??null)||true===($e['network_access_performed']??null)||'imperium.curia-seneschal-occupancy/v1'!==($s['schema']??null)||$sid!==($s['binding_id']??null)||($e['instance_id']??null)!==($s['instance_id']??null)||'ACTIVE'!==($s['status']??null)||true!==($s['operational_return_authorization_authority']??null)||true===($s['execution_authority']??null)||'imperium.garrison-persona-custody/v1'!==($c['schema']??null)||($e['operational_custody']['digest']??null)!==($c['record_digest']??null)||'DEPLOYED_BOUND'!==($c['custody_state']??null)||false!==($c['available']??null)||($e['manifestation_id']??null)!==($c['operational_custodian']['manifestation_id']??null))throw new \RuntimeException('C221_OPERATIONAL_RETURN_AUTHORIZATION_CHAIN_INVALID');}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}private function save(string$id,array$r):array{if(!is_dir($this->authorizations)&&!mkdir($this->authorizations,0770,true)&&!is_dir($this->authorizations))throw new \RuntimeException('C223_OPERATIONAL_RETURN_AUTHORIZATION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->authorizations.'/'.$id.'.json';if(is_file($p)){if(CanonicalJson::encode($x=$this->read($p,'C222_OPERATIONAL_RETURN_AUTHORIZATION_CONFLICT'))!==CanonicalJson::encode($r))throw new \RuntimeException('C222_OPERATIONAL_RETURN_AUTHORIZATION_CONFLICT');return$x;}if(false===file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX))throw new \RuntimeException('C223_OPERATIONAL_RETURN_AUTHORIZATION_FAILED');return$r;}
}
