<?php
declare(strict_types=1);namespace App\Imperium\Runtime\Curia;
use App\Bootstrap\CanonicalJson;use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class OperationalDeploymentAuthorizationService
{
 private string$bindings;private string$occupancy;private string$authorizations;
 public function __construct(#[Autowire('%kernel.project_dir%')]string$root){$this->bindings=$root.'/var/imperium/mission/occupancy';$this->occupancy=$root.'/var/imperium/offices/curia/occupancy';$this->authorizations=$root.'/var/imperium/offices/curia/operational-deployment-authorizations';}
 public function authorize(string$bindingId,string$seneschalBindingId,array$missionUse):array
 {
  if(!preg_match('/^operational-seat-binding-[a-f0-9]{20}$/',$bindingId))throw new \InvalidArgumentException('C201_OPERATIONAL_SEAT_BINDING_ID_INVALID');if(!preg_match('/^curia-seneschal-binding-[a-f0-9]{20}$/',$seneschalBindingId))throw new \InvalidArgumentException('C202_SENESCHAL_BINDING_ID_INVALID');$use=$this->missionUse($missionUse);
  $b=$this->read($this->bindings.'/'.$bindingId.'.json','C203_OPERATIONAL_SEAT_BINDING_ABSENT');$s=$this->read($this->occupancy.'/'.$seneschalBindingId.'.json','C204_SENESCHAL_OCCUPANCY_ABSENT');$this->validate($bindingId,$b,$seneschalBindingId,$s);
  foreach(glob($this->authorizations.'/operational-deployment-authorization-*.json')?:[]as$p){$x=$this->read($p,'C206_OPERATIONAL_DEPLOYMENT_AUTHORIZATION_CONFLICT');if(!$this->ok($x))throw new \RuntimeException('C206_OPERATIONAL_DEPLOYMENT_AUTHORIZATION_CONFLICT');if(($x['source_binding']['id']??null)===$bindingId){if(CanonicalJson::encode($x['mission_use']??null)===CanonicalJson::encode($use))return$x;throw new \RuntimeException('C206_OPERATIONAL_DEPLOYMENT_AUTHORIZATION_CONFLICT');}}
  $actor=['seat'=>'curia.seneschal','binding_id'=>$seneschalBindingId,'manifestation_id'=>$s['manifestation_id'],'occupancy_generation'=>$s['occupancy_generation']];$id='operational-deployment-authorization-'.substr(hash('sha256',CanonicalJson::encode([$bindingId,$b['record_digest'],$actor,$use])),0,20);
  return$this->save($id,['schema'=>'imperium.curia-operational-deployment-authorization/v1','authorization_id'=>$id,'instance_id'=>$b['instance_id'],'case_id'=>$b['case_id'],'case_digest'=>$b['case_digest'],'authorizer'=>$actor,'source_binding'=>['id'=>$bindingId,'digest'=>$b['record_digest']],'seat'=>$b['seat'],'manifestation_id'=>$b['manifestation_id'],'manifestation'=>$b['manifestation'],'persona_identity'=>$b['persona_identity'],'profile_candidate'=>$b['profile_candidate'],'custody_lease'=>$b['custody_lease'],'source_assembly'=>$b['source_assembly'],'source_qualification'=>$b['source_qualification'],'source_imperator_approval'=>$b['source_imperator_approval'],'source_senate_disposition'=>$b['source_senate_disposition'],'admitted_findings'=>$b['admitted_findings'],'reconciliation'=>$b['reconciliation'],'mission_use'=>$use,'status'=>'DEPLOYMENT_AUTHORIZED_PENDING_GARRISON_CUSTODY_TRANSITION','deployment_authority'=>true,'deployment_authority_exercisable'=>true,'garrison_custody_transition_authority'=>true,'garrison_custody_transition_authority_exercisable'=>true,'operational_use_permitted'=>false,'tool_access_authority'=>false,'credentials_authority'=>false,'external_action_authority'=>false,'execution_authority'=>false,'return_authority'=>false,'retirement_authority'=>false,'unbinding_authority'=>false,'supersession_authority'=>false,'sealed'=>true]);
 }
 private function missionUse(array$u):array{$keys=['objective','input_contract','output_contract','stop_condition'];if(count($u)!==count($keys)||[]!==array_diff(array_keys($u),$keys))throw new \InvalidArgumentException('C205_BOUNDED_MISSION_USE_INVALID');$out=[];foreach($keys as$k){if(!is_string($u[$k]??null)||''===trim($u[$k]))throw new \InvalidArgumentException('C205_BOUNDED_MISSION_USE_INVALID');$out[$k]=trim($u[$k]);}return$out;}
 private function validate(string$id,array$b,string$sid,array$s):void{if(!$this->ok($b)||!$this->ok($s)||'imperium.operational-manifestation-seat-binding/v1'!==($b['schema']??null)||$id!==($b['binding_id']??null)||'OPERATIONAL_MANIFESTATION_BOUND_PENDING_DEPLOYMENT_AUTHORIZATION'!==($b['status']??null)||true!==($b['seat_bound']??null)||true!==($b['deployment_authorization_pending']??null)||true===($b['deployment_authority']??null)||true===($b['custody_transfer_authority']??null)||true===($b['execution_authority']??null)||true!==($b['sealed']??null)||'imperium.curia-seneschal-occupancy/v1'!==($s['schema']??null)||$sid!==($s['binding_id']??null)||($b['instance_id']??null)!==($s['instance_id']??null)||'curia.seneschal'!==($s['seat']??null)||'ACTIVE'!==($s['status']??null)||true!==($s['operational_deployment_authorization_authority']??null)||true===($s['execution_authority']??null))throw new \RuntimeException('C207_OPERATIONAL_DEPLOYMENT_AUTHORIZATION_CHAIN_INVALID');}
 private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
 private function save(string$id,array$r):array{if(!is_dir($this->authorizations)&&!mkdir($this->authorizations,0770,true)&&!is_dir($this->authorizations))throw new \RuntimeException('C208_OPERATIONAL_DEPLOYMENT_AUTHORIZATION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->authorizations.'/'.$id.'.json';if(is_file($p)){$x=$this->read($p,'C206_OPERATIONAL_DEPLOYMENT_AUTHORIZATION_CONFLICT');if(CanonicalJson::encode($x)!==CanonicalJson::encode($r))throw new \RuntimeException('C206_OPERATIONAL_DEPLOYMENT_AUTHORIZATION_CONFLICT');return$x;}$t=$p.'.tmp.'.bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException('C208_OPERATIONAL_DEPLOYMENT_AUTHORIZATION_FAILED');}return$r;}
}
