<?php
declare(strict_types=1);
namespace App\Imperium\Runtime\Guildhall;
use App\Bootstrap\CanonicalJson;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
final readonly class SubordinatePersonaFulfillmentAcceptanceService
{
    private string $inbox; private string $occupancy; private string $receipts;
    public function __construct(#[Autowire("%kernel.project_dir%")] string $p){$this->inbox=$p."/var/imperium/offices/guildhall/inbox/subordinate-persona-fulfillments";$this->occupancy=$p."/var/imperium/offices/guildhall/occupancy";$this->receipts=$p."/var/imperium/offices/guildhall/subordinate-persona-fulfillment-receipts";}
    public function accept(string $fulfillmentId,string $bindingId):array
    {
        if(!preg_match('/^foundry-guildhall-persona-fulfillment-[a-f0-9]{20}$/',$fulfillmentId))throw new \InvalidArgumentException("G75_FULFILLMENT_ID_INVALID");
        $f=$this->read($this->inbox."/".$fulfillmentId.".json","G76_FULFILLMENT_CHAIN_INVALID");$g=$this->read($this->occupancy."/".$bindingId.".json","G76_FULFILLMENT_CHAIN_INVALID");
        if(!$this->ok($f)||!$this->ok($g)||"FULFILLED_PENDING_GUILDHALL_ACCEPTANCE"!==($f["status"]??null)||true!==($f["commission_fulfilled"]??null)||false!==($f["candidate_substituted"]??null)||"guildhall.guildmaster"!==($f["recipient"]["seat"]??null)||"guildhall.guildmaster"!==($g["seat"]??null)||($f["instance_id"]??null)!==($g["instance_id"]??null)||"ACTIVE"!==($g["status"]??null)||true!==($g["persona_fulfillment_acceptance_authority"]??null)||true===($g["execution_authority"]??null)||true===($f["admission_authority"]??null))throw new \RuntimeException("G76_FULFILLMENT_CHAIN_INVALID");
        $id="guildhall-persona-fulfillment-receipt-".substr(hash("sha256",CanonicalJson::encode([$fulfillmentId,$f["record_digest"],$bindingId,$g["record_digest"]])),0,20);
        return $this->save($id,["schema"=>"imperium.guildhall-persona-fulfillment-receipt/v1","receipt_id"=>$id,"instance_id"=>$f["instance_id"],"fulfillment_id"=>$fulfillmentId,"fulfillment_digest"=>$f["record_digest"],"originating_guildhall_commission_id"=>$f["originating_guildhall_commission_id"],"originating_guildhall_commission_digest"=>$f["originating_guildhall_commission_digest"],"senate_confirmation_record_id"=>$f["senate_confirmation_record_id"],"senate_confirmation_record_digest"=>$f["senate_confirmation_record_digest"],"candidate_id"=>$f["candidate_id"],"candidate_digest"=>$f["candidate_digest"],"persona_name"=>$f["persona_name"],"persona_specification_version"=>$f["persona_specification_version"],"persona"=>$f["persona"],"review_target_lineage"=>$f["review_target_lineage"],"guildmaster"=>$this->actor($g),"commission_fulfillment_accepted"=>true,"candidate_substituted"=>false,"garrison_forwarding_ready"=>true,"status"=>"GUILDHALL_ACCEPTED_PENDING_GARRISON_FORWARDING","admission_authority"=>false,"execution_authority"=>false,"sealed"=>true]);
    }
    private function actor(array$r):array{return["seat"=>$r["seat"],"binding_id"=>$r["binding_id"],"binding_digest"=>$r["record_digest"],"manifestation_id"=>$r["manifestation_id"],"occupancy_generation"=>$r["occupancy_generation"]];}
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r["record_digest"]??null;unset($r["record_digest"]);return is_string($d)&&hash_equals($d,hash("sha256",CanonicalJson::encode($r)));}
    private function save(string$id,array$r):array{if(!is_dir($this->receipts)&&!mkdir($this->receipts,0770,true)&&!is_dir($this->receipts))throw new \RuntimeException("G77_FULFILLMENT_ACCEPTANCE_FAILED");$r["record_digest"]=hash("sha256",CanonicalJson::encode($r));$p=$this->receipts."/".$id.".json";if(is_file($p)){ $o=$this->read($p,"G78_FULFILLMENT_ACCEPTANCE_CONFLICT");if(CanonicalJson::encode($o)!==CanonicalJson::encode($r))throw new \RuntimeException("G78_FULFILLMENT_ACCEPTANCE_CONFLICT");return$o;}$t=$p.".tmp.".bin2hex(random_bytes(6));if(false===file_put_contents($t,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX)||!rename($t,$p)){@unlink($t);throw new \RuntimeException("G77_FULFILLMENT_ACCEPTANCE_FAILED");}return$r;}
}
