<?php
declare(strict_types=1);
require dirname(__DIR__).'/vendor/autoload.php';

use App\Tests\Imperium\Runtime\Support\CitadelAuthorityFixture;

// No root/key/provider override. All backing data is generated by this synthetic fixture.
if ($argc !== 1) { fwrite(STDERR, "Synthetic proof takes no arguments.\n"); exit(1); }
$f = new CitadelAuthorityFixture();
try {
    $f->seed(); $before = hash_file('sha256', $f->root.'/var/imperium/bootstrap-state.json');
    [$exit, $projection] = $f->command('recruiter-export', 'synthetic-authority-test');
    if ($exit !== 2) { throw new RuntimeException('Synthetic export failed'); }
    $f->command('recruiter-inspect', $projection);
    $f->command('recruiter-compare', ['projection' => $projection, 'instance_id' => 'synthetic-authority-test']);
    $input = $f->requestInput(); [, $request] = $f->command('garrison-request', $input);
    $f->command('garrison-inspect', ['request' => $request, 'occupancy' => $input['occupancy']]);
    $f->command('garrison-verify', ['request' => $request, 'occupancy' => $input['occupancy'], 'decision' => null]);
    foreach ($f->outputs as $out) { if ($out['exit'] !== 2) { throw new RuntimeException('Synthetic command failed'); } }
    if ($before !== hash_file('sha256', $f->root.'/var/imperium/bootstrap-state.json')) { throw new RuntimeException('Synthetic source changed'); }
    $result = ['label' => 'SYNTHETIC_ONLY_NOT_INSTALLATION_EVIDENCE', 'command_di_outputs' => $f->outputs,
        'synthetic_unsigned_request_input' => $input, 'private_bytes_unchanged' => $before === hash_file('sha256', $f->root.'/var/imperium/bootstrap-state.json'),
        'real_keys_used' => false, 'real_installation_read' => false, 'live_ready' => false, 'activation' => false, 'execution_authority' => false];
    $json = json_encode($result, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
    if (str_contains($json, CitadelAuthorityFixture::SECRET)) { throw new RuntimeException('Synthetic disclosure check failed'); }
    echo $json."\n";
} finally { $f->close(); }
