<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson; use App\Bootstrap\StateStore; use App\Imperium\Runtime\Authorship\AuthorshipResidentSeatBindingService; use App\Imperium\Runtime\Authorship\CanonicalAuthorshipStaffRegistry; use App\Imperium\Runtime\Conscription\GenericOfficerSubstrateRegistry; use PHPUnit\Framework\Attributes\DataProvider; use PHPUnit\Framework\TestCase;
final class AuthorshipResidentSeatBindingServiceTest extends TestCase
{
    #[DataProvider('offices')]
    public function testAtomicallyBindsQualifiedResidentWithBoundedAuthorshipAuthority(string $office,string $role,string $seat):void
    {
        $root=sys_get_temp_dir().'/imperium-'.$role.'-binding-'.bin2hex(random_bytes(6));$project=dirname(__DIR__,3);$bootstrap=new StateStore($root);$bootstrap->locked(static function()use($bootstrap):void{$bootstrap->write(['state'=>'CURIA_READY','binding'=>['instance_id'=>'imperium-test'],'events'=>[]]);});mkdir($root.'/runtime/artifacts',0770,true);copy($project.'/runtime/artifacts/generic-officer-substrate.json',$root.'/runtime/artifacts/generic-officer-substrate.json');$staff=new CanonicalAuthorshipStaffRegistry($project);$substrate=new GenericOfficerSubstrateRegistry($root);$member=$staff->member($office);
        $caseId=$office.'-provisioning-1234567890abcdef1234';$case=['case_id'=>$caseId,'office'=>$office,'seat'=>$seat,'status'=>'CANONICAL_STAFF_READY','authorship_authority'=>true,'authorship_authority_exercisable'=>false,'canonical_staff_package'=>$staff->current($office)];$case['record_digest']=hash('sha256',CanonicalJson::encode($case));mkdir($root.'/var/imperium/mastermason/activation-cases',0770,true);file_put_contents($root.'/var/imperium/mastermason/activation-cases/'.$caseId.'.json',json_encode($case,JSON_THROW_ON_ERROR));
        $deliveryId='qualified-delivery-1234567890abcdef1234';$manifestationId='imperium-test.officer.'.$office.'.'.$role.'.123456789abc';$qualification=['candidate_id'=>$manifestationId,'qualification_contract'=>$member['qualification_contract'],'disposition'=>'QUALIFIED'];$packet=['schema'=>'imperium.qualified-manifestation-packet/v1','delivery_id'=>$deliveryId,'source_provisioning_case_id'=>$caseId,'commission'=>['consumed'=>true],'candidate'=>['manifestation_id'=>$manifestationId,'instance_id'=>'imperium-test','persona'=>$member['persona'],'profile'=>$member['profile'],'substrate_instance'=>['substrate'=>$substrate->current(),'status'=>'PROFILE_INSTALLED'],'target_seat'=>$seat,'target_occupancy_generation'=>1,'status'=>'QUALIFIED_UNBOUND'],'qualification'=>$qualification,'qualification_digest'=>hash('sha256',CanonicalJson::encode($qualification)),'sealed'=>true,'authorship_authority'=>false,'subordinate_staff_resolution_authority'=>false,'seat_binding_authority'=>false,'recipient_acceptance'=>false,'execution_authority'=>false];$packet['record_digest']=hash('sha256',CanonicalJson::encode($packet));mkdir($root.'/var/imperium/mastermason/qualified-manifestations',0770,true);file_put_contents($root.'/var/imperium/mastermason/qualified-manifestations/'.$deliveryId.'.json',json_encode($packet,JSON_THROW_ON_ERROR));
        try{$service=new AuthorshipResidentSeatBindingService($root,$bootstrap,$staff,$substrate);$o=$service->bind($office,$deliveryId);self::assertSame($o,$service->bind($office,$deliveryId));self::assertSame('imperium.authorship-resident-occupancy/v1',$o['schema']);self::assertSame($seat,$o['seat']);self::assertSame($manifestationId,$o['manifestation_id']);self::assertSame('ACTIVE',$o['status']);self::assertTrue($o['binding_atomic']);self::assertTrue($o['seat_binding_authority']);self::assertSame('CONSUMED_BY_ATOMIC_BINDING',$o['seat_binding_disposition']);self::assertTrue($o['authorship_authority']);self::assertTrue($o['subordinate_staff_resolution_authority']);self::assertFalse($o['recipient_acceptance']);self::assertFalse($o['execution_authority']);self::assertFileExists($root.'/var/imperium/offices/'.$office.'/occupancy/'.$o['binding_id'].'.json');}finally{$this->removeTree($root);}
    }
    public static function offices():array{return [['hagiography','sanctographer','hagiography.sanctographer'],['studium','chancellor','studium.chancellor']];}
    private function removeTree(string $path):void{if(!is_dir($path))return;foreach(array_diff(scandir($path)?:[],['.','..'])as$entry){$child=$path.'/'.$entry;is_dir($child)?$this->removeTree($child):unlink($child);}rmdir($path);}
}
