<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson; use App\Imperium\Runtime\Authorship\AuthorshipCommissionAcceptanceService; use PHPUnit\Framework\Attributes\DataProvider; use PHPUnit\Framework\TestCase;
final class AuthorshipCommissionAcceptanceServiceTest extends TestCase
{
    #[DataProvider('offices')]
    public function testOccupiedResidentAcceptsExactCommissionWithoutExecution(string $office,string $role,string $seat,string $subordinate):void
    {
        $root=sys_get_temp_dir().'/imperium-'.$office.'-acceptance-'.bin2hex(random_bytes(6));$caseId='persona-production-1234567890abcdef1234';$case=['case_id'=>$caseId,'instance_id'=>'imperium-test','profession'=>'Cybersecurity assessment','status'=>'OPEN_PENDING_SPECIALIZED_INPUTS'];$case['record_digest']=hash('sha256',CanonicalJson::encode($case));mkdir($root.'/var/imperium/offices/foundry/production-cases',0770,true);file_put_contents($root.'/var/imperium/offices/foundry/production-cases/'.$caseId.'.json',json_encode($case,JSON_THROW_ON_ERROR));
        $commissionId='authorship-'.$office.'-1234567890abcdef1234';$commission=['schema'=>'imperium.specialized-authorship-commission/v1','commission_id'=>$commissionId,'instance_id'=>'imperium-test','production_case_id'=>$caseId,'production_case_digest'=>$case['record_digest'],'profession'=>$case['profession'],'office'=>$office,'target_seat'=>$seat,'status'=>'ISSUED_PENDING_RECIPIENT','authorship_authority'=>true,'authorship_class'=>'TEST_AUTHORSHIP','required_product'=>'Exact packet','forbidden_authorship'=>['complete Persona'],'recipient_acceptance'=>null,'persona_selection_authority'=>false,'persona_assembly_authority'=>false,'spawning_authority'=>false,'admission_authority'=>false,'seat_binding_authority'=>false,'execution_authority'=>false];$commission['record_digest']=hash('sha256',CanonicalJson::encode($commission));mkdir($root.'/var/imperium/offices/'.$office.'/inbox',0770,true);file_put_contents($root.'/var/imperium/offices/'.$office.'/inbox/'.$commissionId.'.json',json_encode($commission,JSON_THROW_ON_ERROR));
        $bindingId=$office.'-'.$role.'-binding-1234567890abcdef1234';$binding=['schema'=>'imperium.authorship-resident-occupancy/v1','binding_id'=>$bindingId,'instance_id'=>'imperium-test','office'=>$office,'seat'=>$seat,'manifestation_id'=>'manifestation-'.$role,'occupancy_generation'=>1,'status'=>'ACTIVE','binding_atomic'=>true,'authorship_authority'=>true,'subordinate_staff_resolution_authority'=>true,'recipient_acceptance'=>false,'execution_authority'=>false];$binding['record_digest']=hash('sha256',CanonicalJson::encode($binding));mkdir($root.'/var/imperium/offices/'.$office.'/occupancy',0770,true);file_put_contents($root.'/var/imperium/offices/'.$office.'/occupancy/'.$bindingId.'.json',json_encode($binding,JSON_THROW_ON_ERROR));
        try{$service=new AuthorshipCommissionAcceptanceService($root);$a=$service->accept($office,$commissionId,$bindingId);self::assertSame($a,$service->accept($office,$commissionId,$bindingId));self::assertSame('ACCEPTED_FOR_RESIDENT_AUTHORSHIP',$a['disposition']);self::assertSame($subordinate,$a['subordinate_staff_class']);self::assertTrue($a['recipient_acceptance']);self::assertTrue($a['authorship_authority']);self::assertTrue($a['authorship_authority_exercisable']);self::assertTrue($a['subordinate_staff_resolution_authority']);self::assertTrue($a['subordinate_staff_resolution_pending']);self::assertFalse($a['spawning_authority']);self::assertFalse($a['execution_authority']);self::assertFileExists($root.'/var/imperium/offices/'.$office.'/acceptances/'.$a['acceptance_id'].'.json');}finally{$this->removeTree($root);}
    }
    public static function offices():array{return [['hagiography','sanctographer','hagiography.sanctographer','Chronicler'],['studium','chancellor','studium.chancellor','Notary']];}
    private function removeTree(string $path):void{if(!is_dir($path))return;foreach(array_diff(scandir($path)?:[],['.','..'])as$entry){$child=$path.'/'.$entry;is_dir($child)?$this->removeTree($child):unlink($child);}rmdir($path);}
}
