<?php
declare(strict_types=1);namespace App\Tests\Imperium\Runtime;use App\Bootstrap\CanonicalJson;use App\Imperium\Runtime\Authorship\AuthorshipSubordinateCognitionGateway;use App\Imperium\Runtime\Authorship\AuthorshipSubordinateResolutionService;use PHPUnit\Framework\Attributes\DataProvider;use PHPUnit\Framework\TestCase;
final class AuthorshipSubordinateResolutionServiceTest extends TestCase
{
    #[DataProvider('offices')]
    public function testResidentSealsRequirementsWithoutConstructionAuthority(string $office,string $role,string $seat,string $subordinate):void
    {
        $root=sys_get_temp_dir().'/imperium-'.$office.'-resolution-'.bin2hex(random_bytes(6));$bindingId=$office.'-'.$role.'-binding-1234567890abcdef1234';$binding=['binding_id'=>$bindingId,'instance_id'=>'imperium-test','seat'=>$seat,'manifestation_id'=>'manifestation-'.$role,'occupancy_generation'=>1,'status'=>'ACTIVE','subordinate_staff_resolution_authority'=>true];$binding['record_digest']=hash('sha256',CanonicalJson::encode($binding));mkdir($root.'/var/imperium/offices/'.$office.'/occupancy',0770,true);file_put_contents($root.'/var/imperium/offices/'.$office.'/occupancy/'.$bindingId.'.json',json_encode($binding,JSON_THROW_ON_ERROR));
        $commissionId='authorship-'.$office.'-1234567890abcdef1234';$commission=['commission_id'=>$commissionId,'target_seat'=>$seat,'authorship_authority'=>true,'execution_authority'=>false];$commission['record_digest']=hash('sha256',CanonicalJson::encode($commission));mkdir($root.'/var/imperium/offices/'.$office.'/inbox',0770,true);file_put_contents($root.'/var/imperium/offices/'.$office.'/inbox/'.$commissionId.'.json',json_encode($commission,JSON_THROW_ON_ERROR));
        $acceptanceId=$office.'-acceptance-1234567890abcdef1234';$acceptance=['schema'=>'imperium.authorship-commission-acceptance/v1','acceptance_id'=>$acceptanceId,'instance_id'=>'imperium-test','commission_id'=>$commissionId,'commission_digest'=>$commission['record_digest'],'binding_id'=>$bindingId,'binding_digest'=>$binding['record_digest'],'disposition'=>'ACCEPTED_FOR_RESIDENT_AUTHORSHIP','recipient_acceptance'=>true,'authorship_authority_exercisable'=>true,'subordinate_staff_class'=>$subordinate,'subordinate_staff_resolution_authority'=>true,'subordinate_staff_resolution_pending'=>true,'execution_authority'=>false];$acceptance['record_digest']=hash('sha256',CanonicalJson::encode($acceptance));mkdir($root.'/var/imperium/offices/'.$office.'/acceptances',0770,true);file_put_contents($root.'/var/imperium/offices/'.$office.'/acceptances/'.$acceptanceId.'.json',json_encode($acceptance,JSON_THROW_ON_ERROR));
        $gateway=new class implements AuthorshipSubordinateCognitionGateway{public function resolve(string $office,array $acceptance,array $commission,array $occupancy):array{return ['disposition'=>'SUBORDINATE_REQUIREMENTS_DETERMINED','rationale'=>'Exact bounded specialist work is required.','required_specializations'=>['specialist-'.$office],'seat_requirements'=>['versioned exact Seat'],'profile_requirements'=>['approved current Profile'],'assignment_boundaries'=>['accepted commission only'],'source_requirements'=>['attributable sources'],'return_contracts'=>['sealed attributable return'],'stop_conditions'=>['scope exceeded']];}};
        try{$service=new AuthorshipSubordinateResolutionService($root,$gateway);$r=$service->resolve($office,$acceptanceId);self::assertSame($r,$service->resolve($office,$acceptanceId));self::assertSame('PENDING_CURIA_SUBORDINATE_CONSTRUCTION_AUTHORIZATION',$r['status']);self::assertTrue($r['subordinate_staff_resolution_complete']);self::assertTrue($r['construction_request_authority']);self::assertFalse($r['construction_authority']);self::assertFalse($r['persona_selection_authority']);self::assertFalse($r['profile_approval_authority']);self::assertFalse($r['spawning_authority']);self::assertFalse($r['seat_binding_authority']);self::assertFalse($r['execution_authority']);self::assertTrue($r['sealed']);}finally{$this->removeTree($root);}
    }
    public static function offices():array{return [['hagiography','sanctographer','hagiography.sanctographer','Chronicler'],['studium','chancellor','studium.chancellor','Notary']];}private function removeTree(string $path):void{if(!is_dir($path))return;foreach(array_diff(scandir($path)?:[],['.','..'])as$entry){$child=$path.'/'.$entry;is_dir($child)?$this->removeTree($child):unlink($child);}rmdir($path);}
}
