<?php

declare(strict_types=1);

namespace App\Tests\Imperium\Runtime;

use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Imperator\ActivationCorridorDispositionCallerAuthorityIssuanceAuthorizationContract as Issuance;
use App\Imperium\Runtime\Imperator\ActivationCorridorDispositionEligibilityContract as Eligibility;
use App\Imperium\Runtime\Imperator\ActivationCorridorDispositionEvidenceDossierContract as Dossier;
use App\Imperium\Runtime\Imperator\ActivationCorridorDispositionTargetContract as Target;
use App\Imperium\Runtime\Imperator\CorridorDispositionPrincipalAuthorityRemediationFixtureStore;
use App\Imperium\Runtime\Imperator\ImperatorCorridorDispositionScopeGrantContract as Grant;
use App\Imperium\Runtime\Imperator\ImperatorCorridorDispositionScopeSuccessorContract as Successor;
use App\Imperium\Runtime\Imperator\ImperatorPrincipalLifecycleDispositionContract as Lifecycle;
use App\Imperium\Runtime\Imperator\ImperatorRuntimePrincipalVersionContract as Principal;
use PHPUnit\Framework\TestCase;

final class CorridorDispositionPrincipalAuthorityRemediationBatch2Test extends TestCase
{
    private string $root;
    protected function setUp():void{$this->root=sys_get_temp_dir().'/imperium-cpa-batch2-'.bin2hex(random_bytes(6));mkdir($this->root,0770,true);}
    protected function tearDown():void{if(!is_dir($this->root))return;$i=new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($this->root,\FilesystemIterator::SKIP_DOTS),\RecursiveIteratorIterator::CHILD_FIRST);foreach($i as$f)$f->isDir()?rmdir($f->getPathname()):unlink($f->getPathname());rmdir($this->root);}

    public function testExactOfflineFixturesStoreIdempotentlyWithoutCreatingAuthority():void
    {
        $at=new \DateTimeImmutable('2026-08-30T12:05:00+00:00');$source=$this->principal(1,false,'ACTIVE');$issuer=$this->principal(2,true,'ACTIVE');$grant=$this->grant($source,$issuer);$successor=$this->successor($grant);
        [$target,$dossier,$eligibility]=$this->basis($issuer);$activation=$this->activation($issuer);$issuance=$this->issuance($issuer,$successor,$activation,$target,$dossier,$eligibility);
        $store=new CorridorDispositionPrincipalAuthorityRemediationFixtureStore($this->root);
        self::assertSame($store->putScopeGrant($grant,$source,$at),$store->putScopeGrant($grant,$source,$at));
        self::assertSame($store->putScopeSuccessor($successor,$grant),$store->putScopeSuccessor($successor,$grant));
        self::assertSame($store->putIssuanceAuthorization($issuance,$issuer,$successor,$activation,$target,$dossier,$eligibility,$at),$store->putIssuanceAuthorization($issuance,$issuer,$successor,$activation,$target,$dossier,$eligibility,$at));
        self::assertFileExists($this->root.'/'.CorridorDispositionPrincipalAuthorityRemediationFixtureStore::SCOPE_GRANTS.'/'.$grant['grant_id'].'.json');
    }

    public function testGenerationScopeExpiryRevocationAndCandidateMismatchFailClosed():void
    {
        $at=new \DateTimeImmutable('2026-08-30T12:05:00+00:00');$source=$this->principal(1,false,'ACTIVE');$issuer=$this->principal(2,true,'ACTIVE');$grant=$this->grant($source,$issuer);$store=new CorridorDispositionPrincipalAuthorityRemediationFixtureStore($this->root);
        foreach (['generation','revocation','expiry'] as$case){$bad=$grant;if('generation'===$case)$bad['successor_principal']['generation']=3;if('revocation'===$case)$bad['revocation']=$this->ref('scope-revocation','a','imperium.operator-root.revocation/v1');if('expiry'===$case)$bad['expires_at']='2026-08-30T12:04:00+00:00';$bad=self::seal($bad);try{$store->putScopeGrant($bad,$source,$at);self::fail('Accepted '.$case);}catch(\RuntimeException$e){self::assertStringStartsWith('CPA2',$e->getMessage());}}
        $successor=$this->successor($grant);[$target,$dossier,$eligibility]=$this->basis($issuer);$activation=$this->activation($issuer);$authorization=$this->issuance($issuer,$successor,$activation,$target,$dossier,$eligibility);$authorization['proposed_disposition']='QUARANTINED_PENDING_REMEDIATION';$authorization=self::seal($authorization);
        $this->expectExceptionMessage('CPA220_ISSUANCE_AUTHORIZATION_INVALID');$store->putIssuanceAuthorization($authorization,$issuer,$successor,$activation,$target,$dossier,$eligibility,$at);
    }

    public function testDocumentationAuthorizesOfflineInterruptionProofOnly():void
    {
        $root=dirname(__DIR__,3);$doc=preg_replace('/\s+/',' ',(string)file_get_contents($root.'/docs/corridor-disposition-principal-authority-remediation-validation.md'));$handoff=preg_replace('/\s+/',' ',(string)file_get_contents($root.'/docs/handoffs/corridor-disposition-principal-authority-remediation-batch-2-complete.md'));
        foreach(['BATCH_2_FAIL_CLOSED_VALIDATORS_AND_IMMUTABLE_FIXTURE_STORES_COMPLETE','caller-supplied offline fixtures','generation continuity','expiry and revocation','effective active-principal','no live registry']as$c)self::assertNotFalse(stripos($doc,$c),$c);
        foreach(['Only remediation Batch 3 is authorized','offline replay and interruption proof','may not issue live authority','activate a principal','seal a disposition','external I/O','Iron Gate','Lazaretto','Provider Execution Assurance remains paused']as$b)self::assertNotFalse(stripos($handoff,$b),$b);
    }

    private function principal(int$generation,bool$corridor,string$status):array{return self::seal(['schema'=>Principal::SCHEMA,'principal_version_id'=>'imperator-principal-corridor-'.$generation,'principal_id'=>'imperator-principal-corridor','instance_id'=>'imperium-test','binding_id'=>'imperator-binding-corridor','principal_generation'=>$generation,'constitution_route'=>'EXISTING_INSTANCE_REMEDIATION','source_constitution_authority'=>$this->ref('constitution-'.$generation,'1','imperium.operator-root.imperator-principal-constitution-authority/v1'),'source_operator_root'=>$this->ref('operator-root','2','imperium.operator-root/v1'),'identity'=>['operator_id'=>'operator-test','operator_identity_digest'=>str_repeat('3',64),'imperator_subject_id'=>'imperator-subject','imperator_subject_digest'=>str_repeat('4',64)],'authority_scope'=>['provider_binding_activation_authority'=>true,'outbound_email_authority'=>false,'credential_authority'=>false,'provider_execution_authority'=>false,'corridor_disposition_authority'=>$corridor],'lifecycle'=>['constituted_at'=>'2026-08-30T11:00:00+00:00','effective_at'=>'2026-08-30T11:01:00+00:00','expires_at'=>'2026-08-31T11:01:00+00:00','prior_version'=>1===$generation?null:$this->ref('imperator-principal-corridor-1','5',Principal::SCHEMA),'superseding_version'=>null,'current_disposition'=>null],'status'=>$status,'credential_reference_persisted'=>false,'credential_secret_persisted'=>false,'serialized_capability_persisted'=>false,'sealed'=>true]);}
    private function grant(array$source,array$successor):array{return self::seal(['schema'=>Grant::SCHEMA,'grant_id'=>'corridor-scope-grant-test','instance_id'=>'imperium-test','operator_root'=>['operator_id'=>'operator-test','source_identity_digest'=>str_repeat('3',64),'decision_id'=>'scope-decision-test','decision_digest'=>str_repeat('6',64)],'source_principal'=>$this->pref($source),'successor_principal'=>$this->pref($successor),'scope_delta'=>['corridor_disposition_authority'=>true],'preserved_scope'=>['provider_binding_activation_authority'=>true,'outbound_email_authority'=>false,'credential_authority'=>false,'provider_execution_authority'=>false],'permitted_transition'=>Grant::PERMITTED_TRANSITION,'rationale'=>'Authorize only the exact corridor disposition scope successor.','authority_single_use'=>true,'authority_exercisable'=>true,'issuance_winner_required'=>true,'consumption_winner_required'=>true,'issued_at'=>'2026-08-30T12:00:00+00:00','expires_at'=>'2026-08-30T12:10:00+00:00','revocation'=>null,'consumed'=>false,'continuing_authority'=>false,'sealed'=>true]);}
    private function successor(array$grant):array{return self::seal(['schema'=>Successor::SCHEMA,'successor_transition_id'=>'corridor-scope-successor-test','instance_id'=>'imperium-test','scope_grant'=>self::rto($grant,'grant_id'),'source_principal'=>$grant['source_principal'],'successor_principal'=>$grant['successor_principal'],'source_generation'=>1,'successor_generation'=>2,'identity_preserved'=>true,'binding_preserved'=>true,'scope_delta'=>$grant['scope_delta'],'preserved_scope'=>$grant['preserved_scope'],'initial_status'=>'PENDING_ACTIVATION','activation_required'=>true,'separate_activation_authority_required'=>true,'transition_winner_required'=>true,'committed_at'=>'2026-08-30T12:03:00+00:00','grant_consumed'=>true,'source_principal_mutated'=>false,'source_principal_superseded'=>false,'caller_authority_issued'=>false,'continuing_authority'=>false,'sealed'=>true]);}
    private function activation(array$issuer):array{return self::seal(['schema'=>Lifecycle::SCHEMA,'disposition_id'=>'principal-activation-test','instance_id'=>'imperium-test','operator_root'=>$this->ref('operator-root','2','imperium.operator-root/v1'),'source_principal_version'=>self::rto($issuer,'principal_version_id'),'source_status'=>'PENDING_ACTIVATION','disposition'=>'ACTIVATE','rationale'=>'Separately activate exact corridor scope successor.','effective_at'=>'2026-08-30T12:04:00+00:00','successor_principal_version'=>null,'authority_scope_changed'=>false,'historical_attribution_preserved'=>true,'caller_authority_issuance_permitted_after_effective_at'=>true,'external_action_performed'=>false,'sealed'=>true]);}
    private function basis(array$p):array{$t=self::seal(['schema'=>Target::SCHEMA,'target_id'=>'corridor-target','instance_id'=>'imperium-test','corridor_id'=>'provider-binding-activation-corridor','corridor_generation'=>1,'terminal_custody_refusal'=>$this->ref('custody-refusal','8','imperium.clavium.cross-process-capability-custody-feasibility/v1'),'source_campaign'=>$this->ref('campaign','9','imperium.campaign/v1'),'scope'=>['provider_binding_activation_corridor'=>'provider-binding-activation','activation_artifact_set_digest'=>str_repeat('a',64),'historical_evidence_set_digest'=>str_repeat('b',64)],'identified_at'=>'2026-08-30T11:30:00+00:00','authority_created'=>false,'binding_activated'=>false,'sealed'=>true]);$cuts=[];foreach(range(1,6)as$i)$cuts[]=$this->ref('cut-'.$i,dechex($i+8),'imperium.imperator.activation-transition-interruption-evidence/v1');$d=self::seal(['schema'=>Dossier::SCHEMA,'dossier_id'=>'corridor-dossier','instance_id'=>'imperium-test','target'=>self::rto($t,'target_id'),'active_principal'=>self::rto($p,'principal_version_id'),'activation_decision'=>$this->ref('decision','c','imperium.decision/v1'),'activation_authority'=>$this->ref('authority','d','imperium.authority/v1'),'activation_lease'=>$this->ref('lease','e','imperium.lease/v1'),'transition_interruption_evidence'=>$cuts,'stranded_artifact_dispositions'=>[$this->ref('stranded','f','imperium.disposition/v1')],'process_loss_custody_evidence'=>$this->ref('loss','1','imperium.loss/v1'),'credential_secret_exclusion_evidence'=>$this->ref('exclusion','2','imperium.exclusion/v1'),'terminal_custody_refusal'=>$this->ref('custody-refusal','8','imperium.clavium.cross-process-capability-custody-feasibility/v1'),'completeness'=>'COMPLETE','conflicts'=>[],'assembled_at'=>'2026-08-30T11:40:00+00:00','read_only'=>true,'authority_created'=>false,'disposition_sealed'=>false,'source_artifact_mutated'=>false,'sealed'=>true]);$e=self::seal(['schema'=>Eligibility::SCHEMA,'eligibility_id'=>'corridor-eligibility','instance_id'=>'imperium-test','target'=>self::rto($t,'target_id'),'evidence_dossier'=>self::rto($d,'dossier_id'),'principal'=>self::rto($p,'principal_version_id'),'proposed_disposition'=>'RETIRE_CORRIDOR','predicates'=>array_fill_keys(Eligibility::REQUIRED_PREDICATE_FIELDS,true),'consequences'=>['corridor_operationally_usable'=>false,'retirement_irreversible'=>true,'replacement_corridor_requires_new_authority'=>true,'historical_evidence_readable'=>true,'outstanding_artifacts_create_no_authority'=>true,'terminal_custody_refusal_authoritative'=>true],'classification'=>'ELIGIBLE','reasons'=>['Exact offline basis.'],'assessed_at'=>'2026-08-30T11:50:00+00:00','authority_created'=>false,'disposition_sealed'=>false,'source_artifact_mutated'=>false,'successor_authority_created'=>false,'continuing_custody_refusal'=>Eligibility::CONTINUING_CUSTODY_REFUSAL,'sealed'=>true]);return[$t,$d,$e];}
    private function issuance(array$p,array$s,array$a,array$t,array$d,array$e):array{return self::seal(['schema'=>Issuance::SCHEMA,'issuance_authorization_id'=>'corridor-issuance-authorization','instance_id'=>'imperium-test','issuer_principal'=>$this->pref($p),'scope_successor'=>self::rto($s,'successor_transition_id'),'activation_disposition'=>self::rto($a,'disposition_id'),'target'=>self::rto($t,'target_id'),'evidence_dossier'=>self::rto($d,'dossier_id'),'eligibility'=>self::rto($e,'eligibility_id'),'proposed_disposition'=>'RETIRE_CORRIDOR','result_authority_id'=>'corridor-caller-authority-result','permitted_transition'=>Issuance::PERMITTED_TRANSITION,'authority_single_use'=>true,'authority_exercisable'=>true,'issuance_winner_required'=>true,'consumption_winner_required'=>true,'issued_at'=>'2026-08-30T12:04:00+00:00','expires_at'=>'2026-08-30T12:10:00+00:00','revocation'=>null,'consumed'=>false,'continuing_authority'=>false,'custody_refusal'=>Issuance::CONTINUING_CUSTODY_REFUSAL,'sealed'=>true]);}
    private function ref(string$id,string$d,string$s):array{return['id'=>$id,'digest'=>str_repeat($d,64),'schema'=>$s];}private function pref(array$r):array{return['id'=>$r['principal_version_id'],'digest'=>$r['record_digest'],'schema'=>$r['schema'],'generation'=>$r['principal_generation']];}private static function rto(array$r,string$id):array{return['id'=>$r[$id],'digest'=>$r['record_digest'],'schema'=>$r['schema']];}private static function seal(array$r):array{unset($r['record_digest']);$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}
}
