<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;use App\Imperium\Runtime\Governance\InternalGovernanceLeaseInterruptionDispositionService;use PHPUnit\Framework\TestCase;
final class InternalGovernanceLeaseInterruptionDispositionServiceTest extends TestCase
{
 public function testSeneschalSealsLeaseInterruptionWithoutAuthorityOrMutation():void{$root=sys_get_temp_dir().'/imperium-cag-lease-interrupt-'.bin2hex(random_bytes(5));try{[$lease,$seneschal]=$this->fixtures($root);$s=new InternalGovernanceLeaseInterruptionDispositionService($root);$r=$s->interrupt($lease,$seneschal,'Stop before durable claim creation.',new \DateTimeImmutable('2026-08-27T12:01:00+00:00'));self::assertSame('INTERRUPT',$r['disposition']);self::assertSame('UNCLAIMED_INTERNAL_GOVERNANCE_COGNITION_LEASE',$r['affected_scope']['kind']);self::assertFalse($r['affected_scope']['lease_consumed']);foreach(['enforcement_authority_opened','state_mutated','authority_granted','continuation_authority']as$f)self::assertFalse($r[$f]);self::assertSame($r,$s->interrupt($lease,$seneschal,'Stop before durable claim creation.',new \DateTimeImmutable('2026-08-27T12:02:00+00:00')));$source=json_decode((string)file_get_contents($root.'/var/imperium/offices/clavium/governance-cognition-leases/'.$lease.'.json'),true,512,JSON_THROW_ON_ERROR);self::assertFalse($source['lease_consumed']);}finally{$this->remove($root);}}
 public function testConsumedLeaseFailsStopped():void{$root=sys_get_temp_dir().'/imperium-cag-lease-consumed-'.bin2hex(random_bytes(5));try{[$lease,$seneschal]=$this->fixtures($root);$claim='governance-cognition-invocation-claim-'.str_repeat('d',20);$this->write($root.'/var/imperium/runtime/governance-cognition-invocation-claims/'.$claim.'.json',$this->record(['lease_consumption'=>['lease_id'=>$lease,'consumed'=>true]]));$this->expectExceptionMessage('CAG1203_GOVERNANCE_LEASE_NOT_INTERRUPTIBLE_UNCLAIMED');(new InternalGovernanceLeaseInterruptionDispositionService($root))->interrupt($lease,$seneschal,'Stop.',new \DateTimeImmutable('2026-08-27T12:01:00+00:00'));}finally{$this->remove($root);}}
 public function testExpiredLeaseFailsStopped():void{$root=sys_get_temp_dir().'/imperium-cag-lease-expired-'.bin2hex(random_bytes(5));try{[$lease,$seneschal]=$this->fixtures($root);$this->expectExceptionMessage('CAG1203_GOVERNANCE_LEASE_NOT_INTERRUPTIBLE_UNCLAIMED');(new InternalGovernanceLeaseInterruptionDispositionService($root))->interrupt($lease,$seneschal,'Stop.',new \DateTimeImmutable('2026-08-27T12:05:00+00:00'));}finally{$this->remove($root);}}
 private function fixtures(string$root):array{$lease='governance-cognition-lease-'.str_repeat('a',20);$seneschal='operational-seat-binding-'.str_repeat('b',20);$this->write($root.'/var/imperium/offices/clavium/governance-cognition-leases/'.$lease.'.json',$this->record(['schema'=>'imperium.clavium-governance-cognition-lease/v1','lease_id'=>$lease,'instance_id'=>'imperium-test','case_id'=>'case-test','cluster'=>'foundry','target'=>['seat'=>'foundry.magister-fabricae','purpose'=>'bounded-review'],'issued_at'=>'2026-08-27T12:00:00+00:00','expires_at'=>'2026-08-27T12:05:00+00:00','status'=>'GOVERNANCE_COGNITION_LEASE_ISSUED_PENDING_DURABLE_INVOCATION_CLAIM','opaque'=>true,'lease_single_use'=>true,'lease_consumed'=>false,'sealed'=>true]));$this->write($root.'/var/imperium/operational/occupancy/'.$seneschal.'.json',$this->record(['binding_id'=>$seneschal,'instance_id'=>'imperium-test','seat'=>'curia.seneschal','manifestation_id'=>'seneschal','occupancy_generation'=>1,'status'=>'ACTIVE','sealed'=>true]));return[$lease,$seneschal];}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
