<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;use App\Imperium\Runtime\Governance\InternalGovernanceInterruptionEnforcementAuthorityService;use PHPUnit\Framework\TestCase;
final class InternalGovernanceInterruptionEnforcementAuthorityServiceTest extends TestCase
{
 public function testExactShortLivedAuthorityOpensWithoutConsumptionOrMutation():void{$root=sys_get_temp_dir().'/imperium-cag-authority-'.bin2hex(random_bytes(5));try{[$disposition,$locksmith]=$this->fixtures($root);$at=new \DateTimeImmutable('2026-08-27T12:00:00+00:00');$s=new InternalGovernanceInterruptionEnforcementAuthorityService($root);$r=$s->issue($disposition,$locksmith,$at,$at->modify('+5 minutes'));self::assertSame('DENY_PROVIDER_INVOCATION_JOURNAL_START_FOR_EXACT_CLAIM',$r['permitted_transition']);self::assertSame('curia.seneschal',$r['issuer']['seat']);self::assertSame('clavium.locksmith',$r['enforcer']['seat']);self::assertTrue($r['single_use']);self::assertTrue($r['exercisable']);foreach(['consumed','continuing_authority','external_action_authority','perimeter_authority']as$f)self::assertFalse($r[$f]);self::assertFileDoesNotExist($root.'/var/imperium/runtime/provider-invocation-journal/'.self::CLAIM.'.json');self::assertSame($r,$s->issue($disposition,$locksmith,$at->modify('+1 minute'),$at->modify('+2 minutes')));}finally{$this->remove($root);}}
 public function testAuthorityLongerThanFiveMinutesIsRejected():void{$root=sys_get_temp_dir().'/imperium-cag-expiry-'.bin2hex(random_bytes(5));try{[$d,$l]=$this->fixtures($root);$at=new \DateTimeImmutable('2026-08-27T12:00:00+00:00');$this->expectExceptionMessage('CAG800_ENFORCEMENT_AUTHORITY_INPUT_INVALID');(new InternalGovernanceInterruptionEnforcementAuthorityService($root))->issue($d,$l,$at,$at->modify('+5 minutes +1 second'));}finally{$this->remove($root);}}
 public function testJournaledAttemptFailsStopped():void{$root=sys_get_temp_dir().'/imperium-cag-started-'.bin2hex(random_bytes(5));try{[$d,$l]=$this->fixtures($root);$this->write($root.'/var/imperium/runtime/provider-invocation-journal/'.self::CLAIM.'.json',$this->record(['claim'=>['id'=>self::CLAIM,'digest'=>str_repeat('f',64)]]));$at=new \DateTimeImmutable('2026-08-27T12:00:00+00:00');$this->expectExceptionMessage('CAG804_GOVERNANCE_CLAIM_NO_LONGER_ENFORCEABLE_PRE_IO');(new InternalGovernanceInterruptionEnforcementAuthorityService($root))->issue($d,$l,$at,$at->modify('+1 minute'));}finally{$this->remove($root);}}
 private const CLAIM='governance-cognition-invocation-claim-aaaaaaaaaaaaaaaaaaaa';
 private function fixtures(string$root):array{$seneschal='operational-seat-binding-'.str_repeat('b',20);$locksmith='clavium-locksmith-binding-'.str_repeat('c',20);$claim=$this->record(['schema'=>'imperium.clavium-governance-cognition-invocation-claim/v1','claim_id'=>self::CLAIM,'instance_id'=>'imperium-test','provider_request'=>['external_io_started'=>false],'status'=>'GOVERNANCE_INVOCATION_CLAIMED_DURABLE_PRE_IO']);$this->write($root.'/var/imperium/runtime/governance-cognition-invocation-claims/'.self::CLAIM.'.json',$claim);$sen=$this->record(['binding_id'=>$seneschal,'instance_id'=>'imperium-test','seat'=>'curia.seneschal','manifestation_id'=>'seneschal','occupancy_generation'=>1,'status'=>'ACTIVE']);$this->write($root.'/var/imperium/operational/occupancy/'.$seneschal.'.json',$sen);$lock=$this->record(['schema'=>'imperium.clavium-locksmith-occupancy/v1','binding_id'=>$locksmith,'instance_id'=>'imperium-test','seat'=>'clavium.locksmith','manifestation_id'=>'locksmith','occupancy_generation'=>1,'status'=>'ACTIVE']);$this->write($root.'/var/imperium/offices/clavium/occupancy/'.$locksmith.'.json',$lock);$actor=['seat'=>'curia.seneschal','binding_id'=>$seneschal,'binding_digest'=>$sen['record_digest'],'manifestation_id'=>'seneschal','occupancy_generation'=>1];$id='revocation-disposition-'.str_repeat('d',20);$d=$this->record(['schema'=>'imperium.continuous-governance-revocation-disposition/v1','disposition_id'=>$id,'instance_id'=>'imperium-test','disposition'=>'INTERRUPT','competent_actor'=>$actor,'affected_scope'=>['kind'=>'INTERNAL_GOVERNANCE_COGNITION_INVOCATION','claim'=>['id'=>self::CLAIM,'digest'=>$claim['record_digest']],'external_io_started'=>false],'effective_at'=>'2026-08-27T11:59:00+00:00','prior_references'=>[['id'=>self::CLAIM,'digest'=>$claim['record_digest']]],'enforcement_required'=>true,'enforcement_authority_opened'=>false,'state_mutated'=>false,'authority_granted'=>false,'continuation_authority'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/runtime/continuous-governance-revocation-dispositions/'.$id.'.json',$d);return[$id,$locksmith];}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
