<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;use App\Imperium\Runtime\Clavium\ProviderInvocationJournalService;use App\Imperium\Runtime\Governance\InternalGovernanceInterruptionEnforcementService;use PHPUnit\Framework\TestCase;
final class InternalGovernanceInterruptionEnforcementServiceTest extends TestCase
{
 public function testLocksmithConsumesAuthorityAndJournalAdmissionIsDenied():void{$root=sys_get_temp_dir().'/imperium-cag-enforce-'.bin2hex(random_bytes(5));try{[$authority,$locksmith,$claim]=$this->fixtures($root);$r=(new InternalGovernanceInterruptionEnforcementService($root))->enforce($authority,$locksmith,new \DateTimeImmutable('2026-08-27T12:01:00+00:00'));self::assertTrue($r['authority_consumed']);self::assertFalse($r['journal_created']);foreach(['external_io_started','claim_mutated','lease_mutated','credential_mutated','propagation_performed','continuation_authority']as$f)self::assertFalse($r[$f]);self::assertFileDoesNotExist($root.'/var/imperium/runtime/provider-invocation-journal/'.self::CLAIM.'.json');$this->expectExceptionMessage('CLV416_GOVERNANCE_INVOCATION_INTERRUPTED_PRE_IO');(new ProviderInvocationJournalService($root))->reserveGovernance($claim,new \DateTimeImmutable('2026-08-27T12:02:00+00:00'));}finally{$this->remove($root);}}
 public function testExpiredAuthorityFailsStopped():void{$root=sys_get_temp_dir().'/imperium-cag-expired-'.bin2hex(random_bytes(5));try{[$authority,$locksmith]=$this->fixtures($root);$this->expectExceptionMessage('CAG902_ENFORCEMENT_AUTHORITY_INVALID');(new InternalGovernanceInterruptionEnforcementService($root))->enforce($authority,$locksmith,new \DateTimeImmutable('2026-08-27T12:05:00+00:00'));}finally{$this->remove($root);}}
 public function testExistingJournalWinsRaceAndCannotBeInterruptedAsPreIoAdmission():void{$root=sys_get_temp_dir().'/imperium-cag-admitted-'.bin2hex(random_bytes(5));try{[$authority,$locksmith]=$this->fixtures($root);$this->write($root.'/var/imperium/runtime/provider-invocation-journal/'.self::CLAIM.'.json',['already'=>'reserved']);$this->expectExceptionMessage('CAG905_PROVIDER_ADMISSION_ALREADY_OPENED');(new InternalGovernanceInterruptionEnforcementService($root))->enforce($authority,$locksmith,new \DateTimeImmutable('2026-08-27T12:01:00+00:00'));}finally{$this->remove($root);}}
 private const CLAIM='governance-cognition-invocation-claim-aaaaaaaaaaaaaaaaaaaa';
 private function fixtures(string$root):array{$locksmith='clavium-locksmith-binding-'.str_repeat('b',20);$claim=$this->record(['schema'=>'imperium.clavium-governance-cognition-invocation-claim/v1','claim_id'=>self::CLAIM,'instance_id'=>'imperium-test','lease_consumption'=>['consumed'=>true],'governance_authority_consumption'=>['consumed'=>true],'provider_request'=>['idempotency_identity'=>'imperium-'.self::CLAIM,'external_io_started'=>false],'recovery'=>['automatic_replay_permitted'=>false],'status'=>'GOVERNANCE_INVOCATION_CLAIMED_DURABLE_PRE_IO']);$this->write($root.'/var/imperium/runtime/governance-cognition-invocation-claims/'.self::CLAIM.'.json',$claim);$occupancy=$this->record(['schema'=>'imperium.clavium-locksmith-occupancy/v1','binding_id'=>$locksmith,'instance_id'=>'imperium-test','seat'=>'clavium.locksmith','manifestation_id'=>'locksmith','occupancy_generation'=>1,'status'=>'ACTIVE']);$this->write($root.'/var/imperium/offices/clavium/occupancy/'.$locksmith.'.json',$occupancy);$enforcer=['seat'=>'clavium.locksmith','binding_id'=>$locksmith,'binding_digest'=>$occupancy['record_digest'],'manifestation_id'=>'locksmith','occupancy_generation'=>1];$scope=['kind'=>'INTERNAL_GOVERNANCE_COGNITION_INVOCATION','claim'=>['id'=>self::CLAIM,'digest'=>$claim['record_digest']],'external_io_started'=>false];$disposition='revocation-disposition-'.str_repeat('c',20);$d=$this->record(['schema'=>'imperium.continuous-governance-revocation-disposition/v1','disposition_id'=>$disposition,'instance_id'=>'imperium-test','disposition'=>'INTERRUPT','affected_scope'=>$scope]);$this->write($root.'/var/imperium/runtime/continuous-governance-revocation-dispositions/'.$disposition.'.json',$d);$authority='revocation-enforcement-authority-'.str_repeat('d',20);$a=$this->record(['schema'=>'imperium.continuous-governance-enforcement-authority/v1','authority_id'=>$authority,'instance_id'=>'imperium-test','source_disposition'=>['id'=>$disposition,'digest'=>$d['record_digest']],'issuer'=>['seat'=>'curia.seneschal'],'enforcer'=>$enforcer,'affected_scope'=>$scope,'permitted_transition'=>'DENY_PROVIDER_INVOCATION_JOURNAL_START_FOR_EXACT_CLAIM','issued_at'=>'2026-08-27T12:00:00+00:00','expires_at'=>'2026-08-27T12:05:00+00:00','single_use'=>true,'exercisable'=>true,'consumed'=>false,'continuing_authority'=>false,'external_action_authority'=>false,'perimeter_authority'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/runtime/continuous-governance-enforcement-authorities/'.$authority.'.json',$a);return[$authority,$locksmith,$claim];}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);if(!isset($r['record_digest']))$r=$this->record($r);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
