<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;use App\Imperium\Runtime\Governance\InternalGovernanceInterruptionReconstructionService;use PHPUnit\Framework\TestCase;
final class InternalGovernanceInterruptionReconstructionServiceTest extends TestCase
{
 public function testFourArtifactInterruptedBranchReconstructsWithoutJournal():void{$root=sys_get_temp_dir().'/imperium-cag-reconstruct-'.bin2hex(random_bytes(5));try{$this->fixtures($root);$r=(new InternalGovernanceInterruptionReconstructionService($root))->reconstruct(self::CLAIM);self::assertSame('INTERNAL_GOVERNANCE_PRE_IO_INTERRUPTION_RECONSTRUCTED',$r['status']);self::assertSame('FOUR_ARTIFACT_PRE_IO_INTERRUPTION_SUBCHAIN_ONLY',$r['completeness_claim']);self::assertSame(4,$r['verified_artifact_count']);self::assertTrue($r['provider_journal_absent']);self::assertTrue($r['read_only']);foreach(['provider_reinvoked','state_mutated','propagation_performed','authority_granted','continuation_authority']as$f)self::assertFalse($r[$f]);}finally{$this->remove($root);}}
 public function testUnexpectedJournalInvalidatesInterruptedBranch():void{$root=sys_get_temp_dir().'/imperium-cag-reconstruct-journal-'.bin2hex(random_bytes(5));try{$this->fixtures($root);$this->write($root.'/var/imperium/runtime/provider-invocation-journal/'.self::CLAIM.'.json',['status'=>'INVOCATION_RESERVED_PRE_IO']);$this->expectExceptionMessage('CAG1001_INTERRUPTION_RECONSTRUCTION_INVALID');(new InternalGovernanceInterruptionReconstructionService($root))->reconstruct(self::CLAIM);}finally{$this->remove($root);}}
 public function testDuplicateEnforcementResultFailsStopped():void{$root=sys_get_temp_dir().'/imperium-cag-reconstruct-duplicate-'.bin2hex(random_bytes(5));try{$result=$this->fixtures($root);$result['result_id']='revocation-enforcement-result-'.str_repeat('f',20);unset($result['record_digest']);$this->write($root.'/var/imperium/runtime/continuous-governance-enforcement-results/'.$result['result_id'].'.json',$result);$this->expectExceptionMessage('CAG1001_INTERRUPTION_RECONSTRUCTION_INVALID');(new InternalGovernanceInterruptionReconstructionService($root))->reconstruct(self::CLAIM);}finally{$this->remove($root);}}
 private const CLAIM='governance-cognition-invocation-claim-aaaaaaaaaaaaaaaaaaaa';
 private function fixtures(string$root):array{$claim=$this->record(['schema'=>'imperium.clavium-governance-cognition-invocation-claim/v1','claim_id'=>self::CLAIM,'instance_id'=>'imperium-test','provider_request'=>['external_io_started'=>false],'status'=>'GOVERNANCE_INVOCATION_CLAIMED_DURABLE_PRE_IO','sealed'=>true]);$this->write($root.'/var/imperium/runtime/governance-cognition-invocation-claims/'.self::CLAIM.'.json',$claim);$actor=['seat'=>'curia.seneschal','binding_id'=>'operational-seat-binding-'.str_repeat('b',20)];$enforcer=['seat'=>'clavium.locksmith','binding_id'=>'clavium-locksmith-binding-'.str_repeat('c',20)];$scope=['kind'=>'INTERNAL_GOVERNANCE_COGNITION_INVOCATION','claim'=>['id'=>self::CLAIM,'digest'=>$claim['record_digest']],'external_io_started'=>false];$did='revocation-disposition-'.str_repeat('d',20);$d=$this->record(['schema'=>'imperium.continuous-governance-revocation-disposition/v1','disposition_id'=>$did,'instance_id'=>'imperium-test','disposition'=>'INTERRUPT','competent_actor'=>$actor,'affected_scope'=>$scope,'enforcement_required'=>true,'enforcement_authority_opened'=>false,'state_mutated'=>false,'authority_granted'=>false,'continuation_authority'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/runtime/continuous-governance-revocation-dispositions/'.$did.'.json',$d);$aid='revocation-enforcement-authority-'.str_repeat('e',20);$a=$this->record(['schema'=>'imperium.continuous-governance-enforcement-authority/v1','authority_id'=>$aid,'instance_id'=>'imperium-test','source_disposition'=>['id'=>$did,'digest'=>$d['record_digest']],'issuer'=>$actor,'enforcer'=>$enforcer,'affected_scope'=>$scope,'permitted_transition'=>'DENY_PROVIDER_INVOCATION_JOURNAL_START_FOR_EXACT_CLAIM','single_use'=>true,'exercisable'=>true,'consumed'=>false,'continuing_authority'=>false,'external_action_authority'=>false,'perimeter_authority'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/runtime/continuous-governance-enforcement-authorities/'.$aid.'.json',$a);$rid='revocation-enforcement-result-'.str_repeat('1',20);$r=$this->record(['schema'=>'imperium.continuous-governance-enforcement-result/v1','result_id'=>$rid,'instance_id'=>'imperium-test','source_authority'=>['id'=>$aid,'digest'=>$a['record_digest']],'source_disposition'=>$a['source_disposition'],'enforcer'=>$enforcer,'affected_scope'=>$scope,'performed_transition'=>'DENY_PROVIDER_INVOCATION_JOURNAL_START_FOR_EXACT_CLAIM','authority_consumed'=>true,'journal_created'=>false,'external_io_started'=>false,'claim_mutated'=>false,'lease_mutated'=>false,'credential_mutated'=>false,'propagation_performed'=>false,'continuation_authority'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/runtime/continuous-governance-enforcement-results/'.$rid.'.json',$r);return$r;}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);if(!isset($r['record_digest']))$r=$this->record($r);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
