<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;use App\Imperium\Runtime\Governance\InternalGovernanceInterruptionDispositionService;use PHPUnit\Framework\TestCase;
final class InternalGovernanceInterruptionDispositionServiceTest extends TestCase
{
 public function testSeneschalSealsPreIoInterruptionWithoutEnforcementOrMutation():void{$root=sys_get_temp_dir().'/imperium-cag-interrupt-'.bin2hex(random_bytes(5));try{[$claim,$binding]=$this->fixtures($root);$s=new InternalGovernanceInterruptionDispositionService($root);$r=$s->interrupt($claim,$binding,'The bounded internal iteration must stop pending review.',new \DateTimeImmutable('2026-08-27T09:00:00+00:00'));self::assertSame('INTERRUPT',$r['disposition']);self::assertSame('SENESCHAL_ACTIVE_INTERNAL_MISSION_ITERATION',$r['authority_basis']['jurisdiction']);self::assertTrue($r['enforcement_required']);foreach(['enforcement_authority_opened','state_mutated','authority_granted','continuation_authority']as$f)self::assertFalse($r[$f]);self::assertSame($r,$s->interrupt($claim,$binding,'The bounded internal iteration must stop pending review.',new \DateTimeImmutable('2026-08-27T10:00:00+00:00')));}finally{$this->remove($root);}}
 public function testJournaledClaimFailsStoppedBecauseInFlightCancellationIsDeferred():void{$root=sys_get_temp_dir().'/imperium-cag-journal-'.bin2hex(random_bytes(5));try{[$claim,$binding]=$this->fixtures($root);$this->write($root.'/var/imperium/runtime/provider-invocation-journal/'.$claim.'.json',$this->record(['claim'=>['id'=>$claim,'digest'=>str_repeat('d',64)]]));$this->expectExceptionMessage('CAG703_GOVERNANCE_CLAIM_NOT_INTERRUPTIBLE_PRE_IO');(new InternalGovernanceInterruptionDispositionService($root))->interrupt($claim,$binding,'Stop.',new \DateTimeImmutable());}finally{$this->remove($root);}}
 public function testConflictingActiveSeneschalFailsStopped():void{$root=sys_get_temp_dir().'/imperium-cag-actor-'.bin2hex(random_bytes(5));try{[$claim,$binding]=$this->fixtures($root);$other='operational-seat-binding-'.str_repeat('c',20);$this->write($root.'/var/imperium/operational/occupancy/'.$other.'.json',$this->record(['binding_id'=>$other,'instance_id'=>'imperium-test','seat'=>'curia.seneschal','manifestation_id'=>'other','occupancy_generation'=>2,'status'=>'ACTIVE','sealed'=>true]));$this->expectExceptionMessage('CAG705_SENESCHAL_NOT_COMPETENT_CURRENT_OCCUPANT');(new InternalGovernanceInterruptionDispositionService($root))->interrupt($claim,$binding,'Stop.',new \DateTimeImmutable());}finally{$this->remove($root);}}
 private function fixtures(string$root):array{$claim='governance-cognition-invocation-claim-'.str_repeat('a',20);$binding='operational-seat-binding-'.str_repeat('b',20);$this->write($root.'/var/imperium/runtime/governance-cognition-invocation-claims/'.$claim.'.json',$this->record(['schema'=>'imperium.clavium-governance-cognition-invocation-claim/v1','claim_id'=>$claim,'instance_id'=>'imperium-test','case_id'=>'case-test','cluster'=>'foundry','target'=>['seat'=>'foundry.magister-fabricae','purpose'=>'bounded-review'],'provider_request'=>['external_io_started'=>false],'status'=>'GOVERNANCE_INVOCATION_CLAIMED_DURABLE_PRE_IO','sealed'=>true]));$this->write($root.'/var/imperium/operational/occupancy/'.$binding.'.json',$this->record(['binding_id'=>$binding,'instance_id'=>'imperium-test','seat'=>'curia.seneschal','manifestation_id'=>'seneschal','occupancy_generation'=>1,'status'=>'ACTIVE','sealed'=>true]));return[$claim,$binding];}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
