<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;use App\Imperium\Runtime\Governance\InternalGovernanceLeaseInterruptionEnforcementAuthorityService;use PHPUnit\Framework\TestCase;
final class InternalGovernanceLeaseInterruptionEnforcementAuthorityServiceTest extends TestCase
{
 public function testExactLeaseAuthorityOpensWithoutConsumerOrMutation():void{$root=sys_get_temp_dir().'/imperium-cag-lease-authority-'.bin2hex(random_bytes(5));try{[$d,$l,$lease]=$this->fixtures($root);$at=new \DateTimeImmutable('2026-08-27T12:01:00+00:00');$s=new InternalGovernanceLeaseInterruptionEnforcementAuthorityService($root);$r=$s->issue($d,$l,$at,$at->modify('+4 minutes'));self::assertSame('DENY_DURABLE_GOVERNANCE_INVOCATION_CLAIM_FOR_EXACT_LEASE',$r['permitted_transition']);self::assertSame($lease,$r['affected_scope']['lease']['id']);self::assertTrue($r['single_use']);self::assertTrue($r['exercisable']);foreach(['consumed','continuing_authority','external_action_authority','perimeter_authority']as$f)self::assertFalse($r[$f]);self::assertSame($r,$s->issue($d,$l,$at->modify('+1 minute'),$at->modify('+2 minutes')));self::assertSame([],glob($root.'/var/imperium/runtime/governance-cognition-invocation-claims/*.json')?:[]);}finally{$this->remove($root);}}
 public function testAuthorityCannotOutliveLease():void{$root=sys_get_temp_dir().'/imperium-cag-lease-authority-expiry-'.bin2hex(random_bytes(5));try{[$d,$l]=$this->fixtures($root);$at=new \DateTimeImmutable('2026-08-27T12:01:00+00:00');$this->expectExceptionMessage('CAG1304_GOVERNANCE_LEASE_NO_LONGER_ENFORCEABLE_UNCLAIMED');(new InternalGovernanceLeaseInterruptionEnforcementAuthorityService($root))->issue($d,$l,$at,new \DateTimeImmutable('2026-08-27T12:05:01+00:00'));}finally{$this->remove($root);}}
 public function testExistingClaimFailsStopped():void{$root=sys_get_temp_dir().'/imperium-cag-lease-authority-claim-'.bin2hex(random_bytes(5));try{[$d,$l,$lease]=$this->fixtures($root);$claim='governance-cognition-invocation-claim-'.str_repeat('f',20);$this->write($root.'/var/imperium/runtime/governance-cognition-invocation-claims/'.$claim.'.json',$this->record(['lease_consumption'=>['lease_id'=>$lease,'consumed'=>true]]));$at=new \DateTimeImmutable('2026-08-27T12:01:00+00:00');$this->expectExceptionMessage('CAG1304_GOVERNANCE_LEASE_NO_LONGER_ENFORCEABLE_UNCLAIMED');(new InternalGovernanceLeaseInterruptionEnforcementAuthorityService($root))->issue($d,$l,$at,$at->modify('+1 minute'));}finally{$this->remove($root);}}
 private function fixtures(string$root):array{$lease='governance-cognition-lease-'.str_repeat('a',20);$sen='operational-seat-binding-'.str_repeat('b',20);$lock='clavium-locksmith-binding-'.str_repeat('c',20);$leaseRecord=$this->record(['schema'=>'imperium.clavium-governance-cognition-lease/v1','lease_id'=>$lease,'instance_id'=>'imperium-test','expires_at'=>'2026-08-27T12:05:00+00:00','status'=>'GOVERNANCE_COGNITION_LEASE_ISSUED_PENDING_DURABLE_INVOCATION_CLAIM','lease_single_use'=>true,'lease_consumed'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/offices/clavium/governance-cognition-leases/'.$lease.'.json',$leaseRecord);$senRecord=$this->record(['binding_id'=>$sen,'instance_id'=>'imperium-test','seat'=>'curia.seneschal','manifestation_id'=>'seneschal','occupancy_generation'=>1,'status'=>'ACTIVE']);$this->write($root.'/var/imperium/operational/occupancy/'.$sen.'.json',$senRecord);$lockRecord=$this->record(['schema'=>'imperium.clavium-locksmith-occupancy/v1','binding_id'=>$lock,'instance_id'=>'imperium-test','seat'=>'clavium.locksmith','manifestation_id'=>'locksmith','occupancy_generation'=>1,'status'=>'ACTIVE']);$this->write($root.'/var/imperium/offices/clavium/occupancy/'.$lock.'.json',$lockRecord);$actor=['seat'=>'curia.seneschal','binding_id'=>$sen,'binding_digest'=>$senRecord['record_digest'],'manifestation_id'=>'seneschal','occupancy_generation'=>1];$id='revocation-disposition-'.str_repeat('d',20);$d=$this->record(['schema'=>'imperium.continuous-governance-revocation-disposition/v1','disposition_id'=>$id,'instance_id'=>'imperium-test','disposition'=>'INTERRUPT','competent_actor'=>$actor,'affected_scope'=>['kind'=>'UNCLAIMED_INTERNAL_GOVERNANCE_COGNITION_LEASE','lease'=>['id'=>$lease,'digest'=>$leaseRecord['record_digest']],'lease_consumed'=>false],'effective_at'=>'2026-08-27T12:00:30+00:00','prior_references'=>[['id'=>$lease,'digest'=>$leaseRecord['record_digest']]],'enforcement_required'=>true,'enforcement_authority_opened'=>false,'state_mutated'=>false,'authority_granted'=>false,'continuation_authority'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/runtime/continuous-governance-revocation-dispositions/'.$id.'.json',$d);return[$id,$lock,$lease];}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
