<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Senate\ModelBoundProfileSenatorFindingService;
use App\Imperium\Runtime\Senate\ProfileExaminationFindingCognitionGateway;
use PHPUnit\Framework\TestCase;
final class ModelBoundProfileSenatorFindingServiceTest extends TestCase
{
 public function testSealsIndependentFindingsAndPreservesMandatorySecurityBlock():void
 {
  $root=sys_get_temp_dir().'/imperium-model-profile-findings-'.bin2hex(random_bytes(6));[$opening,$bindings]=$this->fixtures($root);$gateway=new class implements ProfileExaminationFindingCognitionGateway{public function find(string$j,array$a,array$e):array{$fail='security'===$j;return['attributed_defect'=>$fail?'access_restrictions':null,'disposition'=>$fail?'FAIL':'PASS','evidence_references'=>$e['available_evidence_references'],'limitations'=>[],'rationale'=>$fail?'Security restrictions require blocking resolution.':'Evidence supports this jurisdiction.','severity'=>$fail?'HIGH':'NONE','uncertainty'=>[]];}};
  try{$service=new ModelBoundProfileSenatorFindingService($root,$gateway);$readiness=null;foreach(['trust','security','usability']as$i=>$j){$result=$service->issue($opening,$j,$bindings[$i],new \DateTimeImmutable('2026-08-23T22:0'.$i.':00+00:00'));if($i<2)self::assertNull($result['readiness']);$readiness=$result['readiness'];self::assertFalse($result['finding']['peer_findings_visible_at_authorship']);self::assertFalse($result['finding']['deliberation_open']);}
   self::assertSame('PROFILE_EXAMINATION_SENATOR_FINDINGS_SEALED_PENDING_DELIBERATION_OPENING',$readiness['status']);self::assertSame(['trust','security','usability'],array_column($readiness['senator_findings'],'jurisdiction'));self::assertTrue($readiness['mandatory_security_blocking_condition']);self::assertTrue($readiness['all_finding_authorities_consumed']);self::assertTrue($readiness['deliberation_opening_authority']['authority_single_use']);foreach(['deliberation_open','reconciliation_authority_exercisable','vote_authority','aggregation_authority','senate_disposition_authority','profile_approval_authority','profile_installation_authority','profile_activation_authority','deployment_authority','execution_authority']as$f)self::assertFalse($readiness[$f]);
  }finally{$this->remove($root);}
 }
 private function fixtures(string$root):array
 {
  $openingId='model-bound-profile-finding-authority-opening-'.str_repeat('a',20);$caseId='profile-examination-case-'.str_repeat('b',20);$subject=['profile_id'=>'profile-foundry-artificer','profile_version'=>'1.1.0','content_digest'=>'sha256:'.str_repeat('c',64),'target'=>['kind'=>'seat','id'=>'foundry.artificer']];$evidence=['profile_model_binding'=>['id'=>'binding','digest'=>str_repeat('d',64)]];$authorities=[];$bindings=[];
  foreach(['trust','security','usability']as$i=>$j){$seat='senate.committee.'.$j;$bindingId='operational-seat-binding-'.substr(hash('sha256',$seat),0,20);$binding=$this->record(['schema'=>'imperium.operational-seat-binding/v1','binding_id'=>$bindingId,'instance_id'=>'imperium-test','seat'=>$seat,'manifestation_id'=>'manifestation-'.$i,'occupancy_generation'=>1,'status'=>'ACTIVE','binding_atomic'=>true,'senator_finding_authority'=>true,'execution_authority'=>false]);$turnId='model-bound-profile-evidence-turn-'.substr(hash('sha256',$j),0,20);$turn=$this->record(['schema'=>'imperium.senate-model-bound-profile-evidence-testimony-turn/v1','turn_id'=>$turnId,'instance_id'=>'imperium-test','case_id'=>$caseId,'case_digest'=>str_repeat('e',64),'senator'=>['seat'=>$seat,'binding_id'=>$bindingId,'binding_digest'=>$binding['record_digest'],'manifestation_id'=>$binding['manifestation_id'],'occupancy_generation'=>1],'jurisdiction'=>$j,'subject_profile'=>$subject,'evidence_chain'=>$evidence,'examination_rubric'=>['model_selection_provenance','access_restrictions','trust','security','usability','insufficient_evidence'],'evidentiary_response_sealed'=>true,'live_witness_questioned'=>false,'provider_invoked'=>false,'senator_finding'=>null,'senator_finding_authority_exercisable'=>false,'status'=>'PROFILE_EXAMINATION_TESTIMONY_ANSWER_SEALED_PENDING_PANEL_COMPLETION','sealed'=>true]);$this->write($root.'/var/imperium/offices/senate/occupancy/'.$bindingId.'.json',$binding);$this->write($root.'/var/imperium/offices/senate/model-bound-profile-evidence-testimony-turns/'.$turnId.'.json',$turn);$authorities[]=['jurisdiction'=>$j,'senator'=>$turn['senator'],'source_testimony_turn'=>['id'=>$turnId,'digest'=>$turn['record_digest']],'senator_finding_authority_exercisable'=>true,'senator_finding'=>null];$bindings[]=$bindingId;}
  $opening=$this->record(['schema'=>'imperium.senate-model-bound-profile-finding-authority-opening/v1','opening_id'=>$openingId,'instance_id'=>'imperium-test','case_id'=>$caseId,'case_digest'=>str_repeat('e',64),'subject_profile'=>$subject,'evidence_chain'=>$evidence,'finding_authorities'=>$authorities,'status'=>'PROFILE_EXAMINATION_FINDING_AUTHORITIES_OPENED_PENDING_SENATOR_FINDINGS','senator_finding_authority_exercisable'=>true,'senator_findings'=>[],'deliberation_open'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/offices/senate/model-bound-profile-finding-authority-openings/'.$openingId.'.json',$opening);return[$openingId,$bindings];
 }
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
