<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Senate\ModelBoundProfileEvidenceQuestioningService;
use App\Imperium\Runtime\Senate\ModelBoundProfileFindingAuthorityOpeningService;
use PHPUnit\Framework\TestCase;
final class ModelBoundProfileEvidenceAndFindingOpeningTest extends TestCase
{
 public function testSealsThreeEvidenceTurnsThenOnlyOpensIndependentFindingAuthorities():void
 {
  $root=sys_get_temp_dir().'/imperium-model-profile-evidence-'.bin2hex(random_bytes(6));[$opening,$acceptances,$bindings,$lord]=$this->fixtures($root);
  try{$service=new ModelBoundProfileEvidenceQuestioningService($root);$readiness=null;foreach($acceptances as$i=>$acceptance){$result=$service->examine($opening,$acceptance,$bindings[$i],new \DateTimeImmutable('2026-08-23T21:0'.$i.':00+00:00'));if($i<2)self::assertNull($result['readiness']);$readiness=$result['readiness'];self::assertFalse($result['turn']['live_witness_questioned']);self::assertFalse($result['turn']['provider_invoked']);self::assertNotEmpty($result['turn']['evidentiary_response']['citations']);}
   self::assertSame('PROFILE_EXAMINATION_TESTIMONY_ANSWERS_SEALED_PENDING_FINDING_AUTHORITY_OPENING',$readiness['status']);self::assertSame(['trust','security','usability'],array_column($readiness['testimony_turns'],'jurisdiction'));self::assertFalse($readiness['senator_finding_authority_exercisable']);
   $authority=$readiness['finding_authority_opening_authority']['authority_id'];$opener=new ModelBoundProfileFindingAuthorityOpeningService($root);$at=new \DateTimeImmutable('2026-08-23T21:10:00+00:00');$opened=$opener->open($readiness['readiness_id'],$authority,$lord,$at);self::assertSame($opened,$opener->open($readiness['readiness_id'],$authority,$lord,$at));self::assertSame('PROFILE_EXAMINATION_FINDING_AUTHORITIES_OPENED_PENDING_SENATOR_FINDINGS',$opened['status']);self::assertSame(['trust','security','usability'],array_column($opened['finding_authorities'],'jurisdiction'));self::assertTrue($opened['senator_finding_authority_exercisable']);self::assertSame([],$opened['senator_findings']);self::assertTrue($opened['finding_authority_opening_authority']['consumed']);foreach(['deliberation_open','senate_disposition_authority','profile_approval_authority','profile_installation_authority','profile_activation_authority','operational_qualification_authority','manifestation_assembly_authority','seat_binding_authority','credential_use_authority','provider_invocation_authority','deployment_authority','execution_authority']as$f)self::assertFalse($opened[$f]);
  }finally{$this->remove($root);}
 }
 private function fixtures(string$root):array
 {
  $caseId='profile-examination-case-'.str_repeat('a',20);$panel=['senate.committee.trust','senate.committee.security','senate.committee.usability'];$subject=['profile_id'=>'profile-foundry-artificer','profile_version'=>'1.1.0','content_digest'=>'sha256:'.str_repeat('b',64),'target'=>['kind'=>'seat','id'=>'foundry.artificer']];$evidence=['mission_authorization'=>['id'=>'mission-authorization-test','digest'=>str_repeat('c',64)],'profile_model_binding'=>['id'=>'profile-model-binding-test','digest'=>str_repeat('d',64)],'profile_model_access_attestation'=>['id'=>'profile-model-access-test','digest'=>str_repeat('e',64)]];$case=$this->record(['schema'=>'imperium.senate-model-bound-profile-examination-case/v1','case_id'=>$caseId,'instance_id'=>'imperium-test','subject_profile'=>$subject,'evidence_chain'=>$evidence,'panel'=>$panel,'examination_rubric'=>['model_selection_provenance','trust','security','usability','insufficient_evidence'],'model_binding'=>['provider_model_version'=>'openai/gpt-test@2026-08-01','configuration'=>['temperature'=>0.2]],'access_status'=>'ACCESS_AVAILABLE','access_restrictions'=>['region:us'],'status'=>'PROFILE_EXAMINATION_OPENED_PENDING_SENATOR_ACCEPTANCE','sealed'=>true]);$this->write($root.'/var/imperium/offices/senate/profile-examination-cases/'.$caseId.'.json',$case);
  $acceptances=[];$bindings=[];$authorities=[];foreach($panel as$i=>$seat){$bindingId='operational-seat-binding-'.substr(hash('sha256',$seat),0,20);$binding=$this->record(['schema'=>'imperium.operational-seat-binding/v1','binding_id'=>$bindingId,'instance_id'=>'imperium-test','seat'=>$seat,'manifestation_id'=>'manifestation-'.$i,'occupancy_generation'=>1,'status'=>'ACTIVE','binding_atomic'=>true,'senator_question_authority'=>true,'senator_finding_authority'=>true,'execution_authority'=>false]);$acceptanceId='model-bound-profile-examination-acceptance-'.substr(hash('sha256',$seat),0,20);$acceptance=$this->record(['schema'=>'imperium.senate-model-bound-profile-examination-acceptance/v1','acceptance_id'=>$acceptanceId,'instance_id'=>'imperium-test','case_id'=>$caseId,'case_digest'=>$case['record_digest'],'senator'=>['seat'=>$seat,'binding_id'=>$bindingId,'binding_digest'=>$binding['record_digest'],'manifestation_id'=>$binding['manifestation_id'],'occupancy_generation'=>1],'recipient_acceptance'=>true,'senator_question_authority'=>true,'senator_finding_authority'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/offices/senate/occupancy/'.$bindingId.'.json',$binding);$this->write($root.'/var/imperium/offices/senate/model-bound-profile-examination-commission-acceptances/'.$acceptanceId.'.json',$acceptance);$acceptances[]=$acceptanceId;$bindings[]=$bindingId;$authorities[]=['seat'=>$seat,'acceptance_id'=>$acceptanceId,'acceptance_digest'=>$acceptance['record_digest'],'senator_question_authority_exercisable'=>true,'senator_finding_authority'=>false,'senator_finding_authority_exercisable'=>false];}
  $openingId='model-bound-profile-examination-testimony-opening-'.str_repeat('f',20);$opening=$this->record(['schema'=>'imperium.senate-model-bound-profile-examination-testimony-opening/v1','opening_id'=>$openingId,'instance_id'=>'imperium-test','case_id'=>$caseId,'case_digest'=>$case['record_digest'],'subject_profile'=>$subject,'evidence_chain'=>$evidence,'question_authorities'=>$authorities,'status'=>'PROFILE_EXAMINATION_TESTIMONY_OPENED_PENDING_SENATOR_QUESTIONING','testimony_open'=>true,'senator_question_authority_exercisable'=>true,'senator_finding_authority'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/offices/senate/model-bound-profile-examination-testimony-openings/'.$openingId.'.json',$opening);$lord='operational-seat-binding-'.str_repeat('1',20);$this->write($root.'/var/imperium/offices/senate/occupancy/'.$lord.'.json',$this->record(['schema'=>'imperium.operational-seat-binding/v1','binding_id'=>$lord,'instance_id'=>'imperium-test','seat'=>'senate.lord-speaker','manifestation_id'=>'manifestation-lord-speaker','occupancy_generation'=>1,'status'=>'ACTIVE','binding_atomic'=>true,'profile_examination_finding_phase_opening_authority'=>true,'execution_authority'=>false]));return[$openingId,$acceptances,$bindings,$lord];
 }
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
