<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Senate\ModelBoundProfileExaminationCommissionAcceptanceService;
use App\Imperium\Runtime\Senate\ModelBoundProfileExaminationTestimonyOpeningService;
use PHPUnit\Framework\TestCase;

final class ModelBoundProfileExaminationPanelAndTestimonyTest extends TestCase
{
 public function testAcceptsExactPanelThenSeparatelyConsumesTestimonyOpeningAuthority():void
 {
  $root=sys_get_temp_dir().'/imperium-model-profile-panel-'.bin2hex(random_bytes(6));[$commissions,$bindings,$lordSpeaker]=$this->fixtures($root);
  try{$acceptor=new ModelBoundProfileExaminationCommissionAcceptanceService($root);$readiness=null;foreach($commissions as$i=>$commission){$result=$acceptor->accept($commission,$bindings[$i],new \DateTimeImmutable('2026-08-23T20:0'.$i.':00+00:00'));if($i<2)self::assertNull($result['panel_readiness']);$readiness=$result['panel_readiness'];}
   self::assertIsArray($readiness);self::assertSame('PROFILE_EXAMINATION_PANEL_ACCEPTED_PENDING_TESTIMONY_OPENING',$readiness['status']);self::assertTrue($readiness['panel_ready']);self::assertFalse($readiness['testimony_open']);self::assertFalse($readiness['senator_question_authority_exercisable']);self::assertSame(['senate.committee.trust','senate.committee.security','senate.committee.usability'],array_column($readiness['accepted_panel'],'seat'));
   $authority=$readiness['testimony_opening_authority']['authority_id'];$opener=new ModelBoundProfileExaminationTestimonyOpeningService($root);$at=new \DateTimeImmutable('2026-08-23T20:10:00+00:00');$opening=$opener->open($readiness['readiness_id'],$authority,$lordSpeaker,$at);self::assertSame($opening,$opener->open($readiness['readiness_id'],$authority,$lordSpeaker,$at));self::assertSame('PROFILE_EXAMINATION_TESTIMONY_OPENED_PENDING_SENATOR_QUESTIONING',$opening['status']);self::assertTrue($opening['testimony_open']);self::assertTrue($opening['senator_question_authority_exercisable']);self::assertCount(3,$opening['question_authorities']);self::assertTrue($opening['testimony_opening_authority']['consumed']);self::assertFalse($opening['testimony_opening_authority']['continuing_authority']);
   foreach(['deliberation_open','senator_finding_authority','senator_finding_authority_exercisable','profile_approval_authority','profile_installation_authority','profile_activation_authority','operational_qualification_authority','manifestation_assembly_authority','seat_binding_authority','credential_use_authority','provider_invocation_authority','deployment_authority','execution_authority']as$f)self::assertFalse($opening[$f]);foreach($opening['question_authorities']as$q){self::assertTrue($q['senator_question_authority_exercisable']);self::assertFalse($q['senator_finding_authority']);}
  }finally{$this->remove($root);}
 }
 private function fixtures(string$root):array
 {
  $caseId='profile-examination-case-'.str_repeat('a',20);$panel=['senate.committee.trust','senate.committee.security','senate.committee.usability'];$subject=['profile_id'=>'profile-foundry-artificer','profile_version'=>'1.1.0','content_digest'=>'sha256:'.str_repeat('b',64),'target'=>['kind'=>'seat','id'=>'foundry.artificer']];$evidence=['mission_authorization'=>['id'=>'mission-authorization-test','digest'=>str_repeat('c',64)],'profile_model_binding'=>['id'=>'profile-model-binding-test','digest'=>str_repeat('d',64)],'profile_model_access_attestation'=>['id'=>'profile-model-access-test','digest'=>str_repeat('e',64)]];
  $case=$this->record(['schema'=>'imperium.senate-model-bound-profile-examination-case/v1','case_id'=>$caseId,'instance_id'=>'imperium-test','subject_profile'=>$subject,'evidence_chain'=>$evidence,'panel'=>$panel,'examination_rubric'=>['trust','security','usability'],'status'=>'PROFILE_EXAMINATION_OPENED_PENDING_SENATOR_ACCEPTANCE','testimony_open'=>false,'deliberation_open'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/offices/senate/profile-examination-cases/'.$caseId.'.json',$case);
  $commissions=[];$bindings=[];foreach($panel as$i=>$seat){$commissionId='profile-examination-commission-'.substr(hash('sha256',$seat),0,20);$commission=$this->record(['schema'=>'imperium.senate-model-bound-profile-examination-commission/v1','commission_id'=>$commissionId,'instance_id'=>'imperium-test','case_id'=>$caseId,'case_digest'=>$case['record_digest'],'recipient'=>['office'=>'senate','seat'=>$seat],'subject_profile'=>$subject,'evidence_chain'=>$evidence,'examination_rubric'=>$case['examination_rubric'],'status'=>'ISSUED_PENDING_SENATOR_ACCEPTANCE','recipient_acceptance'=>null,'senator_question_authority'=>true,'senator_question_authority_exercisable'=>false,'senator_finding_authority'=>false,'senator_finding_authority_exercisable'=>false,'sealed'=>true]);$bindingId='operational-seat-binding-'.substr(hash('sha256',$seat),0,20);$binding=$this->record(['schema'=>'imperium.operational-seat-binding/v1','binding_id'=>$bindingId,'instance_id'=>'imperium-test','seat'=>$seat,'manifestation_id'=>'manifestation-'.$i,'occupancy_generation'=>1,'status'=>'ACTIVE','binding_atomic'=>true,'senator_question_authority'=>true,'senator_finding_authority'=>true,'execution_authority'=>false]);$this->write($root.'/var/imperium/offices/senate/profile-examination-commission-inbox/'.$commissionId.'.json',$commission);$this->write($root.'/var/imperium/offices/senate/occupancy/'.$bindingId.'.json',$binding);$commissions[]=$commissionId;$bindings[]=$bindingId;}
  $lord='operational-seat-binding-'.str_repeat('f',20);$this->write($root.'/var/imperium/offices/senate/occupancy/'.$lord.'.json',$this->record(['schema'=>'imperium.operational-seat-binding/v1','binding_id'=>$lord,'instance_id'=>'imperium-test','seat'=>'senate.lord-speaker','manifestation_id'=>'manifestation-lord-speaker','occupancy_generation'=>1,'status'=>'ACTIVE','binding_atomic'=>true,'profile_examination_testimony_opening_authority'=>true,'execution_authority'=>false]));return[$commissions,$bindings,$lord];
 }
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
