<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Senate\ModelBoundProfileDeliberationOpeningService;
use PHPUnit\Framework\TestCase;
final class ModelBoundProfileDeliberationOpeningServiceTest extends TestCase
{
 public function testAdmitsExactFindingsAndOpensOnlyReconciliation():void
 {
  $root=sys_get_temp_dir().'/imperium-model-profile-deliberation-'.bin2hex(random_bytes(6));[$readiness,$authority,$lord]=$this->fixtures($root);
  try{$service=new ModelBoundProfileDeliberationOpeningService($root);$at=new \DateTimeImmutable('2026-08-23T23:00:00+00:00');$opened=$service->open($readiness,$authority,$lord,$at);self::assertSame($opened,$service->open($readiness,$authority,$lord,$at));self::assertSame('PROFILE_EXAMINATION_DELIBERATION_OPENED_PENDING_RECONCILIATION',$opened['status']);self::assertTrue($opened['deliberation_open']);self::assertTrue($opened['reconciliation_authority_exercisable']);self::assertTrue($opened['mandatory_security_blocking_condition']);self::assertCount(3,$opened['admitted_findings']);self::assertSame(['trust','security','usability'],array_column($opened['admitted_findings'],'jurisdiction'));self::assertTrue($opened['reconciliation_authority']['security_block_must_be_preserved']);foreach(['vote_authority','aggregation_authority','senate_disposition_authority','profile_approval_authority','profile_installation_authority','profile_activation_authority','operational_qualification_authority','manifestation_assembly_authority','seat_binding_authority','credential_use_authority','provider_invocation_authority','deployment_authority','execution_authority']as$f)self::assertFalse($opened[$f]);}
  finally{$this->remove($root);}
 }
 private function fixtures(string$root):array
 {
  $caseId='profile-examination-case-'.str_repeat('a',20);$subject=['profile_id'=>'profile-foundry-artificer','profile_version'=>'1.1.0','content_digest'=>'sha256:'.str_repeat('b',64),'target'=>['kind'=>'seat','id'=>'foundry.artificer']];$refs=[];foreach(['trust','security','usability']as$j){$security='security'===$j;$id='model-bound-profile-senator-finding-'.substr(hash('sha256',$j),0,20);$finding=$this->record(['schema'=>'imperium.senate-model-bound-profile-senator-finding/v1','finding_id'=>$id,'instance_id'=>'imperium-test','case_id'=>$caseId,'case_digest'=>str_repeat('c',64),'jurisdiction'=>$j,'decision'=>['attributed_defect'=>$security?'access_restrictions':null,'disposition'=>$security?'FAIL':'PASS','evidence_references'=>['evidence-'.$j],'limitations'=>[],'rationale'=>'Finding rationale.','severity'=>$security?'HIGH':'NONE','uncertainty'=>[]],'mandatory_security_blocking_condition'=>$security,'senator_finding_authority_consumed'=>true,'deliberation_open'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/offices/senate/model-bound-profile-senator-findings/'.$id.'.json',$finding);$refs[]=['jurisdiction'=>$j,'finding_id'=>$id,'finding_digest'=>$finding['record_digest'],'disposition'=>$finding['decision']['disposition'],'severity'=>$finding['decision']['severity'],'mandatory_security_blocking_condition'=>$security];}
  $authority='model-bound-profile-deliberation-opening-authority-'.str_repeat('d',20);$readinessId='model-bound-profile-finding-readiness-'.str_repeat('e',20);$readiness=$this->record(['schema'=>'imperium.senate-model-bound-profile-finding-readiness/v1','readiness_id'=>$readinessId,'instance_id'=>'imperium-test','case_id'=>$caseId,'case_digest'=>str_repeat('c',64),'subject_profile'=>$subject,'senator_findings'=>$refs,'mandatory_security_blocking_condition'=>true,'deliberation_opening_authority'=>['authority_id'=>$authority,'authority_single_use'=>true,'lord_speaker_consumption_required'=>true,'status'=>'OPEN_PENDING_DELIBERATION_OPENING'],'status'=>'PROFILE_EXAMINATION_SENATOR_FINDINGS_SEALED_PENDING_DELIBERATION_OPENING','all_finding_authorities_consumed'=>true,'deliberation_open'=>false,'sealed'=>true]);$this->write($root.'/var/imperium/offices/senate/model-bound-profile-finding-readiness/'.$readinessId.'.json',$readiness);$lord='operational-seat-binding-'.str_repeat('f',20);$this->write($root.'/var/imperium/offices/senate/occupancy/'.$lord.'.json',$this->record(['schema'=>'imperium.operational-seat-binding/v1','binding_id'=>$lord,'instance_id'=>'imperium-test','seat'=>'senate.lord-speaker','manifestation_id'=>'manifestation-lord-speaker','occupancy_generation'=>1,'status'=>'ACTIVE','binding_atomic'=>true,'profile_examination_deliberation_opening_authority'=>true,'execution_authority'=>false]));return[$readinessId,$authority,$lord];
 }
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
