<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Senate\ModelBoundProfileExaminationOpeningService;
use PHPUnit\Framework\TestCase;

final class ModelBoundProfileExaminationOpeningServiceTest extends TestCase
{
 public function testOpensExactThreeSeatExaminationWithoutQuestionFindingOrDownstreamAuthority():void
 {
  $root=sys_get_temp_dir().'/imperium-model-profile-examination-'.bin2hex(random_bytes(6));[$attestationId,$lordSpeakerId]=$this->fixtures($root,'ACCESS_AVAILABLE');
  try{$service=new ModelBoundProfileExaminationOpeningService($root);$at=new \DateTimeImmutable('2026-08-23T20:00:00+00:00');$opened=$service->open($attestationId,$lordSpeakerId,$at);self::assertSame($opened,$service->open($attestationId,$lordSpeakerId,$at->modify('+1 minute')));$case=$opened['case'];
   self::assertSame('PROFILE_EXAMINATION_OPENED_PENDING_SENATOR_ACCEPTANCE',$case['status']);self::assertSame(['senate.committee.trust','senate.committee.security','senate.committee.usability'],$case['panel']);self::assertSame('profile-foundry-artificer',$case['subject_profile']['profile_id']);self::assertSame('1.1.0',$case['subject_profile']['profile_version']);self::assertSame('openai/gpt-test@2026-08-01',$case['model_binding']['provider_model_version']);self::assertSame(['region:us'],$case['access_restrictions']);self::assertCount(3,$opened['commissions']);self::assertSame($case['panel'],array_column(array_column($opened['commissions'],'recipient'),'seat'));
   foreach(['testimony_open','deliberation_open','senator_question_authority_exercisable','senator_finding_authority_exercisable','profile_approval_authority','profile_installation_authority','profile_activation_authority','credential_use_authority','provider_invocation_authority','deployment_authority','execution_authority']as$f)self::assertFalse($case[$f]);
   foreach($opened['commissions']as$c){self::assertSame('ISSUED_PENDING_SENATOR_ACCEPTANCE',$c['status']);self::assertTrue($c['senator_question_authority']);foreach(['senator_question_authority_exercisable','senator_finding_authority','senator_finding_authority_exercisable','profile_approval_authority','profile_installation_authority','profile_activation_authority','credential_use_authority','provider_invocation_authority','deployment_authority','execution_authority']as$f)self::assertFalse($c[$f]);}
  }finally{$this->remove($root);}
 }
 public function testUnavailableAccessReturnsToCuriaInsteadOfOpeningExamination():void
 {
  $root=sys_get_temp_dir().'/imperium-model-profile-examination-'.bin2hex(random_bytes(6));[$attestationId,$lordSpeakerId]=$this->fixtures($root,'ACCESS_UNAVAILABLE');
  try{$this->expectExceptionMessage('S244_MODEL_BOUND_PROFILE_EXAMINATION_CHAIN_INVALID');(new ModelBoundProfileExaminationOpeningService($root))->open($attestationId,$lordSpeakerId,new \DateTimeImmutable('2026-08-23T20:00:00+00:00'));}finally{$this->remove($root);}
 }
 private function fixtures(string$root,string$status):array
 {
  $authorizationId='mission-authorization-'.str_repeat('a',20);$bindingId='profile-model-binding-'.str_repeat('b',20);$attestationId='profile-model-access-attestation-'.str_repeat('c',20);$lordSpeakerId='operational-seat-binding-'.str_repeat('d',20);
  $profile=$this->profile(['contract_version'=>'1.0.0','profile_id'=>'profile-foundry-artificer','profile_version'=>'1.1.0','artifact_class'=>'officer','source_persona'=>['persona_id'=>'persona-artificer','persona_version'=>'1.0.0','persona_digest'=>'sha256:'.str_repeat('e',64),'admission_state'=>'admitted','evidence_record'=>'evidence-artificer'],'steward'=>['kind'=>'office','id'=>'foundry'],'target'=>['kind'=>'seat','id'=>'foundry.artificer'],'transformation'=>['case_id'=>'case-artificer','specification_version'=>'1.0.0','alchemist_disposition_id'=>'disposition-artificer'],'cognitive_payload'=>['role'=>'Artificer'],'model_binding'=>['provider_model_version'=>'openai/gpt-test@2026-08-01','authorization_id'=>$authorizationId,'source_line'=>['line_number'=>5,'line_digest'=>str_repeat('f',64)],'configuration'=>['temperature'=>0.2],'constraints'=>['No silent substitution.'],'fallbacks'=>['Return to Curia.'],'access_assertion_required'=>true],'qualification_contract'=>['contract_id'=>'qualification-artificer','criteria'=>['Preserve provenance.']],'limitations'=>['No execution authority.'],'lineage'=>['derived_from'=>'persona-artificer@1.0.0','supersedes'=>['profile_id'=>'profile-foundry-artificer','profile_version'=>'1.0.0','content_digest'=>'sha256:'.str_repeat('1',64)]],'digest_spec'=>['algorithm'=>'sha256','canonicalization'=>'rfc8785','omitted_fields'=>['content_digest']]]);
  $authorization=$this->record(['schema'=>'imperium.mission-authorization/v1','authorization_id'=>$authorizationId,'instance_id'=>'imperium-test','authority_source'=>['dossier'=>['id'=>'planning-dossier-test','version'=>1,'digest'=>str_repeat('2',64)],'imperator_review'=>['id'=>'imperator-review-test','digest'=>str_repeat('3',64)]],'authorized_dossier_lines'=>[['line_number'=>5,'line_digest'=>str_repeat('f',64),'section'=>'proposed_model_binding','text'=>'Approved exact model binding.']],'status'=>'MISSION_AUTHORIZATION_SEALED_PENDING_AUTHORIZED_PREPARATION','sealed'=>true]);
  $binding=$this->record(['schema'=>'imperium.conscription-profile-model-binding/v1','binding_id'=>$bindingId,'sealed_profile'=>$profile,'status'=>'PROFILE_MODEL_BINDING_SEALED_PENDING_ACCESS_AND_ACTIVATION_PREPARATION','sealed'=>true]);
  $attestation=$this->record(['schema'=>'imperium.clavium-profile-model-access-attestation/v1','attestation_id'=>$attestationId,'instance_id'=>'imperium-test','mission_authorization'=>['id'=>$authorizationId,'digest'=>$authorization['record_digest']],'sealed_profile'=>['profile_id'=>$profile['profile_id'],'profile_version'=>$profile['profile_version'],'content_digest'=>$profile['content_digest'],'target'=>$profile['target']],'model_binding'=>['binding_id'=>$bindingId,'binding_digest'=>$binding['record_digest'],'provider_model_version'=>'openai/gpt-test@2026-08-01'],'provider_access_evidence'=>['assertion_id'=>'clavium-provider-access-test','assertion_digest'=>'sha256:'.str_repeat('4',64),'provider'=>'openai','issuer'=>['office'=>'clavium','officer'=>'locksmith'],'observed_at'=>'2026-08-23T18:00:00+00:00','expires_at'=>'2026-08-24T18:00:00+00:00'],'status'=>$status,'restrictions'=>['region:us'],'credential_released'=>false,'provider_invocation_authority'=>false,'profile_approval_authority'=>false,'execution_authority'=>false,'checkpoint'=>'PROFILE_MODEL_ACCESS_ATTESTED_PENDING_APPROVAL_AND_ACTIVATION','sealed'=>true]);
  $lordSpeaker=$this->record(['schema'=>'imperium.operational-seat-binding/v1','binding_id'=>$lordSpeakerId,'instance_id'=>'imperium-test','seat'=>'senate.lord-speaker','manifestation_id'=>'manifestation-lord-speaker','occupancy_generation'=>1,'status'=>'ACTIVE','binding_atomic'=>true,'senate_disposition_authority'=>true,'execution_authority'=>false]);
  $this->write($root.'/var/imperium/authorizations/missions/'.$authorizationId.'.json',$authorization);$this->write($root.'/var/imperium/offices/conscription/profile-model-bindings/'.$bindingId.'.json',$binding);$this->write($root.'/var/imperium/offices/clavium/profile-model-access-attestations/'.$attestationId.'.json',$attestation);$this->write($root.'/var/imperium/offices/senate/occupancy/'.$lordSpeakerId.'.json',$lordSpeaker);return[$attestationId,$lordSpeakerId];
 }
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function profile(array$r):array{$r['content_digest']='sha256:'.hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
