<?php

declare(strict_types=1);

namespace App\Tests\Imperium\Runtime;

use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Curia\ModelRequirementCommissionService;
use App\Imperium\Runtime\Curia\DefaultModelFallbackOrderService;
use App\Imperium\Runtime\Oracle\ModelRequirementCommissionAcceptanceService;
use App\Imperium\Runtime\Oracle\ModelEvaluationCaseOpeningService;
use App\Imperium\Runtime\Oracle\ModelEligibilityFindingService;
use App\Imperium\Runtime\Oracle\ModelComparativeAssessmentService;
use PHPUnit\Framework\TestCase;

final class ModelRequirementCommissionFlowTest extends TestCase
{
    public function testCuriaIssuesExactCriteriaAndOracleAcceptsWithoutEvaluationOrSelection():void
    {
        $root=sys_get_temp_dir().'/imperium-model-requirement-'.bin2hex(random_bytes(6));$issued=new \DateTimeImmutable('2026-08-23T12:00:00+00:00');
        try{
            $snapshot=$this->snapshot();$seneschal=$this->seneschal();$augur=$this->augur();
            $this->write($root.'/var/imperium/offices/oracle/model-intelligence-snapshots/'.$snapshot['snapshot_id'].'.json',$snapshot);$this->write($root.'/var/imperium/offices/curia/occupancy/'.$seneschal['binding_id'].'.json',$seneschal);$this->write($root.'/var/imperium/offices/oracle/occupancy/'.$augur['binding_id'].'.json',$augur);
            $service=new ModelRequirementCommissionService($root);$commission=$service->issue($snapshot['snapshot_id'],$seneschal['binding_id'],$this->target(),$this->criteria(),$issued,$issued->modify('+1 day'));
            self::assertSame($commission,$service->issue($snapshot['snapshot_id'],$seneschal['binding_id'],$this->target(),$this->criteria(),$issued,$issued->modify('+1 day')));self::assertSame('ISSUED_PENDING_ORACLE_ACCEPTANCE',$commission['status']);self::assertSame($snapshot['record_digest'],$commission['catalogue_snapshot']['digest']);self::assertArrayNotHasKey('preferred_model',$commission);self::assertSame('SILENT_SUBSTITUTION_PROHIBITED',$commission['criteria']['substitution_policy']);
            $acceptance=(new ModelRequirementCommissionAcceptanceService($root))->accept($commission['commission_id'],$augur['binding_id'],$issued->modify('+1 minute'));
            self::assertSame($acceptance,(new ModelRequirementCommissionAcceptanceService($root))->accept($commission['commission_id'],$augur['binding_id'],$issued->modify('+2 minutes')));
            self::assertSame('CURIA_MODEL_REQUIREMENT_COMMISSION_ACCEPTED_PENDING_ORACLE_EVALUATION',$acceptance['status']);self::assertSame($commission['criteria'],$acceptance['criteria']);self::assertSame($commission['target'],$acceptance['target']);
            self::assertTrue($acceptance['evaluation_case_opening_authority']);
            foreach(['criteria_reinterpretation_authority','scope_expansion_authority','evaluation_authority','research_authority','recommendation_authority','selection_authority','model_assignment_authority','profile_mutation_authority','provider_invocation_authority','deployment_authority','execution_authority']as$a)self::assertFalse($acceptance[$a]);
            $opener=new ModelEvaluationCaseOpeningService($root);$case=$opener->open($acceptance['acceptance_id'],$augur['binding_id'],$issued->modify('+3 minutes'));
            self::assertSame($case,$opener->open($acceptance['acceptance_id'],$augur['binding_id'],$issued->modify('+4 minutes')));self::assertSame('ORACLE_MODEL_EVALUATION_CASE_OPENED_PENDING_AUGUR_ELIGIBILITY_FINDINGS',$case['status']);self::assertSame(['openai/gpt-test@2026-08-01'],$case['included_candidates']);self::assertTrue($case['candidate_universe_frozen']);self::assertTrue($case['evaluation_case_opening_authority_consumed']);self::assertFalse($case['continuing_case_opening_authority']);
            self::assertContains('ACCESS_NOT_AVAILABLE',$case['excluded_candidates']['anthropic/claude-test@2026-08-01']['reason_codes']);self::assertContains('PROVIDER_NOT_PERMITTED',$case['excluded_candidates']['mistral/mistral-test@2026-08-01']['reason_codes']);self::assertContains('NOT_ADMISSIBLE',$case['excluded_candidates']['mistral/mistral-test@2026-08-01']['reason_codes']);
            $authority=$case['eligibility_authorities']['openai/gpt-test@2026-08-01'];self::assertTrue($authority['eligibility_finding_authority']);self::assertSame(['source-a','source-b'],$authority['source_ids']);
            foreach(['recommendation_authority','ranking_authority','selection_authority','model_assignment_authority','provider_invocation_authority','execution_authority']as$a)self::assertFalse($authority[$a]);
            foreach(['recommendation_authority','ranking_authority','selection_authority','model_assignment_authority','profile_mutation_authority','provider_invocation_authority','deployment_authority','execution_authority']as$a)self::assertFalse($case[$a]);
            $findingService=new ModelEligibilityFindingService($root);$finding=$findingService->issue($case['case_id'],$authority['authority_id'],$augur['binding_id'],'ELIGIBLE',$this->criterionFindings('SATISFIED'),['source-a','source-b'],['claim-a'],[],$issued->modify('+5 minutes'));
            self::assertSame($finding,$findingService->issue($case['case_id'],$authority['authority_id'],$augur['binding_id'],'ELIGIBLE',$this->criterionFindings('SATISFIED'),['source-a','source-b'],['claim-a'],[],$issued->modify('+6 minutes')));self::assertTrue($finding['eligibility_finding_authority_consumed']);self::assertFalse($finding['continuing_finding_authority']);self::assertSame('ORACLE_MODEL_ELIGIBILITY_FINDING_SEALED_NO_SELECTION_AUTHORITY',$finding['status']);
            $phase=$this->onlyRecord($root.'/var/imperium/offices/oracle/model-eligibility-phases');self::assertSame('ORACLE_ELIGIBILITY_FINDINGS_COMPLETE_PENDING_COMPARATIVE_ASSESSMENT',$phase['status']);self::assertSame(['openai/gpt-test@2026-08-01'],$phase['eligible_models']);self::assertTrue($phase['comparative_assessment_authority']);foreach(['ranking_authority','recommendation_authority','selection_authority','model_assignment_authority','profile_mutation_authority','provider_invocation_authority','deployment_authority','execution_authority']as$a)self::assertFalse($phase[$a]);
            $comparisonService=new ModelComparativeAssessmentService($root);$comparison=$comparisonService->seal($phase['phase_id'],$augur['binding_id'],$this->comparisonMatrix(),$issued->modify('+7 minutes'));self::assertSame($comparison,$comparisonService->seal($phase['phase_id'],$augur['binding_id'],[],$issued->modify('+8 minutes')));self::assertSame('ORACLE_COMPARATIVE_ASSESSMENT_SEALED_PENDING_AUGUR_RECOMMENDATION',$comparison['status']);self::assertTrue($comparison['comparative_assessment_authority_consumed']);self::assertFalse($comparison['continuing_comparative_assessment_authority']);self::assertNull($comparison['aggregate_score']);self::assertNull($comparison['ordinal_ranking']);self::assertNull($comparison['winner']);self::assertNull($comparison['preferred_candidate']);self::assertTrue($comparison['recommendation_authority']['recommendation_authority']);self::assertTrue($comparison['recommendation_authority']['authority_single_use']);self::assertSame(['openai/gpt-test@2026-08-01'],$comparison['recommendation_authority']['candidate_models']);foreach(['ranking_authority','selection_authority','model_assignment_authority','profile_mutation_authority','provider_invocation_authority','deployment_authority','execution_authority']as$a)self::assertFalse($comparison[$a]);
        }finally{$this->remove($root);}
    }

    public function testNoEligibleModelReturnsToCuriaForExplicitDefaultFallbackOrder():void
    {
        $root=sys_get_temp_dir().'/imperium-model-fallback-'.bin2hex(random_bytes(6));$issued=new \DateTimeImmutable('2026-08-23T12:00:00+00:00');
        try{$snapshot=$this->snapshot();$seneschal=$this->seneschal();$augur=$this->augur();$this->write($root.'/var/imperium/offices/oracle/model-intelligence-snapshots/'.$snapshot['snapshot_id'].'.json',$snapshot);$this->write($root.'/var/imperium/offices/curia/occupancy/'.$seneschal['binding_id'].'.json',$seneschal);$this->write($root.'/var/imperium/offices/oracle/occupancy/'.$augur['binding_id'].'.json',$augur);$commission=(new ModelRequirementCommissionService($root))->issue($snapshot['snapshot_id'],$seneschal['binding_id'],$this->target(),$this->criteria(),$issued,$issued->modify('+1 day'));$acceptance=(new ModelRequirementCommissionAcceptanceService($root))->accept($commission['commission_id'],$augur['binding_id'],$issued->modify('+1 minute'));$case=(new ModelEvaluationCaseOpeningService($root))->open($acceptance['acceptance_id'],$augur['binding_id'],$issued->modify('+2 minutes'));$authority=$case['eligibility_authorities']['openai/gpt-test@2026-08-01'];$criteria=$this->criterionFindings('SATISFIED');$criteria['reliability']=['disposition'=>'FAILED','rationale'=>'Observed reliability is below the commissioned threshold.'];
            (new ModelEligibilityFindingService($root))->issue($case['case_id'],$authority['authority_id'],$augur['binding_id'],'INELIGIBLE',$criteria,['source-a','source-b'],['claim-a'],['MINIMUM_RELIABILITY_NOT_MET'],$issued->modify('+3 minutes'));$phase=$this->onlyRecord($root.'/var/imperium/offices/oracle/model-eligibility-phases');self::assertTrue($phase['no_eligible_model']);self::assertSame('ORACLE_NO_ELIGIBLE_MODEL_PENDING_CURIA_FALLBACK_ORDER',$phase['status']);self::assertFalse($phase['comparative_assessment_authority']);
            $orders=new DefaultModelFallbackOrderService($root);$order=$orders->issue($phase['phase_id'],$seneschal['binding_id'],'openai/gpt-test@2026-08-01','Mission necessity requires the declared default while Curia accepts the recorded deficiency.',['MINIMUM_RELIABILITY_NOT_MET'],$issued->modify('+4 minutes'));self::assertSame($order,$orders->issue($phase['phase_id'],$seneschal['binding_id'],'openai/gpt-test@2026-08-01','ignored on idempotent replay',[],$issued->modify('+5 minutes')));self::assertSame('INELIGIBLE',$order['oracle_disposition']);self::assertFalse($order['eligibility_override']);self::assertTrue($order['fallback_verification_authority']);self::assertSame('CURIA_DEFAULT_MODEL_FALLBACK_ORDER_ISSUED_PENDING_ORACLE_VERIFICATION',$order['status']);foreach(['ranking_authority','recommendation_authority','selection_authority','model_assignment_authority','profile_mutation_authority','provider_invocation_authority','deployment_authority','execution_authority']as$a)self::assertFalse($order[$a]);
        }finally{$this->remove($root);}
    }

    public function testOracleRejectsAcceptanceWhenPinnedSnapshotChanges():void
    {
        $root=sys_get_temp_dir().'/imperium-model-requirement-invalid-'.bin2hex(random_bytes(6));$issued=new \DateTimeImmutable('2026-08-23T12:00:00+00:00');
        try{$snapshot=$this->snapshot();$seneschal=$this->seneschal();$augur=$this->augur();$this->write($root.'/var/imperium/offices/oracle/model-intelligence-snapshots/'.$snapshot['snapshot_id'].'.json',$snapshot);$this->write($root.'/var/imperium/offices/curia/occupancy/'.$seneschal['binding_id'].'.json',$seneschal);$this->write($root.'/var/imperium/offices/oracle/occupancy/'.$augur['binding_id'].'.json',$augur);$commission=(new ModelRequirementCommissionService($root))->issue($snapshot['snapshot_id'],$seneschal['binding_id'],$this->target(),$this->criteria(),$issued,$issued->modify('+1 day'));$snapshot['models']['openai/gpt-test@2026-08-01']['admissibility']['status']='INADMISSIBLE';$snapshot=$this->digest($snapshot);$this->write($root.'/var/imperium/offices/oracle/model-intelligence-snapshots/'.$snapshot['snapshot_id'].'.json',$snapshot);
            $this->expectException(\RuntimeException::class);$this->expectExceptionMessage('OR43_MODEL_REQUIREMENT_ACCEPTANCE_CHAIN_INVALID');(new ModelRequirementCommissionAcceptanceService($root))->accept($commission['commission_id'],$augur['binding_id'],$issued->modify('+1 minute'));
        }finally{$this->remove($root);}
    }

    private function target():array{return['type'=>'OFFICE_SEAT','id'=>'foundry.artificer','mission_id'=>null];}
    private function criterionFindings(string$disposition):array{$out=[];foreach($this->criteria()['evaluation_rubric']as$c)$out[$c]=['disposition'=>$disposition,'rationale'=>'Catalogue evidence answers the commissioned criterion.'];return$out;}
    private function comparisonMatrix():array{$cell=['observation'=>'The sealed evidence satisfies the commissioned criterion under its recorded operating conditions.','evidence_strength'=>'HIGH','source_ids'=>['source-a','source-b'],'claim_ids'=>['claim-a'],'limitations'=>['Bound to the frozen catalogue snapshot.'],'contradictions'=>[]];$out=[];foreach($this->criteria()['evaluation_rubric']as$c)$out[$c]=['openai/gpt-test@2026-08-01'=>$cell];return$out;}
    private function onlyRecord(string$dir):array{$files=glob($dir.'/*.json')?:[];self::assertCount(1,$files);return json_decode((string)file_get_contents($files[0]),true,512,JSON_THROW_ON_ERROR);}
    private function criteria():array{return['cognitive_task'=>'Construct attributable Persona artifacts.','required_capabilities'=>['structured-output','long-context'],'prohibited_capabilities'=>['autonomous-tool-use'],'required_tools'=>[],'minimum_context_tokens'=>64000,'data_classification'=>'INTERNAL','data_residency'=>'ANY_APPROVED_REGION','permitted_providers'=>['openai','anthropic'],'max_cost_per_million_tokens'=>25,'max_latency_ms'=>15000,'minimum_reliability'=>0.99,'fallback_policy'=>'Return to Curia if no candidate qualifies.','substitution_policy'=>'SILENT_SUBSTITUTION_PROHIBITED','evaluation_rubric'=>['capability-fit','reliability','cost','latency','risk'],'minimum_evidence_sources'=>2];}
    private function snapshot():array{$sources=['source-a'=>['source_id'=>'source-a'],'source-b'=>['source_id'=>'source-b']];return$this->digest(['schema'=>'imperium.oracle-model-intelligence-snapshot/v1','snapshot_id'=>'oracle-model-intelligence-'.str_repeat('a',20),'snapshot_generation'=>1,'prior_snapshot'=>null,'instance_id'=>'imperium-test','steward'=>'oracle','actor'=>['office'=>'oracle','seat'=>'oracle.augur'],'models'=>['openai/gpt-test@2026-08-01'=>['provider'=>'openai','knowledge'=>['sources'=>$sources,'claims'=>['claim-a'=>['claim_id'=>'claim-a']]],'accessibility'=>['status'=>'ACCESSIBLE'],'admissibility'=>['status'=>'ADMISSIBLE']],'anthropic/claude-test@2026-08-01'=>['provider'=>'anthropic','knowledge'=>['sources'=>$sources,'claims'=>[]],'accessibility'=>['status'=>'UNAVAILABLE'],'admissibility'=>['status'=>'ADMISSIBLE']],'mistral/mistral-test@2026-08-01'=>['provider'=>'mistral','knowledge'=>['sources'=>['source-c'=>['source_id'=>'source-c']],'claims'=>[]],'accessibility'=>['status'=>'ACCESSIBLE'],'admissibility'=>['status'=>'INADMISSIBLE']]],'classification_dimensions'=>['knowledge','accessibility','admissibility'],'status'=>'ORACLE_CANONICAL_CATALOGUE_SNAPSHOT_SEALED_NO_SELECTION_AUTHORITY','model_research_authority'=>false,'selection_authority'=>false]);}
    private function seneschal():array{return$this->digest(['schema'=>'imperium.curia-seneschal-occupancy/v1','binding_id'=>'curia-seneschal-binding-'.str_repeat('b',20),'instance_id'=>'imperium-test','office'=>'curia','seat'=>'curia.seneschal','manifestation_id'=>'seneschal-manifestation','occupancy_generation'=>1,'status'=>'ACTIVE','model_requirement_commission_authority'=>true,'execution_authority'=>false]);}
    private function augur():array{return$this->digest(['schema'=>'imperium.oracle-augur-occupancy/v1','binding_id'=>'oracle-augur-binding-'.str_repeat('c',20),'instance_id'=>'imperium-test','office'=>'oracle','seat'=>'oracle.augur','manifestation_id'=>'augur-manifestation','occupancy_generation'=>1,'status'=>'ORACLE_AUGUR_BOUND_ACTIVE_NO_MODEL_SELECTION_AUTHORITY','model_requirement_commission_acceptance_authority'=>true,'selection_authority'=>false]);}
    private function digest(array$r):array{unset($r['record_digest']);$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}
    private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
