<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Curia\OperationalAdoptionIndependentAssessmentService;
use PHPUnit\Framework\TestCase;
final class OperationalAdoptionIndependentAssessmentServiceTest extends TestCase
{
 public function testSealsMutuallyHiddenAssessmentsThenDigestOnlyCompletion():void{$root=sys_get_temp_dir().'/imperium-assess-'.bin2hex(random_bytes(5));try{[$ready,$rows]=$this->fixtures($root);$s=new OperationalAdoptionIndependentAssessmentService($root);foreach($rows as$i=>$r){$out=$s->assess($ready,$r['jurisdiction'],$r['authority'],$r['binding'],['disposition'=>'SUPPORTS_WITH_LIMITATIONS','rationale'=>'Bounded support in this jurisdiction.','evidence_references'=>['sealed-result-digest'],'limitations'=>['No action implied.'],'uncertainties'=>[]],new \DateTimeImmutable('2026-08-24T04:00:00+00:00'));self::assertFalse($out['assessment']['sibling_assessments_disclosed']);self::assertTrue($out['assessment']['assessment_authority']['consumed']);if($i<2)self::assertNull($out['completion']);}self::assertSame('ADOPTION_INDEPENDENT_ASSESSMENTS_SEALED_PENDING_SENESCHAL_RECONCILIATION',$out['completion']['status']);self::assertCount(3,$out['completion']['assessments']);self::assertFalse($out['completion']['assessment_contents_disclosed']);self::assertFalse($out['completion']['aggregation_performed']);self::assertFalse($out['completion']['execution_authority']);}finally{$this->remove($root);}}
 public function testCurialisCannotConsumeSiblingAuthority():void{$root=sys_get_temp_dir().'/imperium-assess-wrong-'.bin2hex(random_bytes(5));try{[$ready,$rows]=$this->fixtures($root);$this->expectExceptionMessage('CUR500_INDEPENDENT_ASSESSMENT_CHAIN_INVALID');(new OperationalAdoptionIndependentAssessmentService($root))->assess($ready,$rows[0]['jurisdiction'],$rows[0]['authority'],$rows[1]['binding'],['disposition'=>'UNRESOLVED','rationale'=>'No.','evidence_references'=>['evidence'],'limitations'=>[],'uncertainties'=>['Mismatch.']],new \DateTimeImmutable());}finally{$this->remove($root);}}
 private function fixtures(string$root):array{$instance='imperium-test';$issuanceId='legate-result-adoption-assessment-issuance-'.str_repeat('a',20);$readyId='legate-result-adoption-assessment-panel-readiness-'.str_repeat('b',20);$jur=['EVIDENCE_SUFFICIENCY','MISSION_OPERATIONAL_FIT','RISK_AUTHORITY_REVERSIBILITY'];$refs=[];$rows=[];$authorities=[];$acceptanceRefs=[];foreach($jur as$i=>$j){$x=dechex($i+1);$bid='operational-seat-binding-'.str_repeat($x,20);$occ=$this->record(['binding_id'=>$bid,'instance_id'=>$instance,'seat'=>'curia.curialis.'.strtolower(str_replace('_','-',$j)),'manifestation_id'=>'m'.$i,'occupancy_generation'=>1,'officer_class'=>'DELEGATE','status'=>'ACTIVE','sealed'=>true]);$this->write($root.'/var/imperium/operational/occupancy/'.$bid.'.json',$occ);$cid='legate-result-adoption-assessment-commission-'.str_repeat(dechex($i+4),20);$commission=$this->record(['schema'=>'imperium.legate-result-adoption-assessment-commission/v1','commission_id'=>$cid,'issuance_id'=>$issuanceId,'instance_id'=>$instance,'source_evaluation_opening'=>['id'=>'opening','digest'=>str_repeat('c',64)],'jurisdiction'=>$j,'question'=>$j.'?']);$this->write($root.'/var/imperium/operational/legate-result-adoption-assessment-commissions/'.$cid.'.json',$commission);$refs[$j]=['id'=>$cid,'digest'=>$commission['record_digest']];$did='legate-result-adoption-assessment-disposition-'.str_repeat(dechex($i+7),20);$disp=$this->record(['disposition_id'=>$did,'source_commission'=>['id'=>$cid,'digest'=>$commission['record_digest']],'recipient'=>['binding_id'=>$bid],'decision'=>'ACCEPTED']);$this->write($root.'/var/imperium/operational/legate-result-adoption-assessment-commission-dispositions/'.$did.'.json',$disp);$aid='adoption-assessment-authority-'.str_repeat(dechex($i+10),20);$authorities[$j]=['authority_id'=>$aid,'recipient'=>['binding_id'=>$bid,'binding_digest'=>$occ['record_digest']],'single_use'=>true,'consumed'=>false,'exercisable'=>true];$rows[]=['jurisdiction'=>$j,'binding'=>$bid,'authority'=>$aid];}$issuance=$this->record(['issuance_id'=>$issuanceId,'instance_id'=>$instance,'commissions'=>$refs]);$this->write($root.'/var/imperium/operational/legate-result-adoption-assessment-issuances/'.$issuanceId.'.json',$issuance);$panel=$this->record(['schema'=>'imperium.legate-result-adoption-assessment-panel-readiness/v1','readiness_id'=>$readyId,'instance_id'=>$instance,'source_issuance'=>['id'=>$issuanceId,'digest'=>$issuance['record_digest']],'assessment_authorities'=>$authorities,'all_commissions_accepted'=>true,'evaluation_closed'=>false,'status'=>'ADOPTION_ASSESSMENT_PANEL_ACCEPTED_AUTHORITIES_OPENED_PENDING_INDEPENDENT_ASSESSMENTS']);$this->write($root.'/var/imperium/operational/legate-result-adoption-assessment-panel-readiness/'.$readyId.'.json',$panel);return[$readyId,$rows];}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
