<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Curia\OperationalAdoptionAssessmentCommissionDispositionService;
use PHPUnit\Framework\TestCase;
final class OperationalAdoptionAssessmentCommissionDispositionServiceTest extends TestCase
{
 public function testAuthoritiesOpenOnlyAfterAllThreeIndependentAcceptances():void{$root=sys_get_temp_dir().'/imperium-panel-'.bin2hex(random_bytes(5));try{[$ids,$bindings]=$this->fixtures($root);$s=new OperationalAdoptionAssessmentCommissionDispositionService($root);foreach($ids as$i=>$id){$r=$s->decide($id,$bindings[$i],'ACCEPTED','Accept exact jurisdiction.',new \DateTimeImmutable('2026-08-24T03:00:00+00:00'));if($i<2)self::assertNull($r['panel_readiness']);}self::assertSame('ADOPTION_ASSESSMENT_PANEL_ACCEPTED_AUTHORITIES_OPENED_PENDING_INDEPENDENT_ASSESSMENTS',$r['panel_readiness']['status']);self::assertCount(3,$r['panel_readiness']['assessment_authorities']);foreach($r['panel_readiness']['assessment_authorities']as$a){self::assertTrue($a['exercisable']);self::assertFalse($a['consumed']);}self::assertFalse($r['panel_readiness']['execution_authority']);}finally{$this->remove($root);}}
 public function testOneRefusalClosesWithoutAssessmentAuthority():void{$root=sys_get_temp_dir().'/imperium-panel-refuse-'.bin2hex(random_bytes(5));try{[$ids,$bindings]=$this->fixtures($root);$s=new OperationalAdoptionAssessmentCommissionDispositionService($root);$s->decide($ids[0],$bindings[0],'ACCEPTED','Accept.',new \DateTimeImmutable());$s->decide($ids[1],$bindings[1],'ACCEPTED','Accept.',new \DateTimeImmutable());$r=$s->decide($ids[2],$bindings[2],'REFUSED','Conflict prevents participation.',new \DateTimeImmutable());self::assertSame('ADOPTION_ASSESSMENT_PANEL_INCOMPLETE_REFUSAL_EVALUATION_CLOSED_NO_AUTHORITY',$r['panel_readiness']['status']);self::assertSame([],$r['panel_readiness']['assessment_authorities']);self::assertTrue($r['panel_readiness']['evaluation_closed']);}finally{$this->remove($root);}}
 private function fixtures(string$root):array{$instance='imperium-test';$jur=['EVIDENCE_SUFFICIENCY','MISSION_OPERATIONAL_FIT','RISK_AUTHORITY_REVERSIBILITY'];$ids=[];$bindings=[];$refs=[];$records=[];foreach($jur as$i=>$j){$bid='operational-seat-binding-'.str_repeat(dechex($i+1),20);$occ=$this->record(['binding_id'=>$bid,'instance_id'=>$instance,'seat'=>'curia.curialis.'.strtolower(str_replace('_','-',$j)),'manifestation_id'=>'m'.$i,'occupancy_generation'=>1,'officer_class'=>'DELEGATE','status'=>'ACTIVE','sealed'=>true]);$this->write($root.'/var/imperium/operational/occupancy/'.$bid.'.json',$occ);$cid='legate-result-adoption-assessment-commission-'.str_repeat(dechex($i+4),20);$records[$j]=['id'=>$cid,'binding'=>$bid,'occ'=>$occ];$ids[]=$cid;$bindings[]=$bid;}$issuanceId='legate-result-adoption-assessment-issuance-'.str_repeat('a',20);foreach($records as$j=>$x){$commission=$this->record(['schema'=>'imperium.legate-result-adoption-assessment-commission/v1','commission_id'=>$x['id'],'issuance_id'=>$issuanceId,'instance_id'=>$instance,'source_evaluation_opening'=>['id'=>'opening','digest'=>str_repeat('b',64)],'target'=>['binding_id'=>$x['binding'],'binding_digest'=>$x['occ']['record_digest']],'jurisdiction'=>$j,'status'=>'ISSUED_PENDING_CURIALIS_ACCEPTANCE','recipient_acceptance_required'=>true,'commission_exercisable'=>false,'assessment_authority'=>false]);$this->write($root.'/var/imperium/operational/legate-result-adoption-assessment-commissions/'.$x['id'].'.json',$commission);$refs[$j]=['id'=>$x['id'],'digest'=>$commission['record_digest']];}$issuance=$this->record(['schema'=>'imperium.legate-result-adoption-assessment-issuance/v1','issuance_id'=>$issuanceId,'instance_id'=>$instance,'commissions'=>$refs]);$this->write($root.'/var/imperium/operational/legate-result-adoption-assessment-issuances/'.$issuanceId.'.json',$issuance);return[$ids,$bindings];}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
