<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Curia\OperationalAdoptionDecisionOpeningService;
use PHPUnit\Framework\TestCase;
final class OperationalAdoptionDecisionOpeningServiceTest extends TestCase
{
 public function testOpensDecisionAuthorityWithoutAdoptingOrAuthorizingUse():void{$root=sys_get_temp_dir().'/imperium-adoption-decision-open-'.bin2hex(random_bytes(5));try{[$reconciliation,$seneschal]=$this->fixtures($root);$s=new OperationalAdoptionDecisionOpeningService($root);$o=$s->open($reconciliation,$seneschal,new \DateTimeImmutable('2026-08-24T07:00:00+00:00'));self::assertSame('OPERATIONAL_ADOPTION_DECISION_AUTHORITY_OPENED_PENDING_SENESCHAL_DISPOSITION',$o['status']);self::assertSame(['ADOPTED','ADOPTED_WITH_LIMITATIONS','NOT_ADOPTED','UNRESOLVED'],$o['decision_contract']['allowed_dispositions']);self::assertTrue($o['adoption_decision_authority']['exercisable']);self::assertFalse($o['adoption_decision_authority']['consumed']);self::assertFalse($o['decision_contract']['plan_amendment_authority_granted_by_disposition']);self::assertFalse($o['decision_contract']['action_authority_granted_by_disposition']);self::assertFalse($o['adoption_disposition_authored']);self::assertFalse($o['result_operationally_adopted']);self::assertFalse($o['operational_use_permitted']);self::assertFalse($o['execution_authority']);self::assertSame($o,$s->open($reconciliation,$seneschal,new \DateTimeImmutable('2026-08-24T08:00:00+00:00')));}finally{$this->remove($root);}}
 private function fixtures(string$root):array{$instance='imperium-test';$sid='operational-seat-binding-'.str_repeat('a',20);$s=$this->record(['binding_id'=>$sid,'instance_id'=>$instance,'seat'=>'curia.seneschal','manifestation_id'=>'seneschal','occupancy_generation'=>1,'status'=>'ACTIVE','sealed'=>true]);$this->write($root.'/var/imperium/operational/occupancy/'.$sid.'.json',$s);$id='legate-result-adoption-reconciliation-'.str_repeat('b',20);$r=$this->record(['schema'=>'imperium.legate-result-adoption-reconciliation/v1','reconciliation_id'=>$id,'instance_id'=>$instance,'source_reconciliation_opening'=>['id'=>'opening','digest'=>str_repeat('c',64)],'source_assessment_completion'=>['id'=>'completion','digest'=>str_repeat('d',64)],'source_panel_readiness'=>['id'=>'panel','digest'=>str_repeat('e',64)],'source_issuance'=>['id'=>'issuance','digest'=>str_repeat('f',64)],'source_evaluation_opening'=>['id'=>'evaluation','digest'=>str_repeat('1',64)],'reconciler'=>['binding_id'=>$sid,'binding_digest'=>$s['record_digest']],'result'=>['output'=>'Recommendation.'],'contract'=>['task'=>'Recommend.'],'assessment_references'=>[['id'=>'assessment','digest'=>str_repeat('2',64),'jurisdiction'=>'EVIDENCE_SUFFICIENCY']],'reconciliation'=>['summary'=>'Reconciled.'],'status'=>'ADOPTION_ASSESSMENTS_RECONCILED_NO_DISPOSITION_PENDING_ADOPTION_DECISION_OPENING','reconciliation_performed'=>true,'voting_performed'=>false,'aggregation_performed'=>false,'adoption_disposition_authored'=>false,'adoption_decision_authority'=>false,'result_operationally_adopted'=>false]);$this->write($root.'/var/imperium/operational/legate-result-adoption-reconciliations/'.$id.'.json',$r);return[$id,$sid];}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
