<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Curia\OperationalAdoptionDispositionService;
use PHPUnit\Framework\TestCase;
final class OperationalAdoptionDispositionServiceTest extends TestCase
{
 public function testAdoptionClosesLifecycleWithoutOperationalOrActionAuthority():void{$root=sys_get_temp_dir().'/imperium-adopt-'.bin2hex(random_bytes(5));try{[$opening,$authority,$seneschal]=$this->fixtures($root);$s=new OperationalAdoptionDispositionService($root);$r=$s->decide($opening,$authority,$seneschal,'ADOPTED','Curia accepts the exact result as evaluated.',[],new \DateTimeImmutable('2026-08-24T08:00:00+00:00'));self::assertSame('OPERATIONAL_ADOPTION_DISPOSITION_ADOPTED_LIFECYCLE_CLOSED_NO_ACTION_AUTHORITY',$r['status']);self::assertTrue($r['result_operationally_adopted']);self::assertTrue($r['adoption_lifecycle_closed']);self::assertTrue($r['adoption_decision_authority']['consumed']);foreach(['planning_amendment_authority','follow_up_commission_authority','provider_invocation_authority','credential_use_authority','tool_use_authority','operational_use_permitted','external_action_authority','execution_authority','continuing_turn_authority']as$f)self::assertFalse($r[$f]);self::assertSame($r,$s->decide($opening,$authority,$seneschal,'ADOPTED','Curia accepts the exact result as evaluated.',[],new \DateTimeImmutable('2026-08-24T09:00:00+00:00')));}finally{$this->remove($root);}}
 public function testConditionalAdoptionRequiresLimitations():void{$root=sys_get_temp_dir().'/imperium-adopt-limits-'.bin2hex(random_bytes(5));try{[$opening,$authority,$seneschal]=$this->fixtures($root);$this->expectExceptionMessage('CUR537_ADOPTION_DISPOSITION_INVALID');(new OperationalAdoptionDispositionService($root))->decide($opening,$authority,$seneschal,'ADOPTED_WITH_LIMITATIONS','Conditional.',[],new \DateTimeImmutable());}finally{$this->remove($root);}}
 public function testNotAdoptedClosesWithoutAuthority():void{$root=sys_get_temp_dir().'/imperium-not-adopt-'.bin2hex(random_bytes(5));try{[$opening,$authority,$seneschal]=$this->fixtures($root);$r=(new OperationalAdoptionDispositionService($root))->decide($opening,$authority,$seneschal,'NOT_ADOPTED','Curia declines adoption.',[],new \DateTimeImmutable());self::assertSame('OPERATIONAL_ADOPTION_DISPOSITION_NOT_ADOPTED_LIFECYCLE_CLOSED_NO_AUTHORITY',$r['status']);self::assertFalse($r['result_operationally_adopted']);self::assertFalse($r['execution_authority']);}finally{$this->remove($root);}}
 private function fixtures(string$root):array{$instance='imperium-test';$sid='operational-seat-binding-'.str_repeat('a',20);$s=$this->record(['binding_id'=>$sid,'instance_id'=>$instance,'seat'=>'curia.seneschal','manifestation_id'=>'seneschal','occupancy_generation'=>1,'status'=>'ACTIVE','sealed'=>true]);$this->write($root.'/var/imperium/operational/occupancy/'.$sid.'.json',$s);$oid='legate-result-adoption-decision-opening-'.str_repeat('b',20);$aid='legate-result-adoption-decision-authority-'.str_repeat('c',20);$o=$this->record(['schema'=>'imperium.legate-result-adoption-decision-opening/v1','opening_id'=>$oid,'instance_id'=>$instance,'source_reconciliation'=>['id'=>'reconciliation','digest'=>str_repeat('d',64)],'source_reconciliation_opening'=>['id'=>'opening','digest'=>str_repeat('e',64)],'source_assessment_completion'=>['id'=>'completion','digest'=>str_repeat('f',64)],'source_panel_readiness'=>['id'=>'panel','digest'=>str_repeat('1',64)],'source_issuance'=>['id'=>'issuance','digest'=>str_repeat('2',64)],'source_evaluation_opening'=>['id'=>'evaluation','digest'=>str_repeat('3',64)],'result'=>['output'=>'Recommendation.'],'contract'=>['task'=>'Recommend.'],'assessment_references'=>[],'reconciliation'=>['summary'=>'Reconciled.'],'adoption_decision_authority'=>['authority_id'=>$aid,'recipient'=>['binding_id'=>$sid,'binding_digest'=>$s['record_digest']],'single_use'=>true,'consumed'=>false,'exercisable'=>true],'status'=>'OPERATIONAL_ADOPTION_DECISION_AUTHORITY_OPENED_PENDING_SENESCHAL_DISPOSITION','adoption_disposition_authored'=>false,'result_operationally_adopted'=>false,'planning_amendment_authority'=>false,'operational_use_permitted'=>false,'execution_authority'=>false]);$this->write($root.'/var/imperium/operational/legate-result-adoption-decision-openings/'.$oid.'.json',$o);return[$oid,$aid,$sid];}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
