<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Curia\OperationalAdoptionReconciliationService;
use PHPUnit\Framework\TestCase;
final class OperationalAdoptionReconciliationServiceTest extends TestCase
{
 public function testConsumesAuthorityAndReconcilesWithoutDisposition():void{$root=sys_get_temp_dir().'/imperium-reconcile-'.bin2hex(random_bytes(5));try{[$opening,$authority,$seneschal,$refs]=$this->fixtures($root);$input=['assessment_references'=>$refs,'summary'=>'The panel agrees on relevance but preserves material limits and residual risk.','agreements'=>['The result is relevant.'],'disagreements'=>['Evidence weight differs by jurisdiction.'],'limitations'=>['No operational action is implied.'],'risks'=>['Residual implementation risk remains.'],'uncertainties'=>['Current mission fit requires a separate decision.']];$s=new OperationalAdoptionReconciliationService($root);$r=$s->reconcile($opening,$authority,$seneschal,$input,new \DateTimeImmutable('2026-08-24T06:00:00+00:00'));self::assertSame('ADOPTION_ASSESSMENTS_RECONCILED_NO_DISPOSITION_PENDING_ADOPTION_DECISION_OPENING',$r['status']);self::assertSame($refs,$r['assessment_references']);self::assertTrue($r['reconciliation_authority']['consumed']);self::assertTrue($r['reconciliation_performed']);self::assertFalse($r['voting_performed']);self::assertFalse($r['aggregation_performed']);self::assertFalse($r['adoption_disposition_authored']);self::assertFalse($r['adoption_decision_authority']);self::assertFalse($r['result_operationally_adopted']);self::assertFalse($r['execution_authority']);self::assertSame($r,$s->reconcile($opening,$authority,$seneschal,$input,new \DateTimeImmutable('2026-08-24T07:00:00+00:00')));}finally{$this->remove($root);}}
 public function testCannotOmitAssessmentReference():void{$root=sys_get_temp_dir().'/imperium-reconcile-missing-'.bin2hex(random_bytes(5));try{[$opening,$authority,$seneschal,$refs]=$this->fixtures($root);array_pop($refs);$this->expectExceptionMessage('CUR521_AUTHORED_RECONCILIATION_INVALID');(new OperationalAdoptionReconciliationService($root))->reconcile($opening,$authority,$seneschal,['assessment_references'=>$refs,'summary'=>'Incomplete.'],new \DateTimeImmutable());}finally{$this->remove($root);}}
 private function fixtures(string$root):array{$instance='imperium-test';$sid='operational-seat-binding-'.str_repeat('a',20);$s=$this->record(['binding_id'=>$sid,'instance_id'=>$instance,'seat'=>'curia.seneschal','manifestation_id'=>'seneschal','occupancy_generation'=>1,'status'=>'ACTIVE','sealed'=>true]);$this->write($root.'/var/imperium/operational/occupancy/'.$sid.'.json',$s);$jur=['EVIDENCE_SUFFICIENCY','MISSION_OPERATIONAL_FIT','RISK_AUTHORITY_REVERSIBILITY'];$admitted=[];$refs=[];foreach($jur as$i=>$j){$id='legate-result-adoption-independent-assessment-'.str_repeat(dechex($i+1),20);$ref=['id'=>$id,'digest'=>str_repeat(dechex($i+4),64),'jurisdiction'=>$j];$refs[]=$ref;$admitted[]=$ref+['assessment'=>['disposition'=>'SUPPORTS_WITH_LIMITATIONS','rationale'=>$j,'evidence_references'=>['evidence'],'limitations'=>[],'uncertainties'=>[]]];}$oid='legate-result-adoption-reconciliation-opening-'.str_repeat('b',20);$aid='legate-result-adoption-reconciliation-authority-'.str_repeat('c',20);$o=$this->record(['schema'=>'imperium.legate-result-adoption-reconciliation-opening/v1','opening_id'=>$oid,'instance_id'=>$instance,'source_assessment_completion'=>['id'=>'completion','digest'=>str_repeat('d',64)],'source_panel_readiness'=>['id'=>'panel','digest'=>str_repeat('e',64)],'source_issuance'=>['id'=>'issuance','digest'=>str_repeat('f',64)],'source_evaluation_opening'=>['id'=>'evaluation','digest'=>str_repeat('1',64)],'result'=>['output'=>'Recommendation.'],'contract'=>['task'=>'Recommend.'],'admitted_assessments'=>$admitted,'reconciliation_authority'=>['authority_id'=>$aid,'recipient'=>['binding_id'=>$sid,'binding_digest'=>$s['record_digest']],'single_use'=>true,'consumed'=>false,'exercisable'=>true],'status'=>'ADOPTION_ASSESSMENTS_ADMITTED_UNCHANGED_RECONCILIATION_AUTHORITY_OPENED_PENDING_SENESCHAL_RECONCILIATION','reconciliation_performed'=>false,'voting_performed'=>false,'aggregation_performed'=>false,'result_operationally_adopted'=>false]);$this->write($root.'/var/imperium/operational/legate-result-adoption-reconciliation-openings/'.$oid.'.json',$o);return[$oid,$aid,$sid,$refs];}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
