<?php
declare(strict_types=1);
namespace App\Tests\Imperium\Runtime;
use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Curia\OperationalAdoptionReconciliationOpeningService;
use PHPUnit\Framework\TestCase;
final class OperationalAdoptionReconciliationOpeningServiceTest extends TestCase
{
 public function testAdmitsThreeUnchangedAssessmentsAndOpensOneBoundedAuthority():void{$root=sys_get_temp_dir().'/imperium-reconcile-open-'.bin2hex(random_bytes(5));try{[$completion,$seneschal,$contents]=$this->fixtures($root);$s=new OperationalAdoptionReconciliationOpeningService($root);$o=$s->open($completion,$seneschal,new \DateTimeImmutable('2026-08-24T05:00:00+00:00'));self::assertSame('ADOPTION_ASSESSMENTS_ADMITTED_UNCHANGED_RECONCILIATION_AUTHORITY_OPENED_PENDING_SENESCHAL_RECONCILIATION',$o['status']);self::assertSame($contents,array_column($o['admitted_assessments'],'assessment','jurisdiction'));self::assertTrue($o['reconciliation_authority']['exercisable']);self::assertFalse($o['reconciliation_authority']['consumed']);self::assertTrue($o['reconciliation_contract']['voting_prohibited']);self::assertTrue($o['reconciliation_contract']['aggregation_prohibited']);self::assertFalse($o['result_operationally_adopted']);self::assertFalse($o['execution_authority']);self::assertSame($o,$s->open($completion,$seneschal,new \DateTimeImmutable('2026-08-24T06:00:00+00:00')));}finally{$this->remove($root);}}
 private function fixtures(string$root):array{$instance='imperium-test';$sid='operational-seat-binding-'.str_repeat('a',20);$s=$this->record(['binding_id'=>$sid,'instance_id'=>$instance,'seat'=>'curia.seneschal','manifestation_id'=>'seneschal','occupancy_generation'=>1,'status'=>'ACTIVE','sealed'=>true]);$this->write($root.'/var/imperium/operational/occupancy/'.$sid.'.json',$s);$eid='legate-result-adoption-evaluation-opening-'.str_repeat('b',20);$e=$this->record(['opening_id'=>$eid,'presiding_seneschal'=>['binding_id'=>$sid,'binding_digest'=>$s['record_digest']],'result'=>['output'=>'Recommendation.'],'contract'=>['task'=>'Recommend.']]);$this->write($root.'/var/imperium/operational/legate-result-adoption-evaluation-openings/'.$eid.'.json',$e);$iid='legate-result-adoption-assessment-issuance-'.str_repeat('c',20);$jur=['EVIDENCE_SUFFICIENCY','MISSION_OPERATIONAL_FIT','RISK_AUTHORITY_REVERSIBILITY'];$commissions=[];foreach($jur as$i=>$j)$commissions[$j]=['id'=>'commission-'.$i,'digest'=>str_repeat(dechex($i+1),64)];$i=$this->record(['issuance_id'=>$iid,'source_evaluation_opening'=>['id'=>$eid,'digest'=>$e['record_digest']],'commissions'=>$commissions]);$this->write($root.'/var/imperium/operational/legate-result-adoption-assessment-issuances/'.$iid.'.json',$i);$pid='legate-result-adoption-assessment-panel-readiness-'.str_repeat('d',20);$p=$this->record(['readiness_id'=>$pid,'source_issuance'=>['id'=>$iid,'digest'=>$i['record_digest']]]);$this->write($root.'/var/imperium/operational/legate-result-adoption-assessment-panel-readiness/'.$pid.'.json',$p);$refs=[];$contents=[];foreach($jur as$n=>$j){$aid='legate-result-adoption-independent-assessment-'.str_repeat(dechex($n+4),20);$assessment=['disposition'=>'SUPPORTS_WITH_LIMITATIONS','rationale'=>$j,'evidence_references'=>['evidence'],'limitations'=>[],'uncertainties'=>[]];$a=$this->record(['assessment_id'=>$aid,'jurisdiction'=>$j,'assessment'=>$assessment]);$this->write($root.'/var/imperium/operational/legate-result-adoption-independent-assessments/'.$aid.'.json',$a);$refs[]=['id'=>$aid,'digest'=>$a['record_digest'],'jurisdiction'=>$j];$contents[$j]=$assessment;}$cid='legate-result-adoption-assessment-completion-'.str_repeat('e',20);$c=$this->record(['schema'=>'imperium.legate-result-adoption-assessment-completion/v1','completion_id'=>$cid,'instance_id'=>$instance,'source_panel_readiness'=>['id'=>$pid,'digest'=>$p['record_digest']],'assessments'=>$refs,'status'=>'ADOPTION_INDEPENDENT_ASSESSMENTS_SEALED_PENDING_SENESCHAL_RECONCILIATION','assessment_contents_disclosed'=>false,'voting_performed'=>false,'aggregation_performed'=>false]);$this->write($root.'/var/imperium/operational/legate-result-adoption-assessment-completions/'.$cid.'.json',$c);return[$cid,$sid,$contents];}
 private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
