<?php

declare(strict_types=1);

namespace App\Tests\Imperium\Runtime;

use App\Bootstrap\CanonicalJson;
use App\Imperium\Runtime\Conscription\ProfileModelBindingSealingService;
use PHPUnit\Framework\TestCase;

final class ProfileModelBindingSealingServiceTest extends TestCase
{
    public function testConsumesAuthorizedBindingIntoNewImmutableProfileVersion():void
    {
        $root=sys_get_temp_dir().'/imperium-profile-model-binding-'.bin2hex(random_bytes(6));$authorizationId='mission-authorization-'.str_repeat('a',20);$authorityId='model-binding-sealing-authority-'.str_repeat('b',20);$profileId='profile-foundry-artificer';$line=['line_number'=>5,'line_digest'=>str_repeat('c',64),'section'=>'proposed_model_binding','text'=>'Proposed model for foundry.artificer: openai/gpt-test@2026-08-01. Configuration: {"temperature":0.2}.','source'=>'curia-model-selection-planning-decision-test'];
        $authorization=$this->record(['schema'=>'imperium.mission-authorization/v1','authorization_id'=>$authorizationId,'instance_id'=>'imperium-test','mission_plan'=>['constraints'=>['No silent model substitution']],'authorized_disclosures'=>['cost_time_retention_limits'=>['Maximum commissioned cost applies.'],'risks_contingencies_fallbacks'=>['Return to Curia if the exact model is unavailable.']],'preparation_authorities'=>['model_binding_sealing'=>['decision-test'=>['authority_id'=>$authorityId,'authority_single_use'=>true,'target'=>['type'=>'OFFICE_SEAT','id'=>'foundry.artificer','mission_id'=>null],'provider_model_version'=>'openai/gpt-test@2026-08-01','configuration'=>['temperature'=>0.2],'source_line'=>$line,'conscription_profile_sealing_authority'=>true,'provider_invocation_authority'=>false,'execution_authority'=>false,'status'=>'OPEN_PENDING_CONSCRIPTION_MODEL_BINDING_SEALING']]],'status'=>'MISSION_AUTHORIZATION_SEALED_PENDING_AUTHORIZED_PREPARATION']);
        $profile=$this->profile(['contract_version'=>'1.0.0','profile_id'=>$profileId,'profile_version'=>'1.0.0','artifact_class'=>'officer','source_persona'=>['persona_id'=>'persona-artificer','persona_version'=>'1.0.0','persona_digest'=>'sha256:'.str_repeat('d',64),'admission_state'=>'admitted','evidence_record'=>'evidence-artificer'],'steward'=>['kind'=>'office','id'=>'foundry'],'target'=>['kind'=>'seat','id'=>'foundry.artificer'],'transformation'=>['case_id'=>'case-artificer','specification_version'=>'1.0.0','alchemist_disposition_id'=>'alchemist-disposition-artificer'],'cognitive_payload'=>['role'=>'Artificer'],'qualification_contract'=>['contract_id'=>'qualification-artificer','criteria'=>['Preserve exact provenance.']],'limitations'=>['No execution authority.'],'lineage'=>['derived_from'=>'persona-artificer@1.0.0'],'digest_spec'=>['algorithm'=>'sha256','canonicalization'=>'rfc8785','omitted_fields'=>['content_digest']]]);
        $this->write($root.'/var/imperium/authorizations/missions/'.$authorizationId.'.json',$authorization);$this->write($root.'/var/imperium/profiles/current/'.$profileId.'.json',$profile);$service=new ProfileModelBindingSealingService($root);$sealedAt=new \DateTimeImmutable('2026-08-23T18:00:00+00:00');
        try{$binding=$service->seal($authorizationId,$authorityId,$profileId,$sealedAt);self::assertSame($binding,$service->seal($authorizationId,$authorityId,$profileId,$sealedAt->modify('+1 minute')));self::assertSame('1.1.0',$binding['sealed_profile']['profile_version']);self::assertSame('openai/gpt-test@2026-08-01',$binding['sealed_profile']['model_binding']['provider_model_version']);self::assertSame(['temperature'=>0.2],$binding['sealed_profile']['model_binding']['configuration']);self::assertSame($line,$binding['sealed_profile']['model_binding']['source_line']);self::assertSame(['profile_id'=>$profileId,'profile_version'=>'1.0.0','content_digest'=>$profile['content_digest']],$binding['sealed_profile']['lineage']['supersedes']);self::assertTrue($binding['binding_authority']['consumed']);self::assertFalse($binding['binding_authority']['continuing_authority']);self::assertSame('PROFILE_MODEL_BINDING_SEALED_PENDING_ACCESS_AND_ACTIVATION_PREPARATION',$binding['status']);foreach(['profile_designated_current_active','access_assertion_attached','credential_released','provider_invoked','manifestation_assembled','deployed','executed','profile_activation_authority','provider_invocation_authority','deployment_authority','execution_authority']as$field)self::assertFalse($binding[$field]);}
        finally{$this->remove($root);}
    }

    private function record(array$r):array{$r['record_digest']=hash('sha256',CanonicalJson::encode($r));return$r;}private function profile(array$r):array{$r['content_digest']='sha256:'.hash('sha256',CanonicalJson::encode($r));return$r;}private function write(string$p,array$r):void{if(!is_dir(dirname($p)))mkdir(dirname($p),0770,true);file_put_contents($p,json_encode($r,JSON_THROW_ON_ERROR));}private function remove(string$p):void{if(!is_dir($p))return;foreach(array_diff(scandir($p)?:[],['.','..'])as$e){$c=$p.'/'.$e;is_dir($c)?$this->remove($c):unlink($c);}rmdir($p);}
}
