<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Oracle;

use App\Bootstrap\CanonicalJson;

final readonly class ModelEvaluationCaseOpeningService
{
    private string$acceptances;private string$snapshots;private string$occupancy;private string$cases;
    public function __construct(string$root){$this->acceptances=$root.'/var/imperium/offices/oracle/model-requirement-acceptances';$this->snapshots=$root.'/var/imperium/offices/oracle/model-intelligence-snapshots';$this->occupancy=$root.'/var/imperium/offices/oracle/occupancy';$this->cases=$root.'/var/imperium/offices/oracle/model-evaluation-cases';}

    public function open(string$acceptanceId,string$augurBindingId,\DateTimeImmutable$openedAt):array
    {
        $existing=$this->existing($acceptanceId);if(null!==$existing)return$existing;
        $a=$this->read($this->acceptances.'/'.$acceptanceId.'.json','OR45_MODEL_REQUIREMENT_ACCEPTANCE_ABSENT');$o=$this->read($this->occupancy.'/'.$augurBindingId.'.json','OR46_AUGUR_OCCUPANCY_ABSENT');$snapshotId=$a['catalogue_snapshot']['id']??'';$s=$this->read($this->snapshots.'/'.$snapshotId.'.json','OR47_EVALUATION_SNAPSHOT_ABSENT');
        if(!$this->ok($a)||'imperium.oracle-model-requirement-acceptance/v1'!==($a['schema']??null)||$acceptanceId!==($a['acceptance_id']??null)||'CURIA_MODEL_REQUIREMENT_COMMISSION_ACCEPTED_PENDING_ORACLE_EVALUATION'!==($a['status']??null)||true!==($a['evaluation_case_opening_authority']??null)||true===($a['evaluation_authority']??null)||new \DateTimeImmutable($a['expires_at'])<=$openedAt
            ||!$this->ok($o)||'imperium.oracle-augur-occupancy/v1'!==($o['schema']??null)||$augurBindingId!==($o['binding_id']??null)||($a['instance_id']??null)!==($o['instance_id']??null)||'oracle.augur'!==($o['seat']??null)||'ORACLE_AUGUR_BOUND_ACTIVE_NO_MODEL_SELECTION_AUTHORITY'!==($o['status']??null)||($a['actor']['binding_id']??null)!==$augurBindingId||true===($o['selection_authority']??null)
            ||!$this->ok($s)||($a['catalogue_snapshot']['digest']??null)!==($s['record_digest']??null)||'ORACLE_CANONICAL_CATALOGUE_SNAPSHOT_SEALED_NO_SELECTION_AUTHORITY'!==($s['status']??null)
        )throw new \RuntimeException('OR48_MODEL_EVALUATION_CASE_CHAIN_INVALID');
        [$candidates,$excluded]=$this->freeze($s['models']??[],$a['criteria']);$actor=['office'=>'oracle','seat'=>'oracle.augur','binding_id'=>$augurBindingId,'manifestation_id'=>$o['manifestation_id'],'occupancy_generation'=>$o['occupancy_generation']];$criteriaDigest=hash('sha256',CanonicalJson::encode($a['criteria']));
        $authorities=[];foreach($candidates as$ref=>$facts){$id='model-eligibility-authority-'.substr(hash('sha256',CanonicalJson::encode([$acceptanceId,$a['record_digest'],$ref,$facts,$criteriaDigest])),0,20);$authorities[$ref]=['authority_id'=>$id,'model_ref'=>$ref,'criteria_digest'=>$criteriaDigest,'catalogue_snapshot_digest'=>$s['record_digest'],'source_ids'=>$facts['source_ids'],'claim_ids'=>$facts['claim_ids'],'eligibility_finding_authority'=>true,'authority_single_use'=>true,'recommendation_authority'=>false,'ranking_authority'=>false,'selection_authority'=>false,'model_assignment_authority'=>false,'provider_invocation_authority'=>false,'execution_authority'=>false,'status'=>'OPEN_PENDING_AUGUR_FINDING'];}ksort($authorities,SORT_STRING);
        $id='oracle-model-evaluation-case-'.substr(hash('sha256',CanonicalJson::encode([$acceptanceId,$a['record_digest'],$snapshotId,$s['record_digest'],$actor,$candidates,$excluded,$criteriaDigest])),0,20);$status=[]===$authorities?'ORACLE_MODEL_EVALUATION_CASE_OPENED_NO_CANDIDATES_PENDING_CURIA':'ORACLE_MODEL_EVALUATION_CASE_OPENED_PENDING_AUGUR_ELIGIBILITY_FINDINGS';
        return$this->save($id,['schema'=>'imperium.oracle-model-evaluation-case/v1','case_id'=>$id,'instance_id'=>$a['instance_id'],'source_acceptance'=>['id'=>$acceptanceId,'digest'=>$a['record_digest']],'source_commission'=>$a['commission'],'catalogue_snapshot'=>$a['catalogue_snapshot'],'target'=>$a['target'],'criteria'=>$a['criteria'],'criteria_digest'=>$criteriaDigest,'actor'=>$actor,'opened_at'=>$openedAt->format(DATE_ATOM),'candidate_universe_frozen'=>true,'included_candidates'=>array_keys($authorities),'candidate_runtime_bindings'=>array_map(static fn(array$candidate):array=>['provider'=>$candidate['provider'],'platform_service'=>$candidate['platform_service'],'runtime_model'=>$candidate['runtime_model']],$candidates),'excluded_candidates'=>$excluded,'eligibility_authorities'=>$authorities,'evaluation_case_opening_authority_consumed'=>true,'continuing_case_opening_authority'=>false,'recommendation_authority'=>false,'ranking_authority'=>false,'selection_authority'=>false,'model_assignment_authority'=>false,'profile_mutation_authority'=>false,'provider_invocation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'status'=>$status,'sealed'=>true]);
    }

    private function freeze(array$models,array$criteria):array{$in=[];$out=[];foreach($models as$ref=>$m){$reasons=[];$provider=$m['provider']??null;if(!in_array($provider,$criteria['permitted_providers'],true))$reasons[]='PROVIDER_NOT_PERMITTED';if('ACCESSIBLE'!==($m['accessibility']['status']??null))$reasons[]='ACCESS_NOT_AVAILABLE';if('ADMISSIBLE'!==($m['admissibility']['status']??null))$reasons[]='NOT_ADMISSIBLE';$platform=$m['platform_service']??null;$runtime=$m['runtime_model']??null;if(!is_string($platform)||''===trim($platform)||!is_string($runtime)||''===trim($runtime))$reasons[]='RUNTIME_BINDING_INVALID';$sources=array_keys($m['knowledge']['sources']??[]);if(count($sources)<$criteria['minimum_evidence_sources'])$reasons[]='EVIDENCE_THRESHOLD_NOT_MET';if([]!==$reasons){$out[$ref]=['reason_codes'=>$reasons,'observed_accessibility'=>$m['accessibility']['status']??null,'observed_admissibility'=>$m['admissibility']['status']??null,'evidence_source_count'=>count($sources)];continue;}$in[$ref]=['provider'=>$provider,'platform_service'=>$platform,'runtime_model'=>$runtime,'source_ids'=>$sources,'claim_ids'=>array_keys($m['knowledge']['claims']??[])];}ksort($in,SORT_STRING);ksort($out,SORT_STRING);return[$in,$out];}
    private function existing(string$a):?array{if(!is_dir($this->cases))return null;foreach(glob($this->cases.'/oracle-model-evaluation-case-*.json')?:[]as$p){$r=$this->read($p,'OR49_MODEL_EVALUATION_CASE_FAILED');if($a===($r['source_acceptance']['id']??null)){if(!$this->ok($r))throw new \RuntimeException('OR49_MODEL_EVALUATION_CASE_FAILED');return$r;}}return null;}
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
    private function save(string$id,array$r):array{if(!is_dir($this->cases)&&!mkdir($this->cases,0770,true)&&!is_dir($this->cases))throw new \RuntimeException('OR49_MODEL_EVALUATION_CASE_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->cases.'/'.$id.'.json';if(is_file($p))return$this->read($p,'OR49_MODEL_EVALUATION_CASE_FAILED');file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
