<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Oracle;

use App\Bootstrap\CanonicalJson;

final readonly class ModelEligibilityFindingService
{
    private string $cases; private string $occupancy; private string $findings; private string $phases;
    public function __construct(string $root){$this->cases=$root.'/var/imperium/offices/oracle/model-evaluation-cases';$this->occupancy=$root.'/var/imperium/offices/oracle/occupancy';$this->findings=$root.'/var/imperium/offices/oracle/model-eligibility-findings';$this->phases=$root.'/var/imperium/offices/oracle/model-eligibility-phases';}

    public function issue(string $caseId,string $authorityId,string $augurBindingId,string $disposition,array $criterionFindings,array $sourceIds,array $claimIds,array $reasonCodes,\DateTimeImmutable $issuedAt):array
    {
        $existing=$this->existing($authorityId);if(null!==$existing)return$existing;
        $case=$this->read($this->cases.'/'.$caseId.'.json','OR50_MODEL_EVALUATION_CASE_ABSENT');$occupancy=$this->read($this->occupancy.'/'.$augurBindingId.'.json','OR51_AUGUR_OCCUPANCY_ABSENT');
        $authority=$this->authority($case,$authorityId);$modelRef=$authority['model_ref']??'';
        if(!$this->ok($case)||'imperium.oracle-model-evaluation-case/v1'!==($case['schema']??null)||'ORACLE_MODEL_EVALUATION_CASE_OPENED_PENDING_AUGUR_ELIGIBILITY_FINDINGS'!==($case['status']??null)||true!==($case['candidate_universe_frozen']??null)
            ||!$this->ok($occupancy)||'imperium.oracle-augur-occupancy/v1'!==($occupancy['schema']??null)||$augurBindingId!==($occupancy['binding_id']??null)||($case['instance_id']??null)!==($occupancy['instance_id']??null)||($case['actor']['binding_id']??null)!==$augurBindingId||'ORACLE_AUGUR_BOUND_ACTIVE_NO_MODEL_SELECTION_AUTHORITY'!==($occupancy['status']??null)
            ||true!==($authority['eligibility_finding_authority']??null)||true!==($authority['authority_single_use']??null)||!in_array($disposition,['ELIGIBLE','INELIGIBLE','INDETERMINATE'],true)
            ||array_keys($criterionFindings)!==($case['criteria']['evaluation_rubric']??[])||!$this->criteriaValid($criterionFindings,$disposition)||!$this->subset($sourceIds,$authority['source_ids']??[])||!$this->subset($claimIds,$authority['claim_ids']??[])||([]===$sourceIds&&[]===$claimIds)||('ELIGIBLE'!==$disposition&&[]===$reasonCodes)||!$this->strings($reasonCodes,true)
        )throw new \RuntimeException('OR52_MODEL_ELIGIBILITY_FINDING_INVALID');
        $actor=['office'=>'oracle','seat'=>'oracle.augur','binding_id'=>$augurBindingId,'manifestation_id'=>$occupancy['manifestation_id'],'occupancy_generation'=>$occupancy['occupancy_generation']];
        $id='oracle-model-eligibility-finding-'.substr(hash('sha256',CanonicalJson::encode([$caseId,$case['record_digest'],$authorityId,$modelRef,$disposition,$criterionFindings,$sourceIds,$claimIds,$reasonCodes,$actor])),0,20);
        $finding=$this->save($this->findings,$id,['schema'=>'imperium.oracle-model-eligibility-finding/v1','finding_id'=>$id,'case'=>['id'=>$caseId,'digest'=>$case['record_digest']],'authority'=>['id'=>$authorityId,'criteria_digest'=>$authority['criteria_digest'],'catalogue_snapshot_digest'=>$authority['catalogue_snapshot_digest']],'model_ref'=>$modelRef,'actor'=>$actor,'disposition'=>$disposition,'criterion_findings'=>$criterionFindings,'evidence'=>['source_ids'=>$sourceIds,'claim_ids'=>$claimIds],'reason_codes'=>$reasonCodes,'issued_at'=>$issuedAt->format(DATE_ATOM),'eligibility_finding_authority_consumed'=>true,'continuing_finding_authority'=>false,'ranking_authority'=>false,'recommendation_authority'=>false,'selection_authority'=>false,'model_assignment_authority'=>false,'profile_mutation_authority'=>false,'provider_invocation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'status'=>'ORACLE_MODEL_ELIGIBILITY_FINDING_SEALED_NO_SELECTION_AUTHORITY','sealed'=>true]);
        $this->closeIfComplete($case,$issuedAt);return$finding;
    }

    private function closeIfComplete(array $case,\DateTimeImmutable $at):void{$all=[];foreach($case['eligibility_authorities']as$a){$f=$this->existing($a['authority_id']);if(null===$f)return;$all[$f['model_ref']]=['finding_id'=>$f['finding_id'],'finding_digest'=>$f['record_digest'],'disposition'=>$f['disposition'],'reason_codes'=>$f['reason_codes']];}ksort($all,SORT_STRING);$eligible=array_keys(array_filter($all,static fn(array$f):bool=>'ELIGIBLE'===$f['disposition']));$id='oracle-model-eligibility-phase-'.substr(hash('sha256',CanonicalJson::encode([$case['case_id'],$case['record_digest'],$all])),0,20);$status=[]===$eligible?'ORACLE_NO_ELIGIBLE_MODEL_PENDING_CURIA_FALLBACK_ORDER':'ORACLE_ELIGIBILITY_FINDINGS_COMPLETE_PENDING_COMPARATIVE_ASSESSMENT';$this->save($this->phases,$id,['schema'=>'imperium.oracle-model-eligibility-phase/v1','phase_id'=>$id,'case'=>['id'=>$case['case_id'],'digest'=>$case['record_digest']],'findings'=>$all,'eligible_models'=>$eligible,'no_eligible_model'=>[]===$eligible,'closed_at'=>$at->format(DATE_ATOM),'comparative_assessment_authority'=>[]!==$eligible,'curia_fallback_order_authority_required'=>[]===$eligible,'ranking_authority'=>false,'recommendation_authority'=>false,'selection_authority'=>false,'model_assignment_authority'=>false,'profile_mutation_authority'=>false,'provider_invocation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'status'=>$status,'sealed'=>true]);}
    private function authority(array$c,string$id):array{foreach($c['eligibility_authorities']??[]as$a)if($id===($a['authority_id']??null))return$a;throw new \RuntimeException('OR52_MODEL_ELIGIBILITY_FINDING_INVALID');}
    private function criteriaValid(array$c,string$d):bool{foreach($c as$v)if(!is_array($v)||!in_array($v['disposition']??null,['SATISFIED','FAILED','UNPROVEN'],true)||!is_string($v['rationale']??null)||''===trim($v['rationale']))return false;if('ELIGIBLE'===$d)foreach($c as$v)if('SATISFIED'!==$v['disposition'])return false;if('INELIGIBLE'===$d&&!in_array('FAILED',array_column($c,'disposition'),true))return false;if('INDETERMINATE'===$d&&!in_array('UNPROVEN',array_column($c,'disposition'),true))return false;return true;}
    private function subset(array$v,array$allowed):bool{return$this->strings($v)&&[]===array_diff($v,$allowed);}
    private function strings(array$v,bool$empty=false):bool{if(!$empty&&[]===$v)return false;foreach($v as$x)if(!is_string($x)||''===trim($x))return false;return array_values(array_unique($v))===$v;}
    private function existing(string$a):?array{if(!is_dir($this->findings))return null;foreach(glob($this->findings.'/oracle-model-eligibility-finding-*.json')?:[]as$p){$r=$this->read($p,'OR53_MODEL_ELIGIBILITY_FINDING_FAILED');if($a===($r['authority']['id']??null)){if(!$this->ok($r))throw new \RuntimeException('OR53_MODEL_ELIGIBILITY_FINDING_FAILED');return$r;}}return null;}
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
    private function save(string$dir,string$id,array$r):array{if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))throw new \RuntimeException('OR53_MODEL_ELIGIBILITY_FINDING_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$dir.'/'.$id.'.json';if(is_file($p))return$this->read($p,'OR53_MODEL_ELIGIBILITY_FINDING_FAILED');file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
