<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Oracle;

use App\Bootstrap\CanonicalJson;

final readonly class ModelComparativeAssessmentService
{
    private string $phases;private string $cases;private string $findings;private string $occupancy;private string $assessments;
    public function __construct(string$root){$this->phases=$root.'/var/imperium/offices/oracle/model-eligibility-phases';$this->cases=$root.'/var/imperium/offices/oracle/model-evaluation-cases';$this->findings=$root.'/var/imperium/offices/oracle/model-eligibility-findings';$this->occupancy=$root.'/var/imperium/offices/oracle/occupancy';$this->assessments=$root.'/var/imperium/offices/oracle/model-comparative-assessments';}

    public function seal(string$phaseId,string$augurBindingId,array$matrix,\DateTimeImmutable$sealedAt):array
    {
        $existing=$this->existing($phaseId);if(null!==$existing)return$existing;$phase=$this->read($this->phases.'/'.$phaseId.'.json','OR54_MODEL_ELIGIBILITY_PHASE_ABSENT');$caseId=$phase['case']['id']??'';$case=$this->read($this->cases.'/'.$caseId.'.json','OR55_MODEL_EVALUATION_CASE_ABSENT');$o=$this->read($this->occupancy.'/'.$augurBindingId.'.json','OR56_AUGUR_OCCUPANCY_ABSENT');$eligible=$phase['eligible_models']??[];
        if(!$this->ok($phase)||'imperium.oracle-model-eligibility-phase/v1'!==($phase['schema']??null)||'ORACLE_ELIGIBILITY_FINDINGS_COMPLETE_PENDING_COMPARATIVE_ASSESSMENT'!==($phase['status']??null)||true!==($phase['comparative_assessment_authority']??null)||[]===$eligible
            ||!$this->ok($case)||($phase['case']['digest']??null)!==($case['record_digest']??null)||!$this->ok($o)||$augurBindingId!==($o['binding_id']??null)||($case['instance_id']??null)!==($o['instance_id']??null)||($case['actor']['binding_id']??null)!==$augurBindingId||'ORACLE_AUGUR_BOUND_ACTIVE_NO_MODEL_SELECTION_AUTHORITY'!==($o['status']??null)
            ||array_keys($matrix)!==($case['criteria']['evaluation_rubric']??[])||!$this->matrixValid($matrix,$eligible,$phase)
        )throw new \RuntimeException('OR57_MODEL_COMPARATIVE_ASSESSMENT_INVALID');
        $actor=['office'=>'oracle','seat'=>'oracle.augur','binding_id'=>$augurBindingId,'manifestation_id'=>$o['manifestation_id'],'occupancy_generation'=>$o['occupancy_generation']];$matrixDigest=hash('sha256',CanonicalJson::encode($matrix));$id='oracle-model-comparative-assessment-'.substr(hash('sha256',CanonicalJson::encode([$phaseId,$phase['record_digest'],$caseId,$case['record_digest'],$matrixDigest,$actor])),0,20);$recommendationAuthorityId='augur-model-recommendation-authority-'.substr(hash('sha256',CanonicalJson::encode([$id,$matrixDigest,$eligible,$phase['findings']])),0,20);
        return$this->save($id,['schema'=>'imperium.oracle-model-comparative-assessment/v1','assessment_id'=>$id,'eligibility_phase'=>['id'=>$phaseId,'digest'=>$phase['record_digest']],'case'=>['id'=>$caseId,'digest'=>$case['record_digest']],'commission'=>$case['source_commission'],'catalogue_snapshot'=>$case['catalogue_snapshot'],'criteria_digest'=>$case['criteria_digest'],'eligible_models'=>$eligible,'runtime_bindings'=>$case['candidate_runtime_bindings'],'source_findings'=>$phase['findings'],'matrix'=>$matrix,'matrix_digest'=>$matrixDigest,'actor'=>$actor,'sealed_at'=>$sealedAt->format(DATE_ATOM),'comparative_assessment_authority_consumed'=>true,'continuing_comparative_assessment_authority'=>false,'recommendation_authority'=>['authority_id'=>$recommendationAuthorityId,'authority_single_use'=>true,'candidate_models'=>$eligible,'matrix_digest'=>$matrixDigest,'recommendation_authority'=>true,'ranking_authority'=>false,'selection_authority'=>false,'status'=>'OPEN_PENDING_AUGUR_RECOMMENDATION'],'aggregate_score'=>null,'ordinal_ranking'=>null,'winner'=>null,'preferred_candidate'=>null,'ranking_authority'=>false,'selection_authority'=>false,'model_assignment_authority'=>false,'profile_mutation_authority'=>false,'provider_invocation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'status'=>'ORACLE_COMPARATIVE_ASSESSMENT_SEALED_PENDING_AUGUR_RECOMMENDATION','sealed'=>true]);
    }

    private function matrixValid(array$m,array$eligible,array$phase):bool{foreach($m as$cells){if(!is_array($cells)||array_keys($cells)!==$eligible)return false;foreach($cells as$model=>$cell){$f=$this->finding($phase['findings'][$model]??[]);if(!is_array($cell)||array_keys($cell)!==['observation','evidence_strength','source_ids','claim_ids','limitations','contradictions']||!$this->text($cell['observation']??null)||!in_array($cell['evidence_strength']??null,['HIGH','MEDIUM','LOW'],true)||!$this->subset($cell['source_ids']??null,$f['evidence']['source_ids']??[])||!$this->subset($cell['claim_ids']??null,$f['evidence']['claim_ids']??[])||!$this->strings($cell['limitations']??null,true)||!$this->strings($cell['contradictions']??null,true))return false;}}return true;}
    private function finding(array$ref):array{$id=$ref['finding_id']??'';$f=$this->read($this->findings.'/'.$id.'.json','OR58_ELIGIBILITY_FINDING_ABSENT');if(!$this->ok($f)||($ref['finding_digest']??null)!==($f['record_digest']??null)||'ELIGIBLE'!==($f['disposition']??null))throw new \RuntimeException('OR57_MODEL_COMPARATIVE_ASSESSMENT_INVALID');return$f;}
    private function subset(mixed$v,array$a):bool{return is_array($v)&&$this->strings($v,true)&&[]===array_diff($v,$a);}
    private function strings(mixed$v,bool$empty=false):bool{if(!is_array($v)||(!$empty&&[]===$v))return false;foreach($v as$x)if(!$this->text($x))return false;return array_values(array_unique($v))===$v;}private function text(mixed$v):bool{return is_string($v)&&''!==trim($v);}
    private function existing(string$p):?array{if(!is_dir($this->assessments))return null;foreach(glob($this->assessments.'/oracle-model-comparative-assessment-*.json')?:[]as$f){$r=$this->read($f,'OR59_MODEL_COMPARATIVE_ASSESSMENT_FAILED');if($p===($r['eligibility_phase']['id']??null)){if(!$this->ok($r))throw new \RuntimeException('OR59_MODEL_COMPARATIVE_ASSESSMENT_FAILED');return$r;}}return null;}
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
    private function save(string$id,array$r):array{if(!is_dir($this->assessments)&&!mkdir($this->assessments,0770,true)&&!is_dir($this->assessments))throw new \RuntimeException('OR59_MODEL_COMPARATIVE_ASSESSMENT_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->assessments.'/'.$id.'.json';if(is_file($p))return$this->read($p,'OR59_MODEL_COMPARATIVE_ASSESSMENT_FAILED');file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
