<?php

declare(strict_types=1);

namespace App\Imperium\Runtime\Oracle;

use App\Bootstrap\CanonicalJson;

final readonly class ModelRecommendationService
{
    private string $assessments;private string $cases;private string $occupancy;private string $recommendations;
    public function __construct(string$root){$this->assessments=$root.'/var/imperium/offices/oracle/model-comparative-assessments';$this->cases=$root.'/var/imperium/offices/oracle/model-evaluation-cases';$this->occupancy=$root.'/var/imperium/offices/oracle/occupancy';$this->recommendations=$root.'/var/imperium/offices/oracle/model-recommendations';}

    public function issue(string$assessmentId,string$authorityId,string$augurBindingId,string$disposition,?string$recommendedModel,array$criterionRationale,array$candidateAssessments,\DateTimeImmutable$issuedAt):array
    {
        $existing=$this->existing($authorityId);if(null!==$existing)return$existing;$a=$this->read($this->assessments.'/'.$assessmentId.'.json','OR60_MODEL_COMPARATIVE_ASSESSMENT_ABSENT');$caseId=$a['case']['id']??'';$case=$this->read($this->cases.'/'.$caseId.'.json','OR61_MODEL_EVALUATION_CASE_ABSENT');$o=$this->read($this->occupancy.'/'.$augurBindingId.'.json','OR62_AUGUR_OCCUPANCY_ABSENT');$authority=$a['recommendation_authority']??[];$models=$a['eligible_models']??[];
        if(!$this->ok($a)||'imperium.oracle-model-comparative-assessment/v1'!==($a['schema']??null)||'ORACLE_COMPARATIVE_ASSESSMENT_SEALED_PENDING_AUGUR_RECOMMENDATION'!==($a['status']??null)||$authorityId!==($authority['authority_id']??null)||true!==($authority['recommendation_authority']??null)||true!==($authority['authority_single_use']??null)||$models!==($authority['candidate_models']??null)||($a['matrix_digest']??null)!==($authority['matrix_digest']??null)||($a['runtime_bindings']??null)!==($case['candidate_runtime_bindings']??null)
            ||!$this->ok($case)||($a['case']['digest']??null)!==($case['record_digest']??null)||!$this->ok($o)||$augurBindingId!==($o['binding_id']??null)||($case['instance_id']??null)!==($o['instance_id']??null)||($a['actor']['binding_id']??null)!==$augurBindingId||'ORACLE_AUGUR_BOUND_ACTIVE_NO_MODEL_SELECTION_AUTHORITY'!==($o['status']??null)
            ||!in_array($disposition,['RECOMMEND_MODEL','NO_UNIQUE_RECOMMENDATION','RECOMMEND_NONE'],true)||!$this->choiceValid($disposition,$recommendedModel,$models,$candidateAssessments)||array_keys($criterionRationale)!==array_keys($a['matrix']??[])||!$this->rationales($criterionRationale,$a['matrix']??[])
        )throw new \RuntimeException('OR63_MODEL_RECOMMENDATION_INVALID');
        $actor=['office'=>'oracle','seat'=>'oracle.augur','binding_id'=>$augurBindingId,'manifestation_id'=>$o['manifestation_id'],'occupancy_generation'=>$o['occupancy_generation']];$id='oracle-model-recommendation-'.substr(hash('sha256',CanonicalJson::encode([$assessmentId,$a['record_digest'],$authorityId,$disposition,$recommendedModel,$criterionRationale,$candidateAssessments,$actor])),0,20);$decisionAuthorityId='curia-model-selection-decision-authority-'.substr(hash('sha256',CanonicalJson::encode([$id,$a['record_digest'],$models,$disposition,$recommendedModel])),0,20);
        return$this->save($id,['schema'=>'imperium.oracle-model-recommendation/v1','recommendation_id'=>$id,'comparative_assessment'=>['id'=>$assessmentId,'digest'=>$a['record_digest'],'matrix_digest'=>$a['matrix_digest']],'case'=>$a['case'],'commission'=>$a['commission'],'catalogue_snapshot'=>$a['catalogue_snapshot'],'eligible_models'=>$models,'runtime_bindings'=>$a['runtime_bindings'],'actor'=>$actor,'disposition'=>$disposition,'recommended_model'=>$recommendedModel,'criterion_rationale'=>$criterionRationale,'candidate_assessments'=>$candidateAssessments,'issued_at'=>$issuedAt->format(DATE_ATOM),'recommendation_authority'=>['id'=>$authorityId,'consumed'=>true,'continuing_authority'=>false],'curia_selection_decision_authority'=>['authority_id'=>$decisionAuthorityId,'authority_single_use'=>true,'eligible_models'=>$models,'permitted_decisions'=>['SELECT_ELIGIBLE_MODEL','REJECT_ALL_MODELS','RETURN_NEW_COMMISSION'],'selection_decision_authority'=>true,'model_assignment_authority'=>false,'status'=>'OPEN_PENDING_CURIA_SELECTION_DECISION'],'ordinal_ranking'=>null,'selection_authority'=>false,'model_assignment_authority'=>false,'profile_mutation_authority'=>false,'provider_invocation_authority'=>false,'deployment_authority'=>false,'execution_authority'=>false,'status'=>'ORACLE_MODEL_RECOMMENDATION_SEALED_PENDING_CURIA_SELECTION_DECISION','sealed'=>true]);
    }

    private function choiceValid(string$d,?string$r,array$m,array$c):bool{if(array_keys($c)!==$m)return false;if('RECOMMEND_MODEL'===$d&&(!is_string($r)||!in_array($r,$m,true)))return false;if('RECOMMEND_MODEL'!==$d&&null!==$r)return false;foreach($c as$model=>$v){if(!is_array($v)||array_keys($v)!==['recommendation_role','rationale','advantages','disadvantages','limitations','contradictions']||!$this->text($v['rationale']??null)||!$this->strings($v['advantages']??null,true)||!$this->strings($v['disadvantages']??null,true)||!$this->strings($v['limitations']??null,true)||!$this->strings($v['contradictions']??null,true))return false;$role=$v['recommendation_role']??null;if('RECOMMEND_MODEL'===$d&&($model===$r?'RECOMMENDED':'ALTERNATIVE')!==$role)return false;if('NO_UNIQUE_RECOMMENDATION'===$d&&'COEQUAL'!==$role)return false;if('RECOMMEND_NONE'===$d&&'DECLINED'!==$role)return false;}return true;}
    private function rationales(array$r,array$m):bool{foreach($r as$criterion=>$v){$allowed=[];foreach($m[$criterion]??[]as$cell)$allowed=array_merge($allowed,$cell['source_ids']??[],$cell['claim_ids']??[]);$allowed=array_values(array_unique($allowed));if(!is_array($v)||array_keys($v)!==['rationale','evidence_refs']||!$this->text($v['rationale']??null)||!$this->strings($v['evidence_refs']??null)||[]!==array_diff($v['evidence_refs'],$allowed))return false;}return true;}
    private function strings(mixed$v,bool$empty=false):bool{if(!is_array($v)||(!$empty&&[]===$v))return false;foreach($v as$x)if(!$this->text($x))return false;return array_values(array_unique($v))===$v;}private function text(mixed$v):bool{return is_string($v)&&''!==trim($v);}
    private function existing(string$a):?array{if(!is_dir($this->recommendations))return null;foreach(glob($this->recommendations.'/oracle-model-recommendation-*.json')?:[]as$p){$r=$this->read($p,'OR64_MODEL_RECOMMENDATION_FAILED');if($a===($r['recommendation_authority']['id']??null)){if(!$this->ok($r))throw new \RuntimeException('OR64_MODEL_RECOMMENDATION_FAILED');return$r;}}return null;}
    private function read(string$p,string$e):array{if(!is_file($p))throw new \RuntimeException($e);return json_decode((string)file_get_contents($p),true,512,JSON_THROW_ON_ERROR);}private function ok(array$r):bool{$d=$r['record_digest']??null;unset($r['record_digest']);return is_string($d)&&hash_equals($d,hash('sha256',CanonicalJson::encode($r)));}
    private function save(string$id,array$r):array{if(!is_dir($this->recommendations)&&!mkdir($this->recommendations,0770,true)&&!is_dir($this->recommendations))throw new \RuntimeException('OR64_MODEL_RECOMMENDATION_FAILED');$r['record_digest']=hash('sha256',CanonicalJson::encode($r));$p=$this->recommendations.'/'.$id.'.json';if(is_file($p))return$this->read($p,'OR64_MODEL_RECOMMENDATION_FAILED');file_put_contents($p,json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);return$r;}
}
